Repository uber/baseweb, pull requests merged in 2018-08, with the labels that each got.

#155 Radio option should be disabled if the group or itself is disabled
  src/components/radio/radiogroup.js
Labels: bug

#159 chore(flow): set up types for cup globals
  flow-typed/globals.js
  src/components/menu/stateful-container.js
  src/components/popover/popover.js
Labels: enhancement

#103 feat: select and autucomplete component, rfc
  .prettierignore
  rfcs/select-component.md
  src/input/stories.js
  src/menu/__tests__/stateful-container.test.js
  src/menu/stateful-container.js
  src/menu/styled-components.js
  src/menu/types.js
  src/select/__tests__/__snapshots__/dropdown.test.js.snap
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/__tests__/__snapshots__/stateful-select-container.test.js.snap
  src/select/__tests__/__snapshots__/styled-components.test.js.snap
  src/select/__tests__/dropdown.test.js
  src/select/__tests__/select.test.js
  src/select/__tests__/stateful-select-container.test.js
  src/select/__tests__/stateful-select.test.js
  src/select/__tests__/styled-components.test.js
  src/select/constants.js
  src/select/dropdown.js
  src/select/examples.js
  src/select/index.js
  src/select/select.js
  src/select/stateful-select-container.js
  src/select/stateful-select.js
  src/select/stories.js
  src/select/styled-components.js
  src/select/types.js
Labels: enhancement

#119 [RFC] Modal Component
  rfcs/modal-component.md
Labels: rfc

#164 feat(rfc): Buttons
  rfcs/button-component.md
Labels: rfc, work in progress
