Repository uber/baseweb, pull requests merged in 2018-11, with the labels that each got.

#309 [RFC] Component for quick layout, spacing, and typography
  rfcs/block-component.md
Labels: docs

#448 Update README.md to handle dependencies
  README.md
Labels: docs

#449 feat(modal): prevent background scroll when modal opens
  src/modal/__tests__/modal.test.js
  src/modal/modal.js
Labels: bugfix

#452 Release v4.1.1
  package.json
Labels: release

#453 fix(font): use UberMoveText instead of UberMove
  src/themes/index.js
Labels: bugfix

#459 fix(storybook): with info
  .storybook/config.js
Labels: bugfix

#463 fix(tag): use a border-radius of 12px
  src/input/examples.js
  src/tag/__tests__/__snapshots__/styled-components.test.js.snap
  src/tag/__tests__/__snapshots__/tag.test.js.snap
  src/tag/styled-components.js
  src/themes/creator.js
Labels: bugfix

#466 fix(select): position the search icon in the middle vertically
  src/select/styled-components.js
Labels: bugfix

#467 chore: add license header eslint rule
  .eslintrc.js
  LICENSE-HEAD
  babel/cup.js
  commitlint.config.js
  e2e/assertions/hasFocus.js
  e2e/helpers/index.js
  e2e/index.js
  examples/fusion/src/main.js
  examples/fusion/src/pages/home.js
  examples/fusion/src/pages/pageNotFound.js
  examples/fusion/src/root.js
  jest.config.js
  nightwatch.conf.js
  package.json
  scripts/flow-copy-src.js
  src/button/examples-list.js
  src/card/card.js
  src/card/examples-list.js
  src/card/images.js
  src/card/index.js
  src/card/stories.js
  src/card/styled-components.js
  src/checkbox/examples-list.js
  src/form-control/__tests__/form-control.test.js
  src/form-control/__tests__/styled-components.test.js
  src/form-control/constants.js
  src/form-control/examples.js
  src/form-control/form-control.js
  src/form-control/index.js
  src/form-control/stories.js
  src/form-control/styled-components.js
  src/form-control/types.js
  src/icon/build-icons.js
  src/icon/icon-exports.js
  src/input/e2e.js
  src/input/examples-list.js
  src/input/examples.js
  src/link/stories.js
  src/menu/__tests__/option-list.test.js
  src/menu/__tests__/option-profile.test.js
  src/menu/option-list.js
  src/menu/option-profile.js
  src/modal/examples-list.js
  src/pagination/constants.js
  src/pagination/examples-list.js
  src/popover/examples-list.js
  src/radio/examples-list.js
  src/select/examples-list.js
  src/slider/constants.js
  src/textarea/e2e.js
  src/textarea/examples-list.js
  src/toast/examples-list.js
  src/toast/toaster.js
  src/tooltip/examples-list.js
  src/utils/__tests__/deep-merge.test.js
  src/utils/deep-merge.js
  yarn.lock
Labels: bugfix

#469 chore: remove commit test hook
  package.json
Labels: build/tooling, feature

#470 fix(icons): update to new styles
  package.json
  src/icon/README.md
  src/icon/alert.js
  src/icon/arrow-down.js
  src/icon/arrow-left.js
  src/icon/arrow-right.js
  src/icon/arrow-up.js
  src/icon/build-icons.js
  src/icon/check-indeterminate.js
  src/icon/check.js
  src/icon/chevron-left.js
  src/icon/chevron-right.js
  src/icon/delete-alt.js
  src/icon/delete.js
  src/icon/filter.js
  src/icon/menu.js
  src/icon/plus.js
  src/icon/search.js
  src/icon/svg/alert.svg
  src/icon/svg/arrow-down.svg
  src/icon/svg/arrow-left.svg
  src/icon/svg/arrow-right.svg
  src/icon/svg/arrow-up.svg
  src/icon/svg/check-indeterminate.svg
  src/icon/svg/check.svg
  src/icon/svg/chevron-left.svg
  src/icon/svg/chevron-right.svg
  src/icon/svg/delete-alt.svg
  src/icon/svg/delete.svg
  src/icon/svg/filter.svg
  src/icon/svg/menu.svg
  src/icon/svg/plus.svg
  src/icon/svg/search.svg
  src/icon/svg/upload.svg
  src/icon/upload.js
Labels: bugfix

#455 feat(accordion): storybook accordion examples (part2)
  src/accordion/examples-list.js
  src/accordion/examples.js
  src/accordion/stories.js
Labels: feature

#471 fix(select): export types
  src/card/index.js
  src/form-control/index.js
  src/index.js
  src/input/index.js
  src/radio/index.js
  src/select/index.js
  src/slider/index.js
  src/tag/index.js
  src/textarea/index.js
  src/themes/index.js
Labels: bugfix

#454 feat(accordion): add accordion component (part1)
  src/accordion/accordion.js
  src/accordion/constants.js
  src/accordion/examples-list.js
  src/accordion/examples.js
  src/accordion/index.js
  src/accordion/panel.js
  src/accordion/stateful-panel-container.js
  src/accordion/stateful-panel.js
  src/accordion/stories.js
  src/accordion/styled-components.js
  src/accordion/types.js
  src/toast/examples.js
  src/toast/toast.js
Labels: feature

#468 feat(accordion): add unit tests for accordion (part3)
  src/accordion/__tests__/__snapshots__/panel.test.js.snap
  src/accordion/__tests__/__snapshots__/styled-components.test.js.snap
  src/accordion/__tests__/panel.test.js
  src/accordion/__tests__/stateful-panel-container.test.js
  src/accordion/__tests__/stateful-panel.test.js
  src/accordion/__tests__/styled-components.test.js
Labels: feature

#460 fix(fonts): ubermove scale updates
  src/themes/index.js
  src/themes/light-theme-primitives.js
  src/themes/light-theme-with-move.js
Labels: bugfix

#472 fix(toast): button is left-aligned
  src/toast/examples.js
Labels: bugfix

#474 fix(icons): size to scale 600
  src/accordion/__tests__/__snapshots__/styled-components.test.js.snap
  src/button/__tests__/__snapshots__/styled-components.test.js.snap
  src/button/styled-components.js
  src/icon/__tests__/__snapshots__/styled-components.test.js.snap
  src/icon/styled-components.js
  src/spinner/__tests__/__snapshots__/styled-components.test.js.snap
  src/themes/creator.js
  src/toast/__tests__/__snapshots__/styled-components.test.js.snap
Labels: bugfix

#476 fix(storybook): use custom webpack to disable minifiaction
  .storybook-base/webpack.config.js
  .storybook-move/webpack.config.js
  .storybook/webpack.config.js
Labels: bugfix

#477 fix(accordion): update RFC and fix toggle icon look
  rfcs/accordion-component.md
  src/accordion/__tests__/__snapshots__/panel.test.js.snap
  src/accordion/__tests__/__snapshots__/styled-components.test.js.snap
  src/accordion/examples.js
  src/accordion/panel.js
  src/accordion/styled-components.js
Labels: bugfix

#479 fix(logo): update base ui logo
  src/welcome.stories.js
Labels: bugfix

#480 fix(checkbox): set lineHeight on label to 24
  src/checkbox/__tests__/__snapshots__/styled-components.test.js.snap
  src/checkbox/styled-components.js
Labels: bugfix

#482 Release v4.2.0
  package.json
Labels: release

#483 docs(readme): fix themes code example
  src/themes/README.md
Labels: docs

#484 feat(vrt): add basic screener integration
  .buildkite/pipeline.yml
  docker-compose.yml
  package.json
  screener.config.js
  src/card/examples-list.js
  yarn.lock
Labels: feature

#481 feat(block): introduce new Block layout and typography component
  package.json
  rfcs/block-component.md
  src/block/__tests__/block.test.js
  src/block/block.js
  src/block/examples-list.js
  src/block/examples.js
  src/block/index.js
  src/block/stories.js
  src/block/styled-components.js
  src/block/types.js
  src/styles/types.js
Labels: feature

#488 test(menu): add axe end-to-end tests
  nightwatch.conf.js
  src/menu/e2e.js
  src/menu/examples-list.js
  src/menu/examples.js
  src/menu/menu.js
Labels: feature

#489 Release v4.3.0
  package.json
Labels: release

#490 test(tags): add axe end to end tests
  src/tag/e2e.js
  src/tag/examples-list.js
  src/tag/examples.js
Labels: feature

#487 Update event handler usage link [skip ci]
  README.md
Labels: docs

#496 fix: export createTheme, lightThemePrimitives, and LightThemeMove
  src/index.js
  src/themes/README.md
  src/themes/index.js
Labels: bugfix

#497 fix(themes): add back light-theme
  .storybook-move/config.js
  src/themes/light-theme.js
Labels: bugfix

#498 Release v4.3.1
  package.json
Labels: release

#494 chore: upgrade flow versions
  package.json
  src/helpers/overrides.js
  src/pagination/pagination.js
  src/popover/utils.js
  src/styles/styled.js
  src/styles/theme-provider.js
  yarn.lock
Labels: greenkeeping

#500 fix(checkbox): use border-box explicitly
  src/checkbox/__tests__/__snapshots__/styled-components.test.js.snap
  src/checkbox/styled-components.js
Labels: bugfix

#502 Release v4.3.2
  package.json
Labels: release

#501 fix(select): various visual tweaks
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/__tests__/__snapshots__/styled-components.test.js.snap
  src/select/select.js
  src/select/styled-components.js
Labels: bugfix

#505 fix(select): handle error state
  src/select/styled-components.js
Labels: bugfix

#507 Release v4.3.3
  package.json
Labels: release

#508 Make button/input respect useRoundedCorners
  src/button/styled-components.js
  src/input/styled-components.js
Labels: bugfix

#503 feat: introduce new ProgressSteps components
  rfcs/progress-steps-component.md
  src/progress-steps/__tests__/__snapshots__/numbered-step.test.js.snap
  src/progress-steps/__tests__/__snapshots__/step.test.js.snap
  src/progress-steps/__tests__/numbered-step.test.js
  src/progress-steps/__tests__/progress-steps.test.js
  src/progress-steps/__tests__/step.test.js
  src/progress-steps/examples-list.js
  src/progress-steps/examples.js
  src/progress-steps/index.js
  src/progress-steps/numbered-step.js
  src/progress-steps/progress-steps.js
  src/progress-steps/step.js
  src/progress-steps/stories.js
  src/progress-steps/styled-components.js
  src/progress-steps/types.js
Labels: feature

#510 fix: update styles of ProgressSteps example
  src/progress-steps/examples.js
  src/progress-steps/styled-components.js
Labels: bugfix

#511 test(various): tests for useRoundedCorners in button and input
  src/button/__tests__/styled-components.test.js
  src/input/__tests__/__snapshots__/styled-components.test.js.snap
  src/input/__tests__/styled-components.test.js
  src/styles/__mocks__/styled.js
Labels: bugfix

#509 fix: URI encode all themed SVG usages
  src/checkbox/__tests__/__snapshots__/styled-components.test.js.snap
  src/checkbox/styled-components.js
  src/pagination/icons.js
  src/slider/__tests__/__snapshots__/styled-components.test.js.snap
  src/slider/icons.js
Labels: bugfix

#513 test(progress-step): add vrt
  screener.config.js
  src/progress-steps/examples-list.js
Labels: feature

#517 fix(form-control): add support for control container override
  src/form-control/__tests__/form-control.test.js
  src/form-control/form-control.js
  src/form-control/types.js
Labels: bugfix

#514 add mini RFC for header navigation
  rfcs/header-navigation-component.md
Labels: docs, documentation, feature

#515 fix: update ProgressSteps styled-components to calculate positioning
  src/progress-steps/__tests__/__snapshots__/numbered-step.test.js.snap
  src/progress-steps/__tests__/__snapshots__/step.test.js.snap
  src/progress-steps/numbered-step.js
  src/progress-steps/step.js
  src/progress-steps/styled-components.js
Labels: bugfix

#522 docs: fix modal example [skip ci]
  rfcs/modal-component.md
Labels: bugfix, docs

#519 fix(toast): fix animate in
  src/toast/__tests__/__snapshots__/styled-components.test.js.snap
  src/toast/__tests__/styled-components.test.js
  src/toast/__tests__/toast.test.js
  src/toast/styled-components.js
  src/toast/toast.js
  src/toast/toaster.js
  src/toast/types.js
Labels: bugfix

#524 Release v4.4.1
  package.json
Labels: release

#528 fix: enable jsx-a11y checks in eslint
  .eslintrc.js
  e2e/tests.js
  src/card/__tests__/card.test.js
  src/checkbox/examples.js
  src/input/examples.js
  src/modal/__tests__/modal.test.js
  src/pagination/icons.js
  src/tag/examples.js
  src/textarea/examples.js
Labels: bugfix

#527 feat: enable SSR for toaster implementation
  .storybook-move/config.js
  .storybook/config.js
  docs/migrations/00527.md
  docs/pages/pages.js
  rfcs/toast-component.md
  src/block/examples.js
  src/toast/__tests__/toaster.test.js
  src/toast/examples.js
  src/toast/index.js
  src/toast/toaster.js
  src/toast/types.js
  src/welcome.stories.js
Labels: breaking, bugfix

#533 fix: remove radio animation jitter in firefox
  src/radio/__tests__/__snapshots__/styled-components.test.js.snap
  src/radio/__tests__/styled-components.test.js
  src/radio/index.js
  src/radio/radiogroup.js
  src/radio/radiomark.js
  src/radio/styled-components.js
Labels: bugfix

#535 docs: adds info for new contributors to run a dev version of the project
  CONTRIBUTING.md
Labels: docs

#530 feat: add RFC for Ratings component
  rfcs/rating-component.md
Labels: docs, documentation

#542 fix: disable all a11y tests
  src/button/e2e.js
  src/card/e2e.js
  src/checkbox/e2e.js
  src/input/e2e.js
  src/menu/e2e.js
  src/modal/e2e.js
  src/pagination/e2e.js
  src/popover/e2e.js
  src/tag/e2e.js
  src/textarea/e2e.js
  src/tooltip/e2e.js
Labels: bugfix

#541 fix malicious version of dependency flatmap-stream
  package.json
  src/tag/e2e.js
  yarn.lock
Labels: bugfix

#543 fix: allow Icons to receive color prop
  src/icon/__tests__/__snapshots__/styled-components.test.js.snap
  src/icon/styled-components.js
  src/spinner/__tests__/__snapshots__/styled-components.test.js.snap
  src/toast/__tests__/__snapshots__/styled-components.test.js.snap
Labels: bugfix

#538 feat(themes): add dark theme
  .storybook-dark/.babelrc
  .storybook-dark/addons.js
  .storybook-dark/config.js
  .storybook-dark/preview-head.html
  .storybook-dark/webpack.config.js
  package.json
  src/accordion/__tests__/__snapshots__/styled-components.test.js.snap
  src/accordion/styled-components.js
  src/card/styled-components.js
  src/checkbox/__tests__/__snapshots__/styled-components.test.js.snap
  src/checkbox/styled-components.js
  src/form-control/__tests__/__snapshots__/styled-components.test.js.snap
  src/form-control/styled-components.js
  src/input/__tests__/__snapshots__/styled-components.test.js.snap
  src/input/styled-components.js
  src/menu/__tests__/__snapshots__/styled-components.test.js.snap
  src/menu/styled-components.js
  src/modal/__tests__/__snapshots__/styled-components.test.js.snap
  src/modal/styled-components.js
  src/pagination/__tests__/__snapshots__/styled-components.test.js.snap
  src/pagination/styled-components.js
  src/popover/__tests__/__snapshots__/styled-components.test.js.snap
  src/popover/styled-components.js
  src/progress-steps/styled-components.js
  src/radio/__tests__/__snapshots__/styled-components.test.js.snap
  src/radio/styled-components.js
  src/select/__tests__/__snapshots__/styled-components.test.js.snap
  src/styles/types.js
  src/textarea/__tests__/__snapshots__/styled-components.test.js.snap
  src/themes/creator.js
  src/themes/dark-theme-primitives.js
  src/themes/dark-theme.js
  src/themes/index.js
  src/tooltip/__tests__/__snapshots__/styled-components.test.js.snap
Labels: feature

#545 feat: add rating palette to light theme
  docs/pages/theming/theming-values/colors.js
  src/rating/__tests__/__snapshots__/styled-components.test.js.snap
  src/rating/examples.js
  src/rating/styled-components.js
  src/styles/types.js
  src/themes/creator.js
  src/themes/dark-theme-primitives.js
  src/themes/light-theme-primitives.js
  src/themes/types.js
Labels: feature

#520 feat(select): rethink select component implementation
  .eslintrc.js
  docs/migrations/00520.md
  rfcs/select-component.md
  src/checkbox/types.js
  src/menu/__tests__/__snapshots__/styled-components.test.js.snap
  src/menu/option-list.js
  src/menu/styled-components.js
  src/select/__tests__/__snapshots__/dropdown.test.js.snap
  src/select/__tests__/__snapshots__/multi-value.test.js.snap
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/__tests__/__snapshots__/stateful-select-container.test.js.snap
  src/select/__tests__/__snapshots__/styled-components.test.js.snap
  src/select/__tests__/autosize-input.test.js
  src/select/__tests__/dropdown.test.js
  src/select/__tests__/multi-value.test.js
  src/select/__tests__/select.test.js
  src/select/__tests__/stateful-select-container.test.js
  src/select/__tests__/stateful-select.test.js
  src/select/__tests__/styled-components.test.js
  src/select/__tests__/value.test.js
  src/select/autosize-input.js
  src/select/constants.js
  src/select/default-props.js
  src/select/dropdown.js
  src/select/e2e.js
  src/select/examples-list.js
  src/select/examples.js
  src/select/index.js
  src/select/multi-value.js
  src/select/select.js
  src/select/stateful-select-container.js
  src/select/stateful-select.js
  src/select/styled-components.js
  src/select/types.js
  src/select/utils/default-filter-options.js
  src/select/utils/index.js
  src/select/value.js
  src/slider/types.js
  src/tag/__tests__/__snapshots__/styled-components.test.js.snap
  src/tag/styled-components.js
Labels: breaking, feature

#550 fix(saucelabs): add start_period
  .buildkite/pipeline.yml
  docker-compose.yml
  nightwatch.conf.js
Labels: bugfix

#554 fix(select): make dropdown positioned absolute and bump z-index
  rfcs/select-component.md
  src/select/dropdown.js
  src/select/index.js
  src/select/styled-components.js
  src/select/types.js
Labels: bugfix

#557 fix(select): fix control's height in a disabled state with no value
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/select.js
Labels: bugfix

#532 feat: add tabs RFC
  rfcs/tabs-component.md
Labels: docs

#559 fix(input): change onInputChange event to be type input
  src/select/types.js
Labels: bugfix

#560 fix(tooltip): typography fixes
  src/themes/dark-theme.js
  src/tooltip/__tests__/__snapshots__/styled-components.test.js.snap
  src/tooltip/styled-components.js
Labels: bugfix

#561 Release v5.1.0
  package.json
Labels: release

#562 docs(): updated intro and playground
  docs/pages/introduction/welcome.md
  docs/pages/pages.js
  docs/pages/playground/index.js
Labels: feature

#564 fix: proper fallback for size prop
  src/icon/__tests__/styled-components.test.js
  src/icon/examples.js
  src/icon/styled-components.js
Labels: bugfix

#567 docs(welcome): add links to dark and light theme
  docs/pages/introduction/welcome.md
Labels: docs

#549 fix: constrain flow $values util type
  src/checkbox/constants.js
  src/select/constants.js
  src/slider/constants.js
Labels: bugfix

#569 fix: Add ellipsis to long text in Select component
  src/select/__tests__/__snapshots__/styled-components.test.js.snap
  src/select/styled-components.js
  src/styles/util.js
Labels: bugfix

#563 feat: introduce Breadcrumbs component
  rfcs/breadcrumbs-component.md
  screener.config.js
  src/breadcrumbs/__tests__/__snapshots__/breadcrumbs.test.js.snap
  src/breadcrumbs/__tests__/__snapshots__/styled-components.test.js.snap
  src/breadcrumbs/__tests__/breadcrumbs.test.js
  src/breadcrumbs/__tests__/styled-components.test.js
  src/breadcrumbs/breadcrumbs.js
  src/breadcrumbs/examples-list.js
  src/breadcrumbs/examples.js
  src/breadcrumbs/index.js
  src/breadcrumbs/stories.js
  src/breadcrumbs/styled-components.js
  src/breadcrumbs/types.js
  src/styles/types.js
  src/themes/creator.js
  src/themes/dark-theme.js
Labels: feature

#577 fix(select): make option type inexact
  src/select/types.js
Labels: bugfix

#525 feat(header-navigation): add implementation
  rfcs/header-navigation-component.md
  src/header-navigation/__tests__/__snapshots__/header-navigation.test.js.snap
  src/header-navigation/__tests__/__snapshots__/styled-components.test.js.snap
  src/header-navigation/__tests__/header-navigation.test.js
  src/header-navigation/__tests__/styled-components.test.js
  src/header-navigation/constants.js
  src/header-navigation/examples-icons.js
  src/header-navigation/examples-list.js
  src/header-navigation/examples.js
  src/header-navigation/header-navigation.js
  src/header-navigation/index.js
  src/header-navigation/stories.js
  src/header-navigation/styled-components.js
  src/header-navigation/types.js
  src/styles/__mocks__/as-primary-export-hoc.js
  src/styles/as-primary-export-hoc.js
  src/styles/index.js
  src/test/test-framework-setup.js
Labels: feature

#576 fix(accordion): removes flowfixme comments in accordion component
  src/accordion/__tests__/panel.test.js
  src/accordion/accordion.js
  src/accordion/examples.js
  src/accordion/types.js
Labels: bugfix

#578 fix(toast): add component specific theme colors
  src/styles/types.js
  src/themes/creator.js
  src/toast/__tests__/__snapshots__/styled-components.test.js.snap
  src/toast/__tests__/styled-components.test.js
  src/toast/styled-components.js
Labels: bugfix

#579 Release v5.2.0
  package.json
Labels: release
