Repository uber/baseweb, pull requests merged in 2018-10, with the labels that each got.

#322 fix(docs): update the usage of a `styled` function
  examples/fusion/src/pages/home.js
  examples/fusion/src/root.js
Labels: bugfix, documentation

#319 test(vrt): add for button
  .gitignore
  TESTING.md
  e2e/helpers/index.js
  nightwatch.conf.js
  package.json
  src/button/e2e.js
  vrt/baseline/button/e2e/buttons-with-enhancers.png
  yarn.lock
Labels: feature

#328 refactor(cards): follow the pattern other components follow for examples
  src/card/examples-list.js
  src/card/examples.js
  src/card/stories.js
Labels: bugfix, enhancement

#331 test(cards): add end to end tests
  e2e/helpers/index.js
  e2e/tests.js
  nightwatch.conf.js
  package.json
  src/button/e2e.js
  src/card/e2e.js
  src/card/examples-list.js
  src/modal/e2e.js
  vrt/baseline/the-button-component/buttons-with-enhancers.png
  vrt/baseline/the-card-component/headline-and-text-with-thumbnail.png
  vrt/baseline/the-card-component/headline-and-text.png
  vrt/baseline/the-card-component/headline-with-image.png
  vrt/baseline/the-card-component/kitchen-sink-(composed).png
  vrt/baseline/the-card-component/kitchen-sink-(props).png
  vrt/baseline/the-card-component/text-only.png
  vrt/baseline/the-card-component/text-with-button.png
  vrt/baseline/the-card-component/text-with-image-and-button.png
  vrt/baseline/the-card-component/text-with-image.png
  vrt/baseline/the-card-component/text-with-link.png
  vrt/baseline/the-card-component/text-wwith-image-and-link.png
  vrt/baseline/the-card-component/thumbnail-and-button.png
  vrt/baseline/the-card-component/thumbnail-and-link.png
Labels: feature

#292 feature: fix bugs for select and change styles
  rfcs/select-component.md
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/__tests__/__snapshots__/stateful-select-container.test.js.snap
  src/select/__tests__/__snapshots__/styled-components.test.js.snap
  src/select/__tests__/select.test.js
  src/select/__tests__/stateful-select-container.test.js
  src/select/__tests__/stateful-select.test.js
  src/select/__tests__/styled-components.test.js
  src/select/constants.js
  src/select/dropdown.js
  src/select/examples.js
  src/select/index.js
  src/select/select.js
  src/select/stateful-select-container.js
  src/select/styled-components.js
  src/select/types.js
  src/tag/tag.js
  src/tag/types.js
Labels: bugfix

#336 Release v2.1.0
  package.json
Labels: release

#334 test(e2e): add more components
  e2e/tests.js
Labels: feature

#337 chore(select): update examples
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/__tests__/select.test.js
  src/select/examples-colors.json
  src/select/examples.js
  src/select/select.js
Labels: bugfix

#338 feat(fonts): font can be overwritten; adding move font
  .storybook/config.js
  e2e/index.js
  src/styles/__mocks__/styled.js
  src/styles/theme-provider.js
  src/tag/constants.js
  src/test/test-utils.js
  src/themes/index.js
  src/themes/light-theme.js
Labels: feature

#342 fix(typography): remove letter spacing
  src/modal/__tests__/__snapshots__/styled-components.test.js.snap
  src/themes/light-theme.js
  vrt/baseline/the-card-component/headline-and-text-with-thumbnail.png
  vrt/baseline/the-card-component/headline-and-text.png
  vrt/baseline/the-card-component/headline-with-image.png
  vrt/baseline/the-card-component/kitchen-sink-(composed).png
  vrt/baseline/the-card-component/kitchen-sink-(props).png
  vrt/baseline/the-card-component/text-with-button.png
  vrt/baseline/the-card-component/text-with-image-and-button.png
  vrt/baseline/the-card-component/text-with-image.png
  vrt/baseline/the-card-component/text-with-link.png
  vrt/baseline/the-card-component/text-wwith-image-and-link.png
  vrt/baseline/the-card-component/thumbnail-and-button.png
  vrt/baseline/the-card-component/thumbnail-and-link.png
Labels: bugfix

#346 feat(theme): add theme factory
  src/themes/creator.js
  src/themes/index.js
  src/themes/light-theme.js
  src/themes/types.js
Labels: feature

#343 feat(toast): initial implementation of the toast component (part1)
  rfcs/toast-component.md
  src/toast/constants.js
  src/toast/index.js
  src/toast/styled-components.js
  src/toast/toast.js
  src/toast/types.js
Labels: feature

#344 feat(toast): add toast storybook examples (part2)
  src/toast/examples.js
  src/toast/stories.js
Labels: feature

#345 feat(toast): add toast tests (part3)
  src/toast/__tests__/__snapshots__/styled-components.test.js.snap
  src/toast/__tests__/styled-components.test.js
  src/toast/__tests__/toast.test.js
Labels: feature

#354 feat(toast): add toast storybook examples and tests (part2)
  src/toast/__tests__/__snapshots__/styled-components.test.js.snap
  src/toast/__tests__/styled-components.test.js
  src/toast/__tests__/toast.test.js
  src/toast/examples.js
  src/toast/stories.js
Labels: feature

#356 Release v2.2.0
  package.json
Labels: release

#355 docs(themes): documenting create theme
  README.md
  src/themes/README.md
Labels: docs

#357 fix(e2e): add retry logic
  package.json
Labels: bugfix

#358 chore(tests): some minor tests related clean up
  src/card/examples.js
  src/checkbox/examples.js
  src/modal/examples.js
  src/spinner/__tests__/component.test.js
  src/toast/__tests__/toast.test.js
  src/toast/examples-list.js
  src/toast/examples.js
Labels: bugfix

#359 fix(button): disable pointer events when in loading state
  src/button/__tests__/button.test.js
  src/button/button.js
  src/button/types.js
Labels: bugfix

#362 docs(readme): remove pre-production warning
  README.md
Labels: docs

#364 test(e2e): report on master
  e2e/commands/notifySauceLabs.js
Labels: bugfix

#365 test(e2e): migrate checkbox e2e tests to mocha
  src/checkbox/e2e.js
  vrt/baseline/the-checkbox-component/checkbox-indeterminate.png
Labels: bugfix

#367 fix(e2e): remove sauce notifier
  e2e/commands/notifySauceLabs.js
  nightwatch.conf.js
  src/button/e2e.js
  src/card/e2e.js
  src/checkbox/e2e.js
  src/modal/e2e.js
Labels: bugfix

#349 fix(tag): fixes #339
  src/tag/__tests__/__snapshots__/tag.test.js.snap
  src/tag/constants.js
  src/tag/examples.js
  src/tag/index.js
  src/tag/styled-components.js
  src/tag/tag.js
  src/tag/types.js
Labels: bugfix

#371 Release v2.2.1
  package.json
Labels: release

#369 feat: add stateless progressbar implementation
  rfcs/progress-bar-component.md
  src/progressbar/examples.js
  src/progressbar/index.js
  src/progressbar/progressbar.js
  src/progressbar/stories.js
  src/progressbar/styled-components.js
  src/progressbar/types.js
Labels: feature, work in progress

#373 fix(select): remove selectedOptions from controlled select state
  src/menu/types.js
  src/select/__tests__/select.test.js
  src/select/examples.js
  src/select/select.js
  src/select/types.js
Labels: bugfix

#335 fix(flow): use exact theme object type
  src/styles/types.js
Labels: bugfix

#374 feat: add unit tests for progress bar
  src/progress-bar/__tests__/__snapshots__/progressbar.test.js.snap
  src/progress-bar/__tests__/__snapshots__/styled-components.test.js.snap
  src/progress-bar/__tests__/progressbar.test.js
  src/progress-bar/__tests__/styled-components.test.js
  src/progress-bar/examples.js
  src/progress-bar/index.js
  src/progress-bar/progressbar.js
  src/progress-bar/stories.js
  src/progress-bar/styled-components.js
  src/progress-bar/types.js
Labels: feature

#383 fix(button): propagate event by spreading args
  src/button/__tests__/button.test.js
  src/button/button.js
Labels: bugfix

#385 Release v2.2.2
  package.json
Labels: release

#389 feat(toast): add toaster tests (part 2)
  src/toast/__tests__/toaster.test.js
Labels: feature

#391 fix(select): filteroption prop flow type
  src/select/types.js
Labels: bugfix

#390 chore: cleanup tests log
  src/progress-bar/__tests__/__snapshots__/styled-components.test.js.snap
  src/progress-bar/__tests__/styled-components.test.js
Labels: bugfix

#370 feat(toast): add toaster component (part 1)
  rfcs/toast-component.md
  src/toast/__tests__/__snapshots__/styled-components.test.js.snap
  src/toast/__tests__/toaster.test.js
  src/toast/constants.js
  src/toast/examples-list.js
  src/toast/examples.js
  src/toast/index.js
  src/toast/styled-components.js
  src/toast/toast.js
  src/toast/toaster.js
  src/toast/types.js
Labels: feature

#393 fix(e2e): remove iphone
  package.json
Labels: bugfix

#392 refactor(popover): prep for e2e tests
  src/popover/examples-list.js
  src/popover/examples.js
Labels: feature

#395 Release v2.3.0
  package.json
Labels: release

#398 test(popover): add e2e tests
  src/popover/e2e.js
  src/popover/examples.js
Labels: feature

#400 Release v3.0.0
  package.json
Labels: release

#401 refactor(tooltip): examples
  src/tooltip/examples-list.js
  src/tooltip/examples.js
  src/tooltip/stories.js
Labels: feature

#405 docs(issues): redirect uber employees to internal link
  .github/ISSUE_TEMPLATE/3.uber.employee.md
Labels: docs

#372 docs(rfcs): change handler consistency
  README.md
  docs/event-handlers.md
  docs/migrations/00372.md
  rfcs/accordion-component.md
  rfcs/file-uploader-component.md
  rfcs/menu-component.md
  rfcs/modal-component.md
  rfcs/pagination-component.md
  rfcs/progress-steps-component.md
  rfcs/select-component.md
  rfcs/slider-component.md
  rfcs/tag-component.md
  src/menu/__tests__/stateful-container.test.js
  src/menu/stateful-container.js
  src/menu/types.js
  src/modal/__tests__/modal.test.js
  src/modal/modal.js
  src/modal/types.js
  src/pagination/__tests__/pagination.test.js
  src/pagination/pagination.js
  src/pagination/types.js
  src/select/__tests__/select.test.js
  src/select/__tests__/stateful-select-container.test.js
  src/select/examples.js
  src/select/select.js
  src/select/stateful-select-container.js
  src/select/types.js
Labels: breaking, feature

#411 Release v4.0.0
  package.json
Labels: release

#409 feat(select): add accessibility to select component
  rfcs/select-component.md
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/dropdown.js
  src/select/index.js
  src/select/select.js
  src/select/styled-components.js
  src/select/types.js
Labels: feature

#421 test(e2e): temporarily disable visual tests
  nightwatch.conf.js
Labels: bugfix

#416 chore(package): move commit hooks to husky.hooks to avoid warnings
  package.json
Labels: bugfix, build/tooling

#420 chore(input): prep for e2e tests
  src/input/__tests__/__snapshots__/input.test.js.snap
  src/input/base-input.js
  src/input/examples-list.js
  src/input/examples.js
  src/input/input.js
  src/input/stories.js
Labels: feature

#419 feat(input): use more accurate Flow types
  src/input/base-input.js
  src/input/input.js
  src/input/stateful-container.js
  src/input/types.js
  src/input/utils.js
  src/textarea/types.js
Labels: bugfix

#407 test(select): add e2e tests to Select
  src/select/e2e.js
  src/select/examples-list.js
  src/select/examples.js
Labels: feature, greenkeeping

#413 fix(menu): propagate props for highlight state
  rfcs/select-component.md
  src/menu/option-list.js
  src/menu/types.js
Labels: bugfix

#427 fix(pagination): fix page selection from dropdown menu
  src/pagination/__tests__/pagination.test.js
  src/pagination/__tests__/stateful-container.test.js
  src/pagination/pagination.js
  src/pagination/stateful-container.js
  src/pagination/types.js
Labels: bugfix

#426 fix(pagination): fix expected behavior of dropdown menu style override
  src/pagination/examples.js
  src/pagination/pagination.js
Labels: bugfix

#430 test(e2e): remove custom 1000 wait timeouts so the default set to 10000 is used
  src/button/e2e.js
  src/card/e2e.js
  src/checkbox/e2e.js
  src/modal/e2e.js
  src/popover/e2e.js
  src/select/e2e.js
  src/tooltip/e2e.js
Labels: bugfix

#422 test(input): add e2e tests
  e2e/tests.js
  src/input/e2e.js
  src/input/examples.js
Labels: feature

#433 feat(vrt): remove nightwatch in favor of screener
  TESTING.md
  e2e/helpers/index.js
  nightwatch.conf.js
  package.json
  src/button/e2e.js
  src/card/e2e.js
  src/checkbox/e2e.js
  vrt/baseline/the-button-component/buttons-with-enhancers.png
  vrt/baseline/the-card-component/headline-and-text-with-thumbnail.png
  vrt/baseline/the-card-component/headline-and-text.png
  vrt/baseline/the-card-component/headline-with-image.png
  vrt/baseline/the-card-component/kitchen-sink-(composed).png
  vrt/baseline/the-card-component/kitchen-sink-(props).png
  vrt/baseline/the-card-component/text-only.png
  vrt/baseline/the-card-component/text-with-button.png
  vrt/baseline/the-card-component/text-with-image-and-button.png
  vrt/baseline/the-card-component/text-with-image.png
  vrt/baseline/the-card-component/text-with-link.png
  vrt/baseline/the-card-component/text-wwith-image-and-link.png
  vrt/baseline/the-card-component/thumbnail-and-button.png
  vrt/baseline/the-card-component/thumbnail-and-link.png
  vrt/baseline/the-checkbox-component/checkbox-indeterminate.png
  yarn.lock
Labels: build/tooling, feature

#217 docs(datepicker): add datepicker RFC
  rfcs/datepicker-component.md
Labels: docs, rfc

#436 fix(progress-bar): default behaviour is not to show label
  rfcs/progress-bar-component.md
  src/progress-bar/__tests__/__snapshots__/progressbar.test.js.snap
  src/progress-bar/__tests__/progressbar.test.js
  src/progress-bar/examples.js
  src/progress-bar/progressbar.js
Labels: bugfix

#440 refactor(pagination): prep for e2e tests
  src/pagination/examples-list.js
  src/pagination/examples.js
Labels: greenkeeping

#441 fix(toast): update spacing between toasts
  src/toast/__tests__/__snapshots__/styled-components.test.js.snap
  src/toast/styled-components.js
Labels: bugfix

#429 test(slider): add unit tests to Slider
  src/slider/__tests__/__snapshots__/slider.test.js.snap
  src/slider/__tests__/__snapshots__/stateful-slider-container.test.js.snap
  src/slider/__tests__/__snapshots__/styled-components.test.js.snap
  src/slider/__tests__/slider.test.js
  src/slider/__tests__/stateful-slider-container.test.js
  src/slider/__tests__/stateful-slider.test.js
  src/slider/__tests__/styled-components.test.js
  src/slider/types.js
Labels: feature

#442 test(pagination): add e2e tests
  src/pagination/e2e.js
  src/pagination/examples.js
Labels: feature

#443 chore(radio): refactoring examples to prep for e2e test
  src/radio/examples-list.js
  src/radio/examples.js
Labels: greenkeeping
