Repository uber/baseweb, pull requests merged in 2018-12, with the labels that each got.

#581 fix(deps): move screener-storybook to dev dependencies
  package.json
  yarn.lock
Labels: bugfix

#582 Release v5.2.1
  package.json
Labels: release

#583 fix(components): add displayName
  CONTRIBUTING.md
  src/accordion/panel.js
  src/avatar/styled-components.js
  src/breadcrumbs/__tests__/__snapshots__/breadcrumbs.test.js.snap
  src/breadcrumbs/styled-components.js
  src/button/styled-components.js
  src/card/styled-components.js
  src/checkbox/styled-components.js
  src/form-control/styled-components.js
  src/header-navigation/__tests__/__snapshots__/header-navigation.test.js.snap
  src/header-navigation/styled-components.js
  src/icon/__tests__/__snapshots__/icon.test.js.snap
  src/icon/styled-components.js
  src/input/__tests__/__snapshots__/input.test.js.snap
  src/input/styled-components.js
  src/link/styled-components.js
  src/menu/styled-components.js
  src/modal/__tests__/__snapshots__/modal.test.js.snap
  src/modal/styled-components.js
  src/pagination/styled-components.js
  src/popover/styled-components.js
  src/progress-bar/__tests__/__snapshots__/progressbar.test.js.snap
  src/progress-bar/styled-components.js
  src/progress-steps/__tests__/__snapshots__/numbered-step.test.js.snap
  src/progress-steps/__tests__/__snapshots__/step.test.js.snap
  src/progress-steps/styled-components.js
  src/radio/styled-components.js
  src/rating/__tests__/__snapshots__/emoticon-rating.test.js.snap
  src/rating/__tests__/__snapshots__/star-rating.test.js.snap
  src/rating/styled-components.js
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/styled-components.js
  src/slider/__tests__/__snapshots__/slider.test.js.snap
  src/slider/styled-components.js
  src/spinner/styled-components.js
  src/tag/__tests__/__snapshots__/tag.test.js.snap
  src/tag/styled-components.js
  src/template-component/styled-components.js
  src/textarea/styled-components.js
  src/toast/styled-components.js
  src/tooltip/styled-components.js
Labels: bugfix

#584 fix(select): import React in types.js
  src/header-navigation/examples.js
  src/select/types.js
Labels: bugfix

#586 docs(tag): remove example with components inside a tag
  src/tag/examples-list.js
  src/tag/examples.js
Labels: bugfix

#587 docs(contributing): expose contributing docs on the docs site
  CONTRIBUTING.md
  docs/pages/pages.js
Labels: bugfix

#612 docs(template) review template rfc
  rfcs/templates/component.md
  src/template-component/README.md
  src/template-component/stories.js
Labels: bugfix, documentation

#606 docs(progress-bar) review progress-bar rfc
  src/progress-bar/README.md
  src/progress-bar/stories.js
Labels: bugfix, documentation

#607 docs(progress-steps) review progress-steps rfc
  src/progress-steps/README.md
  src/progress-steps/stories.js
Labels: bugfix, documentation

#610 docs(slider) review slider rfc
  rfcs/slider-component.md
  src/slider/README.md
  src/slider/stories.js
Labels: bugfix, documentation

#609 docs(rating) review rating rfc
  src/rating/README.md
  src/rating/stories.js
Labels: bugfix, documentation

#590 docs(accordion) review accordion rfc
  rfcs/accordion-component.md
  src/accordion/README.md
  src/accordion/stories.js
Labels: bugfix, documentation

#591 docs(avatar) review avatar rfc
  rfcs/avatar-component.md
  src/avatar/README.md
  src/avatar/stories.js
Labels: bugfix, documentation

#592 docs(block) review block rfc
  src/block/README.md
  src/block/stories.js
Labels: bugfix, documentation

#593 docs(breadcrumbs) review breadcrumbs rfc
  src/breadcrumbs/README.md
  src/breadcrumbs/stories.js
Labels: bugfix, documentation

#594 docs(button) review button rfc
  rfcs/button-component.md
  src/button/README.md
  src/button/stories.js
Labels: bugfix, documentation

#595 docs(card) review card rfc
  rfcs/card-component.md
  src/card/README.md
  src/card/stories.js
Labels: bugfix, documentation

#596 docs(checkbox) review checkbox rfc
  rfcs/checkbox-component.md
  src/checkbox/README.md
  src/checkbox/stories.js
Labels: bugfix, documentation

#599 docs(icon) review icon rfc
  rfcs/icon-component.md
  src/icon/README.md
  src/icon/stories.js
Labels: bugfix, documentation

#598 docs(header-navigation) review header navigation rfc
  src/header-navigation/README.md
  src/header-navigation/stories.js
Labels: bugfix, documentation

#597 docs(form-control) review form control rfc
  rfcs/form-control-component.md
  src/form-control/README.md
  src/form-control/stories.js
Labels: bugfix, documentation

#600 docs(input) review input rfc
  rfcs/input-component.md
  src/input/README.md
  src/input/stories.js
Labels: bugfix, documentation

#603 docs(notification) review notification rfc
  src/notification/README.md
  src/notification/stories.js
Labels: bugfix, documentation

#605 docs(popover) review popover rfc
  src/popover/README.md
  src/popover/stories.js
Labels: bugfix, documentation

#608 docs(radio) review radio rfc
  rfcs/radiogroup-component.md
  src/radio/README.md
  src/radio/stories.js
Labels: bugfix, documentation

#617 build: flow fix me markdown imports (again)
  .flowconfig
  flow/WebpackAsset.js.flow
  src/accordion/stories.js
  src/avatar/stories.js
  src/block/stories.js
  src/breadcrumbs/stories.js
  src/button/stories.js
  src/card/stories.js
  src/checkbox/stories.js
  src/form-control/stories.js
  src/header-navigation/stories.js
  src/icon/stories.js
  src/input/stories.js
  src/menu/stories.js
  src/modal/stories.js
  src/notification/stories.js
  src/pagination/stories.js
  src/popover/stories.js
  src/progress-bar/stories.js
  src/progress-steps/stories.js
  src/radio/stories.js
  src/rating/stories.js
  src/select/stories.js
  src/slider/stories.js
  src/spinner/stories.js
  src/tag/stories.js
  src/template-component/stories.js
  src/textarea/stories.js
  src/toast/stories.js
  src/tooltip/stories.js
Labels: bugfix

#620 docs: calls out required props in readmes
  src/accordion/README.md
  src/avatar/README.md
  src/button/README.md
  src/card/README.md
  src/checkbox/README.md
  src/header-navigation/README.md
  src/input/README.md
  src/menu/README.md
  src/modal/README.md
  src/pagination/README.md
  src/popover/README.md
  src/progress-bar/README.md
  src/progress-steps/README.md
  src/radio/README.md
  src/select/README.md
  src/slider/README.md
  src/tag/README.md
  src/template-component/README.md
  src/toast/README.md
Labels: docs

#618 docs(spinner): review spinner rfc
  src/spinner/README.md
  src/spinner/stories.js
Labels: bugfix, documentation

#621 Docs/audit textarea rfc
  rfcs/textarea-component.md
  src/textarea/README.md
  src/textarea/stories.js
Labels: bugfix, documentation

#622 fix(select): make option a readOnly type
  src/menu/types.js
  src/select/select.js
  src/select/types.js
  src/select/utils/default-filter-options.js
Labels: bugfix

#623 docs(modal): correct default value for closeable attribute
  src/modal/README.md
Labels: docs

#624 Release v5.2.3
  package.json
Labels: release

#625 docs(overrides): add link to the external article
  docs/pages/theming/custom-themes.md
Labels: docs

#627 Fix typo in README.md
  src/select/README.md
Labels: docs

#631 docs: update rfc constant syntax, rename rfcs folder to 'proposals'
  .prettierignore
  CONTRIBUTING.md
  docs/migrations/00520.md
  package.json
  proposals/button-group-component.md
  proposals/datepicker-component.md
  proposals/file-uploader-component.md
  proposals/tabs-component.md
  src/button/README.md
  src/checkbox/README.md
  src/header-navigation/README.md
  src/input/README.md
  src/menu/README.md
  src/pagination/README.md
  src/popover/README.md
  src/select/README.md
  src/tag/README.md
  src/template-component/README.md
  src/toast/README.md
Labels: bugfix, documentation

#630 fix(block): enumerate types for css properties
  src/block/README.md
  src/block/types.js
Labels: bugfix

#633 docs(versioning): add versioning policy
  docs/pages/introduction/versioning.md
  docs/pages/pages.js
Labels: feature

#635 chore: remove styletron-standard peer dependency
  README.md
  package.json
Labels: bugfix

#637 fix(popover): fix onOpen/onClose callbacks
  src/popover/__tests__/stateful-container.test.js
  src/popover/stateful-container.js
Labels: bugfix

#636 feat(block): add CSS Grid properties
  src/block/README.md
  src/block/__tests__/block.test.js
  src/block/block.js
  src/block/examples-list.js
  src/block/examples.js
  src/block/styled-components.js
  src/block/types.js
Labels: feature

#640 fix(popover): fix enzyme matcher warning in tests
  flow-typed/npm/jest_v23.x.x.js
  src/popover/__tests__/popover.test.js
Labels: bugfix

#628 feat(file-uploader): implements file uploader
  .eslintrc.js
  e2e/tests.js
  package.json
  proposals/file-uploader-component.md
  screener.config.js
  src/file-uploader/README.md
  src/file-uploader/__tests__/__snapshots__/styled-components.test.js.snap
  src/file-uploader/__tests__/file-uploader.test.js
  src/file-uploader/__tests__/styled-components.test.js
  src/file-uploader/examples-list.js
  src/file-uploader/examples.js
  src/file-uploader/file-uploader.js
  src/file-uploader/index.js
  src/file-uploader/stories.js
  src/file-uploader/styled-components.js
  src/file-uploader/types.js
  src/styles/types.js
  src/themes/creator.js
  src/themes/dark-theme.js
  yarn.lock
Labels: feature

#643 test(rating): mount star rating test
  src/rating/__tests__/star-rating.test.js
Labels: bugfix

#642 feat(input): implements the input mask feature
  package.json
  src/input/README.md
  src/input/__tests__/__snapshots__/masked-input.test.js.snap
  src/input/__tests__/input.test.js
  src/input/__tests__/masked-input.test.js
  src/input/base-input.js
  src/input/examples-list.js
  src/input/examples.js
  src/input/index.js
  src/input/masked-input.js
  src/input/types.js
  yarn.lock
Labels: feature

#645 Change default type ramp to be consistent with Uber move theme
  src/input/__tests__/__snapshots__/styled-components.test.js.snap
  src/themes/creator.js
  src/themes/light-theme-primitives.js
Labels: bugfix

#648 fix: Various type fixes
  src/button/__tests__/__snapshots__/styled-components.test.js.snap
  src/button/styled-components.js
  src/card/styled-components.js
  src/checkbox/__tests__/__snapshots__/styled-components.test.js.snap
  src/checkbox/styled-components.js
  src/tag/__tests__/__snapshots__/styled-components.test.js.snap
  src/tag/styled-components.js
  src/themes/light-theme-with-move.js
  src/toast/__tests__/__snapshots__/styled-components.test.js.snap
  src/toast/styled-components.js
Labels: bugfix

#650 fix: Type stack fixes
  src/input/__tests__/__snapshots__/styled-components.test.js.snap
  src/themes/dark-theme-primitives.js
  src/themes/light-theme-primitives.js
  src/themes/light-theme-with-move.js
Labels: bugfix

#651 fix: organize unstable components in storybook
  .storybook-base/loadStories.js
  .storybook-dark/config.js
  .storybook-move/config.js
  .storybook/config.js
  src/file-uploader/stories.js
Labels: bugfix

#652 fix(header-navigation): optionals
  src/header-navigation/styled-components.js
Labels: bugfix

#656 Release v5.3.1
  package.json
Labels: release

#660 docs(versioning): clarifies feature deprecation path
  docs/pages/introduction/versioning.md
Labels: docs

#661 fix(deps): upgrade styletron-react
  README.md
  package.json
  src/styles/styled.js
  yarn.lock
Labels: bugfix, dependencies

#662 Release v5.3.2
  package.json
Labels: release

#664 feat(select): scroll to the selected option
  src/menu/stateful-container.js
  src/menu/utils.js
  src/select/dropdown.js
Labels: bugfix

#663 docs(popover): update to include overrides
  src/popover/README.md
Labels: docs

#665 Release v5.3.3
  package.json
Labels: release

#632 docs(table): update table rfc based on feedback
  proposals/table-component.md
Labels: docs

#666 fix(header-navigation): use normal cursor
  src/header-navigation/__tests__/__snapshots__/styled-components.test.js.snap
  src/header-navigation/styled-components.js
Labels: bugfix

#669 fix: Update breadcrumbs docs
  src/breadcrumbs/README.md
Labels: docs

#657 feat(button-group) implements the ButtonGroup component
  proposals/button-group-component.md
  screener.config.js
  src/button-group/README.md
  src/button-group/__tests__/__snapshots__/styled-components.test.js.snap
  src/button-group/__tests__/button-group.test.js
  src/button-group/__tests__/stateful-button-group.test.js
  src/button-group/__tests__/stateful-container.test.js
  src/button-group/__tests__/styled-components.test.js
  src/button-group/button-group.js
  src/button-group/constants.js
  src/button-group/examples-list.js
  src/button-group/examples.js
  src/button-group/index.js
  src/button-group/stateful-button-group.js
  src/button-group/stateful-container.js
  src/button-group/stories.js
  src/button-group/styled-components.js
  src/button-group/types.js
  src/button/README.md
  src/button/__tests__/__snapshots__/styled-components.test.js.snap
  src/button/__tests__/styled-components.test.js
  src/button/button-internals.js
  src/button/button.js
  src/button/styled-components.js
  src/button/types.js
  src/button/utils.js
  src/pagination/__tests__/pagination.test.js
Labels: feature

#674 docs(popover): update popover and tooltip docs [skip ci]
  src/popover/README.md
  src/tooltip/README.md
Labels: docs

#677 fix(input): pass ref to input in order to attach popover and add input with a datepicker example
  src/datepicker/examples.js
  src/datepicker/index.js
  src/input/base-input.js
  src/input/types.js
Labels: bugfix

#673 fix(select): highlight the first item initially
  src/select/__tests__/select.test.js
  src/select/dropdown.js
Labels: bugfix

#653 feat(tabs): add tabs implementation
  src/tabs/README.md
  src/tabs/__tests__/__snapshots__/stateful-tabs.test.js.snap
  src/tabs/__tests__/__snapshots__/styled-components.test.js.snap
  src/tabs/__tests__/__snapshots__/tab.test.js.snap
  src/tabs/__tests__/stateful-tabs.test.js
  src/tabs/__tests__/styled-components.test.js
  src/tabs/__tests__/tab.test.js
  src/tabs/constants.js
  src/tabs/examples-list.js
  src/tabs/examples.js
  src/tabs/index.js
  src/tabs/stateful-tabs.js
  src/tabs/stories.js
  src/tabs/styled-components.js
  src/tabs/tab-panel.js
  src/tabs/tab.js
  src/tabs/tabs.js
  src/tabs/types.js
Labels: feature

#678 Release v5.4.0
  package.json
Labels: release

#675 feat(docs): skeleton for new docs site
  .eslintignore
  .eslintrc.js
  .flowconfig
  .gitignore
  documentation-site/.babelrc
  documentation-site/components/meta.js
  documentation-site/helpers/styletron.js
  documentation-site/next.config.js
  documentation-site/pages/_app.js
  documentation-site/pages/index.js
  package.json
  yarn.lock
Labels: feature

#679 fix(build): use the public folder
  .eslintignore
  .gitignore
  documentation-site/next.config.js
  netlify.toml
  package.json
Labels: bugfix

#680 Spelling mistake in example
  src/header-navigation/examples-list.js
Labels: bugfix

#670 [Link, Card] style tweaks
  src/card/styled-components.js
  src/link/styled-components.js
Labels: bugfix

#681 fix(typos): fix various typos
  CONTRIBUTING.md
  docs/pages/theming/custom-themes.md
  src/accordion/README.md
  src/accordion/__tests__/__snapshots__/styled-components.test.js.snap
  src/accordion/styled-components.js
  src/block/examples-list.js
  src/button-group/__tests__/button-group.test.js
  src/checkbox/__tests__/checkbox.test.js
  src/checkbox/__tests__/stateful-checkbox-container.test.js
  src/checkbox/__tests__/stateful-checkbox.test.js
  src/checkbox/examples.js
  src/datepicker/README.md
  src/datepicker/types.js
  src/file-uploader/file-uploader.js
  src/form-control/__tests__/form-control.test.js
  src/header-navigation/__tests__/header-navigation.test.js
  src/helpers/overrides.js
  src/input/__tests__/base-input.test.js
  src/input/__tests__/input.test.js
  src/modal/README.md
  src/pagination/e2e.js
  src/popover/README.md
  src/popover/__tests__/stateful-container.test.js
  src/popover/popover.js
  src/progress-bar/__tests__/progressbar.test.js
  src/progress-steps/examples.js
  src/progress-steps/types.js
  src/radio/__tests__/stateful-radiogroup-container.test.js
  src/rating/__tests__/emoticon-rating.test.js
  src/rating/__tests__/star-rating.test.js
  src/select/README.md
  src/select/__tests__/__snapshots__/multi-value.test.js.snap
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/__tests__/multi-value.test.js
  src/select/__tests__/select.test.js
  src/slider/__tests__/__snapshots__/stateful-slider-container.test.js.snap
  src/slider/__tests__/stateful-slider-container.test.js
  src/slider/__tests__/stateful-slider.test.js
  src/slider/slider.js
  src/tabs/__tests__/tab.test.js
  src/tag/e2e.js
  src/template-component/README.md
  src/template-component/__tests__/stateful-container.test.js
  src/textarea/README.md
  src/toast/README.md
  src/toast/__tests__/toaster.test.js
  src/utils/get-bui-id.js
Labels: bugfix

#668 fix(select): fix blur and close select when double clicked
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/select.js
  src/select/types.js
Labels: bugfix

#685 Release v5.4.1
  package.json
Labels: release

#667 fix(datepicker): add overrides functionality
  src/datepicker/calendar-header.js
  src/datepicker/calendar.js
  src/datepicker/day.js
  src/datepicker/examples-list.js
  src/datepicker/examples.js
  src/datepicker/index.js
  src/datepicker/month.js
  src/datepicker/types.js
  src/datepicker/week.js
Labels: feature

#688 chore: simplify github templates
  .github/ISSUE_TEMPLATE/1.bug.md
  .github/ISSUE_TEMPLATE/2.feature.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: docs

#691 feat(docs-site): page layout
  .flowconfig
  documentation-site/.babelrc
  documentation-site/components/layout.js
  documentation-site/components/meta.js
  documentation-site/images/Logo.png
  documentation-site/next.config.js
  documentation-site/pages/index.js
  package.json
  yarn.lock
Labels: feature
