Repository uber/baseweb, pull requests merged in 2018-09, with the labels that each got.

#178 [RFC] Pagination Component
  rfcs/pagination-component.md
Labels: rfc

#132 feat(menu): add profile list to Menu component; tweak styles
  rfcs/menu-component.md
  src/helpers/__tests__/overrides.test.js
  src/helpers/overrides.js
  src/menu/__tests__/__snapshots__/styled-components.test.js.snap
  src/menu/__tests__/menu.test.js
  src/menu/__tests__/option-list.test.js
  src/menu/__tests__/option-profile.test.js
  src/menu/__tests__/stateful-container.test.js
  src/menu/__tests__/styled-components.test.js
  src/menu/index.js
  src/menu/menu.js
  src/menu/option-list.js
  src/menu/option-profile.js
  src/menu/stateful-container.js
  src/menu/stateful-menu.js
  src/menu/stories.js
  src/menu/styled-components.js
  src/menu/types.js
  src/menu/utils.js
  src/select/__tests__/__snapshots__/styled-components.test.js.snap
  src/select/dropdown.js
  src/select/styled-components.js
Labels: enhancement

#187 docs(rfcs): reorder to better fit docs page
  .markdownlint.json
  .prettierignore
  README.md
  package.json
  rfcs/button-component.md
  rfcs/checkbox-component.md
  rfcs/input-component.md
  rfcs/menu-component.md
  rfcs/modal-component.md
  rfcs/pagination-component.md
  rfcs/popover-component.md
  rfcs/radiogroup-component.md
  rfcs/select-component.md
  rfcs/switch-component.md
  rfcs/templates/component.md
  rfcs/textarea-component.md
  rfcs/tooltip-component.md
  yarn.lock
Labels: documentation, work in progress

#190 docs(button): remove enhancers from usage example
  rfcs/button-component.md
Labels: enhancement, rfc

#172 feat: create tag rfc
  rfcs/tag-component.md
Labels: rfc

#196 docs(spinner): add spinner rfc
  rfcs/spinner-component.md
Labels: rfc

#197 docs(icon): icon rfc
  rfcs/icon-component.md
Labels: rfc

#125 feat: form control component that adds label and caption
  package.json
  rfcs/form-control-component.md
  rfcs/input-component.md
  src/form-control/__tests__/__snapshots__/styled-components.test.js.snap
  src/form-control/__tests__/form-control.test.js
  src/form-control/__tests__/styled-components.test.js
  src/form-control/constants.js
  src/form-control/examples.js
  src/form-control/form-control.js
  src/form-control/index.js
  src/form-control/stories.js
  src/form-control/styled-components.js
  src/form-control/types.js
  src/input/__tests__/__snapshots__/base-input.test.js.snap
  src/input/__tests__/__snapshots__/input.test.js.snap
  src/input/__tests__/__snapshots__/stateful-container.test.js.snap
  src/input/__tests__/__snapshots__/stateful-input.test.js.snap
  src/input/__tests__/__snapshots__/styled-components.test.js.snap
  src/input/__tests__/input.test.js
  src/input/__tests__/stateful-container.test.js
  src/input/__tests__/stateful-input.test.js
  src/input/__tests__/styled-components.test.js
  src/input/base-input.js
  src/input/index.js
  src/input/input.js
  src/input/stories.js
  src/input/styled-components.js
  src/input/types.js
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/select.js
  src/textarea/__tests__/__snapshots__/textarea.test.js.snap
Labels: enhancement

#203 docs(toast): toast notification rfc
  rfcs/toast-component.md
Labels: rfc

#219 docs(rfcs): spinner remove variant
  rfcs/spinner-component.md
Labels: rfc

#231 fix(package.json): use the same naming convention for scripts
  .buildkite/pipeline.yml
  Dockerfile
  docker-compose.yml
  e2e/e2e.js
  package.json
Labels: bugfix

#232 docs(readme): add hiring cta
  README.md
Labels: docs

#230 docs(examples): add working fusion example
  .flowconfig
  .gitignore
  examples/fusion/README.md
  examples/fusion/flow-typed/globals.js
  examples/fusion/package.json
  examples/fusion/src/main.js
  examples/fusion/src/pages/home.js
  examples/fusion/src/pages/pageNotFound.js
  examples/fusion/src/root.js
  examples/fusion/yarn.lock
Labels: feature

#234 chore(select): add task reference for TODO
  src/select/styled-components.js
Labels: bugfix

#233 docs: Update the contributing guide
  CONTRIBUTING.md
Labels: docs

#235 Release v1.7.0
  package.json
Labels: release

#239 Release v1.7.1
  package.json
Labels: release

#236 fix(select): remove DefaultPropsT
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/select.js
  src/select/types.js
Labels: bugfix

#240 fix(input): move the cursor style out of :hover state
  src/input/__tests__/__snapshots__/styled-components.test.js.snap
  src/input/styled-components.js
  src/select/__tests__/__snapshots__/styled-components.test.js.snap
  src/textarea/__tests__/__snapshots__/styled-components.test.js.snap
Labels: bugfix

#241 fix(input): remove default prop for value in BaseInput
  src/input/__tests__/__snapshots__/base-input.test.js.snap
  src/input/__tests__/__snapshots__/input.test.js.snap
  src/input/__tests__/base-input.test.js
  src/input/base-input.js
  src/input/types.js
  src/select/__tests__/__snapshots__/select.test.js.snap
Labels: bugfix

#242 fix(flow): include flow files in the npm dist
  package.json
  scripts/flow-copy-src.js
Labels: bugfix

#243 Release 1.7.2
  package.json
Labels: release

#244 Release v1.7.3
  package.json
Labels: release

#247 fix(menu): address Menu todos; fix types; better a11y
  src/form-control/form-control.js
  src/menu/__tests__/__snapshots__/styled-components.test.js.snap
  src/menu/__tests__/stateful-container.test.js
  src/menu/__tests__/utils.test.js
  src/menu/constants.js
  src/menu/menu.js
  src/menu/stateful-container.js
  src/menu/stateful-menu.js
  src/menu/styled-components.js
  src/menu/types.js
  src/menu/utils.js
Labels: bugfix

#238 docs(file-uploader): file uploader rfc
  rfcs/file-uploader-component.md
Labels: docs, rfc

#204 docs(slider): add rfc for slider
  rfcs/slider-component.md
Labels: docs, rfc

#245 docs(progress-bar): progress bar rfc
  rfcs/progress-bar-component.md
Labels: docs

#221 fix select styles and extra features
  src/select/__tests__/__snapshots__/styled-components.test.js.snap
  src/select/styled-components.js
Labels: bugfix, enhancement

#251 chore(build): Add a prepublish script
  package.json
  prepublish.sh
Labels: bugfix

#253 fix(button): refactor tests; more correct types
  src/button/__tests__/__snapshots__/styled-components.test.js.snap
  src/button/__tests__/button.test.js
  src/button/__tests__/styled-components.test.js
  src/button/button.js
  src/button/constants.js
  src/button/styled-components.js
  src/button/types.js
Labels: bugfix

#212 feat(pagination): initial component implementation (part 1)
  package.json
  rfcs/pagination-component.md
  src/menu/types.js
  src/pagination/__tests__/__snapshots__/styled-components.test.js.snap
  src/pagination/__tests__/pagination.test.js
  src/pagination/__tests__/stateful-container.test.js
  src/pagination/__tests__/stateful-pagination.test.js
  src/pagination/__tests__/styled-components.test.js
  src/pagination/__tests__/utils.test.js
  src/pagination/constants.js
  src/pagination/examples.js
  src/pagination/icons.js
  src/pagination/index.js
  src/pagination/pagination.js
  src/pagination/stateful-container.js
  src/pagination/stateful-pagination.js
  src/pagination/stories.js
  src/pagination/styled-components.js
  src/pagination/types.js
  src/pagination/utils.js
  yarn.lock
Labels: feature

#259 Release v1.8.0
  package.json
Labels: release

#255 fix(button): change content to justify center
  src/button/__tests__/__snapshots__/styled-components.test.js.snap
  src/button/index.js
  src/button/styled-components.js
  src/pagination/pagination.js
Labels: bugfix

#262 chore(overrides): better merging of overrides objects
  src/helpers/__tests__/__snapshots__/overrides.test.js.snap
  src/helpers/__tests__/overrides.test.js
  src/helpers/overrides.js
  src/utils/__tests__/deep-merge.test.js
  src/utils/deep-merge.js
Labels: bugfix

#261 chore(ci): remove prepublish script in favor of probot ENV var
  Dockerfile
  package.json
  prepublish.sh
Labels: bugfix

#265 Release v1.8.1
  package.json
Labels: release

#264 docs(labels): add pr labels to contrib
  CONTRIBUTING.md
Labels: docs

#263 chore(modal): use new button component
  src/modal/__tests__/modal-button.test.js
  src/modal/index.js
  src/modal/modal-button.js
  src/modal/styled-components.js
Labels: bugfix

#266 docs: update stories to use new button component
  src/modal/examples.js
  src/popover/examples.js
  src/tooltip/examples.js
Labels: bugfix

#222 docs(accordion): add rfc for accordion
  rfcs/accordion-component.md
Labels: docs, rfc

#268 feat: add RFC for accordians
  rfcs/accordion-component.md
Labels: docs

#258 feat(menu): add compact styling to OptionList
  src/menu/__tests__/__snapshots__/styled-components.test.js.snap
  src/menu/__tests__/styled-components.test.js
  src/menu/constants.js
  src/menu/examples.js
  src/menu/option-list.js
  src/menu/styled-components.js
  src/menu/types.js
Labels: feature

#257 feat(pagination): change API to take in labels object
  rfcs/pagination-component.md
  src/pagination/examples.js
  src/pagination/index.js
  src/pagination/pagination.js
  src/pagination/stateful-pagination.js
  src/pagination/types.js
Labels: feature

#225 feat: extract Tag into separate component
  rfcs/tag-component.md
  src/select/__tests__/__snapshots__/styled-components.test.js.snap
  src/select/__tests__/select.test.js
  src/select/__tests__/stateful-select.test.js
  src/select/__tests__/styled-components.test.js
  src/select/constants.js
  src/select/index.js
  src/select/select.js
  src/select/styled-components.js
  src/styles/index.js
  src/styles/util.js
  src/tag/__tests__/__snapshots__/styled-components.test.js.snap
  src/tag/__tests__/__snapshots__/tag.test.js.snap
  src/tag/__tests__/styled-components.test.js
  src/tag/__tests__/tag.test.js
  src/tag/constants.js
  src/tag/examples.js
  src/tag/index.js
  src/tag/stories.js
  src/tag/styled-components.js
  src/tag/tag.js
  src/tag/types.js
Labels: enhancement, feature

#271 docs(rfc): update tag and accordion
  rfcs/accordion-component.md
  rfcs/tag-component.md
Labels: docs

#272 Release v1.9.0
  package.json
Labels: release

#274 bugfix(tags): correct relative import that breaks in dist
  src/tag/constants.js
Labels: bugfix

#275 Release v1.9.1
  package.json
Labels: release

#276 fix(card): dont include overrides in rest props
  src/card/card.js
Labels: bugfix

#277 Release v1.9.2
  package.json
Labels: release

#278 docs(coc): add code of conduct
  CODE_OF_CONDUCT.md
Labels: docs

#281 docs(storybook): card uses the button component for examples
  src/card/stories.js
Labels: bugfix, documentation

#283 Release v1.10.0
  package.json
Labels: release

#282 feat(testing): integrate saucelabs
  .buildkite/pipeline.yml
  TESTING.md
  docker-compose.yml
  jest-e2e.config.js
  src/checkbox/e2e.js
  src/e2e-test-utils.js
  src/e2e-test.setup.js
  src/modal/e2e.js
Labels: build/tooling, feature

#279 Feature/select
  rfcs/select-component.md
  src/menu/constants.js
  src/menu/stateful-container.js
  src/menu/types.js
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/__tests__/__snapshots__/styled-components.test.js.snap
  src/select/__tests__/select.test.js
  src/select/__tests__/stateful-select-container.test.js
  src/select/constants.js
  src/select/dropdown.js
  src/select/examples.js
  src/select/index.js
  src/select/select.js
  src/select/stateful-select-container.js
  src/select/styled-components.js
  src/select/types.js
Labels: bugfix

#290 fix(tooltip): shouldnt steal onclick events from children
  src/popover/__tests__/popover.test.js
  src/popover/popover.js
Labels: bugfix

#254 feat(button): add isLoading prop and loading spinner
  rfcs/button-component.md
  src/button/__tests__/__snapshots__/styled-components.test.js.snap
  src/button/__tests__/button.test.js
  src/button/__tests__/styled-components.test.js
  src/button/button-internals.js
  src/button/button.js
  src/button/examples.js
  src/button/index.js
  src/button/styled-components.js
  src/button/types.js
  src/button/utils.js
  src/pagination/__tests__/pagination.test.js
Labels: feature

#293 Release v1.11.0
  package.json
Labels: release

#295 chore: add a component template
  .storybook/config.js
  package.json
  scripts/flow-copy-src.js
  src/template-component/__tests__/__snapshots__/styled-components.test.js.snap
  src/template-component/__tests__/component.test.js
  src/template-component/__tests__/stateful-component.test.js
  src/template-component/__tests__/stateful-container.test.js
  src/template-component/__tests__/styled-components.test.js
  src/template-component/component.js
  src/template-component/constants.js
  src/template-component/examples.js
  src/template-component/index.js
  src/template-component/stateful-component.js
  src/template-component/stateful-container.js
  src/template-component/stories.js
  src/template-component/styled-components.js
  src/template-component/types.js
Labels: bugfix, documentation

#284 docs(progress-steps): progress steps component RFC
  rfcs/progress-steps-component.md
Labels: docs

#286 refactor(e2e): use nightwatch
  .buildkite/pipeline.yml
  .gitignore
  docker-compose.yml
  e2e/assertions/hasFocus.js
  e2e/serve.js
  e2e/tests.js
  nightwatch.conf.js
  package.json
  src/checkbox/e2e.js
  src/checkbox/examples-list.js
  src/checkbox/examples.js
  src/modal/e2e.js
  src/modal/examples-list.js
  src/modal/examples.js
  yarn.lock
Labels: build/tooling, feature, work in progress

#300 feat(e2e): add multiple browsers
  nightwatch.conf.js
  package.json
Labels: build/tooling, feature, work in progress

#299 fix(menu): change padding to margin for first/last children
  src/menu/__tests__/__snapshots__/styled-components.test.js.snap
  src/menu/styled-components.js
Labels: bugfix

#301 refactor(e2e): remove unused files
  jest-e2e.config.js
  src/e2e-test-utils.js
  src/e2e-test.setup.js
Labels: bugfix

#303 Release v1.12.0
  package.json
Labels: release

#305 fix(modal): use role=dialog
  src/modal/__tests__/__snapshots__/modal.test.js.snap
  src/modal/__tests__/modal.test.js
  src/modal/e2e.js
  src/modal/modal.js
Labels: bugfix

#304 feat(spinner): spinner component implementation
  rfcs/spinner-component.md
  src/icon/styled-components.js
  src/spinner/__tests__/__snapshots__/styled-components.test.js.snap
  src/spinner/__tests__/component.test.js
  src/spinner/__tests__/styled-components.test.js
  src/spinner/examples.js
  src/spinner/index.js
  src/spinner/spinner.js
  src/spinner/stories.js
  src/spinner/styled-components.js
  src/spinner/types.js
Labels: feature

#310 fix(e2e): add build numbers
  nightwatch.conf.js
Labels: bugfix, build/tooling

#311 docs(readme): add saucelabs badge
  README.md
Labels: docs

#313 feat(e2e): notifiy sauce if test is passed
  e2e/commands/notifySauceLabs.js
  nightwatch.conf.js
  package.json
  src/checkbox/e2e.js
  src/modal/e2e.js
  yarn.lock
Labels: build/tooling, feature

#316 refactor(e2e): create goToUrl
  e2e/helpers/index.js
  src/checkbox/e2e.js
  src/modal/e2e.js
Labels: bugfix, build/tooling

#320 Release v2.0.0
  package.json
Labels: release
