Repository uber/baseweb, pull requests merged in 2019-04, with the labels that each got.

#1059 fix(components): remove z-index usage
  documentation-site/pages/components/select.mdx
  documentation-site/static/examples/select/in-modal.js
  src/modal/styled-components.js
  src/popover/styled-components.js
  src/select/__tests__/select-in-modal.scenario.js
  src/table/styled-components.js
Labels: bugfix

#1106 Release v6.12.4
  package.json
Labels: release

#1105 feat(screener): add dark theme
  .storybook/config.js
  .storybook/load-stories.js
  package.json
  screener.config.js
Labels: feature

#1069 feat: blog
  .eslintignore
  .gitignore
  .npmignore
  documentation-site/components/blog.js
  documentation-site/components/posts.js
  documentation-site/components/sidebar.js
  documentation-site/pages/blog/getting-started-with-base-web/index.mdx
  documentation-site/pages/blog/getting-started-with-base-web/metadata.json
  documentation-site/pages/blog/index.mdx
  documentation-site/routes.js
  documentation-site/static/images/blog/getting-started-with-base-web/base-web.svg
  documentation-site/static/images/blog/getting-started-with-base-web/foundation.png
  documentation-site/static/images/blog/getting-started-with-base-web/input-with-cta.png
  documentation-site/static/images/blog/getting-started-with-base-web/mockup.png
  documentation-site/static/images/blog/getting-started-with-base-web/result.png
  documentation-site/static/images/blog/getting-started-with-base-web/strength-meter.gif
  documentation-site/static/images/blog/getting-started-with-base-web/styled.png
  package.json
  scripts/post-generator.js
Labels: feature

#1108 feat: updates to mobile layout + intro to base web tweaks
  documentation-site/components/header-navigation.js
  documentation-site/components/layout.js
  documentation-site/pages/_app.js
  documentation-site/pages/blog/getting-started-with-base-web/index.mdx
  documentation-site/pages/index.js
Labels: bugfix

#1104 fix(avatar): make src prop optional for Avatar
  src/avatar/__tests__/avatar-nosrc.scenario.js
  src/avatar/__tests__/avatar.test.js
  src/avatar/avatar.js
  src/avatar/types.js
Labels: feature

#1112 fix(dev-env): windows support
  package.json
  yarn.lock
Labels: bugfix

#1114 fix(styles): remove the rest of shorthands
  documentation-site/components/example.js
  documentation-site/components/markdown-elements.js
  documentation-site/components/posts.js
Labels: bugfix

#1116 feat(docs): add delighted
  documentation-site/pages/_document.js
Labels: feature

#1119 feat(popover): export animation timings
  src/popover/constants.js
  src/popover/index.js
  src/popover/popover.js
Labels: feature

#1120 chore(react-extract-type): switch back from the fork
  documentation-site/pages/components/accordion.mdx
  documentation-site/pages/components/avatar.mdx
  documentation-site/pages/components/block.mdx
  documentation-site/pages/components/breadcrumbs.mdx
  documentation-site/pages/components/button-group.mdx
  documentation-site/pages/components/button.mdx
  documentation-site/pages/components/card.mdx
  documentation-site/pages/components/checkbox.mdx
  documentation-site/pages/components/datepicker.mdx
  documentation-site/pages/components/dnd-list.mdx
  documentation-site/pages/components/file-uploader.mdx
  documentation-site/pages/components/form-control.mdx
  documentation-site/pages/components/header-navigation.mdx
  documentation-site/pages/components/icon.mdx
  documentation-site/pages/components/input.mdx
  documentation-site/pages/components/link.mdx
  documentation-site/pages/components/menu.mdx
  documentation-site/pages/components/modal.mdx
  documentation-site/pages/components/notification.mdx
  documentation-site/pages/components/pagination.mdx
  documentation-site/pages/components/popover.mdx
  documentation-site/pages/components/progress-bar.mdx
  documentation-site/pages/components/progress-steps.mdx
  documentation-site/pages/components/radio.mdx
  documentation-site/pages/components/rating.mdx
  documentation-site/pages/components/select.mdx
  documentation-site/pages/components/sidenav.mdx
  documentation-site/pages/components/slider.mdx
  documentation-site/pages/components/spinner.mdx
  documentation-site/pages/components/table.mdx
  documentation-site/pages/components/tabs.mdx
  documentation-site/pages/components/tag.mdx
  documentation-site/pages/components/textarea.mdx
  documentation-site/pages/components/toast.mdx
  documentation-site/pages/components/tooltip.mdx
  documentation-site/pages/components/typography.mdx
  package.json
  yarn.lock
Labels: greenkeeping

#1122 feat(spinner): dark theme
  src/spinner/styled-components.js
  src/styles/types.js
  src/themes/creator.js
  src/themes/dark-theme-colors.js
Labels: feature

#1107 chore: bump screener-storybook
  Dockerfile
  package.json
  src/select/__tests__/select-in-modal.scenario.js
  yarn.lock
Labels: greenkeeping

#1124 test: add back screener screenshots after actions
  src/progress-steps/__tests__/progress-steps.scenario.js
  src/rating/__tests__/rating-star.scenario.js
  src/select/__tests__/select-search-single.scenario.js
Labels: bugfix

#1118 feat(menu): dark theme
  src/themes/dark-theme-colors.js
Labels: feature

#1126 docs: simplify example for button with dropdown
  documentation-site/static/examples/button/dropdown.js
Labels: bugfix

#1127 feat(dark-theme): notification
  src/themes/dark-theme-colors.js
Labels: feature

#1117 feat(navigation-elements): dark theme
  src/header-navigation/styled-components.js
  src/pagination/pagination.js
  src/styles/types.js
  src/tabs/styled-components.js
  src/themes/creator.js
  src/themes/dark-theme-colors.js
Labels: feature

#1128 feat(table): dark theme colors
  documentation-site/static/examples/table/cells.js
  src/styles/types.js
  src/table/filter.js
  src/table/styled-components.js
  src/themes/creator.js
  src/themes/dark-theme-colors.js
Labels: feature

#1125 feat(dark-theme) list dark colors
  src/accordion/styled-components.js
  src/dnd-list/styled-components.js
  src/progress-steps/styled-components.js
  src/styles/types.js
  src/themes/creator.js
  src/themes/dark-theme-colors.js
Labels: feature

#1130 feat(progress-bar): dark theme
  src/progress-bar/styled-components.js
  src/styles/types.js
  src/themes/creator.js
  src/themes/dark-theme-colors.js
Labels: feature

#1136 feat(datepicker): add onClose property to the datepickers API
  src/datepicker/datepicker.js
  src/datepicker/types.js
Labels: feature

#1134 fix(dev-env): add run-s and run-p to support win envs
  package.json
  yarn.lock
Labels: bugfix

#1123 Release v6.13.0
  package.json
Labels: release

#1110 feat: import styletron post + blog styling updates
  documentation-site/components/blog.js
  documentation-site/components/layout.js
  documentation-site/components/posts.js
  documentation-site/pages/blog/getting-started-with-base-web/index.mdx
  documentation-site/pages/blog/getting-started-with-base-web/metadata.json
  documentation-site/pages/blog/getting-started-with-styletron/index.mdx
  documentation-site/pages/blog/getting-started-with-styletron/metadata.json
  documentation-site/pages/blog/index.mdx
  documentation-site/static/images/blog/getting-started-with-base-web/strength-meter.gif
  documentation-site/static/images/blog/getting-started-with-styletron/fancy-button.gif
  documentation-site/static/images/blog/getting-started-with-styletron/themed-buttons.gif
  scripts/post-generator.js
Labels: feature

#1140 feat(tag): dark theme
  documentation-site/static/examples/tag/custom-color.js
  package.json
  src/styles/types.js
  src/tag/constants.js
  src/tag/styled-components.js
  src/themes/creator.js
  src/themes/dark-theme-colors.js
  yarn.lock
Labels: feature

#1145 fix(docs-site): don't use a custom color on tag
  documentation-site/components/header-navigation.js
Labels: bugfix

#1137 feat(file uploader): button override
  src/file-uploader/file-uploader.js
  src/file-uploader/types.js
Labels: feature

#1155 docs(readme) fix broken themes link
  README.md
Labels: docs

#1157 fix(popover): use longhand border-radius
  documentation-site/static/examples/popover/overrides.js
  src/popover/styled-components.js
Labels: bugfix

#1142 fix(sort-head-cell): properly relax override types
  src/table/types.js
Labels: bugfix

#1160 fix(styles): remove semicolons from styles
  src/checkbox/styled-components.js
  src/rating/styled-components.js
Labels: bugfix

#1158 Release v6.14.0
  package.json
Labels: release

#1162 fix(link): get color values from related theme tokens
  src/link/styled-components.js
  src/themes/creator.js
  src/themes/dark-theme-colors.js
Labels: bugfix, enhancement

#1138 feat(Menu/Select): add onHighlightedItemChanged handler
  documentation-site/pages/components/select.mdx
  documentation-site/static/examples/select/overridden.js
  src/select/__tests__/select-overridden-menu.scenario.js
  src/select/dropdown.js
  src/select/types.js
Labels: feature

#1161 fix(select): enables globally overrided search icon
  package.json
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/select.js
  src/select/styled-components.js
Labels: bugfix

#1164 feat(avatar): crop non-square images
  src/avatar/styled-components.js
Labels: bugfix

#1163 docs(datetime-picker-components): adds proposal
  proposals/datetime-picker-range-example.png
  proposals/datetime-picker-tools.md
Labels: feature

#1165 fix(accordion): enables expanded prop, only render content if expanded
  src/accordion/__tests__/__snapshots__/panel.test.js.snap
  src/accordion/__tests__/accordion-expanded.scenario.js
  src/accordion/accordion.js
  src/accordion/panel.js
Labels: bugfix

#1169 Release v6.14.1
  package.json
Labels: release

#1170 fix(block): use safe get for font values
  src/block/__tests__/block.test.js
  src/block/styled-components.js
Labels: bugfix

#1172 Release v6.14.2
  package.json
Labels: release

#1175 docs(roadmap): add page
  documentation-site/pages/getting-started/roadmap.mdx
  documentation-site/routes.js
Labels: feature

#1174 fix(link): add linkActive to ColorsT type
  src/styles/types.js
Labels: bugfix

#1176 fix(button-group): add margins with values of zero
  src/button/styled-components.js
Labels: bugfix

#1180 Release v6.14.3
  package.json
Labels: release

#1156 feat(timezone-picker): Timezone Picker
  documentation-site/pages/components/datepicker.mdx
  documentation-site/static/examples/datepicker/timezone-picker.js
  package.json
  src/datepicker/__tests__/timezone-picker.e2e.js
  src/datepicker/__tests__/timezone-picker.scenario.js
  src/datepicker/index.js
  src/datepicker/locale.js
  src/datepicker/timezone-picker.js
  src/datepicker/types.js
  yarn.lock
Labels: bugfix, feature

#1146 fix(menu): accept rootRef through props
  src/menu/stateful-container.js
  src/menu/types.js
  src/select/types.js
Labels: bugfix

#1181 docs(*): various fixes for the select and datepicker components
  documentation-site/pages/components/datepicker.mdx
  documentation-site/pages/components/select.mdx
Labels: bugfix

#1183 docs(themeprovider): add to the theming intro pages
  documentation-site/pages/theming/custom-themes.mdx
Labels: documentation, feature

#1168 feat(time-picker): implements component
  documentation-site/pages/components/datepicker.mdx
  documentation-site/static/examples/datepicker/timepicker.js
  src/datepicker/__tests__/time-picker.e2e.js
  src/datepicker/__tests__/time-picker.scenario.js
  src/datepicker/index.js
  src/datepicker/locale.js
  src/datepicker/timepicker.js
  src/datepicker/types.js
Labels: feature

#1147 feat(layer): initial implementation of the Layer component (Part 1)
  .storybook/config.js
  documentation-site/pages/_app.js
  documentation-site/pages/components/layer.mdx
  documentation-site/routes.js
  documentation-site/static/examples/layer/basic.js
  e2e/index.js
  src/layer/__tests__/layer.test.js
  src/layer/constants.js
  src/layer/index.js
  src/layer/layer.js
  src/layer/layers-manager.js
  src/layer/types.js
Labels: feature

#1148 feat(layer): initial implementation of the TetherBehavior (Part 2)
  documentation-site/pages/components/layer.mdx
  documentation-site/static/examples/layer/basic-tether.js
  src/layer/__mocks__/popper.js.js
  src/layer/__tests__/layer.test.js
  src/layer/__tests__/tether.test.js
  src/layer/__tests__/utils.test.js
  src/layer/constants.js
  src/layer/index.js
  src/layer/tether.js
  src/layer/types.js
  src/layer/utils.js
Labels: feature

#1149 fix(modal): render modal with Layer (Part 3)
  src/modal/__tests__/__snapshots__/modal.test.js.snap
  src/modal/__tests__/modal.test.js
  src/modal/modal.js
Labels: bugfix

#1150 fix(popover): render popover with Layer and TetherBehavior (Part 4)
  documentation-site/static/examples/popover/placements.js
  src/popover/__mocks__/popper.js.js
  src/popover/__tests__/popover.test.js
  src/popover/__tests__/utils.test.js
  src/popover/default-props.js
  src/popover/popover.js
  src/popover/types.js
  src/popover/utils.js
Labels: bugfix

#1182 feat(block): transform width and height props using getScale
  src/block/styled-components.js
Labels: feature

#1188 fix(block): does not apply undefined value in transform
  src/block/styled-components.js
Labels: bugfix

#1189 Release v6.15.0
  package.json
Labels: release

#1187 fix(select): quick re-selection, mobile bugs
  src/popover/constants.js
  src/popover/popover.js
  src/popover/types.js
  src/select/select.js
  src/select/styled-components.js
Labels: bugfix

#1191 Release v6.15.1
  package.json
Labels: release

#1193 chore: fix typos
  docs/migrations/00875.md
  documentation-site/pages/components/file-uploader.mdx
  documentation-site/pages/components/form-control.mdx
  documentation-site/pages/components/header-navigation.mdx
  documentation-site/pages/components/layer.mdx
  documentation-site/pages/components/menu.mdx
  documentation-site/pages/components/pagination.mdx
  documentation-site/pages/components/progress-bar.mdx
  documentation-site/pages/components/progress-steps.mdx
  documentation-site/pages/components/styled.mdx
  documentation-site/pages/components/tag.mdx
  documentation-site/pages/getting-started/roadmap.mdx
  documentation-site/pages/theming/overriding-icons.mdx
  proposals/heading-component.md
  src/accordion/__tests__/accordion-expanded.scenario.js
  src/checkbox/__tests__/checkbox-indeterminite.scenario.js
  src/checkbox/__tests__/checkbox.e2e.js
  src/datepicker/timepicker.js
  src/datepicker/timezone-picker.js
  src/datepicker/types.js
  src/icon/__tests__/__snapshots__/icon.test.js.snap
  src/icon/__tests__/icon.test.js
  src/layer/layer.js
  src/layer/layers-manager.js
  src/layer/types.js
  src/menu/__tests__/menu.e2e.js
  src/menu/types.js
  src/menu/utils.js
  src/pagination/__tests__/pagination.e2e.js
  src/rating/__tests__/rating.e2e.js
  src/select/dropdown.js
  src/select/select.js
  src/side-navigation/styled-components.js
  src/side-navigation/types.js
  src/slider/slider.js
  src/table/__tests__/sortable-head-cell.test.js
  src/table/trap-focus.js
  src/tabs/__tests__/tabs.e2e.js
  src/themes/creator.js
  src/toast/__tests__/toast.e2e.js
  src/toast/__tests__/toaster.test.js
  src/toast/types.js
Labels: bugfix

#1184 fix(tooltip): use predefined theme tokens
  src/styles/types.js
  src/themes/creator.js
  src/themes/dark-theme-colors.js
  src/tooltip/styled-components.js
Labels: bugfix

#1197 Correct the name of the project
  documentation-site/pages/getting-started/comparison.mdx
Labels: bugfix

#1192 chore: consistently name rest parameters
  documentation-site/static/examples/input/with-tags.js
  documentation-site/static/examples/layer/basic-tether.js
  documentation-site/static/examples/side-navigation/nav-overrides.js
  src/accordion/stateful-panel-container.js
  src/block/block.js
  src/card/card.js
  src/checkbox/__tests__/stateful-checkbox.test.js
  src/checkbox/stateful-checkbox-container.js
  src/datepicker/stateful-container.js
  src/dnd-list/stateful-list-container.js
  src/input/input.js
  src/input/stateful-container.js
  src/layer/tether.js
  src/menu/menu.js
  src/radio/stateful-radiogroup-container.js
  src/select/autosize-input.js
  src/select/multi-value.js
  src/select/stateful-select-container.js
  src/select/value.js
  src/side-navigation/stateful-container.js
  src/slider/__tests__/stateful-slider.test.js
  src/slider/stateful-slider-container.js
  src/template-component/examples.js
  src/template-component/stateful-container.js
  src/toast/toaster.js
Labels: greenkeeping

#1200 fix(docs): some a11y fixes
  documentation-site/components/header-navigation.js
  documentation-site/components/layout.js
Labels: bugfix

#1201 docs: sort side nav in alphabetical order
  documentation-site/routes.js
Labels: bugfix, documentation

#1202 feat(theme): dark theme docs
  documentation-site/components/bulb.js
  documentation-site/components/header-navigation.js
  documentation-site/components/layout.js
  documentation-site/components/overrides.js
  documentation-site/components/search.js
  documentation-site/components/sidebar.js
  documentation-site/images/base-web-white.svg
  documentation-site/pages/_app.js
  documentation-site/pages/index.js
  documentation-site/static/examples/icon/list.js
  src/styles/types.js
  src/themes/dark-theme-with-move.js
  src/themes/dark-theme.js
  src/themes/index.js
  src/themes/light-theme-with-move.js
Labels: feature

#1206 chore(tag): remove deprecated COLOR_STYLE_KEYS export
  docs/migrations/01206.md
  src/tag/constants.js
  src/tag/index.js
Labels: breaking, greenkeeping
