Repository uber/baseweb, pull requests merged in 2019-03, with the labels that each got.

#971 fix(table): cleans up the table docs
  documentation-site/static/examples/table/sortable.js
Labels: bugfix

#973 docs: understanding overrides, installation, styled
  documentation-site/components/example.js
  documentation-site/components/markdown-elements.js
  documentation-site/components/overrides.js
  documentation-site/pages/components/styled.mdx
  documentation-site/pages/getting-started/installation.mdx
  documentation-site/pages/theming/understanding-overrides.mdx
  documentation-site/static/examples/dnd-list/overrides_short.js
  documentation-site/static/examples/dnd-list/overrides_state_props.js
  documentation-site/static/examples/dnd-list/overrides_style.js
  documentation-site/static/examples/dnd-list/overrides_whole_subcomponent.js
  src/dnd-list/list.js
Labels: documentation, feature

#972 docs(title): add title to all pages
  documentation-site/components/markdown-elements.js
  documentation-site/components/meta.js
Labels: feature

#978 chore(project): remove style snapshot tests
  src/accordion/__tests__/__snapshots__/styled-components.test.js.snap
  src/accordion/__tests__/styled-components.test.js
  src/avatar/__tests__/__snapshots__/styled-components.test.js.snap
  src/avatar/__tests__/styled-components.test.js
  src/breadcrumbs/__tests__/__snapshots__/styled-components.test.js.snap
  src/breadcrumbs/__tests__/styled-components.test.js
  src/button-group/__tests__/__snapshots__/styled-components.test.js.snap
  src/button-group/__tests__/styled-components.test.js
  src/button/__tests__/__snapshots__/styled-components.test.js.snap
  src/button/__tests__/styled-components.test.js
  src/checkbox/__tests__/__snapshots__/styled-components.test.js.snap
  src/checkbox/__tests__/styled-components.test.js
  src/datepicker/__tests__/__snapshots__/styled-components.test.js.snap
  src/datepicker/__tests__/styled-components.test.js
  src/dnd-list/__tests__/__snapshots__/styled-components.test.js.snap
  src/dnd-list/__tests__/styled-components.test.js
  src/file-uploader/__tests__/__snapshots__/styled-components.test.js.snap
  src/file-uploader/__tests__/styled-components.test.js
  src/form-control/__tests__/__snapshots__/styled-components.test.js.snap
  src/form-control/__tests__/styled-components.test.js
  src/header-navigation/__tests__/__snapshots__/styled-components.test.js.snap
  src/header-navigation/__tests__/styled-components.test.js
  src/icon/__tests__/__snapshots__/styled-components.test.js.snap
  src/icon/__tests__/styled-components.test.js
  src/input/__tests__/__snapshots__/styled-components.test.js.snap
  src/input/__tests__/styled-components.test.js
  src/menu/__tests__/__snapshots__/styled-components.test.js.snap
  src/menu/__tests__/styled-components.test.js
  src/modal/__tests__/__snapshots__/styled-components.test.js.snap
  src/modal/__tests__/styled-components.test.js
  src/pagination/__tests__/__snapshots__/styled-components.test.js.snap
  src/pagination/__tests__/styled-components.test.js
  src/popover/__tests__/__snapshots__/styled-components.test.js.snap
  src/popover/__tests__/styled-components.test.js
  src/progress-bar/__tests__/__snapshots__/styled-components.test.js.snap
  src/progress-bar/__tests__/styled-components.test.js
  src/radio/__tests__/__snapshots__/styled-components.test.js.snap
  src/radio/__tests__/styled-components.test.js
  src/rating/__tests__/__snapshots__/styled-components.test.js.snap
  src/rating/__tests__/styled-components.test.js
  src/select/__tests__/__snapshots__/styled-components.test.js.snap
  src/select/__tests__/styled-components.test.js
  src/slider/__tests__/__snapshots__/styled-components.test.js.snap
  src/slider/__tests__/styled-components.test.js
  src/spinner/__tests__/__snapshots__/styled-components.test.js.snap
  src/spinner/__tests__/styled-components.test.js
  src/table/__tests__/__snapshots__/styled-components.test.js.snap
  src/table/__tests__/styled-components.test.js
  src/tabs/__tests__/__snapshots__/styled-components.test.js.snap
  src/tabs/__tests__/styled-components.test.js
  src/tag/__tests__/__snapshots__/styled-components.test.js.snap
  src/tag/__tests__/styled-components.test.js
  src/template-component/__tests__/__snapshots__/styled-components.test.js.snap
  src/template-component/__tests__/styled-components.test.js
  src/textarea/__tests__/__snapshots__/styled-components.test.js.snap
  src/textarea/__tests__/styled-components.test.js
  src/toast/__tests__/__snapshots__/styled-components.test.js.snap
  src/toast/__tests__/styled-components.test.js
  src/tooltip/__tests__/__snapshots__/styled-components.test.js.snap
  src/tooltip/__tests__/styled-components.test.js
Labels: greenkeeping

#979 fix(docs): point getting started docs to styletron
  documentation-site/pages/getting-started/installation.mdx
Labels: bugfix

#980 feat(docs): broken link checker
  .buildkite/pipeline.yml
  Dockerfile
  docker-compose.yml
  package.json
  yarn.lock
Labels: feature

#982 chore(project): rebrand to use base-web
  .github/ISSUE_TEMPLATE/1.bug.md
  .github/ISSUE_TEMPLATE/2.feature.md
  README.md
  docs/event-handlers.md
  docs/migrations/00372.md
  documentation-site/components/layout.js
  documentation-site/components/markdown-elements.js
  documentation-site/components/meta.js
  documentation-site/images/Logo.png
  documentation-site/images/base-web.svg
  documentation-site/pages/components/checkbox.mdx
  documentation-site/pages/components/menu.mdx
  documentation-site/pages/components/styled.mdx
  documentation-site/pages/components/table.mdx
  documentation-site/pages/getting-started/comparison.mdx
  documentation-site/pages/getting-started/installation.mdx
  documentation-site/pages/getting-started/internationalization.mdx
  documentation-site/pages/getting-started/learn.mdx
  documentation-site/pages/getting-started/supported-platforms.mdx
  documentation-site/pages/getting-started/usage.mdx
  documentation-site/pages/getting-started/versioning-policy.mdx
  documentation-site/pages/index.js
  documentation-site/pages/theming/custom-themes.mdx
  documentation-site/pages/theming/understanding-overrides.mdx
  documentation-site/static/android-chrome-192x192.png
  documentation-site/static/android-chrome-512x512.png
  documentation-site/static/apple-touch-icon.png
  documentation-site/static/browserconfig.xml
  documentation-site/static/favicon-16x16.png
  documentation-site/static/favicon-32x32.png
  documentation-site/static/favicon.ico
  documentation-site/static/mstile-144x144.png
  documentation-site/static/mstile-150x150.png
  documentation-site/static/mstile-310x150.png
  documentation-site/static/mstile-310x310.png
  documentation-site/static/mstile-70x70.png
  documentation-site/static/safari-pinned-tab.svg
  documentation-site/static/site.webmanifest
  examples/fusion/README.md
  examples/fusion/src/pages/home.js
Labels: greenkeeping

#977 fix(popover): render without error after ssr
  src/popover/__tests__/__snapshots__/popover.test.js.snap
  src/popover/__tests__/popover.test.js
  src/popover/popover.js
  src/popover/types.js
Labels: bugfix

#984 Release v6.4.1
  package.json
Labels: release

#985 fix(menu): add marginBottom: 0 for list items
  src/menu/styled-components.js
Labels: bugfix

#987 Release v6.4.2
  package.json
Labels: release

#992 fix(breadcrumbs): key prop
  src/breadcrumbs/__tests__/__snapshots__/breadcrumbs.test.js.snap
  src/breadcrumbs/breadcrumbs.js
Labels: bugfix

#991 chore(project): greenkeeping
  Dockerfile
  package.json
  yarn.lock
Labels: greenkeeping

#995 fix(modal-example): remove className
  documentation-site/static/examples/modal/basic.js
Labels: bugfix

#997 fix(button): remove :enabled
  src/button/styled-components.js
Labels: bugfix

#901 feat(datepicker-popover): adds support of mountNode
  src/datepicker/datepicker.js
  src/datepicker/types.js
  src/popover/__tests__/__snapshots__/stateful-container.test.js.snap
  src/popover/popover.js
  src/popover/stateful-container.js
  src/popover/types.js
Labels: feature

#996 fix(pagination): use icons from the base lib
  src/pagination/icons.js
  src/pagination/pagination.js
Labels: bugfix

#998 docs(button): simplify and add spacing
  documentation-site/pages/components/button.mdx
  documentation-site/static/examples/button/basic-compact.js
  documentation-site/static/examples/button/basic.js
  documentation-site/static/examples/button/states.js
Labels: bugfix

#1000 Release v6.5.0
  package.json
Labels: release

#1001 docs(typography): link to theming values
  documentation-site/pages/components/typography.mdx
Labels: bugfix, documentation

#975 fix(select): render the dropdown in a popover
  src/datepicker/__tests__/datepicker.e2e.js
  src/menu/__tests__/menu-stateful.scenario.js
  src/menu/__tests__/stateful-container.test.js
  src/menu/__tests__/utils.test.js
  src/menu/stateful-container.js
  src/menu/utils.js
  src/popover/popover.js
  src/popover/types.js
  src/select/__tests__/__snapshots__/dropdown.test.js.snap
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/__tests__/dropdown.test.js
  src/select/__tests__/select.e2e.js
  src/select/__tests__/select.test.js
  src/select/dropdown.js
  src/select/select.js
  src/select/styled-components.js
  src/select/types.js
Labels: bugfix

#1002 fix(docs): Correct documentation typos
  documentation-site/pages/components/typography.mdx
  documentation-site/pages/getting-started/installation.mdx
  documentation-site/pages/getting-started/learn.mdx
  documentation-site/pages/getting-started/usage.mdx
  documentation-site/pages/theming/custom-themes.mdx
  documentation-site/pages/theming/understanding-overrides.mdx
Labels: bugfix

#1003 docs(toggle): add toggle for uber move
  documentation-site/pages/_app.js
  documentation-site/pages/_document.js
  documentation-site/static/fonts.css
Labels: feature

#1004 Release v6.5.1
  package.json
Labels: release

#999 docs: Make baseweb.design responsive
  documentation-site/components/api.js
  documentation-site/components/component-menu.js
  documentation-site/components/contributors.js
  documentation-site/components/example.js
  documentation-site/components/header-navigation.js
  documentation-site/components/json.js
  documentation-site/components/layout.js
  documentation-site/components/markdown-elements.js
  documentation-site/components/overrides.js
  documentation-site/components/search.js
  documentation-site/components/sidebar.js
  documentation-site/components/theming-values/common.js
  documentation-site/pages/_app.js
  documentation-site/pages/_document.js
  documentation-site/pages/components/accordion.mdx
  documentation-site/pages/components/avatar.mdx
  documentation-site/pages/components/block.mdx
  documentation-site/pages/components/breadcrumbs.mdx
  documentation-site/pages/components/button-group.mdx
  documentation-site/pages/components/button.mdx
  documentation-site/pages/components/card.mdx
  documentation-site/pages/components/checkbox.mdx
  documentation-site/pages/components/datepicker.mdx
  documentation-site/pages/components/dnd-list.mdx
  documentation-site/pages/components/file-uploader.mdx
  documentation-site/pages/components/form-control.mdx
  documentation-site/pages/components/header-navigation.mdx
  documentation-site/pages/components/icon.mdx
  documentation-site/pages/components/input.mdx
  documentation-site/pages/components/link.mdx
  documentation-site/pages/components/menu.mdx
  documentation-site/pages/components/modal.mdx
  documentation-site/pages/components/notification.mdx
  documentation-site/pages/components/pagination.mdx
  documentation-site/pages/components/popover.mdx
  documentation-site/pages/components/progress-bar.mdx
  documentation-site/pages/components/progress-steps.mdx
  documentation-site/pages/components/radio.mdx
  documentation-site/pages/components/rating.mdx
  documentation-site/pages/components/select.mdx
  documentation-site/pages/components/slider.mdx
  documentation-site/pages/components/spinner.mdx
  documentation-site/pages/components/table.mdx
  documentation-site/pages/components/tabs.mdx
  documentation-site/pages/components/tag.mdx
  documentation-site/pages/components/textarea.mdx
  documentation-site/pages/components/toast.mdx
  documentation-site/pages/components/tooltip.mdx
  documentation-site/pages/components/typography.mdx
  documentation-site/pages/getting-started/internationalization.mdx
  documentation-site/pages/index.js
  documentation-site/pages/theming/theming-values.js
  documentation-site/pages/theming/theming-values.mdx
  documentation-site/pages/theming/understanding-overrides.mdx
  documentation-site/prism-coy.css
  documentation-site/routes.js
  documentation-site/static/examples/block/flexbox.js
  package.json
  yarn.lock
Labels: documentation, feature

#1005 docs(typography): add block api
  documentation-site/pages/components/typography.mdx
Labels: bugfix

#1006 docs: spacing improvements
  documentation-site/components/api.js
  documentation-site/components/example.js
  documentation-site/prism-coy.css
Labels: bugfix

#1007 docs: fix favicons and title
  documentation-site/components/markdown-elements.js
  documentation-site/components/meta.js
  documentation-site/pages/_document.js
Labels: bugfix, documentation

#1009 docs: fix typos and remove broken link
  CONTRIBUTING.md
  documentation-site/pages/getting-started/learn.mdx
Labels: bugfix

#1010 fix(datepicker): safari stacked buttons
  src/datepicker/calendar.js
Labels: bugfix

#1008 fix(datepicker): ensures sub-popovers do not trigger close
  src/datepicker/__tests__/datepicker.e2e.js
  src/datepicker/__tests__/datepicker.scenario.js
  src/datepicker/datepicker.js
  src/popover/__tests__/popover.test.js
  src/popover/popover.js
  src/select/__tests__/__snapshots__/dropdown.test.js.snap
  src/select/dropdown.js
Labels: bugfix

#1012 docs: add notes about longhand vs shorthand props
  documentation-site/components/overrides.js
  documentation-site/pages/theming/understanding-overrides.mdx
Labels: documentation, feature

#1013 Release v6.5.2
  package.json
Labels: release

#1014 fix(table): updates example in table so smaller width works
  documentation-site/static/examples/table/fixed-width-column.js
Labels: bugfix

#1015 feat(docs): add dark theme switcher
  documentation-site/components/example.js
  documentation-site/components/layout.js
  documentation-site/components/markdown-elements.js
  documentation-site/components/nav-link.js
  documentation-site/pages/_app.js
  src/index.js
  src/themes/dark-theme-colors.js
  src/themes/dark-theme-with-move.js
  src/themes/dark-theme.js
  src/themes/index.js
Labels: feature

#1017 fix(theme-changing): add option to use defults
  documentation-site/pages/_app.js
  documentation-site/pages/components/icon.mdx
Labels: bugfix

#1018 fix(tag): make text override-able
  src/tag/tag.js
  src/tag/types.js
Labels: bugfix

#1020 Release v6.6.0
  package.json
Labels: release

#1021 docs(theme): shape of theme
  documentation-site/pages/theming/custom-themes.mdx
Labels: feature

#1023 fix(popover): ensure priority event timing
  src/popover/__tests__/popover.test.js
  src/popover/popover.js
Labels: bugfix

#1024 fix(button): dropdown example closes on click outside
  documentation-site/static/examples/button/dropdown.js
Labels: bugfix, documentation

#1025 docs: add link for the bedrock setup
  documentation-site/pages/getting-started/installation.mdx
Labels: documentation, feature

#1027 fix: select prop typo
  src/select/types.js
Labels: bugfix, documentation

#1034 feat: add data-baseweb attribute
  src/accordion/accordion.js
  src/avatar/avatar.js
  src/block/block.js
  src/breadcrumbs/__tests__/__snapshots__/breadcrumbs.test.js.snap
  src/breadcrumbs/breadcrumbs.js
  src/button-group/button-group.js
  src/button/button.js
  src/card/card.js
  src/checkbox/checkbox.js
  src/datepicker/calendar.js
  src/dnd-list/list.js
  src/file-uploader/file-uploader.js
  src/form-control/form-control.js
  src/header-navigation/__tests__/__snapshots__/header-navigation.test.js.snap
  src/header-navigation/header-navigation.js
  src/icon/__tests__/__snapshots__/icon.test.js.snap
  src/icon/icon.js
  src/input/__tests__/__snapshots__/input.test.js.snap
  src/input/base-input.js
  src/input/input.js
  src/input/types.js
  src/link/index.js
  src/menu/menu.js
  src/modal/__tests__/__snapshots__/modal.test.js.snap
  src/modal/modal.js
  src/notification/notification.js
  src/pagination/pagination.js
  src/popover/__tests__/__snapshots__/popover.test.js.snap
  src/popover/__tests__/popover.test.js
  src/popover/popover.js
  src/popover/types.js
  src/progress-bar/__tests__/__snapshots__/progressbar.test.js.snap
  src/progress-bar/progressbar.js
  src/progress-steps/progress-steps.js
  src/radio/radio.js
  src/rating/emoticon-rating.js
  src/rating/star-rating.js
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/select.js
  src/slider/slider.js
  src/spinner/spinner.js
  src/table/__tests__/table.test.js
  src/table/index.js
  src/table/table.js
  src/tabs/__tests__/__snapshots__/stateful-tabs.test.js.snap
  src/tabs/tabs.js
  src/tag/__tests__/__snapshots__/tag.test.js.snap
  src/tag/tag.js
  src/template-component/component.js
  src/textarea/__tests__/__snapshots__/textarea.test.js.snap
  src/textarea/textarea.js
  src/toast/toast.js
  src/toast/toaster.js
  src/toast/types.js
  src/tooltip/__tests__/tooltip.test.js
  src/tooltip/tooltip.js
  src/typography/index.js
Labels: feature

#1028 fix: add controlled checkbox example
  documentation-site/pages/components/checkbox.mdx
  documentation-site/static/examples/checkbox/basic-controlled.js
  documentation-site/static/examples/checkbox/basic-uncontrolled.js
Labels: bugfix, documentation

#1029 fix: add native select example
  documentation-site/pages/components/select.mdx
  documentation-site/static/examples/select/native.js
Labels: bugfix, documentation

#1031 feat(select): adds support to mountNode
  src/select/select.js
  src/select/types.js
Labels: feature

#1036 Release v6.7.0
  package.json
Labels: release

#1037 fix(docs): native select clarification
  documentation-site/pages/components/select.mdx
Labels: bugfix

#1038 fix(spinner): size and color props
  src/icon/styled-components.js
  src/spinner/__tests__/component.test.js
  src/spinner/spinner.js
Labels: bugfix

#1039 Release v6.7.1
  package.json
Labels: release

#1040 fix(types): change handler returns mixed instead of any
  package.json
  src/accordion/types.js
  src/button/types.js
  src/checkbox/types.js
  src/input/types.js
  src/modal/types.js
  src/popover/types.js
  src/radio/types.js
  src/rating/types.js
  src/select/types.js
  src/slider/types.js
  src/tabs/types.js
  src/tag/types.js
  src/textarea/types.js
  src/toast/toast.js
  src/toast/toaster.js
  src/toast/types.js
  yarn.lock
Labels: bugfix

#1042 Release v6.7.2
  package.json
Labels: release

#1046 fix(accordion): remove outline flickering
  src/accordion/styled-components.js
Labels: bugfix

#1032 feat(datepicker): adds support to error
  src/datepicker/datepicker.js
  src/datepicker/types.js
Labels: feature

#1047 fix(menu): handles unclosed state, virtual example works
  documentation-site/static/examples/menu/virtual-list.js
  src/menu/__tests__/menu.e2e.js
  src/menu/menu.js
  src/menu/stateful-container.js
Labels: bugfix

#1048 feat(theme): add icons to themes
  documentation-site/pages/theming/overriding-icons.mdx
  documentation-site/routes.js
  documentation-site/static/examples/theme/icon-overrides.js
  src/icon/alert.js
  src/icon/arrow-down.js
  src/icon/arrow-left.js
  src/icon/arrow-right.js
  src/icon/arrow-up.js
  src/icon/build-icons.js
  src/icon/check-indeterminate.js
  src/icon/check.js
  src/icon/chevron-left.js
  src/icon/chevron-right.js
  src/icon/delete-alt.js
  src/icon/delete.js
  src/icon/filter.js
  src/icon/grab.js
  src/icon/icon-template.txt
  src/icon/menu.js
  src/icon/overflow.js
  src/icon/plus.js
  src/icon/search.js
  src/icon/spinner.js
  src/icon/triangle-down.js
  src/icon/triangle-left.js
  src/icon/triangle-right.js
  src/icon/triangle-up.js
  src/icon/upload.js
  src/styles/types.js
Labels: feature

#1049 Release v6.8.0
  package.json
Labels: release

#1050 fix(tabs): enables more nested override patterns
  documentation-site/pages/components/tabs.mdx
  documentation-site/static/examples/tabs/basic.js
  documentation-site/static/examples/tabs/controlled.js
  documentation-site/static/examples/tabs/vertical.js
  src/tabs/__tests__/__snapshots__/stateful-tabs.test.js.snap
  src/tabs/__tests__/stateful-tabs.test.js
  src/tabs/__tests__/tabs.scenario.js
  src/tabs/index.js
  src/tabs/tab-panel.js
  src/tabs/tabs.js
  src/tabs/types.js
Labels: bugfix

#1053 fix(rating): use rating400 for emoticon
  src/rating/styled-components.js
Labels: bugfix

#1055 Release v6.8.1
  package.json
Labels: release

#1058 chore: delete the outdated fusion example
  examples/fusion/README.md
  examples/fusion/flow-typed/globals.js
  examples/fusion/package.json
  examples/fusion/src/main.js
  examples/fusion/src/pages/home.js
  examples/fusion/src/pages/pageNotFound.js
  examples/fusion/src/root.js
  examples/fusion/yarn.lock
Labels: documentation, greenkeeping

#1019 feat(sidenav): initial implementation of the side navigation component
  documentation-site/components/layout.js
  documentation-site/components/nav-link.js
  documentation-site/components/sidebar.js
  documentation-site/pages/components/sidenav.mdx
  documentation-site/routes.js
  documentation-site/static/examples/side-navigation/basic.js
  documentation-site/static/examples/side-navigation/nav-overrides.js
  src/side-navigation/README.md
  src/side-navigation/__tests__/__snapshots__/stateful-container.test.js.snap
  src/side-navigation/__tests__/__snapshots__/stateful-nav.test.js.snap
  src/side-navigation/__tests__/nav.e2e.js
  src/side-navigation/__tests__/nav.scenario.js
  src/side-navigation/__tests__/nav.test.js
  src/side-navigation/__tests__/stateful-container.test.js
  src/side-navigation/__tests__/stateful-nav.test.js
  src/side-navigation/constants.js
  src/side-navigation/index.js
  src/side-navigation/nav-item.js
  src/side-navigation/nav.js
  src/side-navigation/stateful-container.js
  src/side-navigation/stateful-nav.js
  src/side-navigation/styled-components.js
  src/side-navigation/types.js
Labels: feature

#1061 Release v6.9.0
  package.json
Labels: release

#1056 feat(datepicker): dark theme colors
  documentation-site/components/overrides.js
  src/datepicker/styled-components.js
  src/styles/types.js
  src/themes/creator.js
  src/themes/dark-theme-colors.js
Labels: feature

#1062 fix(tabs): ensures proper rendering with no children
  src/tabs/__tests__/__snapshots__/stateful-tabs.test.js.snap
  src/tabs/__tests__/tabs-controlled.scenario.js
  src/tabs/tabs.js
  src/tabs/types.js
Labels: bugfix

#1071 fix(package): ignore test files
  .npmignore
Labels: bugfix

#1072 fix(toast): tabindex on close
  src/toast/__tests__/toast.e2e.js
  src/toast/toast.js
Labels: bugfix

#1052 fix(styles): import react for types
  src/styles/types.js
Labels: bugfix

#1070 fix(select): removes the need to compare the element instance
  src/select/select.js
Labels: bugfix

#1073 fix(toast): use flex
  src/toast/__tests__/toast.scenario.js
  src/toast/styled-components.js
  src/toast/toast.js
Labels: bugfix

#1074 Release v6.10.0
  package.json
Labels: release

#1064 feat(button): dark theme colors
  src/themes/dark-theme-colors.js
Labels: feature

#1063 feat(control-components): audit dark theme colors
  documentation-site/pages/components/radio.mdx
  documentation-site/static/examples/radio/disabled.js
  src/checkbox/styled-components.js
  src/radio/styled-components.js
  src/slider/styled-components.js
  src/styles/types.js
  src/themes/creator.js
  src/themes/dark-theme-colors.js
Labels: feature

#1076 feat(radio): adds description
  documentation-site/static/examples/radio/basic.js
  src/radio/__tests__/radio.scenario.js
  src/radio/__tests__/radio.test.js
  src/radio/index.js
  src/radio/radio.js
  src/radio/styled-components.js
  src/radio/types.js
Labels: feature

#1075 feat(inputs): dark theme
  documentation-site/pages/_app.js
  src/file-uploader/styled-components.js
  src/menu/styled-components.js
  src/styles/types.js
  src/themes/creator.js
  src/themes/dark-theme-colors.js
Labels: feature

#1081 fix(theme): add scale550 to type defs
  src/styles/types.js
Labels: bugfix

#1082 fix(icon): applies isolated styles to globally overridden icons
  documentation-site/routes.js
  src/accordion/styled-components.js
  src/icon/alert.js
  src/icon/arrow-down.js
  src/icon/arrow-left.js
  src/icon/arrow-right.js
  src/icon/arrow-up.js
  src/icon/check-indeterminate.js
  src/icon/check.js
  src/icon/chevron-left.js
  src/icon/chevron-right.js
  src/icon/delete-alt.js
  src/icon/delete.js
  src/icon/filter.js
  src/icon/grab.js
  src/icon/icon-template.txt
  src/icon/menu.js
  src/icon/overflow.js
  src/icon/plus.js
  src/icon/search.js
  src/icon/spinner.js
  src/icon/triangle-down.js
  src/icon/triangle-left.js
  src/icon/triangle-right.js
  src/icon/triangle-up.js
  src/icon/upload.js
Labels: bugfix

#1080 fix(table): add roles to styled components
  src/table/styled-components.js
  src/table/table.js
Labels: bugfix

#1078 feat(input): adds autocomplete prop
  src/input/__tests__/__snapshots__/base-input.test.js.snap
  src/input/__tests__/__snapshots__/input.test.js.snap
  src/input/__tests__/__snapshots__/masked-input.test.js.snap
  src/input/__tests__/__snapshots__/stateful-input.test.js.snap
  src/input/base-input.js
  src/input/input.js
  src/input/types.js
  src/textarea/__tests__/__snapshots__/textarea.test.js.snap
Labels: feature

#1083 Release v6.11.0
  package.json
Labels: release

#1084 docs(button): button as an anchor
  documentation-site/pages/components/button.mdx
  documentation-site/static/examples/button/as-an-anchor.js
Labels: documentation, feature

#1086 feat(select): creatable
  documentation-site/pages/components/select.mdx
  documentation-site/static/examples/select/creatable-multi.js
  documentation-site/static/examples/select/creatable.js
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/__tests__/select-creatable.scenario.js
  src/select/__tests__/select.e2e.js
  src/select/default-props.js
  src/select/locale.js
  src/select/select.js
  src/select/types.js
Labels: feature

#1088 fix(link): re-enable styletron overrides
  src/link/index.js
Labels: bugfix

#1087 fix(select): don't suggest creation of an option that was already picked
  src/select/__tests__/select-creatable-multi.scenario.js
  src/select/__tests__/select.e2e.js
  src/select/select.js
Labels: bugfix

#1089 Release v6.12.0
  package.json
Labels: release

#1090 fix(radio): reduces margin if description provided
  src/radio/radio.js
  src/radio/styled-components.js
Labels: bugfix

#1091 Revert "fix(icon): applies isolated styles to globally overridden icons"
  documentation-site/routes.js
  src/accordion/styled-components.js
  src/icon/alert.js
  src/icon/arrow-down.js
  src/icon/arrow-left.js
  src/icon/arrow-right.js
  src/icon/arrow-up.js
  src/icon/check-indeterminate.js
  src/icon/check.js
  src/icon/chevron-left.js
  src/icon/chevron-right.js
  src/icon/delete-alt.js
  src/icon/delete.js
  src/icon/filter.js
  src/icon/grab.js
  src/icon/icon-template.txt
  src/icon/menu.js
  src/icon/overflow.js
  src/icon/plus.js
  src/icon/search.js
  src/icon/spinner.js
  src/icon/triangle-down.js
  src/icon/triangle-left.js
  src/icon/triangle-right.js
  src/icon/triangle-up.js
  src/icon/upload.js
Labels: bugfix

#1093 fix(accordion): icon layout evenly if overridden
  documentation-site/routes.js
  src/accordion/styled-components.js
Labels: bugfix

#1092 Release v6.12.1
  package.json
Labels: release

#1094 fix(table): styledHead is missing styletron reassign
  src/table/styled-components.js
Labels: bugfix

#1095 Release v6.12.2
  package.json
Labels: release

#1096 fix(docs-site): bump react version in sandbox
  documentation-site/components/example.js
Labels: bugfix

#1097 docs(contrib): update
  CONTRIBUTING.md
Labels: bugfix, docs

#1060 docs: add proposal for component heading
  proposals/heading-component.md
Labels: docs

#1098 fix(styles): use longhand everywhere
  src/avatar/styled-components.js
  src/card/styled-components.js
  src/modal/styled-components.js
  src/popover/styled-components.js
  src/progress-bar/styled-components.js
  src/slider/styled-components.js
  src/tooltip/styled-components.js
Labels: bugfix
