Repository uber/baseweb, pull requests merged in 2019-10, with the labels that each got.

#1977 Release v9.6.0
  package.json
Labels: release

#1976 docs(yard): textarea
  documentation-site/components/yard/config/input.ts
  documentation-site/components/yard/config/textarea.ts
  documentation-site/pages/components/textarea.mdx
  package.json
  src/textarea/constants.js
  src/textarea/index.d.ts
  yarn.lock
Labels: docs

#1967 docs(checkbox): add yard
  documentation-site/components/yard/code-generator.ts
  documentation-site/components/yard/config/checkbox.ts
  documentation-site/components/yard/knob.tsx
  documentation-site/components/yard/knobs.tsx
  documentation-site/components/yard/types.ts
  documentation-site/components/yard/yard.tsx
  documentation-site/pages/components/checkbox.mdx
  src/checkbox/constants.js
  src/checkbox/index.d.ts
  src/checkbox/index.js
Labels: docs

#1984 docs(textarea): add back exports
  documentation-site/pages/components/textarea.mdx
Labels: docs

#1979 feat(yard): cleaning up the code, config shape changes, better types
  documentation-site/components/yard/__tests__/ast.test.ts
  documentation-site/components/yard/__tests__/code-generator.test.ts
  documentation-site/components/yard/actions.ts
  documentation-site/components/yard/ast.ts
  documentation-site/components/yard/code-generator.ts
  documentation-site/components/yard/config/button-group.ts
  documentation-site/components/yard/config/button.ts
  documentation-site/components/yard/config/checkbox.ts
  documentation-site/components/yard/config/input.ts
  documentation-site/components/yard/config/tabs.ts
  documentation-site/components/yard/config/textarea.ts
  documentation-site/components/yard/editor.tsx
  documentation-site/components/yard/index.tsx
  documentation-site/components/yard/knob.tsx
  documentation-site/components/yard/knobs.tsx
  documentation-site/components/yard/override.tsx
  documentation-site/components/yard/overrides.tsx
  documentation-site/components/yard/reducer.ts
  documentation-site/components/yard/styled-components.tsx
  documentation-site/components/yard/types.ts
  documentation-site/components/yard/utils.ts
  documentation-site/components/yard/yard.tsx
Labels: feature

#1919 fix(build): changes to es modules mapping
  package.json
  scripts/build-package-json.js
  scripts/flow-copy-src.js
  src/index.js
Labels: bugfix, build/tooling

#1985 Release v9.6.1
  package.json
Labels: release

#1986 fix(build): copy package.json to the dist
  package.json
Labels: bugfix, build/tooling

#1990 Release v9.6.2
  package.json
Labels: release

#1978 docs(yard): add pin
  documentation-site/@types/just-omit.d.ts
  documentation-site/components/yard/compiler.tsx
  documentation-site/components/yard/config/pin-code.ts
  documentation-site/components/yard/config/textarea.ts
  documentation-site/components/yard/yard.tsx
  documentation-site/pages/components/pin-code.mdx
  src/pin-code/index.js
Labels: docs

#1989 docs(use-styletron): fix example
  documentation-site/examples/styled/basic.js
  documentation-site/examples/styled/basic.tsx
  documentation-site/examples/use-styletron/basic.js
  documentation-site/examples/use-styletron/basic.tsx
Labels: docs

#1970 fix(phone-input): fix the behavior of highlighted item
  src/menu/__tests__/utils.test.js
  src/menu/stateful-container.js
  src/menu/utils.js
  src/phone-input/__tests__/country-select-small-dropdown.scenario.js
  src/phone-input/country-select.js
  src/phone-input/phone-input.js
Labels: bugfix

#1993 docs(ga): track clean urls
  documentation-site/pages/_app.js
Labels: docs

#1983 docs(yard): add radio
  documentation-site/@types/just-clone.d.ts
  documentation-site/components/yard/__tests__/code-generator.test.ts
  documentation-site/components/yard/code-generator.ts
  documentation-site/components/yard/config/button-group.ts
  documentation-site/components/yard/config/button.ts
  documentation-site/components/yard/config/checkbox.ts
  documentation-site/components/yard/config/input.ts
  documentation-site/components/yard/config/pin-code.ts
  documentation-site/components/yard/config/radio.ts
  documentation-site/components/yard/config/tabs.ts
  documentation-site/components/yard/config/textarea.ts
  documentation-site/components/yard/types.ts
  documentation-site/components/yard/utils.ts
  documentation-site/pages/components/radio.mdx
  package.json
  tsconfig.json
  yarn.lock
Labels: docs, feature

#1988 fix(phone-input): removes block component
  src/phone-input/country-select.js
  src/phone-input/index.d.ts
  src/phone-input/styled-components.js
  src/phone-input/types.js
Labels: bugfix

#1999 fix(popover): fix type definition
  src/popover/index.d.ts
Labels: bugfix

#2000 fix(build): Run `prebuild` in the docs dev builds
  package.json
Labels: bugfix, build/tooling

#1997 docs(yard): add phone input
  documentation-site/components/yard/config/phone-input.ts
  documentation-site/components/yard/knob.tsx
  documentation-site/pages/components/phone-input.mdx
Labels: docs

#2002 docs(yard): add payment card
  documentation-site/components/yard/config/payment-card.ts
  documentation-site/pages/components/payment-card.mdx
Labels: docs

#1982 fix(datepicker): fix color of day of one-day range (#1980)
  src/datepicker/styled-components.js
Labels: bugfix

#2005 docs(yard): add file-uploader
  documentation-site/components/yard/config/file-uploader.ts
  documentation-site/pages/components/file-uploader.mdx
  src/file-uploader/types.js
Labels: docs

#2006 docs(now): move to now
  build-now.sh
  now.json
  package.json
Labels: build/tooling, greenkeeping

#2008 feat(yard): better knob sizing, editor bug
  documentation-site/components/yard/code-generator.ts
  documentation-site/components/yard/config/radio.ts
  documentation-site/components/yard/editor.tsx
  documentation-site/components/yard/knob.tsx
  src/select/index.d.ts
Labels: bugfix

#2009 Release v9.6.3
  package.json
Labels: release

#1996 feat(phone-input): allow consumer to provide countries list
  src/phone-input/__tests__/phone-input.scenario.js
  src/phone-input/country-select.js
  src/phone-input/default-props.js
  src/phone-input/index.d.ts
  src/phone-input/index.js
  src/phone-input/phone-input-lite.js
  src/phone-input/phone-input.js
  src/phone-input/stateful-phone-input-container.js
  src/phone-input/types.js
Labels: feature

#2015 Release v9.7.0
  package.json
Labels: release

#2017 docs(yard): add tag
  documentation-site/components/yard/code-generator.ts
  documentation-site/components/yard/config/phone-input.ts
  documentation-site/components/yard/config/tag.ts
  documentation-site/components/yard/knob.tsx
  documentation-site/components/yard/theme-editor.tsx
  documentation-site/components/yard/types.ts
  documentation-site/components/yard/utils.ts
  documentation-site/pages/components/tag.mdx
Labels: docs

#2013 docs(yard): create common changehandlers
  documentation-site/components/yard/config/checkbox.ts
  documentation-site/components/yard/config/common.ts
  documentation-site/components/yard/config/input.ts
  documentation-site/components/yard/config/radio.ts
  package.json
  yarn.lock
Labels: docs

#2010 docs(build): deploy buildkite
  .gitignore
  deploy.sh
  docker-compose.yml
  netlify.toml
  package.json
  yarn.lock
Labels: docs

#2012 docs(yard): add slider
  documentation-site/components/yard/config/slider.ts
  documentation-site/pages/components/slider.mdx
  src/slider/styled-components.js
Labels: docs

#2016 docs(yard): adds yard to avatar page
  documentation-site/components/yard/config/avatar.ts
  documentation-site/pages/components/avatar.mdx
Labels: docs

#2007 docs(yard): adds yard to breadcrumbs page
  documentation-site/components/yard/config/breadcrumbs.ts
  documentation-site/pages/components/breadcrumbs.mdx
Labels: docs

#2011 docs(yard): adds pagination component
  documentation-site/components/yard/config/pagination.ts
  documentation-site/components/yard/types.ts
  documentation-site/pages/components/pagination.mdx
Labels: docs

#2022 docs(deploy): only from master
  deploy.sh
Labels: build/tooling, docs

#2014 docs(yard): adds yard for side-nav
  documentation-site/components/yard/config/side-nav.ts
  documentation-site/pages/components/side-nav.mdx
Labels: docs

#2020 docs(tooltip): fix multiline comment in types
  src/popover/types.js
Labels: bugfix

#2027 docs(yard): debounce component, knobs, editor and theme editor
  documentation-site/components/yard/editor.tsx
  documentation-site/components/yard/knob.tsx
  documentation-site/components/yard/theme-editor.tsx
  documentation-site/components/yard/yard.tsx
  package.json
  yarn.lock
Labels: docs

#2031 chore(build): various improvements
  .flowconfig
  e2e.Dockerfile
  scripts/link-checker.sh
Labels: chore, docs

#2030 docs(modal): add sizing example
  documentation-site/examples/modal/sized.js
  documentation-site/examples/modal/sized.tsx
  documentation-site/pages/components/modal.mdx
Labels: ci, docs

#2026 fix(datepicker): properly disable first and last days of month
  scripts/link-checker.sh
  src/datepicker/styled-components.js
Labels: bugfix

#2032 docs(build): build only for the master
  deploy.sh
  e2e.Dockerfile
  package.json
Labels: build/tooling, docs

#2023 docs(yard): adds yard to rating component page
  documentation-site/components/yard/config/rating.ts
  documentation-site/pages/components/rating.mdx
Labels: docs

#2034 docs(yard): add spinner
  documentation-site/components/yard/config/spinner.ts
  documentation-site/pages/components/spinner.mdx
Labels: docs

#2033 docs(yard): add progress bar
  documentation-site/components/yard/config/progress-bar.ts
  documentation-site/pages/components/progress-bar.mdx
Labels: docs

#2037 fix(yard): edits knob debounce and adds form-control
  documentation-site/components/yard/compiler.tsx
  documentation-site/components/yard/config/form-control.ts
  documentation-site/components/yard/editor.tsx
  documentation-site/components/yard/knob.tsx
  documentation-site/components/yard/theme-editor.tsx
  documentation-site/components/yard/utils.ts
  documentation-site/components/yard/yard.tsx
  documentation-site/pages/components/form-control.mdx
  src/form-control/styled-components.js
Labels: bugfix

#2021 docs(yard): add accordion
  documentation-site/components/yard/config/accordion.ts
  documentation-site/pages/components/accordion.mdx
  src/accordion/__tests__/__snapshots__/accordion.test.js.snap
  src/accordion/__tests__/accordion-disabled.scenario.js
  src/accordion/accordion.js
  src/accordion/styled-components.js
  src/select/__tests__/select.scenario.js
Labels: docs

#2036 Release v9.7.1
  package.json
Labels: release

#2035 docs(yard): add card
  documentation-site/components/yard/config/card.ts
  documentation-site/pages/components/card.mdx
Labels: docs

#1991 fix(table): fix type of StyledTable
  src/table/index.d.ts
Labels: bugfix

#2040 docs(yard): cleanup docs, more robust code generation
  documentation-site/components/yard/__tests__/code-generator.test.ts
  documentation-site/components/yard/code-generator.ts
  documentation-site/components/yard/config/card.ts
  documentation-site/components/yard/config/side-nav.ts
  documentation-site/components/yard/knob.tsx
  documentation-site/pages/components/accordion.mdx
  documentation-site/pages/components/avatar.mdx
  documentation-site/pages/components/breadcrumbs.mdx
  documentation-site/pages/components/button-group.mdx
  documentation-site/pages/components/button.mdx
  documentation-site/pages/components/card.mdx
  documentation-site/pages/components/checkbox.mdx
  documentation-site/pages/components/file-uploader.mdx
  documentation-site/pages/components/form-control.mdx
  documentation-site/pages/components/input.mdx
  documentation-site/pages/components/pagination.mdx
  documentation-site/pages/components/phone-input.mdx
  documentation-site/pages/components/pin-code.mdx
  documentation-site/pages/components/progress-bar.mdx
  documentation-site/pages/components/radio.mdx
  documentation-site/pages/components/rating.mdx
  documentation-site/pages/components/side-nav.mdx
  documentation-site/pages/components/slider.mdx
  documentation-site/pages/components/spinner.mdx
  documentation-site/pages/components/tabs.mdx
  documentation-site/pages/components/textarea.mdx
Labels: docs

#2038 docs(yard): adds yard to select component page
  documentation-site/components/yard/code-generator.ts
  documentation-site/components/yard/config/select.ts
  documentation-site/pages/components/select.mdx
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/styled-components.js
  src/select/types.js
Labels: docs

#2041 docs(yard): add popover
  documentation-site/components/yard/config/common.ts
  documentation-site/components/yard/config/popover.ts
  documentation-site/pages/components/popover.mdx
  scripts/link-checker.sh
Labels: docs

#2042 fix(modal): update close button colors
  src/themes/creator.js
Labels: bugfix

#2004 fix(select): hightlight index
  src/select/__tests__/highlight-default.test.js
  src/select/__tests__/highlight.test.js
  src/select/__tests__/select-highlight.scenario.js
  src/select/dropdown.js
Labels: bugfix

#2043 fix(accordion): keep child overrides
  src/accordion/accordion.js
Labels: bugfix

#2049 fix(drawer): use the same close icon as the modal
  src/drawer/styled-components.js
Labels: bugfix

#2046 docs(yard): fix boolean prop handling with default value set to true
  documentation-site/components/yard/code-generator.ts
Labels: docs

#2019 feat(datepicker): add quickSelect locale
  src/datepicker/calendar.js
  src/datepicker/locale.js
Labels: bugfix

#2051 fix: revert boolean docs fix
  documentation-site/components/yard/code-generator.ts
Labels: bugfix

#2050 docs(yard): add tooltip
  documentation-site/components/yard/config/tooltip.ts
  documentation-site/pages/components/tooltip.mdx
  src/tooltip/index.d.ts
Labels: docs

#2047 docs(yard): adds yard to menu
  documentation-site/components/yard/config/menu.ts
  documentation-site/pages/components/menu.mdx
Labels: docs

#2052 docs(zeit): add support for forks
  docker-compose.yml
  scripts/link-checker.sh
Labels: build/tooling, docs

#2054 docs: fix the boolean prop rendering
  documentation-site/components/yard/code-generator.ts
Labels: docs

#2053 docs(list): adds yard to list-item
  documentation-site/components/yard/config/list-item.ts
  documentation-site/pages/components/list.mdx
  src/list/styled-components.js
Labels: feature

#2044 docs(yard): adds yard to notification component page
  documentation-site/components/yard/config/notification.ts
  documentation-site/pages/components/notification.mdx
Labels: docs

#2057 docs(yard): show the default value of enum type props & skip it in code example
  documentation-site/components/yard/__tests__/code-generator.test.ts
  documentation-site/components/yard/code-generator.ts
  documentation-site/components/yard/config/button.ts
  documentation-site/components/yard/config/checkbox.ts
  documentation-site/components/yard/config/input.ts
  documentation-site/components/yard/config/popover.ts
  documentation-site/components/yard/config/select.ts
  documentation-site/components/yard/config/tabs.ts
  documentation-site/components/yard/config/tag.ts
  documentation-site/components/yard/types.ts
  documentation-site/components/yard/utils.ts
  src/input/input.js
Labels: bugfix, docs

#2061 docs(yard): small fixes for card and checkbox
  documentation-site/components/yard/config/card.ts
  documentation-site/components/yard/config/checkbox.ts
Labels: docs

#2062 chore(github): update refs to the new url
  .github/ISSUE_TEMPLATE/1.bug.md
  CONTRIBUTING.md
  deploy.sh
  docs/migrations/00520.md
  docs/migrations/01390.md
  documentation-site/components/cheat-sheet.js
  documentation-site/components/footer.js
  documentation-site/components/header-navigation.js
  documentation-site/components/layout.js
  documentation-site/examples/table-grid/cell-span.js
  documentation-site/examples/table-grid/cell-span.tsx
  documentation-site/examples/table-grid/nested.js
  documentation-site/examples/table-grid/nested.tsx
  documentation-site/pages/blog/base-web-v8/index.mdx
  documentation-site/pages/blog/phone-input/index.mdx
  documentation-site/pages/blog/responsive-web/index.mdx
  documentation-site/pages/discover-more/versioning-policy.mdx
  documentation-site/pages/getting-started/learn.mdx
  documentation-site/pages/guides/internationalization.mdx
  documentation-site/pages/guides/theming.mdx
  documentation-site/pages/guides/understanding-overrides.mdx
  documentation-site/pages/index.js
  package.json
  packages/baseui-codemods/README.md
  scripts/build-docs.js
  scripts/link-checker.sh
  scripts/version-generator.js
  src/flex-grid/flex-grid-item.js
  src/input/__tests__/input.e2e.js
  src/menu/types.js
  src/styles/types.js
  src/table-grid/__tests__/table-grid-jobs.scenario.js
  src/table-grid/__tests__/table-grid-records.scenario.js
  src/tag/__tests__/tag.test.js
Labels: chore

#2063 fix(select): placeholder can be an empty string
  src/select/select-component.js
Labels: bugfix

#2064 chore(build): url check uses new url .
  scripts/link-checker.sh
Labels: docs

#2065 docs(select): remove startOpen example
  documentation-site/components/yard/config/select.ts
  documentation-site/examples/select/open.js
  documentation-site/examples/select/open.tsx
  documentation-site/pages/components/select.mdx
Labels: docs

#2055 docs(modal): adds yard to modal page
  documentation-site/components/yard/compiler.tsx
  documentation-site/components/yard/config/modal.ts
  documentation-site/components/yard/index.tsx
  documentation-site/pages/components/modal.mdx
Labels: docs

#2067 fix(package): remove engine restriction
  build-now.sh
  package.json
  scripts/build-documentation-site-files.js
  scripts/cheat-sheet-generator.js
  scripts/ts-copy.js
  scripts/validate-examples.js
Labels: bugfix

#2069 docs(yard): add table
  documentation-site/components/yard/config/table.ts
  documentation-site/pages/components/table.mdx
Labels: docs

#2068 docs(yard): add icon
  documentation-site/components/yard/config/icon.ts
  documentation-site/pages/components/icon.mdx
Labels: docs

#2070 docs(yard): add link
  documentation-site/components/yard/config/link.ts
  documentation-site/examples/link/basic.js
  documentation-site/examples/link/basic.tsx
  documentation-site/pages/components/link.mdx
Labels: docs

#2060 test(e2e): add screenshots
  .buildkite/pipeline.yml
  jest.e2e.config.js
  jest.e2e.setup.js
Labels: bugfix, build/tooling, enhancement

#2056 docs(header-navigation): adds yard to docs page
  documentation-site/components/yard/config/header-navigation.ts
  documentation-site/pages/components/header-navigation.mdx
Labels: docs

#2059 docs(drawer): adds yard to docs page
  documentation-site/components/yard/config/avatar.ts
  documentation-site/components/yard/config/drawer.ts
  documentation-site/pages/components/drawer.mdx
Labels: docs

#2071 docs(yard): adds yard to dnd list component page
  documentation-site/components/yard/config/dnd-list.ts
  documentation-site/pages/components/dnd-list.mdx
Labels: docs

#2078 bug(styletron): updates dependency to 5.2.2
  package.json
  yarn.lock
Labels: bug

#2058 docs(yard): add progress-steps
  documentation-site/components/yard/__tests__/ast.test.ts
  documentation-site/components/yard/actions.ts
  documentation-site/components/yard/ast.ts
  documentation-site/components/yard/config/progress-steps-numbered.ts
  documentation-site/components/yard/config/progress-steps.ts
  documentation-site/components/yard/index.tsx
  documentation-site/components/yard/types.ts
  documentation-site/components/yard/yard.tsx
  documentation-site/pages/components/progress-steps.mdx
Labels: docs

#2081 fix(tag): do not call onClick for the action
  src/tag/__tests__/__snapshots__/tag.test.js.snap
  src/tag/__tests__/tag.test.js
  src/tag/tag.js
Labels: bugfix

#2082 chore: update dubstep/core
  packages/baseui-codemods/package.json
  packages/baseui-codemods/yarn.lock
Labels: dependencies

#2075 docs(yard): adds yard to toast component page
  documentation-site/components/yard/config/notification.ts
  documentation-site/components/yard/config/toast.ts
  documentation-site/pages/components/toast.mdx
  src/toast/index.d.ts
  src/toast/toaster.js
  src/toast/types.js
Labels: docs

#2066 Release v9.8.0
  package.json
Labels: release

#2091 fix(pagination): button overrides
  documentation-site/components/yard/config/pagination.ts
  src/pagination/pagination.js
Labels: bugfix

#2106 fix(dnd-list): prevent list hover being triggered when dragging
  src/dnd-list/styled-components.js
Labels: bugfix

#2107 docs(yard): add codesandbox
  documentation-site/components/const.js
  documentation-site/components/example.js
  documentation-site/components/yard/yard.tsx
Labels: docs

#2112 docs(datepicker): add formatString and mask props
  documentation-site/components/yard/config/datepicker.ts
Labels: docs

#2080 test(vrt): update snapshots during ci
  .buildkite/pipeline.yml
  .github/CODEOWNERS
  docker-compose.yml
  package.json
  vrt/ci.js
  yarn.lock
Labels: build/tooling, discussion

#2092 fix(select): select-arrow override
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/select-component.js
  vrt/__image_snapshots__/pagination-rtl-snap.png
  vrt/__image_snapshots__/pagination-snap.png
  vrt/__image_snapshots__/table-pagination-snap.png
Labels: bugfix

#2072 feat(treeview): initial implementation of tree view
  documentation-site/examples/tree-view/controlled.js
  documentation-site/examples/tree-view/controlled.tsx
  documentation-site/examples/tree-view/custom-label.js
  documentation-site/examples/tree-view/custom-label.tsx
  documentation-site/examples/tree-view/overrides.js
  documentation-site/examples/tree-view/overrides.tsx
  documentation-site/examples/tree-view/uncontrolled.js
  documentation-site/examples/tree-view/uncontrolled.tsx
  documentation-site/pages/components/tree-view.mdx
  documentation-site/routes.js
  src/tree-view/__tests__/tree-view.e2e.js
  src/tree-view/__tests__/tree-view.scenario.js
  src/tree-view/__tests__/tree-view.test.js
  src/tree-view/index.d.ts
  src/tree-view/index.js
  src/tree-view/stateful-container.js
  src/tree-view/stateful-tree-view.js
  src/tree-view/styled-components.js
  src/tree-view/tree-node.js
  src/tree-view/tree-view.js
  src/tree-view/types.js
  vrt/__image_snapshots__/tree-view-snap.png
Labels: feature

#2114 docs(help): add floating help button
  documentation-site/components/help.js
  documentation-site/components/layout.js
Labels: docs

#2109 Release v9.9.0
  package.json
Labels: release

#2129 test(vrt): resolve race-condition with e2e tests
  .buildkite/pipeline.yml
  docker-compose.yml
  jest-puppeteer.config.js
  package.json
Labels: bugfix

#2117 fix(vrt): ci snapshots
  vrt/ci.js
  vrt/tests.vrt.js
Labels: bugfix

#2095 feat(data-table): adds row/column hover highlights
  src/data-table/__tests__/data-table-batch-action.e2e.js
  src/data-table/data-table.js
  src/data-table/measure-column-widths.js
  vrt/__image_snapshots__/data-table--dark-snap.png
  vrt/__image_snapshots__/data-table--mobile-snap.png
  vrt/__image_snapshots__/data-table-batch-action--dark-snap.png
  vrt/__image_snapshots__/data-table-batch-action--mobile-snap.png
  vrt/__image_snapshots__/data-table-batch-action-snap.png
  vrt/__image_snapshots__/data-table-columns--dark-snap.png
  vrt/__image_snapshots__/data-table-columns--mobile-snap.png
  vrt/__image_snapshots__/data-table-columns-snap.png
  vrt/__image_snapshots__/data-table-snap.png
Labels: feature

#2135 test(ci): remove screener from ci pipeline
  .buildkite/pipeline.yml
  docker-compose.yml
  documentation-site/examples/table-grid/nested.js
  documentation-site/examples/table-grid/nested.tsx
  flow-typed/npm/screener-storybook_vx.x.x.js
  package.json
  screener.config.js
  src/datepicker/__tests__/datepicker-range-highlight.scenario.js
  src/input/__tests__/input-password.scenario.js
  src/layer/__tests__/layer-z-index.scenario.js
  src/phone-input/__tests__/country-select-dropdown.scenario.js
  src/phone-input/__tests__/country-select-small-dropdown.scenario.js
  src/progress-steps/__tests__/progress-steps.scenario.js
  src/rating/__tests__/rating-star.scenario.js
  src/select/__tests__/select-highlight.scenario.js
  src/select/__tests__/select-in-modal.scenario.js
  src/select/__tests__/select-search-single.scenario.js
  src/table-grid/__tests__/table-grid-jobs.scenario.js
  yarn.lock
Labels: feature

#2119 feat(table-grid): stabilize the component
  documentation-site/examples/table-grid/basic.js
  documentation-site/examples/table-grid/basic.tsx
  documentation-site/examples/table-grid/cell-span.js
  documentation-site/examples/table-grid/cell-span.tsx
  documentation-site/examples/table-grid/nested.js
  documentation-site/examples/table-grid/nested.tsx
  documentation-site/pages/components/table-grid.mdx
  src/table-grid/__tests__/table-grid-jobs.scenario.js
  src/table-grid/__tests__/table-grid-records.scenario.js
  src/table-grid/__tests__/table-grid.scenario.js
  src/table-grid/index.d.ts
  src/table-grid/index.js
Labels: feature

#2143 fix(vrt): guard against recursive builds
  vrt/ci.js
Labels: bugfix

#2146 build(compose): do not expose port to host machine
  .buildkite/pipeline.yml
  docker-compose.yml
  package.json
Labels: bugfix, build/tooling

#2145 fix(radio): add align prop to ts defs
  documentation-site/components/yard/config/radio.ts
  src/radio/constants.js
  src/radio/index.d.ts
  src/radio/index.js
  src/radio/types.js
Labels: bugfix

#2147 test(vrt): fix prs on forked repos
  docker-compose.yml
  vrt/ci.js
Labels: bugfix

#2148 fix(vrt): get owner logic
  vrt/ci.js
Labels: bugfix

#2156 docs(yard): fix overrides in notification config
  documentation-site/components/yard/config/notification.ts
Labels: docs

#2158 fix(tether): ensures no flow errors from tether
  package.json
  src/layer/__tests__/tether.test.js
  src/layer/tether.js
  yarn.lock
Labels: bugfix

#2159 docs(blog-post): removes getMediaQuery from responsive blog post
  documentation-site/pages/blog/responsive-web/index.mdx
Labels: docs

#2157 Release v9.10.0
  package.json
Labels: release

#2153 docs(survey): automated csat collection
  documentation-site/components/layout.js
  documentation-site/components/survey.js
  documentation-site/helpers/ga.ts
  documentation-site/pages/_app.js
  documentation-site/pages/_document.js
  package.json
  yarn.lock
Labels: docs

#2160 fix(vrt): pull requests from forks
  vrt/ci.js
Labels: bugfix

#2162 docs(datepicker): composed datepicker should not use range mask
  documentation-site/examples/datepicker/composed-range-pickers.js
  documentation-site/examples/datepicker/composed-range-pickers.tsx
  src/datepicker/index.d.ts
Labels: docs

#2163 chore(node): update to 12.13.0
  Dockerfile
Labels: greenkeeping

#1563 feat(table-semantic): add table-semantic components
  documentation-site/components/gallery.js
  documentation-site/components/yard/config/table-semantic.ts
  documentation-site/examples/table-semantic/basic.js
  documentation-site/examples/table-semantic/basic.tsx
  documentation-site/examples/table-semantic/builder.js
  documentation-site/examples/table-semantic/builder.tsx
  documentation-site/examples/table-semantic/scroll.js
  documentation-site/examples/table-semantic/scroll.tsx
  documentation-site/examples/table-semantic/sortable.js
  documentation-site/examples/table-semantic/sortable.tsx
  documentation-site/examples/table-semantic/span.js
  documentation-site/examples/table-semantic/span.tsx
  documentation-site/examples/table-semantic/toggleable.js
  documentation-site/examples/table-semantic/toggleable.tsx
  documentation-site/pages/components/table-semantic.mdx
  documentation-site/routes.js
  scripts/link-checker.sh
  src/icon/blank.js
  src/icon/icon-exports.js
  src/icon/svg/alert.svg
  src/icon/svg/blank.svg
  src/styles/types.js
  src/table-semantic/__tests__/table-builder.e2e.js
  src/table-semantic/__tests__/table-builder.test.js
  src/table-semantic/__tests__/table-semantic-builder.scenario.js
  src/table-semantic/__tests__/table-semantic-compose.scenario.js
  src/table-semantic/__tests__/table-semantic.scenario.js
  src/table-semantic/__tests__/table.e2e.js
  src/table-semantic/__tests__/table.test.js
  src/table-semantic/index.d.ts
  src/table-semantic/index.js
  src/table-semantic/styled-components.js
  src/table-semantic/table-builder-column.js
  src/table-semantic/table-builder.js
  src/table-semantic/table.js
  src/table-semantic/types.js
  src/table/index.d.ts
  vrt/__image_snapshots__/table-semantic-builder__dark-snap.png
  vrt/__image_snapshots__/table-semantic-builder__desktop-snap.png
  vrt/__image_snapshots__/table-semantic-builder__mobile-snap.png
  vrt/__image_snapshots__/table-semantic-compose__dark-snap.png
  vrt/__image_snapshots__/table-semantic-compose__desktop-snap.png
  vrt/__image_snapshots__/table-semantic-compose__mobile-snap.png
  vrt/__image_snapshots__/table-semantic__dark-snap.png
  vrt/__image_snapshots__/table-semantic__desktop-snap.png
  vrt/__image_snapshots__/table-semantic__mobile-snap.png
  yarn.lock
Labels: feature

#2169 Update learn.mdx
  documentation-site/pages/getting-started/learn.mdx
Labels: bugfix

#2164 feat(yard): hover tokens to show prop type
  documentation-site/components/yard/ast.ts
  documentation-site/components/yard/config/accordion.ts
  documentation-site/components/yard/config/avatar.ts
  documentation-site/components/yard/config/breadcrumbs.ts
  documentation-site/components/yard/config/button-group.ts
  documentation-site/components/yard/config/button.ts
  documentation-site/components/yard/config/card.ts
  documentation-site/components/yard/config/checkbox.ts
  documentation-site/components/yard/config/datepicker.ts
  documentation-site/components/yard/config/dnd-list.ts
  documentation-site/components/yard/config/drawer.ts
  documentation-site/components/yard/config/file-uploader.ts
  documentation-site/components/yard/config/form-control.ts
  documentation-site/components/yard/config/header-navigation.ts
  documentation-site/components/yard/config/icon.ts
  documentation-site/components/yard/config/input.ts
  documentation-site/components/yard/config/list-item.ts
  documentation-site/components/yard/config/menu.ts
  documentation-site/components/yard/config/modal.ts
  documentation-site/components/yard/config/notification.ts
  documentation-site/components/yard/config/pagination.ts
  documentation-site/components/yard/config/payment-card.ts
  documentation-site/components/yard/config/phone-input.ts
  documentation-site/components/yard/config/pin-code.ts
  documentation-site/components/yard/config/popover.ts
  documentation-site/components/yard/config/progress-bar.ts
  documentation-site/components/yard/config/progress-steps-numbered.ts
  documentation-site/components/yard/config/progress-steps.ts
  documentation-site/components/yard/config/radio.ts
  documentation-site/components/yard/config/rating.ts
  documentation-site/components/yard/config/select.ts
  documentation-site/components/yard/config/side-nav.ts
  documentation-site/components/yard/config/slider.ts
  documentation-site/components/yard/config/spinner.ts
  documentation-site/components/yard/config/table.ts
  documentation-site/components/yard/config/tabs.ts
  documentation-site/components/yard/config/tag.ts
  documentation-site/components/yard/config/textarea.ts
  documentation-site/components/yard/config/timepicker.ts
  documentation-site/components/yard/config/timezonepicker.ts
  documentation-site/components/yard/config/toast.ts
  documentation-site/components/yard/config/tooltip.ts
  documentation-site/components/yard/editor.tsx
  documentation-site/components/yard/props-tooltip.tsx
  documentation-site/components/yard/type-definition.js
  documentation-site/components/yard/types.ts
  documentation-site/components/yard/yard.tsx
  src/list/list-item.js
Labels: docs

#2138 feat(data-table): text search row filter
  documentation-site/examples/data-table/batch-action.js
  documentation-site/examples/data-table/batch-action.tsx
  documentation-site/pages/blog/responsive-web/index.mdx
  src/data-table/__tests__/animal-data.js
  src/data-table/__tests__/data-table-columns.e2e.js
  src/data-table/__tests__/data-table-text-search.e2e.js
  src/data-table/__tests__/data-table-text-search.scenario.js
  src/data-table/cell-shell.js
  src/data-table/column-boolean.js
  src/data-table/column-categorical.js
  src/data-table/column-custom.js
  src/data-table/column-numerical.js
  src/data-table/column-string.js
  src/data-table/data-table.js
  src/data-table/header-cell.js
  src/data-table/measure-column-widths.js
  src/data-table/text-search.js
  src/data-table/types.js
  vrt/__image_snapshots__/data-table--dark-snap.png
  vrt/__image_snapshots__/data-table--mobile-snap.png
  vrt/__image_snapshots__/data-table-batch-action--dark-snap.png
  vrt/__image_snapshots__/data-table-batch-action--mobile-snap.png
  vrt/__image_snapshots__/data-table-batch-action-snap.png
  vrt/__image_snapshots__/data-table-batch-action__dark-snap.png
  vrt/__image_snapshots__/data-table-batch-action__desktop-snap.png
  vrt/__image_snapshots__/data-table-batch-action__mobile-snap.png
  vrt/__image_snapshots__/data-table-columns--dark-snap.png
  vrt/__image_snapshots__/data-table-columns--mobile-snap.png
  vrt/__image_snapshots__/data-table-columns-snap.png
  vrt/__image_snapshots__/data-table-columns__dark-snap.png
  vrt/__image_snapshots__/data-table-columns__desktop-snap.png
  vrt/__image_snapshots__/data-table-columns__mobile-snap.png
  vrt/__image_snapshots__/data-table-snap.png
  vrt/__image_snapshots__/data-table-text-search--dark-snap.png
  vrt/__image_snapshots__/data-table-text-search--mobile-snap.png
  vrt/__image_snapshots__/data-table-text-search-snap.png
  vrt/__image_snapshots__/data-table-text-search__dark-snap.png
  vrt/__image_snapshots__/data-table-text-search__desktop-snap.png
  vrt/__image_snapshots__/data-table-text-search__mobile-snap.png
  vrt/__image_snapshots__/data-table__dark-snap.png
  vrt/__image_snapshots__/data-table__desktop-snap.png
  vrt/__image_snapshots__/data-table__mobile-snap.png
Labels: feature

#2170 docs(table-semantic): add unstable warning to docs page
  documentation-site/pages/components/table-semantic.mdx
Labels: docs

#2174 Release v9.11.0
  package.json
Labels: release

#2171 feat(checkbox): allow checkboxes to be unlabeled
  documentation-site/components/yard/config/checkbox.ts
  src/checkbox/__tests__/checkbox-unlabeled.scenario.js
  src/checkbox/__tests__/checkbox.e2e.js
  src/checkbox/checkbox.js
  src/checkbox/index.d.ts
  src/checkbox/types.js
  vrt/__image_snapshots__/checkbox-unlabeled__dark-snap.png
  vrt/__image_snapshots__/checkbox-unlabeled__desktop-snap.png
  vrt/__image_snapshots__/checkbox-unlabeled__mobile-snap.png
Labels: feature

#2166 fix(select): multi and single select has the same height
  documentation-site/examples/timepicker/timepicker.js
  documentation-site/examples/timepicker/timepicker.tsx
  e2e/dist/index.html
  src/pagination/pagination.js
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/select-component.js
  src/select/styled-components.js
  src/select/types.js
  src/timepicker/__tests__/time-picker.scenario.js
  vrt/__image_snapshots__/country-select-dropdown__dark-snap.png
  vrt/__image_snapshots__/country-select-dropdown__desktop-snap.png
  vrt/__image_snapshots__/country-select-dropdown__expanded-snap.png
  vrt/__image_snapshots__/country-select-dropdown__mobile-snap.png
  vrt/__image_snapshots__/country-select-small-dropdown__dark-snap.png
  vrt/__image_snapshots__/country-select-small-dropdown__desktop-snap.png
  vrt/__image_snapshots__/country-select-small-dropdown__expanded-snap.png
  vrt/__image_snapshots__/country-select-small-dropdown__mobile-snap.png
  vrt/__image_snapshots__/datepickers-color-states__dark-snap.png
  vrt/__image_snapshots__/datepickers-color-states__desktop-snap.png
  vrt/__image_snapshots__/datepickers-color-states__mobile-snap.png
  vrt/__image_snapshots__/datepickers-composed-range__dark-snap.png
  vrt/__image_snapshots__/datepickers-composed-range__desktop-snap.png
  vrt/__image_snapshots__/datepickers-composed-range__mobile-snap.png
  vrt/__image_snapshots__/datepickers-composed-single__dark-snap.png
  vrt/__image_snapshots__/datepickers-composed-single__desktop-snap.png
  vrt/__image_snapshots__/datepickers-composed-single__mobile-snap.png
  vrt/__image_snapshots__/phone-input-overrides__dark-snap.png
  vrt/__image_snapshots__/phone-input-overrides__desktop-snap.png
  vrt/__image_snapshots__/phone-input-overrides__mobile-snap.png
  vrt/__image_snapshots__/phone-input__dark-snap.png
  vrt/__image_snapshots__/phone-input__desktop-snap.png
  vrt/__image_snapshots__/phone-input__mobile-snap.png
  vrt/__image_snapshots__/select-creatable-multi__dark-snap.png
  vrt/__image_snapshots__/select-creatable-multi__desktop-snap.png
  vrt/__image_snapshots__/select-creatable-multi__mobile-snap.png
  vrt/__image_snapshots__/select-open__dark-snap.png
  vrt/__image_snapshots__/select-open__mobile-snap.png
  vrt/__image_snapshots__/select-overridden-menu__dark-snap.png
  vrt/__image_snapshots__/select-overridden-menu__desktop-snap.png
  vrt/__image_snapshots__/select-overridden-menu__mobile-snap.png
  vrt/__image_snapshots__/select-search-multi__dark-snap.png
  vrt/__image_snapshots__/select-search-multi__desktop-snap.png
  vrt/__image_snapshots__/select-search-multi__mobile-snap.png
  vrt/__image_snapshots__/slider-rtl__mobile-snap.png
  vrt/__image_snapshots__/time-picker__dark-snap.png
  vrt/__image_snapshots__/time-picker__desktop-snap.png
  vrt/__image_snapshots__/time-picker__mobile-snap.png
  vrt/tests.vrt.js
Labels: bugfix

#2136 docs(yard): react view proposal
  documentation-site/components/yard/README.md
Labels: docs

#2189 chore: add volta
  package.json
Labels: build/tooling, greenkeeping

#2192 chore(project): update deps
  package.json
  src/drawer/__tests__/__snapshots__/drawer.test.js.snap
  src/modal/__tests__/__snapshots__/modal.test.js.snap
  yarn.lock
Labels: greenkeeping

#2190 test(vrt): make it possible to name forks othen than baseweb
  vrt/ci.js
Labels: bugfix, test

#2182 fix(datepicker): multimonth render
  src/datepicker/__tests__/calendar-multi-month.scenario.js
  src/datepicker/styled-components.js
  vrt/__image_snapshots__/calendar-multi-month__dark-snap.png
  vrt/__image_snapshots__/calendar-multi-month__desktop-snap.png
  vrt/__image_snapshots__/calendar-multi-month__mobile-snap.png
Labels: bugfix

#2193 Release v9.12.0
  package.json
Labels: release

#2198 docs(survey): fix cookie path
  documentation-site/components/survey.js
Labels: docs

#2194 feat(data-table): numberical filter between case
  src/data-table/__tests__/column-numerical.test.js
  src/data-table/__tests__/data-table-columns.e2e.js
  src/data-table/column-numerical.js
  vrt/__image_snapshots__/data-table-numerical-column__dark-snap.png
  vrt/__image_snapshots__/data-table-numerical-column__desktop-snap.png
  vrt/__image_snapshots__/data-table-numerical-column__mobile-snap.png
Labels: feature

#2197 docs(blog): building a drag and drop list
  documentation-site/pages/blog/drag-and-drop-list/index.mdx
  documentation-site/pages/blog/drag-and-drop-list/metadata.json
  package.json
  yarn.lock
Labels: docs

#2202 fix(vrt): original repository information
  vrt/ci.js
Labels: bugfix

#2199 docs(walkthrough): add yard info
  documentation-site/components/layout.js
  documentation-site/components/walkthrough.js
  documentation-site/components/yard/config/modal.ts
Labels: docs

#2204 docs(yard): fix mobile view
  documentation-site/components/yard/knobs.tsx
  documentation-site/components/yard/override.tsx
  documentation-site/components/yard/theme-editor.tsx
  documentation-site/components/yard/yard.tsx
Labels: docs

#2118 feat(data-table): row actions
  documentation-site/examples/data-table/batch-action.js
  documentation-site/examples/data-table/batch-action.tsx
  src/data-table/__tests__/data-table-columns.e2e.js
  src/data-table/__tests__/data-table-row-actions.e2e.js
  src/data-table/__tests__/data-table-row-actions.scenario.js
  src/data-table/__tests__/data-table-text-search.e2e.js
  src/data-table/cell-shell.js
  src/data-table/data-table.js
  src/data-table/index.d.ts
  src/data-table/measure-column-widths.js
  src/data-table/types.js
  vrt/__image_snapshots__/data-table-row-actions--dark-snap.png
  vrt/__image_snapshots__/data-table-row-actions--mobile-snap.png
  vrt/__image_snapshots__/data-table-row-actions-snap.png
  vrt/__image_snapshots__/data-table-row-actions__dark-snap.png
  vrt/__image_snapshots__/data-table-row-actions__desktop-snap.png
  vrt/__image_snapshots__/data-table-row-actions__mobile-snap.png
Labels: feature

#2184 feat(data-table): filter menu
  src/data-table/__tests__/data-table-columns.e2e.js
  src/data-table/__tests__/data-table-text-search.scenario.js
  src/data-table/__tests__/data-table.scenario.js
  src/data-table/data-table.js
  src/data-table/filter-menu.js
  src/data-table/header-cell.js
  src/data-table/measure-column-widths.js
  vrt/__image_snapshots__/data-table-batch-action__dark-snap.png
  vrt/__image_snapshots__/data-table-batch-action__desktop-snap.png
  vrt/__image_snapshots__/data-table-batch-action__mobile-snap.png
  vrt/__image_snapshots__/data-table-columns__dark-snap.png
  vrt/__image_snapshots__/data-table-columns__desktop-snap.png
  vrt/__image_snapshots__/data-table-columns__mobile-snap.png
  vrt/__image_snapshots__/data-table-row-actions__dark-snap.png
  vrt/__image_snapshots__/data-table-row-actions__desktop-snap.png
  vrt/__image_snapshots__/data-table-row-actions__mobile-snap.png
  vrt/__image_snapshots__/data-table-text-search__dark-snap.png
  vrt/__image_snapshots__/data-table-text-search__desktop-snap.png
  vrt/__image_snapshots__/data-table-text-search__mobile-snap.png
  vrt/__image_snapshots__/data-table__dark-snap.png
  vrt/__image_snapshots__/data-table__desktop-snap.png
  vrt/__image_snapshots__/data-table__mobile-snap.png
Labels: feature

#2209 fix(spinner): slow down the rotation
  src/spinner/styled-components.js
  src/styles/types.js
  src/theme.ts
  src/themes/creator.js
Labels: bugfix

#2196 docs(validation): add email validation example
  documentation-site/examples/form-control/validation.js
  documentation-site/examples/form-control/validation.tsx
  documentation-site/pages/components/form-control.mdx
  package.json
  yarn.lock
Labels: docs

#2206 fix(modal): make modal scrollable while cursor is on the backdrop
  src/modal/__tests__/__snapshots__/modal.test.js.snap
  src/modal/modal.js
  src/modal/styled-components.js
Labels: bugfix

#2210 Release v9.13.0
  package.json
Labels: release
