Repository uber/baseweb, pull requests merged in 2019-01, with the labels that each got.

#687 feat(select): add StyledDropdown and StyledDropdownListItem to exports and overrides
  src/menu/__tests__/__snapshots__/styled-components.test.js.snap
  src/menu/styled-components.js
  src/select/README.md
  src/select/__tests__/__snapshots__/dropdown.test.js.snap
  src/select/dropdown.js
  src/select/examples.js
  src/select/index.js
  src/select/styled-components.js
  src/select/types.js
Labels: feature

#686 docs(browser-support): adds browser support documentation
  docs/pages/introduction/browser-support.md
  docs/pages/pages.js
Labels: documentation, feature

#701 Release v5.5.0
  package.json
Labels: release

#692 feat(docs-site): adds example component
  .eslintignore
  .flowconfig
  documentation-site/.babelrc
  documentation-site/.babelrc.js
  documentation-site/components/example.js
  documentation-site/env-config.js
  documentation-site/next.config.js
  documentation-site/pages/index.js
  documentation-site/static/examples/input/example.js
  package.json
  yarn.lock
Labels: feature

#689 feat(menu): implements child menus on hover
  src/menu/__tests__/__snapshots__/styled-components.test.js.snap
  src/menu/__tests__/maybe-child-menu.test.js
  src/menu/examples-list.js
  src/menu/examples.js
  src/menu/maybe-child-menu.js
  src/menu/menu.js
  src/menu/option-list.js
  src/menu/option-profile.js
  src/menu/stateful-container.js
  src/menu/styled-components.js
  src/menu/types.js
  src/popover/__tests__/__snapshots__/stateful-container.test.js.snap
  src/popover/__tests__/__snapshots__/stateful-popover.test.js.snap
  src/popover/default-props.js
  src/popover/popover.js
  src/popover/stateful-container.js
  src/popover/types.js
  src/tooltip/__tests__/__snapshots__/stateful-tooltip.test.js.snap
  src/tooltip/__tests__/stateful-tooltip-container.test.js
  src/tooltip/__tests__/stateful-tooltip.test.js
  src/tooltip/__tests__/tooltip.test.js
Labels: feature

#697 feat(docs-site): introduction pages and markdown
  CONTRIBUTING.md
  docs/pages/pages.js
  documentation-site/components/layout.js
  documentation-site/components/markdown-elements.js
  documentation-site/components/theming-values/colors.js
  documentation-site/components/theming-values/common.js
  documentation-site/components/theming-values/lighting.js
  documentation-site/components/theming-values/sizing.js
  documentation-site/components/theming-values/typography.js
  documentation-site/next.config.js
  documentation-site/pages/contributing.mdx
  documentation-site/pages/custom-themes.mdx
  documentation-site/pages/getting-started.mdx
  documentation-site/pages/index.js
  documentation-site/pages/index.mdx
  documentation-site/pages/playground.js
  documentation-site/pages/theming-values.js
  documentation-site/pages/versioning-policy.mdx
  package.json
  yarn.lock
Labels: feature

#702 feat(overrides): export `mergeStyleOverrides` and add tests
  src/helpers/__tests__/overrides.test.js
  src/helpers/overrides.js
Labels: feature

#705 fix(menu): fix overflow in menu
  src/menu/__tests__/__snapshots__/styled-components.test.js.snap
  src/menu/examples.js
  src/menu/styled-components.js
Labels: bugfix

#704 feat(docs): add sidenav
  documentation-site/components/layout.js
  documentation-site/components/sidebar.js
  documentation-site/routes.js
  netlify.toml
Labels: feature

#706 test(select): add open state for screener
  screener.config.js
  src/select/examples.js
Labels: bugfix

#711 fix(input): fix enhancers bg color
  screener.config.js
  src/input/__tests__/__snapshots__/styled-components.test.js.snap
  src/input/examples.js
  src/input/styled-components.js
  src/themes/creator.js
  src/themes/dark-theme.js
Labels: bugfix

#707 feat(docs-site): adds component readme
  documentation-site/components/example.js
  documentation-site/components/layout.js
  documentation-site/components/sidebar.js
  documentation-site/next.config.js
  documentation-site/pages/components/input.mdx
  documentation-site/routes.js
  documentation-site/static/examples/input/available-states.js
  documentation-site/static/examples/input/basic-controlled.js
  documentation-site/static/examples/input/basic-uncontrolled.js
  documentation-site/static/examples/input/before-after.js
  documentation-site/static/examples/input/compact-size.js
  documentation-site/static/examples/input/enhancers.js
  documentation-site/static/examples/input/example.js
  documentation-site/static/examples/input/focus.js
  documentation-site/static/examples/input/mask.js
  documentation-site/static/examples/input/overrides.js
Labels: feature

#713 feat(docs): add api description component
  documentation-site/components/api.js
  documentation-site/env-config.js
  documentation-site/pages/components/input.mdx
  package.json
  src/input/masked-input.js
  src/input/types.js
  yarn.lock
Labels: feature

#717 feat(docs-site): component menu
  documentation-site/components/component-menu.js
  documentation-site/components/layout.js
  documentation-site/components/nav-link.js
  documentation-site/components/sidebar.js
  documentation-site/routes.js
Labels: feature

#715 feat(menu): adds examples using react-virtualized
  package.json
  src/menu/examples-list.js
  src/menu/examples.js
  src/select/examples-list.js
  src/select/examples.js
  yarn.lock
Labels: documentation, examples, feature

#709 test(rating): add vrt for 5 stars
  src/rating/examples.js
Labels: bugfix

#714 docs(button): move to the new docs site
  documentation-site/components/example.js
  documentation-site/pages/components/button.mdx
  documentation-site/routes.js
  documentation-site/static/examples/button/basic-compact.js
  documentation-site/static/examples/button/basic.js
  documentation-site/static/examples/button/with-enchancers.js
  src/button/button-internals.js
  src/button/button.js
  src/button/types.js
Labels: feature

#719 docs(accordion): move to the new doc site
  documentation-site/components/component-menu.js
  documentation-site/pages/components/accordion.mdx
  documentation-site/routes.js
  documentation-site/static/examples/accordion/basic.js
  documentation-site/static/examples/accordion/stateful.js
  src/accordion/types.js
Labels: feature

#720 docs(header-navigation): move to the new doc site
  documentation-site/pages/components/header-navigation.mdx
  documentation-site/routes.js
  documentation-site/static/examples/header-navigation/basic.js
  documentation-site/static/examples/header-navigation/with-search.js
Labels: feature

#721 docs(tabs): move to new doc site
  documentation-site/pages/components/tabs.mdx
  documentation-site/routes.js
  documentation-site/static/examples/tabs/basic.js
  documentation-site/static/examples/tabs/controlled.js
  documentation-site/static/examples/tabs/vertical.js
  src/tabs/types.js
Labels: feature

#722 docs(breadcrumbs): move to the new docs site
  documentation-site/pages/components/breadcrumbs.mdx
  documentation-site/routes.js
  documentation-site/static/examples/breadcrumbs/basic.js
Labels: feature

#724 docs(toast): move to the new docs site
  documentation-site/pages/components/toast.mdx
  documentation-site/routes.js
  documentation-site/static/examples/toast/basic.js
  documentation-site/static/examples/toast/toast-notification.js
  src/toast/types.js
Labels: feature

#725 fix(toast): add margin to the toaster container
  src/toast/styled-components.js
Labels: bugfix

#726 docs(card): move to the new doc site
  documentation-site/pages/components/card.mdx
  documentation-site/routes.js
  documentation-site/static/examples/card/basic.js
  documentation-site/static/examples/card/image-cta.js
  documentation-site/static/examples/card/thumbnail-cta.js
  src/card/types.js
Labels: feature

#729 docs(modal): move to the new doc site
  documentation-site/pages/components/modal.mdx
  documentation-site/routes.js
  documentation-site/static/examples/modal/basic.js
  src/modal/types.js
Labels: feature

#730 docs(overrides): move to new site
  docs/pages/theming/custom-themes.md
  documentation-site/components/markdown-elements.js
  documentation-site/pages/understanding-overrides.mdx
  documentation-site/routes.js
  documentation-site/static/examples/overrides/component.js
  documentation-site/static/examples/overrides/props.js
  documentation-site/static/examples/overrides/style.js
Labels: feature

#731 docs(progress-steps): move to the new docs site
  documentation-site/pages/components/progress-steps.mdx
  documentation-site/routes.js
  documentation-site/static/examples/progress-steps/dotted.js
  documentation-site/static/examples/progress-steps/numbered.js
  src/progress-steps/styled-components.js
  src/progress-steps/types.js
Labels: feature

#734 fix(progress-steps): visual regression in numbered steps
  screener.config.js
  src/progress-steps/styled-components.js
Labels: bugfix

#737 Release v5.6.0
  package.json
Labels: release

#728 feat(menu): support disabled options
  src/menu/__tests__/__snapshots__/styled-components.test.js.snap
  src/menu/__tests__/stateful-container.test.js
  src/menu/constants.js
  src/menu/examples.js
  src/menu/stateful-container.js
  src/menu/styled-components.js
Labels: feature

#742 Release v5.7.0
  package.json
Labels: release

#738 docs(block): adds block component to docs site
  documentation-site/pages/components/block.mdx
  documentation-site/routes.js
  documentation-site/static/examples/block/basic.js
  documentation-site/static/examples/block/flexbox.js
  documentation-site/static/examples/block/fonts.js
  documentation-site/static/examples/block/grid.js
  documentation-site/static/examples/block/override.js
  src/block/types.js
Labels: feature

#736 docs(avatar): adds avatar to new docs site
  documentation-site/pages/components/avatar.mdx
  documentation-site/routes.js
  documentation-site/static/examples/avatar/error.js
  documentation-site/static/examples/avatar/override.js
  documentation-site/static/examples/avatar/sizes.js
  src/avatar/types.js
Labels: feature

#739 docs(button-group): adds button-group to docs site
  documentation-site/pages/components/button-group.mdx
  documentation-site/routes.js
  documentation-site/static/examples/button-group/basic.js
  documentation-site/static/examples/button-group/checkbox-mode.js
  documentation-site/static/examples/button-group/controlled.js
  documentation-site/static/examples/button-group/disabled.js
  documentation-site/static/examples/button-group/radio-mode.js
  src/button-group/types.js
Labels: feature

#743 docs(select): move to the new docs site
  documentation-site/pages/components/select.mdx
  documentation-site/routes.js
  documentation-site/static/examples/select/basic.js
  documentation-site/static/examples/select/search-multi-pick.js
  documentation-site/static/examples/select/search-single-pick.js
  documentation-site/static/examples/select/with-many-options.js
  src/select/types.js
Labels: feature

#745 fix(block): correct docs site route
  documentation-site/routes.js
Labels: bugfix

#741 docs(textarea): move to the new docs site
  documentation-site/pages/components/textarea.mdx
  documentation-site/routes.js
  documentation-site/static/examples/textarea/basic.js
  documentation-site/static/examples/textarea/ref.js
Labels: feature

#746 docs(checkbox): adds to new docs site
  documentation-site/pages/components/checkbox.mdx
  documentation-site/routes.js
  documentation-site/static/examples/checkbox/alignment.js
  documentation-site/static/examples/checkbox/basic.js
  documentation-site/static/examples/checkbox/component-overrides.js
  documentation-site/static/examples/checkbox/disabled.js
  documentation-site/static/examples/checkbox/error.js
  documentation-site/static/examples/checkbox/focus.js
  documentation-site/static/examples/checkbox/indeterminate.js
  documentation-site/static/examples/checkbox/multiline.js
  documentation-site/static/examples/checkbox/overrides.js
  src/checkbox/types.js
Labels: feature

#747 build(docs-site) Fixes flash of unstyled content
  documentation-site/components/meta.js
  documentation-site/helpers/styletron.js
  documentation-site/pages/_app.js
  documentation-site/pages/_document.js
Labels: bugfix

#748 fix(Select): fix select search icon z-index
  src/select/__tests__/__snapshots__/styled-components.test.js.snap
  src/select/styled-components.js
Labels: bugfix

#750 fix(theme): modify fontWeight and lineHeight type to be `string | num…
  src/styles/types.js
Labels: bugfix

#716 docs(dnd-list): add dnd-list proposal
  proposals/dnd-list.md
Labels: docs, documentation

#751 docs(Icon): adds icon to docs site
  documentation-site/pages/components/icon.mdx
  documentation-site/routes.js
  documentation-site/static/examples/icon/basic.js
  documentation-site/static/examples/icon/button.js
  documentation-site/static/examples/icon/list.js
  src/icon/types.js
Labels: feature

#752 docs(contributing): fix broken contributors page on storybook
  CONTRIBUTING.md
  docs/pages/pages.js
Labels: bugfix

#749 docs(Checkbox): adds toggle example
  documentation-site/pages/components/checkbox.mdx
  documentation-site/static/examples/checkbox/toggle.js
Labels: feature

#755 docs(notification): add notification to docs site
  documentation-site/pages/components/notification.mdx
  documentation-site/routes.js
  documentation-site/static/examples/notification/basic.js
  documentation-site/static/examples/notification/closeable.js
  documentation-site/static/examples/notification/custom-dismiss.js
  documentation-site/static/examples/notification/kinds.js
  documentation-site/static/examples/notification/overrides.js
Labels: feature

#759 feat(docs): move the spinner
  documentation-site/pages/components/spinner.mdx
  documentation-site/routes.js
  documentation-site/static/examples/spinner/basic.js
  documentation-site/static/examples/spinner/with-overrides.js
  documentation-site/static/examples/spinner/with-size.js
Labels: feature

#753 docs(menu): adds menu to docs site
  documentation-site/components/example.js
  documentation-site/pages/components/menu.mdx
  documentation-site/pages/components/select.mdx
  documentation-site/routes.js
  documentation-site/static/examples/menu/basic.js
  documentation-site/static/examples/menu/child.js
  documentation-site/static/examples/menu/compact.js
  documentation-site/static/examples/menu/profile.js
  documentation-site/static/examples/menu/stateful.js
  documentation-site/static/examples/menu/virtual-list.js
  src/menu/README.md
  src/menu/stateful-menu.js
  src/menu/types.js
Labels: feature

#756 docs(pagination): adds pagination to docs site
  documentation-site/pages/components/pagination.mdx
  documentation-site/routes.js
  documentation-site/static/examples/pagination/controlled.js
  documentation-site/static/examples/pagination/labels.js
  documentation-site/static/examples/pagination/overrides.js
  documentation-site/static/examples/pagination/uncontrolled.js
  src/pagination/stateful-pagination.js
  src/pagination/types.js
Labels: feature

#757 docs(popover): adds popover to docs site
  documentation-site/pages/components/popover.mdx
  documentation-site/routes.js
  documentation-site/static/examples/popover/clipping.js
  documentation-site/static/examples/popover/dismiss.js
  documentation-site/static/examples/popover/overrides.js
  documentation-site/static/examples/popover/placements.js
  documentation-site/static/examples/popover/stateful-click.js
  documentation-site/static/examples/popover/stateful-hover.js
  documentation-site/static/examples/popover/stateless.js
  documentation-site/static/examples/popover/with-arrow.js
  src/popover/stateful-container.js
  src/popover/stateful-popover.js
  src/popover/types.js
Labels: feature

#758 docs(progress-bar): adds progress-bar to docs site
  documentation-site/pages/components/progress-bar.mdx
  documentation-site/routes.js
  documentation-site/static/examples/progress-bar/basic.js
  documentation-site/static/examples/progress-bar/custom-label.js
  documentation-site/static/examples/progress-bar/overrides.js
  documentation-site/static/examples/progress-bar/success-value.js
  documentation-site/static/examples/progress-bar/with-label.js
  src/progress-bar/types.js
Labels: feature

#761 docs(radio): adds radio to docs site
  documentation-site/pages/components/radio.mdx
  documentation-site/routes.js
  documentation-site/static/examples/radio/basic.js
  documentation-site/static/examples/radio/error.js
  documentation-site/static/examples/radio/horizontal-align.js
  documentation-site/static/examples/radio/overrides.js
  documentation-site/static/examples/radio/stateful.js
  src/radio/types.js
Labels: feature

#763 docs(slider): moves slider component to new docs site
  documentation-site/pages/components/slider.mdx
  documentation-site/routes.js
  documentation-site/static/examples/slider/basic.js
  documentation-site/static/examples/slider/overrides.js
  documentation-site/static/examples/slider/range.js
  documentation-site/static/examples/slider/stateful.js
  documentation-site/static/examples/slider/step.js
  documentation-site/static/examples/slider/ticks.js
  src/slider/types.js
Labels: feature

#765 feat(docs): move the rating component to the new doc site
  documentation-site/pages/components/rating.mdx
  documentation-site/routes.js
  documentation-site/static/examples/rating/emoticon.js
  documentation-site/static/examples/rating/star.js
  src/rating/types.js
Labels: feature

#767 feat(tooltip): move to the new doc site
  documentation-site/pages/components/tooltip.mdx
  documentation-site/routes.js
  documentation-site/static/examples/tooltip/stateful-complex-content.js
  documentation-site/static/examples/tooltip/stateful.js
Labels: feature

#762 feat(dnd-list): add drag and drop list component
  documentation-site/pages/components/dnd-list.mdx
  documentation-site/routes.js
  documentation-site/static/examples/dnd-list/basic.js
  documentation-site/static/examples/dnd-list/customDragHandle.js
  documentation-site/static/examples/dnd-list/overrideLabel.js
  documentation-site/static/examples/dnd-list/removable.js
  documentation-site/static/examples/dnd-list/stateless.js
  documentation-site/static/examples/dnd-list/varyingHeights.js
  package.json
  proposals/dnd-list.md
  src/dnd-list/README.md
  src/dnd-list/__tests__/__snapshots__/styled-components.test.js.snap
  src/dnd-list/__tests__/list.test.js
  src/dnd-list/__tests__/stateful-list-container.test.js
  src/dnd-list/__tests__/stateful-list.test.js
  src/dnd-list/__tests__/styled-components.test.js
  src/dnd-list/constants.js
  src/dnd-list/examples.js
  src/dnd-list/index.js
  src/dnd-list/list.js
  src/dnd-list/stateful-list-container.js
  src/dnd-list/stateful-list.js
  src/dnd-list/stories.js
  src/dnd-list/styled-components.js
  src/dnd-list/types.js
  yarn.lock
Labels: feature

#768 feat(docs): overrides docs
  documentation-site/components/overrides.js
  documentation-site/pages/components/accordion.mdx
  documentation-site/routes.js
  package.json
  yarn.lock
Labels: feature

#769 feat(docs): textarea api + uber-web-ui/extract-react-types
  documentation-site/pages/components/accordion.mdx
  documentation-site/pages/components/avatar.mdx
  documentation-site/pages/components/block.mdx
  documentation-site/pages/components/breadcrumbs.mdx
  documentation-site/pages/components/button-group.mdx
  documentation-site/pages/components/button.mdx
  documentation-site/pages/components/card.mdx
  documentation-site/pages/components/checkbox.mdx
  documentation-site/pages/components/dnd-list.mdx
  documentation-site/pages/components/header-navigation.mdx
  documentation-site/pages/components/icon.mdx
  documentation-site/pages/components/input.mdx
  documentation-site/pages/components/menu.mdx
  documentation-site/pages/components/modal.mdx
  documentation-site/pages/components/notification.mdx
  documentation-site/pages/components/pagination.mdx
  documentation-site/pages/components/popover.mdx
  documentation-site/pages/components/progress-bar.mdx
  documentation-site/pages/components/progress-steps.mdx
  documentation-site/pages/components/radio.mdx
  documentation-site/pages/components/rating.mdx
  documentation-site/pages/components/select.mdx
  documentation-site/pages/components/slider.mdx
  documentation-site/pages/components/spinner.mdx
  documentation-site/pages/components/tabs.mdx
  documentation-site/pages/components/tag.mdx
  documentation-site/pages/components/textarea.mdx
  documentation-site/pages/components/toast.mdx
  documentation-site/pages/components/tooltip.mdx
  package.json
  yarn.lock
Labels: feature

#770 feat(docs): swap documentation site
  docs/pages/introduction/welcome.md
  documentation-site/components/layout.js
  documentation-site/components/overrides.js
  documentation-site/env-config.js
  documentation-site/next.config.js
  documentation-site/routes.js
  netlify.toml
  package.json
Labels: feature

#775 docs(block): remove superfine reference
  documentation-site/pages/components/block.mdx
  src/block/README.md
Labels: bugfix

#772 docs(datepicker): move datepicker to docs site
  documentation-site/pages/components/datepicker.mdx
  documentation-site/routes.js
  documentation-site/static/examples/datepicker/basic.js
  documentation-site/static/examples/datepicker/in-popover.js
  documentation-site/static/examples/datepicker/with-overrides.js
  src/datepicker/README.md
  src/datepicker/stateful-calendar.js
  src/datepicker/types.js
Labels: documentation, feature

#708 feat(datepicker): add date range select
  documentation-site/routes.js
  src/datepicker/__tests__/__snapshots__/styled-components.test.js.snap
  src/datepicker/__tests__/styled-components.test.js
  src/datepicker/calendar.js
  src/datepicker/day.js
  src/datepicker/examples-list.js
  src/datepicker/examples.js
  src/datepicker/month.js
  src/datepicker/navigation-container.js
  src/datepicker/styled-components.js
  src/datepicker/types.js
  src/datepicker/utils/index.js
  src/datepicker/week.js
Labels: feature

#778 chore(babel): Adds styletron display name babel transform
  .babelrc.js
  package.json
  src/avatar/styled-components.js
  src/breadcrumbs/__tests__/__snapshots__/breadcrumbs.test.js.snap
  src/breadcrumbs/styled-components.js
  src/button-group/styled-components.js
  src/button/styled-components.js
  src/card/styled-components.js
  src/checkbox/styled-components.js
  src/file-uploader/styled-components.js
  src/form-control/styled-components.js
  src/header-navigation/__tests__/__snapshots__/header-navigation.test.js.snap
  src/header-navigation/styled-components.js
  src/icon/__tests__/__snapshots__/icon.test.js.snap
  src/icon/styled-components.js
  src/input/__tests__/__snapshots__/input.test.js.snap
  src/input/styled-components.js
  src/link/styled-components.js
  src/menu/styled-components.js
  src/modal/__tests__/__snapshots__/modal.test.js.snap
  src/modal/styled-components.js
  src/pagination/styled-components.js
  src/popover/styled-components.js
  src/progress-bar/__tests__/__snapshots__/progressbar.test.js.snap
  src/progress-bar/styled-components.js
  src/progress-steps/__tests__/__snapshots__/numbered-step.test.js.snap
  src/progress-steps/__tests__/__snapshots__/step.test.js.snap
  src/progress-steps/styled-components.js
  src/radio/styled-components.js
  src/rating/__tests__/__snapshots__/emoticon-rating.test.js.snap
  src/rating/__tests__/__snapshots__/star-rating.test.js.snap
  src/rating/styled-components.js
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/styled-components.js
  src/spinner/styled-components.js
  src/tag/__tests__/__snapshots__/tag.test.js.snap
  src/tag/styled-components.js
  src/template-component/styled-components.js
  src/textarea/styled-components.js
  src/toast/styled-components.js
  src/tooltip/styled-components.js
  yarn.lock
Labels: bugfix

#781 docs(form-control): move form-control to docs site
  documentation-site/pages/components/form-control.mdx
  documentation-site/routes.js
  documentation-site/static/examples/form-control/basic.js
  src/form-control/types.js
Labels: documentation, feature

#784 fix(pagination): dropdown z-index bug
  src/pagination/__tests__/__snapshots__/styled-components.test.js.snap
  src/pagination/styled-components.js
Labels: bugfix

#785 fix(button): fix round shape button radius
  screener.config.js
  src/button/styled-components.js
Labels: bugfix

#780 feat(puppeteer): adding the test runner
  .buildkite/pipeline.yml
  .eslintrc.js
  docker-compose.yml
  e2e/helpers/index.js
  e2e/tests.js
  jest-puppeteer.config.js
  jest.e2e.config.js
  package.json
  src/accordion/pup-e2e.js
  yarn.lock
Labels: feature

#786 feat(slider): enable custom slider labels
  documentation-site/pages/components/slider.mdx
  documentation-site/static/examples/slider/range-label.js
  src/slider/__tests__/slider.test.js
  src/slider/examples-list.js
  src/slider/examples.js
  src/slider/slider.js
  src/slider/types.js
Labels: feature

#788 feat(button-group): Align color scheme with designs
  documentation-site/static/examples/button-group/basic.js
  documentation-site/static/examples/button-group/checkbox-mode.js
  documentation-site/static/examples/button-group/disabled.js
  src/button-group/__tests__/button-group.test.js
  src/button-group/button-group.js
  src/button-group/examples.js
  src/button/styled-components.js
  src/styles/types.js
  src/themes/creator.js
  src/themes/dark-theme.js
Labels: feature

#787 feat(docs): add github links and simplify spacing in the sidebar
  documentation-site/components/component-menu.js
  documentation-site/components/example.js
  documentation-site/components/github-logo.js
  documentation-site/components/layout.js
  documentation-site/components/sidebar.js
  documentation-site/routes.js
Labels: documentation, feature

#791 feat(docs): code syntax highlighting
  documentation-site/components/code.js
  documentation-site/components/example.js
  package.json
  yarn.lock
Labels: feature

#793 feat(docs): add algolia search
  documentation-site/components/layout.js
  documentation-site/components/search.js
  documentation-site/pages/_document.js
Labels: documentation, feature

#797 feat(docs): highlight inlined code examples
  documentation-site/components/code.js
  documentation-site/next.config.js
  documentation-site/pages/_app.js
  documentation-site/pages/getting-started.mdx
  documentation-site/prism-coy.css
  package.json
  yarn.lock
Labels: documentation, feature

#794 fix(icon): pass sharedProps after a rest props spread
  src/icon/icon.js
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/styled-components.js
Labels: bugfix

#790 feat(tests): moving to puppeteer
  .buildkite/pipeline.yml
  README.md
  TESTING.md
  docker-compose.yml
  e2e/helpers/index.js
  jest-puppeteer.config.js
  jest.e2e.config.js
  nightwatch.conf.js
  package.json
  src/accordion/e2e.js
  src/button/e2e.js
  src/card/e2e.js
  src/checkbox/e2e.js
  src/input/e2e.js
  src/menu/e2e.js
  src/modal/e2e.js
  src/pagination/e2e.js
  src/popover/e2e.js
  src/popover/examples.js
  src/select/e2e.js
  src/tag/e2e.js
  src/textarea/e2e.js
  src/tooltip/e2e.js
  yarn.lock
Labels: feature

#798 feat(avatar): fallback initials
  documentation-site/static/examples/avatar/error.js
  documentation-site/static/examples/avatar/override.js
  documentation-site/static/examples/avatar/sizes.js
  src/avatar/__tests__/__snapshots__/styled-components.test.js.snap
  src/avatar/__tests__/avatar.test.js
  src/avatar/avatar.js
  src/avatar/examples.js
  src/avatar/index.js
  src/avatar/styled-components.js
  src/avatar/types.js
Labels: feature

#801 Release v5.9.0
  package.json
Labels: release

#803 feat(docs): overrides component upgrade
  documentation-site/components/overrides.js
  documentation-site/pages/_app.js
  documentation-site/pages/components/accordion.mdx
Labels: feature

#804 feat(docs): getting started and theming updates & next steps
  documentation-site/components/layout.js
  documentation-site/components/markdown-elements.js
  documentation-site/components/overrides.js
  documentation-site/pages/getting-started/installation.mdx
  documentation-site/pages/getting-started/learn.mdx
  documentation-site/pages/getting-started/usage.mdx
  documentation-site/pages/getting-started/versioning-policy.mdx
  documentation-site/pages/playground.js
  documentation-site/pages/theming/custom-themes.mdx
  documentation-site/pages/theming/theming-values.js
  documentation-site/pages/theming/understanding-overrides.mdx
  documentation-site/routes.js
Labels: feature

#800 feat(tag): add closeable prop to disable close button
  documentation-site/pages/components/tag.mdx
  documentation-site/static/examples/tag/uncloseable.js
  src/tag/README.md
  src/tag/__tests__/__snapshots__/styled-components.test.js.snap
  src/tag/__tests__/__snapshots__/tag.test.js.snap
  src/tag/examples-list.js
  src/tag/examples.js
  src/tag/styled-components.js
  src/tag/tag.js
  src/tag/types.js
Labels: feature

#802 feat(typography): a first implementation of typography components
  src/typography/README.md
  src/typography/__tests__/index.js
  src/typography/examples-list.js
  src/typography/examples.js
  src/typography/index.js
  src/typography/stories.js
Labels: feature

#805 Release v5.10.0
  package.json
Labels: release

#799 feat(docs-site): recognize contributors
  documentation-site/components/contributors.js
  documentation-site/env-config.js
  documentation-site/pages/index.js
  documentation-site/pages/index.mdx
  package.json
  yarn.lock
Labels: feature

#806 docs(typography): add typhography to docs
  documentation-site/pages/components/typography.mdx
  documentation-site/routes.js
  documentation-site/static/examples/typography/display.js
  documentation-site/static/examples/typography/heading.js
  documentation-site/static/examples/typography/text.js
Labels: feature

#809 fix(docs-site): correct tag uncloseable example path
  documentation-site/pages/components/tag.mdx
Labels: bugfix

#810 feat(styled): add docs
  documentation-site/pages/components/styled.mdx
  documentation-site/pages/theming/understanding-overrides.mdx
  documentation-site/routes.js
  documentation-site/static/examples/overrides/style-with-theme.js
  documentation-site/static/examples/styled/basic.js
  documentation-site/static/examples/styled/overrides.js
Labels: feature

#811 Release v5.11.0
  package.json
Labels: release

#812 chore(build): deploy on zeit now on git tag
  .buildkite/pipeline.yml
  now.json
  package.json
  yarn.lock
Labels: feature

#816 chore(build): auto alias the now deployment
  .buildkite/pipeline.yml
  now.json
Labels: bugfix, build/tooling

#815 feat(toast): add autoHideDuration to ToasterContainer
  src/toast/__tests__/toaster.test.js
  src/toast/examples.js
  src/toast/toaster.js
  src/toast/types.js
Labels: bugfix, enhancement

#817 feat(docs): add ctas to the index page
  documentation-site/components/contributors.js
  documentation-site/components/layout.js
  documentation-site/components/slack-logo.js
  documentation-site/pages/index.js
Labels: feature

#819 feat(docs): display current version
  documentation-site/components/layout.js
Labels: feature

#820 fix(docs): landing copy
  documentation-site/pages/index.js
Labels: bugfix

#807 fix(typography): set the default font color
  src/themes/creator.js
  src/themes/dark-theme.js
  src/typography/README.md
  src/typography/__tests__/index.js
  src/typography/index.js
Labels: bugfix

#825 fix(select): mark input as required only if the select value is empty
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/select.js
Labels: bugfix

#826 chore: bump react-movable to v1
  package.json
  yarn.lock
Labels: greenkeeping

#823 feat(docs): add favicon
  documentation-site/components/meta.js
  documentation-site/static/android-chrome-192x192.png
  documentation-site/static/android-chrome-512x512.png
  documentation-site/static/apple-touch-icon.png
  documentation-site/static/browserconfig.xml
  documentation-site/static/favicon-16x16.png
  documentation-site/static/favicon-32x32.png
  documentation-site/static/favicon.ico
  documentation-site/static/mstile-144x144.png
  documentation-site/static/mstile-150x150.png
  documentation-site/static/mstile-310x150.png
  documentation-site/static/mstile-310x310.png
  documentation-site/static/mstile-70x70.png
  documentation-site/static/safari-pinned-tab.svg
  documentation-site/static/site.webmanifest
Labels: feature

#828 fix(docs): title
  documentation-site/env-config.js
Labels: bugfix

#829 Release v5.12.1
  package.json
Labels: release

#822 feat(docs): add overrides documentation to all components
  documentation-site/components/overrides.js
  documentation-site/pages/_app.js
  documentation-site/pages/components/avatar.mdx
  documentation-site/pages/components/breadcrumbs.mdx
  documentation-site/pages/components/button-group.mdx
  documentation-site/pages/components/button.mdx
  documentation-site/pages/components/card.mdx
  documentation-site/pages/components/checkbox.mdx
  documentation-site/pages/components/datepicker.mdx
  documentation-site/pages/components/dnd-list.mdx
  documentation-site/pages/components/file-uploader.mdx
  documentation-site/pages/components/form-control.mdx
  documentation-site/pages/components/header-navigation.mdx
  documentation-site/pages/components/icon.mdx
  documentation-site/pages/components/input.mdx
  documentation-site/pages/components/menu.mdx
  documentation-site/pages/components/notification.mdx
  documentation-site/pages/components/pagination.mdx
  documentation-site/pages/components/popover.mdx
  documentation-site/pages/components/progress-bar.mdx
  documentation-site/pages/components/progress-steps.mdx
  documentation-site/pages/components/radio.mdx
  documentation-site/pages/components/rating.mdx
  documentation-site/pages/components/select.mdx
  documentation-site/pages/components/slider.mdx
  documentation-site/pages/components/spinner.mdx
  documentation-site/pages/components/tabs.mdx
  documentation-site/pages/components/tag.mdx
  documentation-site/pages/components/textarea.mdx
  documentation-site/pages/components/toast.mdx
  documentation-site/pages/components/tooltip.mdx
  documentation-site/static/examples/button/basic-compact.js
  documentation-site/static/examples/button/shapes.js
  documentation-site/static/examples/button/states.js
  documentation-site/static/examples/button/with-enchancers.js
  documentation-site/static/examples/button/with-enhancers.js
  documentation-site/static/examples/file-uploader/_overrides_component.js
  src/card/card.js
  src/card/index.js
  src/datepicker/README.md
  src/datepicker/__tests__/__snapshots__/styled-components.test.js.snap
  src/datepicker/__tests__/styled-components.test.js
  src/datepicker/calendar-header.js
  src/datepicker/styled-components.js
  src/input/__tests__/__snapshots__/styled-components.test.js.snap
  src/input/__tests__/styled-components.test.js
  src/input/index.js
  src/menu/menu.js
  src/modal/examples.js
  src/toast/toast.js
  src/toast/toaster.js
Labels: documentation, feature

#830 fix(build): add now script
  package.json
Labels: bugfix, build/tooling

#831 docs(readme): minor nit on punctuation
  README.md
Labels: docs, documentation
