Repository uber/baseweb, pull requests merged in 2019-02, with the labels that each got.

#824 feat(block): responsive style props breakpoints
  documentation-site/pages/components/block.mdx
  documentation-site/static/examples/block/responsive.js
  src/block/__tests__/block.test.js
  src/block/block.js
  src/block/examples.js
  src/block/styled-components.js
  src/block/types.js
  src/styles/types.js
  src/themes/creator.js
  src/typography/index.js
Labels: feature

#832 chore(build): adds more reliable now deploy script
  .buildkite/pipeline.yml
  docker-compose.yml
  scripts/now-deploy.sh
Labels: build/tooling, feature

#835 fix(radio): prevent deformations of the radio input
  src/radio/__tests__/__snapshots__/styled-components.test.js.snap
  src/radio/styled-components.js
Labels: bugfix

#837 Release v5.13.0
  package.json
Labels: release

#833 fix(table): removes scroll when rows do not fill available height
  documentation-site/static/examples/table/virtual-horizontal-scroll.js
  documentation-site/static/examples/table/virtual.js
  src/table/__tests__/__snapshots__/styled-components.test.js.snap
  src/table/examples.js
  src/table/index.js
  src/table/styled-components.js
  src/table/table.js
Labels: bugfix

#841 docs(installation): using with fusion
  documentation-site/pages/getting-started/installation.mdx
Labels: feature

#842 Release v5.13.1
  package.json
Labels: release

#844 fix(build): uncomments the jq install >.<
  scripts/now-deploy.sh
Labels: bugfix

#846 fix(build): update package lists
  scripts/now-deploy.sh
Labels: bugfix

#847 test(e2e): adds accordion a11y test
  src/accordion/e2e.js
  src/accordion/styled-components.js
Labels: bugfix

#848 test(e2e): add progress steps e2e test
  e2e/tests.js
  src/progress-steps/e2e.js
  src/progress-steps/examples.js
Labels: bugfix

#843 fix(select): update the getOptionLabel prop type
  src/select/select.js
  src/select/types.js
Labels: bugfix

#851 test(e2e): toast a11y and close
  e2e/tests.js
  src/toast/e2e.js
Labels: feature

#853 fix(select): change type of autoFocus from false to boolean in Select component
  src/select/types.js
Labels: bugfix

#854 Release v5.13.2
  package.json
Labels: release

#856 fix(docs): Update testing docs
  TESTING.md
Labels: docs

#858 test(header-navigation): e2e a11y test
  src/header-navigation/__tests__/header-navigation.e2e.js
  src/header-navigation/__tests__/header-navigation.scenario.js
Labels: feature

#860 test(e2e): progress bar
  src/progress-bar/__tests__/progressbar.e2e.js
  src/progress-bar/__tests__/progressbar.scenario.js
Labels: feature

#855 feat(file-uploader): adds spinner if no progress info available
  documentation-site/pages/components/file-uploader.mdx
  documentation-site/static/examples/file-uploader/indeterminate-progress.js
  src/file-uploader/__tests__/__snapshots__/styled-components.test.js.snap
  src/file-uploader/__tests__/file-uploader.test.js
  src/file-uploader/examples.js
  src/file-uploader/file-uploader.js
  src/file-uploader/styled-components.js
Labels: feature

#857 test(e2e): rating component e2e tests
  src/rating/__tests__/rating-emoticon.scenario.js
  src/rating/__tests__/rating-star.scenario.js
  src/rating/__tests__/rating.e2e.js
Labels: feature

#863 feat(file-uploader): stabilize it
  .storybook-base/loadStories.js
  documentation-site/routes.js
  documentation-site/static/examples/file-uploader/_overrides_component.js
  documentation-site/static/examples/file-uploader/basic.js
  documentation-site/static/examples/file-uploader/disabled.js
  documentation-site/static/examples/file-uploader/error.js
  documentation-site/static/examples/file-uploader/indeterminate-progress.js
  documentation-site/static/examples/file-uploader/overrides.js
  src/file-uploader/README.md
  src/file-uploader/__tests__/file-uploader.test.js
  src/file-uploader/examples.js
  src/file-uploader/file-uploader.js
  src/file-uploader/index.js
  src/file-uploader/stories.js
Labels: feature

#865 chore: removes old proposals
  proposals/responsive-props.md
  proposals/table-component.md
  proposals/tabs-component.md
Labels: bugfix, docs

#866 fix(docs): landing site cards were broken into two lines
  documentation-site/components/layout.js
  documentation-site/pages/index.js
Labels: bugfix

#867 test(file-uploader): e2e tests
  src/file-uploader/__tests__/file-uploader-post-drop.scenario.js
  src/file-uploader/__tests__/file-uploader-pre-drop.scenario.js
  src/file-uploader/__tests__/file-uploader.e2e.js
Labels: feature

#864 test(radio): e2e tests
  src/radio/__tests__/radio.e2e.js
  src/radio/__tests__/radio.scenario.js
  src/radio/__tests__/radiogroup.test.js
  src/radio/__tests__/radiogroup1.test.js
  src/radio/radiogroup.js
  src/radio/types.js
Labels: feature

#870 fix(build): Use builders queue for puppeteer tests
  .buildkite/pipeline.yml
Labels: bugfix

#869 Release v5.14.0
  package.json
Labels: release

#868 feat(slider): slider rework
  docs/migrations/00868.md
  documentation-site/components/markdown-elements.js
  documentation-site/pages/components/slider.mdx
  documentation-site/prism-coy.css
  documentation-site/static/examples/slider/basic.js
  documentation-site/static/examples/slider/custom-ticks.js
  documentation-site/static/examples/slider/disabled.js
  documentation-site/static/examples/slider/overrides.js
  documentation-site/static/examples/slider/range.js
  documentation-site/static/examples/slider/stateful.js
  documentation-site/static/examples/slider/step-min-max.js
  documentation-site/static/examples/slider/ticks.js
  package.json
  src/slider/README.md
  src/slider/__tests__/__snapshots__/slider.test.js.snap
  src/slider/__tests__/__snapshots__/stateful-slider-container.test.js.snap
  src/slider/__tests__/__snapshots__/styled-components.test.js.snap
  src/slider/__tests__/slider.test.js
  src/slider/__tests__/stateful-slider-container.test.js
  src/slider/__tests__/stateful-slider.test.js
  src/slider/__tests__/styled-components.test.js
  src/slider/constants.js
  src/slider/examples-list.js
  src/slider/examples.js
  src/slider/icons.js
  src/slider/index.js
  src/slider/slider.js
  src/slider/stateful-slider-container.js
  src/slider/styled-components.js
  src/slider/types.js
  yarn.lock
Labels: breaking, documentation, feature

#873 react-movable v2 upgrade
  documentation-site/pages/components/dnd-list.mdx
  package.json
  src/dnd-list/list.js
  src/dnd-list/types.js
  yarn.lock
Labels: bugfix, documentation

#875 chore(table): removes styledcontent component
  docs/migrations/00875.md
  src/table/__tests__/__snapshots__/styled-components.test.js.snap
  src/table/__tests__/styled-components.test.js
  src/table/index.js
  src/table/styled-components.js
Labels: breaking

#874 chore(button-group): deprecate kind prop
  docs/migrations/00874.md
  src/button-group/README.md
  src/button-group/button-group.js
  src/button-group/types.js
Labels: breaking

#878 Release v6.0.0
  package.json
Labels: release

#876 fix(select): fix a11y test
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/__tests__/select-search-multi.scenario.js
  src/select/__tests__/select-search-single.scenario.js
  src/select/__tests__/select.e2e.js
  src/select/__tests__/select.scenario.js
  src/select/__tests__/value.test.js
  src/select/dropdown.js
  src/select/examples.js
  src/select/select.js
  src/select/value.js
Labels: bugfix

#879 chore: adds debug logs to now deploy script
  scripts/now-deploy.sh
Labels: bugfix

#877 fix(input): add aria-label/labelledby
  src/input/__tests__/__snapshots__/base-input.test.js.snap
  src/input/__tests__/__snapshots__/input.test.js.snap
  src/input/__tests__/__snapshots__/masked-input.test.js.snap
  src/input/__tests__/input.e2e.js
  src/input/__tests__/input.scenario.js
  src/input/base-input.js
  src/input/types.js
  src/textarea/__tests__/__snapshots__/textarea.test.js.snap
Labels: bugfix

#882 fix(tag): handles text overflow
  documentation-site/static/examples/tag/basic.js
  src/tag/__tests__/__snapshots__/tag.test.js.snap
  src/tag/__tests__/tag-long-text.scenario.js
  src/tag/examples.js
  src/tag/index.js
  src/tag/styled-components.js
  src/tag/tag.js
Labels: bugfix

#881 test(slider): e2e a11y test
  src/slider/__tests__/slider.e2e.js
  src/slider/__tests__/slider.scenario.js
Labels: feature

#880 fix(datepicker): add e2e tests
  src/datepicker/__tests__/calendar.scenario.js
  src/datepicker/__tests__/datepicker-range.scenario.js
  src/datepicker/__tests__/datepicker.e2e.js
  src/datepicker/__tests__/datepicker.scenario.js
  src/datepicker/calendar.js
  src/datepicker/datepicker.js
  src/datepicker/day.js
  src/datepicker/month.js
  src/datepicker/types.js
  src/datepicker/week.js
Labels: bugfix

#884 chore(package): update to next@8
  documentation-site/components/meta.js
  documentation-site/pages/_document.js
  package.json
  yarn.lock
Labels: greenkeeping

#885 fix(datepicker): remove padding in the select dropdown container
  src/datepicker/calendar-header.js
Labels: bugfix

#886 fix(datepicker): add couple more e2e tests
  src/datepicker/__tests__/datepicker.e2e.js
  src/datepicker/__tests__/datepicker.scenario.js
Labels: bugfix

#887 Release v6.0.1
  package.json
Labels: release

#888 docs(layout): add proposal
  src/layout/README.md
  src/layout/layout_1.png
  src/layout/layout_2.png
  src/layout/layout_3.png
Labels: feature

#891 fix: ensures consistent date in calendar screener
  src/datepicker/__tests__/stateful-calendar-overrides.scenario.js
  src/datepicker/__tests__/stateful-calendar.scenario.js
  src/datepicker/__tests__/stateful-datepicker-quick-select.scenario.js
  src/datepicker/__tests__/stateful-range-quick-select.scenario.js
Labels: bugfix

#893 docs(getting-started): supported platforms
  documentation-site/pages/getting-started/supported-platforms.mdx
  documentation-site/routes.js
Labels: feature

#889 fix(radio): decouples radio from checkbox, enables overrides
  documentation-site/components/overrides.js
  documentation-site/pages/components/radio.mdx
  documentation-site/static/examples/form-control/basic.js
  documentation-site/static/examples/radio/basic.js
  documentation-site/static/examples/radio/error.js
  documentation-site/static/examples/radio/horizontal-align.js
  documentation-site/static/examples/radio/overrides.js
  documentation-site/static/examples/radio/stateful.js
  src/form-control/__tests__/form-control.scenario.js
  src/form-control/__tests__/form-control.test.js
  src/radio/README.md
  src/radio/__tests__/radio.scenario.js
  src/radio/__tests__/radio.test.js
  src/radio/__tests__/radiogroup.test.js
  src/radio/__tests__/radiogroup1.test.js
  src/radio/__tests__/stateful-radiogroup.test.js
  src/radio/index.js
  src/radio/radio.js
  src/radio/radiogroup.js
  src/radio/radiomark.js
  src/radio/styled-radio.js
  src/radio/types.js
Labels: bugfix

#890 docs(input): tags example
  documentation-site/pages/components/input.mdx
  documentation-site/static/examples/input/with-tags.js
Labels: feature

#895 docs(contributing): add docs site instead of storybook
  CONTRIBUTING.md
Labels: bugfix, docs

#894 docs(select): adds controlled example to docs site
  documentation-site/pages/components/select.mdx
  documentation-site/static/examples/select/controlled.js
Labels: bugfix

#892 chore(screener): add browsers
  screener.config.js
Labels: feature

#900 docs(algolia): exclude parts of the website
  documentation-site/components/layout.js
  documentation-site/components/sidebar.js
Labels: feature

#896 docs: deletes manual readme file docs, moves a11y info to docs site
  documentation-site/pages/components/accordion.mdx
  documentation-site/pages/components/avatar.mdx
  documentation-site/pages/components/datepicker.mdx
  documentation-site/pages/components/file-uploader.mdx
  documentation-site/pages/components/menu.mdx
  documentation-site/pages/components/modal.mdx
  documentation-site/pages/components/pagination.mdx
  documentation-site/pages/components/popover.mdx
  documentation-site/pages/components/progress-bar.mdx
  documentation-site/pages/components/rating.mdx
  documentation-site/pages/components/spinner.mdx
  documentation-site/pages/components/tabs.mdx
  documentation-site/pages/components/toast.mdx
  src/accordion/README.md
  src/avatar/README.md
  src/block/README.md
  src/breadcrumbs/README.md
  src/button-group/README.md
  src/button/README.md
  src/card/README.md
  src/checkbox/README.md
  src/datepicker/README.md
  src/dnd-list/README.md
  src/file-uploader/README.md
  src/form-control/README.md
  src/header-navigation/README.md
  src/icon/README.md
  src/input/README.md
  src/menu/README.md
  src/modal/README.md
  src/notification/README.md
  src/pagination/README.md
  src/popover/README.md
  src/progress-bar/README.md
  src/progress-steps/README.md
  src/radio/README.md
  src/rating/README.md
  src/select/README.md
  src/slider/README.md
  src/spinner/README.md
  src/table/README.md
  src/tabs/README.md
  src/tag/README.md
  src/template-component/README.md
  src/textarea/README.md
  src/toast/README.md
  src/tooltip/README.md
  src/typography/README.md
Labels: bugfix

#902 fix(algolia): proper attributes
  documentation-site/components/layout.js
  documentation-site/components/sidebar.js
Labels: bugfix

#903 feat(docs): add anchor for headings
  documentation-site/components/anchor.js
  documentation-site/components/example.js
  documentation-site/components/markdown-elements.js
Labels: feature

#899 fix(progress-step): overflow fixes
  documentation-site/static/examples/progress-steps/dotted.js
  src/progress-steps/styled-components.js
Labels: bugfix

#906 Release v6.0.2
  package.json
Labels: release

#909 fix(modal): removes any type in modal ref def
  src/modal/types.js
Labels: bugfix

#912 fix(project): remove selenium
  .buildkite/pipeline.yml
  docker-compose.yml
  package.json
  yarn.lock
Labels: bugfix

#914 fix(project): remove unused deps
  package.json
  yarn.lock
Labels: bugfix

#910 docs: adds button/button-group dropdown examples
  documentation-site/pages/components/button-group.mdx
  documentation-site/pages/components/button.mdx
  documentation-site/static/examples/button-group/dropdown.js
  documentation-site/static/examples/button/dropdown.js
Labels: bugfix

#917 docs(changelog): add link to changelog
  documentation-site/components/layout.js
Labels: feature

#905 fix(storybook): use move font in storybook
  .storybook/config.js
Labels: bugfix

#919 fix(input): update styletron-atomic to handle ie 11 placeholder fail
  package.json
  yarn.lock
Labels: bugfix

#921 fix(rating): fix missing svgs in IE
  src/pagination/icons.js
  src/rating/__tests__/__snapshots__/styled-components.test.js.snap
  src/rating/styled-components.js
  src/rating/svg-icons.js
Labels: bugfix

#916 fix(checkbox): fix toggle in ie 11
  documentation-site/pages/components/checkbox.mdx
  documentation-site/static/examples/checkbox/toggle.js
  src/checkbox/__tests__/__snapshots__/styled-components.test.js.snap
  src/checkbox/__tests__/styled-components.test.js
  src/checkbox/checkbox.js
  src/checkbox/index.js
  src/checkbox/styled-components.js
  src/checkbox/types.js
Labels: bugfix

#922 fix(docs-site): loads ie polyfills
  documentation-site/components/overrides.js
  documentation-site/helpers/polyfills.js
  documentation-site/next.config.js
Labels: bugfix

#923 docs(table): adds fixed col width example
  documentation-site/pages/components/table.mdx
  documentation-site/static/examples/table/fixed-width-column.js
Labels: bugfix

#908 feat(table): action buttons
  documentation-site/pages/components/table.mdx
  documentation-site/static/examples/table/cells.js
  src/table/__tests__/__snapshots__/styled-components.test.js.snap
  src/table/__tests__/styled-components.test.js
  src/table/__tests__/table-cells.scenario.js
  src/table/index.js
  src/table/styled-components.js
Labels: feature

#926 Release v6.1.0
  package.json
Labels: release

#927 fix(radio, checkbox): Correct spacing and font weights for radios and checkboxes
  documentation-site/static/examples/checkbox/alignment.js
  src/checkbox/__tests__/__snapshots__/styled-components.test.js.snap
  src/checkbox/styled-components.js
  src/radio/__tests__/__snapshots__/styled-components.test.js.snap
  src/radio/styled-components.js
Labels: bugfix

#929 fix(tag): closable prop disables hover
  src/tag/__tests__/__snapshots__/styled-components.test.js.snap
  src/tag/__tests__/styled-components.test.js
  src/tag/styled-components.js
Labels: bugfix

#930 Release v6.1.1
  package.json
Labels: release

#932 fix: removes overrides helper
  src/file-uploader/file-uploader.js
Labels: bugfix

#840 feat(table): adds filter functionality
  documentation-site/pages/components/table.mdx
  documentation-site/static/examples/table/filter.js
  package.json
  src/table/__tests__/__snapshots__/styled-components.test.js.snap
  src/table/__tests__/filter.test.js
  src/table/__tests__/styled-components.test.js
  src/table/__tests__/table-filter.scenario.js
  src/table/filter.js
  src/table/index.js
  src/table/styled-components.js
  src/table/trap-focus.js
  src/table/types.js
  yarn.lock
Labels: feature

#924 fix(datepicker): improve accessibility, make days focusable instead of the whole month
  src/datepicker/__tests__/datepicker.e2e.js
  src/datepicker/__tests__/datepicker.test.js
  src/datepicker/__tests__/navigation-container.test.js
  src/datepicker/calendar-header.js
  src/datepicker/calendar.js
  src/datepicker/datepicker.js
  src/datepicker/day.js
  src/datepicker/index.js
  src/datepicker/month.js
  src/datepicker/navigation-container.js
  src/datepicker/stateful-calendar.js
  src/datepicker/types.js
  src/datepicker/week.js
  src/input/__tests__/__snapshots__/base-input.test.js.snap
  src/input/__tests__/__snapshots__/input.test.js.snap
  src/input/__tests__/__snapshots__/masked-input.test.js.snap
  src/input/base-input.js
  src/input/types.js
  src/textarea/__tests__/__snapshots__/textarea.test.js.snap
Labels: bugfix

#925 feat(datepicker): make the datepicker a stable component
  documentation-site/pages/components/datepicker.mdx
  documentation-site/routes.js
  documentation-site/static/examples/datepicker/basic.js
  documentation-site/static/examples/datepicker/in-popover.js
  documentation-site/static/examples/datepicker/quick-select.js
  documentation-site/static/examples/datepicker/with-overrides.js
  src/datepicker/__tests__/calendar.scenario.js
  src/datepicker/__tests__/calendar.test.js
  src/datepicker/__tests__/datepicker-range.scenario.js
  src/datepicker/__tests__/datepicker.scenario.js
  src/datepicker/__tests__/datepicker.test.js
  src/datepicker/__tests__/stateful-calendar-overrides.scenario.js
  src/datepicker/__tests__/stateful-calendar.scenario.js
  src/datepicker/__tests__/stateful-calendar.test.js
  src/datepicker/__tests__/stateful-datepicker-quick-select.scenario.js
  src/datepicker/__tests__/stateful-datepicker.scenario.js
  src/datepicker/__tests__/stateful-datepicker.test.js
  src/datepicker/__tests__/stateful-range-datepicker.scenario.js
  src/datepicker/__tests__/stateful-range-quick-select.scenario.js
  src/datepicker/__tests__/stateless-calendar.scenario.js
  src/datepicker/__tests__/styled-components.test.js
  src/datepicker/calendar.js
  src/datepicker/datepicker.js
  src/datepicker/day.js
  src/datepicker/index.js
  src/datepicker/month.js
  src/datepicker/styled-components.js
  src/datepicker/types.js
  src/datepicker/week.js
Labels: feature

#933 fix(deploy): properly index last element in tags array
  scripts/now-deploy.sh
Labels: bugfix

#938 docs(copy-to-clipboard): remove
  documentation-site/components/example.js
  package.json
  yarn.lock
Labels: bugfix

#931 fix(tabs): do not render non-active tabs content
  src/tabs/__tests__/__snapshots__/stateful-tabs.test.js.snap
  src/tabs/tabs.js
Labels: bugfix

#937 feat(docs-site): adds an alias mapping to commit hash
  scripts/now-deploy.sh
Labels: feature

#939 Release v6.2.0
  package.json
Labels: release

#940 docs(api): make it a bit more like base
  documentation-site/components/api.js
Labels: feature

#942 fix(select): remove top and bottom margin on multi value
  src/select/multi-value.js
Labels: bugfix

#943 fix(deploy): rolls now version back to v13
  package.json
  yarn.lock
Labels: bugfix

#949 fix(datepicker): resolves calendar e2e test fails
  src/datepicker/__tests__/calendar.scenario.js
  src/datepicker/__tests__/stateless-calendar.scenario.js
Labels: bugfix

#950 fix(input): updates key events to use correct type
  src/input/types.js
Labels: bugfix

#948 table(feat): adds large text cell
  documentation-site/static/examples/table/cells.js
  src/table/__tests__/__snapshots__/styled-components.test.js.snap
  src/table/__tests__/table-cells.scenario.js
  src/table/styled-components.js
Labels: feature

#953 feat(table): add expandable cell example
  documentation-site/static/examples/table/cells.js
  src/table/__tests__/table-cells.scenario.js
Labels: feature

#957 fix(table): fixes table docs example
  documentation-site/static/examples/table/cells.js
Labels: bugfix

#958 docs(table): add example using react-vis
  documentation-site/pages/components/table.mdx
  documentation-site/static/examples/table/graph.js
  package.json
  yarn.lock
Labels: feature

#961 fix(table): removes expandable cell for now
  documentation-site/static/examples/table/cells.js
Labels: bugfix

#962 docs(link): add documentation for link
  documentation-site/pages/components/link.mdx
  documentation-site/routes.js
  documentation-site/static/examples/link/basic.js
Labels: documentation, feature

#964 fix(avatar): handle transparent avatar images
  src/avatar/__tests__/__snapshots__/styled-components.test.js.snap
  src/avatar/styled-components.js
Labels: bugfix

#965 Release v6.3.0
  package.json
Labels: release

#904 feat(table): enables sorting
  documentation-site/pages/components/table.mdx
  documentation-site/static/examples/table/sortable.js
  src/table/__tests__/sortable-head-cell.test.js
  src/table/__tests__/table-sortable.scenario.js
  src/table/index.js
  src/table/sortable-head-cell.js
  src/table/styled-components.js
  src/table/types.js
Labels: feature

#956 feat(spinner): enables negative color
  documentation-site/pages/components/progress-bar.mdx
  documentation-site/pages/components/spinner.mdx
  documentation-site/static/examples/progress-bar/negative.js
  documentation-site/static/examples/spinner/negative.js
  src/progress-bar/__tests__/progressbar-negative.scenario.js
  src/spinner/__tests__/__snapshots__/styled-components.test.js.snap
  src/spinner/__tests__/component.test.js
  src/spinner/__tests__/spinner-negative.scenario.js
  src/spinner/__tests__/styled-components.test.js
  src/spinner/index.js
  src/spinner/spinner.js
  src/spinner/styled-components.js
  src/spinner/types.js
Labels: feature

#959 feat(table): pagination example
  documentation-site/pages/components/table.mdx
  documentation-site/static/examples/table/pagination.js
  src/table/__tests__/table-pagination.scenario.js
Labels: feature

#960 docs: update the installation page
  documentation-site/pages/getting-started/installation.mdx
Labels: documentation, feature

#966 fix(table): gets rid of react-virtualized warnings
  documentation-site/static/examples/table/fixed-width-column.js
  documentation-site/static/examples/table/virtual-horizontal-scroll.js
  documentation-site/static/examples/table/virtual.js
Labels: bugfix

#963 docs: markdown element improvements and React bump
  CONTRIBUTING.md
  documentation-site/components/anchor.js
  documentation-site/components/example.js
  documentation-site/components/hooks.js
  documentation-site/components/markdown-elements.js
  documentation-site/helpers/slugify.js
  documentation-site/pages/components/styled.mdx
  documentation-site/pages/getting-started/installation.mdx
  jest.config.js
  package.json
  src/input/__tests__/__snapshots__/stateful-input.test.js.snap
  src/modal/__tests__/__snapshots__/modal.test.js.snap
  src/popover/__tests__/__snapshots__/stateful-popover.test.js.snap
  src/popover/__tests__/popover.test.js
  src/textarea/__tests__/__snapshots__/stateful-textarea.test.js.snap
  src/tooltip/__tests__/__snapshots__/stateful-tooltip.test.js.snap
  yarn.lock
Labels: documentation, feature

#967 docs: fix API doc headings and StatefulTab examples
  documentation-site/components/api.js
  documentation-site/pages/components/tabs.mdx
  documentation-site/static/examples/tabs/basic.js
  documentation-site/static/examples/tabs/vertical.js
Labels: bugfix, documentation

#951 feat(i18n): add i18n support
  documentation-site/components/code.js
  documentation-site/components/json.js
  documentation-site/pages/getting-started/internationalization.mdx
  documentation-site/routes.js
  documentation-site/static/examples/internationalization/example.js
  package.json
  src/accordion/locale.js
  src/accordion/panel.js
  src/breadcrumbs/__tests__/__snapshots__/breadcrumbs.test.js.snap
  src/breadcrumbs/__tests__/breadcrumbs.test.js
  src/breadcrumbs/breadcrumbs.js
  src/breadcrumbs/locale.js
  src/breadcrumbs/types.js
  src/button-group/__tests__/button-group.test.js
  src/button-group/button-group.js
  src/button-group/locale.js
  src/datepicker/__tests__/__snapshots__/styled-components.test.js.snap
  src/datepicker/calendar-header.js
  src/datepicker/datepicker.js
  src/datepicker/locale.js
  src/file-uploader/file-uploader.js
  src/file-uploader/locale.js
  src/index.js
  src/input/__tests__/__snapshots__/styled-components.test.js.snap
  src/locale/en_US.js
  src/locale/index.js
  src/locale/types.js
  src/modal/locale.js
  src/modal/modal.js
  src/pagination/locale.js
  src/pagination/pagination.js
  src/pagination/stateful-pagination.js
  src/pagination/types.js
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/default-props.js
  src/select/locale.js
  src/select/select.js
  src/select/types.js
  src/toast/locale.js
  src/toast/toast.js
  yarn.lock
Labels: feature

#970 Release v6.4.0
  package.json
Labels: release
