Repository uber/baseweb, pull requests merged in 2019-05, with the labels that each got.

#1208 fix: typo in ThemeProvider docs
  documentation-site/pages/theming/custom-themes.mdx
Labels: bugfix

#1204 feat(button): update button styles
  docs/migrations/01204.md
  documentation-site/pages/blog/getting-started-with-base-web/index.mdx
  documentation-site/static/examples/button/basic-compact.js
  documentation-site/static/examples/button/shapes.js
  documentation-site/static/examples/icon/button.js
  src/button-group/__tests__/button-group-sizes.scenario.js
  src/button-group/button-group.js
  src/button/__tests__/button-sizes.scenario.js
  src/button/constants.js
  src/button/styled-components.js
  src/icon/__tests__/icon-buttons.scenario.js
Labels: breaking, feature

#1211 chore(radiogroup): remove deprecated aria props
  docs/migrations/01211.md
  documentation-site/pages/theming/custom-themes.mdx
  src/radio/radiogroup.js
  src/radio/types.js
Labels: breaking, greenkeeping

#1213 chore(project): update to react 16.8
  docs/migrations/01213.md
  package.json
Labels: breaking, greenkeeping

#1151 feat(pagination): replace pagination dropdown with the Select component
  docs/migrations/01151.md
  documentation-site/pages/components/pagination.mdx
  documentation-site/static/examples/pagination/controlled.js
  documentation-site/static/examples/pagination/overrides.js
  src/pagination/__tests__/pagination.e2e.js
  src/pagination/__tests__/pagination.scenario.js
  src/pagination/__tests__/pagination.test.js
  src/pagination/index.js
  src/pagination/pagination.js
  src/pagination/styled-components.js
  src/pagination/types.js
Labels: breaking

#1210 feat(theme): theme docs respect OS theme preference
  documentation-site/pages/_app.js
Labels: feature

#1216 chore(theme): remove deprecated props
  docs/migrations/01216.md
  src/styles/types.js
  src/themes/creator.js
  src/themes/dark-theme-colors.js
Labels: breaking, greenkeeping

#1220 Release v6.16.0
  package.json
Labels: release

#1225 fix(buildkite): pin docker-compose plugin version
  .buildkite/pipeline.yml
Labels: bugfix

#1219 fix(docs): retain theme preference across page loads
  documentation-site/pages/_app.js
Labels: bugfix

#1226 docs(overrides): add nested examples
  documentation-site/pages/theming/understanding-overrides.mdx
  documentation-site/static/examples/select/overriden-tag.js
Labels: documentation, feature

#1218 fix(popover): avoids menu flash
  src/popover/popover.js
Labels: bugfix

#1228 chore: remove redundant conditional expressions and consistently use !!
  .babelrc.js
  documentation-site/static/examples/modal/basic.js
  jest-puppeteer.config.js
  src/button-group/button-group.js
  src/card/card.js
  src/datepicker/day.js
  src/modal/__tests__/modal.scenario.js
  src/modal/modal.js
  src/popover/popover.js
  src/select/select.js
  src/side-navigation/nav.js
Labels: greenkeeping

#1229 Remove engines fields, too restrictive and not being used
  package.json
Labels: bugfix

#1173 feat(side-nav): [wip] add mapItem to side-nav
  src/side-navigation/__tests__/__snapshots__/nav.test.js.snap
  src/side-navigation/__tests__/__snapshots__/stateful-nav.test.js.snap
  src/side-navigation/__tests__/nav.test.js
  src/side-navigation/nav.js
  src/side-navigation/types.js
Labels: feature, question

#1231 feat: accessibility addition suggestions for pagination
  src/pagination/pagination.js
  src/pagination/styled-components.js
Labels: feature

#1233 chore(readme): update
  README.md
Labels: docs

#1238 chore(project): add fossa
  .buildkite/pipeline.yml
  docker-compose.yml
  package.json
Labels: feature

#1239 docs: describe react-router integration with sidenav
  documentation-site/pages/components/sidenav.mdx
Labels: documentation

#1227 fix(progress-steps): fix the overlaping of the circle and vert line
  src/progress-steps/styled-components.js
Labels: bugfix

#1203 feat: add BaseProvider
  .storybook/config.js
  documentation-site/pages/_app.js
  documentation-site/pages/components/base-provider.mdx
  documentation-site/pages/components/layer.mdx
  documentation-site/pages/getting-started/usage.mdx
  documentation-site/pages/theming/custom-themes.mdx
  documentation-site/routes.js
  e2e/index.js
  src/helpers/base-provider.js
  src/index.js
Labels: feature

#1243 fix(select): show real value in DOM
  src/select/select.js
Labels: bugfix

#1240 fix(avatar): use a single pic in the screener test
  .storybook/webpack.config.js
  scripts/flow-copy-src.js
  src/avatar/__tests__/avatar.scenario.js
  src/avatar/__tests__/static/adorable.png
  webpack.e2e.config.js
Labels: bugfix

#1245 feat(menu and select): add empty/no results state
  src/locale/en_US.js
  src/locale/types.js
  src/menu/__tests__/menu-empty.scenario.js
  src/menu/__tests__/menu.test.js
  src/menu/__tests__/option-list.test.js
  src/menu/__tests__/option-profile.test.js
  src/menu/index.js
  src/menu/locale.js
  src/menu/menu.js
  src/menu/option-list.js
  src/menu/option-profile.js
  src/menu/styled-components.js
  src/menu/types.js
  src/select/dropdown.js
  src/select/locale.js
  src/select/select.js
  src/select/types.js
Labels: feature

#1246 fix(select): allow overrides for the Popover in Select
  src/select/select.js
  src/select/types.js
Labels: bugfix

#1244 fix(slider): set root's position to relative so overflow doesn't matter
  src/slider/styled-components.js
Labels: bugfix

#1247 Release v6.17.0
  package.json
Labels: release

#1248 fix(docs): add props description for the Layer and Tether components
  src/helpers/base-provider.js
  src/helpers/types.js
  src/layer/types.js
  src/pagination/pagination.js
Labels: bugfix, documentation

#1249 docs(providers): use baseprovider in the docs
  README.md
  documentation-site/pages/blog/getting-started-with-styletron/index.mdx
  documentation-site/pages/getting-started/usage.mdx
  documentation-site/pages/theming/custom-themes.mdx
Labels: bugfix, documentation

#1250 feat(block): allow gridRowGap
  src/block/block.js
  src/block/styled-components.js
  src/block/types.js
Labels: feature

#1253 fix(styled-components): border radius long hand
  src/avatar/styled-components.js
  src/button/styled-components.js
  src/checkbox/styled-components.js
  src/datepicker/styled-components.js
  src/file-uploader/styled-components.js
  src/menu/styled-components.js
  src/modal/styled-components.js
  src/progress-steps/styled-components.js
  src/radio/styled-components.js
  src/table/styled-components.js
  src/tag/styled-components.js
  src/toast/styled-components.js
  src/tooltip/styled-components.js
Labels: bugfix

#1254 fix(types): more accurately type react ref
  src/checkbox/types.js
  src/input/base-input.js
  src/input/types.js
  src/layer/layers-manager.js
  src/menu/nested-menus.js
  src/menu/stateful-container.js
  src/menu/types.js
  src/modal/types.js
  src/pagination/pagination.js
  src/radio/types.js
  src/select/autosize-input.js
  src/select/select.js
  src/select/types.js
  src/textarea/textarea.js
Labels: bugfix

#1255 Release v6.17.1
  package.json
Labels: release

#1256 fix(block): allow zero for scale props and numbers for flex props
  src/block/types.js
Labels: bugfix

#1251 feat(side-navigation): Remove renderItem prop, fix overrides
  docs/migrations/01251.md
  documentation-site/static/examples/side-navigation/nav-overrides.js
  src/side-navigation/__tests__/__snapshots__/stateful-nav.test.js.snap
  src/side-navigation/nav-item.js
  src/side-navigation/nav.js
  src/side-navigation/types.js
Labels: breaking

#1257 fix(layer-manager): use exact element type in ref instance
  src/layer/layers-manager.js
Labels: bugfix

#1258 Release v6.17.2
  package.json
Labels: release

#1264 fix(docs): update base-web-white.svg to be consistent with base-web.svg
  documentation-site/images/base-web-white.svg
Labels: bugfix

#1265 docs(accordion): clarify panel overrides
  documentation-site/pages/components/accordion.mdx
Labels: bugfix

#1263 fix(accordion): fix StatefulPanel props list in docs
  src/accordion/stateful-panel-container.js
  src/accordion/types.js
Labels: bugfix

#1269 chore: add CODEOWNERS
  .github/CODEOWNERS
Labels: feature

#1266 fix(tether): print out a warning message if an anchor ref is not set
  documentation-site/pages/components/popover.mdx
  documentation-site/static/examples/popover/ref-handling.js
  src/layer/tether.js
  src/select/types.js
Labels: bugfix

#1271 fix(icons): only import icons used by the component
  src/accordion/panel.js
  src/breadcrumbs/styled-components.js
  src/datepicker/calendar-header.js
  src/select/select.js
  src/toast/toast.js
Labels: bugfix

#1275 fix(docs): update react router sidenav example
  documentation-site/pages/components/sidenav.mdx
Labels: bugfix, documentation

#1276 fix(menu): pass props down to the stateless menu
  src/menu/stateful-container.js
Labels: bugfix

#1262 feat(inputs): update to latest styles
  docs/migrations/01262.md
  documentation-site/pages/components/input.mdx
  documentation-site/static/examples/input/available-states.js
  documentation-site/static/examples/input/compact-size.js
  documentation-site/static/examples/input/sizes.js
  src/input/__tests__/__snapshots__/base-input.test.js.snap
  src/input/__tests__/__snapshots__/input.test.js.snap
  src/input/__tests__/__snapshots__/masked-input.test.js.snap
  src/input/__tests__/__snapshots__/utils.test.js.snap
  src/input/__tests__/input-sizes.scenario.js
  src/input/__tests__/input-states.scenario.js
  src/input/__tests__/input-with-button.scenario.js
  src/input/__tests__/utils.test.js
  src/input/base-input.js
  src/input/constants.js
  src/input/input.js
  src/input/styled-components.js
  src/input/types.js
  src/input/utils.js
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/__tests__/select-sizes.scenario.js
  src/select/__tests__/select-states.scenario.js
  src/select/default-props.js
  src/select/select.js
  src/select/styled-components.js
  src/select/types.js
  src/side-navigation/styled-components.js
  src/styles/types.js
  src/textarea/__tests__/__snapshots__/textarea.test.js.snap
  src/themes/creator.js
  src/themes/dark-theme-colors.js
Labels: breaking, enhancement, feature

#1278 docs(select): add custom label example
  documentation-site/pages/components/select.mdx
  documentation-site/static/examples/select/label.js
Labels: bugfix, documentation

#1280 docs: uncontrolled input with default value
  documentation-site/pages/components/input.mdx
  documentation-site/static/examples/input/basic-uncontrolled-default-value.js
Labels: documentation, examples, feature

#1277 docs(legacy): deploy legacy docs sites
  .buildkite/pipeline.yml
  documentation-site/components/header-navigation.js
  package.json
  scripts/build-docs.js
  scripts/now-deploy.sh
  yarn.lock
Labels: feature

#1281 Release v6.17.3
  package.json
Labels: release

#1195 chore: remove undefined attributes
  documentation-site/components/markdown-elements.js
  documentation-site/env-config.js
  src/file-uploader/file-uploader.js
  src/form-control/__tests__/form-control.test.js
  src/layer/layers-manager.js
  src/layer/types.js
  src/modal/modal.js
  src/select/utils/default-filter-options.js
  src/tag/__tests__/tag.scenario.js
Labels: greenkeeping

#1283 fix(toast): add tabIndex to <Toast/> body so it can be focused
  src/toast/toast.js
Labels: bugfix

#1279 docs(theming-values): add example borders
  documentation-site/components/theming-values/borders.js
  documentation-site/pages/theming/theming-values.mdx
Labels: documentation, feature

#1285 Release v6.17.4
  package.json
Labels: release

#1286 feat(block): add backgroundColor prop to Block
  src/block/__tests__/block.test.js
  src/block/block.js
  src/block/styled-components.js
  src/block/types.js
Labels: feature

#1287 chore(block): use backgroundColor prop when possible
  documentation-site/components/layout.js
  documentation-site/pages/_app.js
  documentation-site/static/examples/block/responsive.js
  documentation-site/static/examples/layer/basic-tether.js
  documentation-site/static/examples/layer/basic.js
  documentation-site/static/examples/select/label.js
Labels: greenkeeping

#1288 fix(select): expand the condition for the input width check
  src/select/autosize-input.js
Labels: bugfix

#1291 fix(menu): add aria-activedescendant
  documentation-site/pages/components/menu.mdx
  src/menu/__tests__/stateful-container.test.js
  src/menu/menu.js
  src/menu/stateful-container.js
  src/menu/stateful-menu.js
  src/menu/types.js
Labels: bugfix

#1292 Release v6.18.0
  package.json
Labels: release

#1294 fix(nav-item): add missing item prop and update doc site sidebar
  documentation-site/components/sidebar.js
  src/side-navigation/nav-item.js
Labels: bugfix, documentation

#1289 feat(flex-grid): add flex-grid component
  documentation-site/pages/components/flex-grid.mdx
  documentation-site/routes.js
  documentation-site/static/examples/flex-grid/basic.js
  documentation-site/static/examples/flex-grid/missing.js
  documentation-site/static/examples/flex-grid/responsive.js
  documentation-site/static/examples/flex-grid/unequal-narrow.js
  documentation-site/static/examples/flex-grid/unequal-wide.js
  package.json
  src/block/styled-components.js
  src/block/types.js
  src/flex-grid/__tests__/__snapshots__/flex-grid-item.test.js.snap
  src/flex-grid/__tests__/__snapshots__/flex-grid.test.js.snap
  src/flex-grid/__tests__/flex-grid-item.test.js
  src/flex-grid/__tests__/flex-grid-missing.scenario.js
  src/flex-grid/__tests__/flex-grid-unequal-narrow.scenario.js
  src/flex-grid/__tests__/flex-grid-unequal-wide.scenario.js
  src/flex-grid/__tests__/flex-grid.scenario.js
  src/flex-grid/__tests__/flex-grid.test.js
  src/flex-grid/flex-grid-item.js
  src/flex-grid/flex-grid.js
  src/flex-grid/index.js
  src/flex-grid/types.js
  src/helpers/__tests__/__snapshots__/react-helpers.test.js.snap
  src/helpers/__tests__/react-helpers.test.js
  src/helpers/__tests__/responsive-helpers.test.js
  src/helpers/__tests__/strings.test.js
  src/helpers/react-helpers.js
  src/helpers/responsive-helpers.js
  src/helpers/strings.js
  yarn.lock
Labels: feature

#1295 Release v6.19.0
  package.json
Labels: release

#1178 Calendar dropdown quick select
  docs/migrations/01178.md
  documentation-site/components/search.js
  documentation-site/components/theming-values/common.js
  documentation-site/pages/components/datepicker.mdx
  documentation-site/static/examples/datepicker/calendar-time-select.js
  documentation-site/static/examples/datepicker/composed-range-pickers.js
  documentation-site/static/examples/datepicker/composed-single-pickers.js
  documentation-site/static/examples/datepicker/with-overrides.js
  src/datepicker/__tests__/calendar-time-select.scenario.js
  src/datepicker/__tests__/calendar.test.js
  src/datepicker/__tests__/datepicker.e2e.js
  src/datepicker/__tests__/datepicker.scenario.js
  src/datepicker/__tests__/datepickers-composed-range.scenario.js
  src/datepicker/__tests__/datepickers-composed-single.scenario.js
  src/datepicker/__tests__/stateful-calendar-overrides.scenario.js
  src/datepicker/__tests__/timezone-picker.scenario.js
  src/datepicker/calendar-header.js
  src/datepicker/calendar.js
  src/datepicker/datepicker.js
  src/datepicker/locale.js
  src/datepicker/stateful-calendar.js
  src/datepicker/stateful-container.js
  src/datepicker/styled-components.js
  src/datepicker/timepicker.js
  src/datepicker/timezone-picker.js
  src/datepicker/types.js
  src/datepicker/utils/index.js
Labels: breaking, feature

#1298 fix(dropdown): change width of dropdown, added v6
  documentation-site/components/header-navigation.js
  scripts/build-docs.js
Labels: bugfix

#1297 fix(select): add missing StyledIconsContainer export and fix override…
  documentation-site/pages/components/select.mdx
  src/select/index.js
Labels: bugfix

#1299 feat(menu): pass event to onItemSelect when called with onClick
  src/menu/__tests__/stateful-container.test.js
  src/menu/stateful-container.js
Labels: feature

#1300 Release v6.19.1
  package.json
Labels: release

#1223 fix: fix flow type to allow stateful tab to have one child element
  src/tabs/__tests__/tabs-one-child.scenario.js
  src/tabs/types.js
Labels: bugfix

#1305 fix(masked-input): avoid passing overrides to MaskOverride
  src/input/__tests__/__snapshots__/masked-input.test.js.snap
  src/input/masked-input.js
  src/input/types.js
Labels: bugfix

#1307 chore: consistently order border-radius properties
  documentation-site/static/examples/popover/overrides.js
  src/avatar/styled-components.js
  src/button-group/button-group.js
  src/button/styled-components.js
  src/checkbox/styled-components.js
  src/datepicker/styled-components.js
  src/file-uploader/styled-components.js
  src/menu/styled-components.js
  src/modal/styled-components.js
  src/popover/styled-components.js
  src/progress-bar/styled-components.js
  src/progress-steps/styled-components.js
  src/radio/styled-components.js
  src/slider/styled-components.js
  src/table/styled-components.js
  src/tag/styled-components.js
  src/toast/styled-components.js
  src/tooltip/styled-components.js
Labels: greenkeeping

#1303 fix(datepicker): formatting
  package.json
  src/datepicker/datepicker.js
  src/datepicker/day.js
  src/datepicker/utils/index.js
  src/flex-grid/__tests__/flex-grid-unequal-narrow.scenario.js
  src/flex-grid/__tests__/flex-grid-unequal-wide.scenario.js
  yarn.lock
Labels: bugfix

#1309 Release v6.19.2
  package.json
Labels: release

#1306 chore: remove redundant measure units and use numbers when possible
  documentation-site/components/sidebar.js
  documentation-site/pages/components/tooltip.mdx
  documentation-site/prism-coy.css
  documentation-site/static/examples/checkbox/alignment.js
  documentation-site/static/examples/tooltip/stateful-complex-content.js
  documentation-site/static/examples/tooltip/stateful.js
  src/accordion/styled-components.js
  src/button/styled-components.js
  src/datepicker/calendar-header.js
  src/datepicker/datepicker.js
  src/datepicker/day.js
  src/datepicker/styled-components.js
  src/dnd-list/styled-components.js
  src/form-control/styled-components.js
  src/header-navigation/styled-components.js
  src/input/styled-components.js
  src/menu/styled-components.js
  src/modal/__tests__/__snapshots__/modal.test.js.snap
  src/modal/modal.js
  src/modal/styled-components.js
  src/popover/styled-components.js
  src/popover/types.js
  src/progress-bar/styled-components.js
  src/progress-steps/styled-components.js
  src/select/multi-value.js
  src/select/styled-components.js
  src/side-navigation/styled-components.js
  src/slider/styled-components.js
  src/table/__tests__/table-cells.scenario.js
  src/tag/__tests__/__snapshots__/tag.test.js.snap
  src/tag/styled-components.js
  src/tag/tag.js
  src/toast/styled-components.js
  src/typography/__tests__/index.js
Labels: bugfix

#1308 chore: consistently use longhand border-radius properties
  documentation-site/components/blog.js
  documentation-site/components/markdown-elements.js
  documentation-site/components/search.js
  documentation-site/components/theming-values/borders.js
  documentation-site/components/theming-values/lighting.js
  documentation-site/pages/blog/getting-started-with-base-web/index.mdx
  documentation-site/pages/blog/getting-started-with-styletron/index.mdx
  documentation-site/pages/getting-started/usage.mdx
  documentation-site/static/examples/avatar/override.js
  documentation-site/static/examples/datepicker/with-overrides.js
  documentation-site/static/examples/pagination/overrides.js
  documentation-site/static/examples/slider/overrides.js
  documentation-site/static/examples/spinner/with-overrides.js
  src/datepicker/__tests__/stateful-calendar-overrides.scenario.js
  src/datepicker/styled-components.js
  src/input/styled-components.js
  src/select/styled-components.js
  src/styles/__tests__/styled.test.js
Labels: greenkeeping

#1313 Release v6.19.3
  package.json
Labels: release

#1314 fix(masked-input): pass props to input
  src/input/__tests__/__snapshots__/masked-input.test.js.snap
  src/input/__tests__/masked-input.test.js
  src/input/masked-input.js
Labels: bugfix

#1315 fix(table): remove fixed width for table filter footer
  src/table/styled-components.js
Labels: bugfix

#1316 Release v6.19.4
  package.json
Labels: release

#1311 feat(heading): add component Heading
  documentation-site/pages/components/heading.mdx
  documentation-site/pages/components/typography.mdx
  documentation-site/routes.js
  documentation-site/static/examples/heading/basic.js
  documentation-site/static/examples/heading/decouple-styles.js
  proposals/heading-component.md
  src/heading/__tests__/__snapshots__/heading.test.js.snap
  src/heading/__tests__/heading.scenario.js
  src/heading/__tests__/heading.test.js
  src/heading/heading-level.js
  src/heading/heading.js
  src/heading/index.js
  src/heading/types.js
Labels: feature

#1319 fix(border-radius): use the proper long-hand prop
  documentation-site/components/blog.js
  documentation-site/components/markdown-elements.js
  documentation-site/components/search.js
  documentation-site/components/theming-values/borders.js
  documentation-site/components/theming-values/lighting.js
  documentation-site/pages/blog/getting-started-with-base-web/index.mdx
  documentation-site/pages/blog/getting-started-with-styletron/index.mdx
  documentation-site/pages/getting-started/usage.mdx
  documentation-site/static/examples/avatar/override.js
  documentation-site/static/examples/datepicker/with-overrides.js
  documentation-site/static/examples/pagination/overrides.js
  documentation-site/static/examples/slider/overrides.js
  documentation-site/static/examples/spinner/with-overrides.js
  src/datepicker/__tests__/stateful-calendar-overrides.scenario.js
  src/datepicker/styled-components.js
  src/input/styled-components.js
  src/select/styled-components.js
  src/styles/__tests__/styled.test.js
Labels: bugfix

#1317 Release v6.20.0
  package.json
Labels: release

#1321 docs(avatar): add initials example
  documentation-site/pages/components/avatar.mdx
  documentation-site/static/examples/avatar/initals.js
Labels: feature

#1320 fix: updating Select/StyledValueContainer to fix text color in dark mode
  src/select/styled-components.js
Labels: bugfix

#1324 fix(timezone-picker): fix select overrides
  src/datepicker/timezone-picker.js
Labels: bugfix

#1326 docs(styletron-codemod): adds instructions to run
  docs/migrations/01207.md
Labels: docs

#1325 Release v6.20.1
  package.json
Labels: release

#1327 docs(usage): remove hardcoded codesandbox
  documentation-site/pages/getting-started/usage.mdx
  documentation-site/static/examples/getting-started/usage.js
Labels: bugfix

#1329 fix(datepicker): keyboard control ally improvements
  docs/migrations/01207.md
  documentation-site/pages/blog/base-web-v7/index.mdx
  src/datepicker/__tests__/datepicker.e2e.js
  src/datepicker/calendar-header.js
  src/datepicker/types.js
Labels: feature

#1333 Select v7 touch ups
  documentation-site/pages/components/select.mdx
  documentation-site/static/examples/select/sizes.js
  src/menu/styled-components.js
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/styled-components.js
Labels: feature

#1332 feat(icon): add chevron up and down
  documentation-site/components/header-navigation.js
  documentation-site/static/examples/button/dropdown.js
  src/icon/chevron-down.js
  src/icon/chevron-up.js
  src/icon/icon-exports.js
  src/icon/svg/chevron-down.svg
  src/icon/svg/chevron-up.svg
  src/styles/types.js
Labels: feature

#1322 feat(timepicker): add prop to allow manual entry of times
  documentation-site/static/examples/datepicker/timepicker.js
  src/datepicker/__tests__/time-picker.e2e.js
  src/datepicker/__tests__/time-picker.scenario.js
  src/datepicker/timepicker.js
  src/datepicker/types.js
Labels: feature

#1336 Release v6.21.0
  package.json
Labels: release

#1337 feat(border-radius): removes radius from components
  documentation-site/components/search.js
  documentation-site/components/theming-values/borders.js
  documentation-site/components/theming-values/lighting.js
  documentation-site/static/examples/datepicker/with-overrides.js
  documentation-site/static/examples/popover/overrides.js
  src/card/styled-components.js
  src/datepicker/__tests__/stateful-calendar-overrides.scenario.js
  src/file-uploader/styled-components.js
  src/modal/styled-components.js
  src/popover/__tests__/__snapshots__/popover.test.js.snap
  src/popover/styled-components.js
  src/toast/styled-components.js
  src/tooltip/styled-components.js
Labels: feature

#1339 fix(compatiblity): ie11 starts-with
  documentation-site/helpers/polyfills.js
  src/datepicker/timepicker.js
Labels: bugfix

#1341 docs(v7-migration): adds info about withStyle
  docs/migrations/01207.md
Labels: bugfix, docs

#1340 feat(documentation): adds new showcase example in README and docs
  README.md
  documentation-site/pages/getting-started/learn.mdx
Labels: ci, documentation, feature

#1338 fix: fix input sizes, colors and rounded borders in dropdowns and popovers
  documentation-site/static/examples/input/before-after.js
  documentation-site/static/examples/input/enhancers.js
  documentation-site/static/examples/select/sizes.js
  documentation-site/static/examples/side-navigation/nav-overrides.js
  src/input/__tests__/__snapshots__/base-input.test.js.snap
  src/input/__tests__/__snapshots__/input.test.js.snap
  src/input/__tests__/__snapshots__/masked-input.test.js.snap
  src/input/styled-components.js
  src/pagination/pagination.js
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/autosize-input.js
  src/select/styled-components.js
  src/select/types.js
  src/styles/types.js
  src/textarea/__tests__/__snapshots__/textarea.test.js.snap
  src/themes/creator.js
Labels: bugfix

#1343 feat(textarea): add sizes, allow before/after elements
  documentation-site/static/examples/input/before-after.js
  documentation-site/static/examples/textarea/basic.js
  src/input/__tests__/__snapshots__/base-input.test.js.snap
  src/input/__tests__/__snapshots__/input.test.js.snap
  src/input/__tests__/__snapshots__/masked-input.test.js.snap
  src/input/styled-components.js
  src/input/types.js
  src/pagination/pagination.js
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/styled-components.js
  src/textarea/__tests__/__snapshots__/textarea.test.js.snap
  src/textarea/__tests__/textarea.test.js
  src/textarea/constants.js
  src/textarea/index.js
  src/textarea/styled-components.js
  src/textarea/textarea.js
  src/textarea/types.js
Labels: bugfix

#1344 fix(select): left/right arrows should navigate input
  src/menu/stateful-container.js
  src/select/__tests__/select.e2e.js
Labels: bugfix

#1345 Release v6.21.1
  package.json
Labels: release

#1342 chore: bump styletron deps
  package.json
  yarn.lock
Labels: feature

#1347 fix(docs-site): minor fixes
  documentation-site/components/header-navigation.js
  documentation-site/components/search.js
  documentation-site/pages/components/link.mdx
  documentation-site/static/examples/button/dropdown.js
  documentation-site/static/examples/header-navigation/basic.js
Labels: bugfix

#1349 fix(pagination): dropdown max height
  src/pagination/pagination.js
Labels: bugfix

#1350 docs: deemphasize version selector
  documentation-site/components/header-navigation.js
Labels: feature
