Repository uber/baseweb, pull requests merged in 2019-06, with the labels that each got.

#1352 fix(select): fix font size in compact select input
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/autosize-input.js
  src/select/styled-components.js
Labels: bugfix

#1353 fix(button): fix button side paddings, font and add back square shape
  docs/migrations/01207.md
  documentation-site/static/examples/button/shapes.js
  documentation-site/static/examples/pagination/overrides.js
  src/button/constants.js
  src/button/styled-components.js
  src/input/styled-components.js
  src/select/styled-components.js
  src/styles/types.js
  src/themes/creator.js
Labels: bugfix

#1354 docs: dark theme for code examples
  documentation-site/components/blog.js
  documentation-site/components/posts.js
  documentation-site/pages/_app.js
  documentation-site/tomorrow-night.css
Labels: documentation, feature

#1351 fix(documentation): updates popover ref example
  documentation-site/static/examples/popover/ref-handling.js
Labels: bugfix

#1355 fix(blog-post): add migrations
  documentation-site/pages/blog/base-web-v7/index.mdx
Labels: bugfix

#1358 fix(input): change tag to solid
  documentation-site/static/examples/input/with-tags.js
Labels: bugfix

#1359 bugfix(tooltip): use scale600 for left and right padding
  src/tooltip/styled-components.js
Labels: bugfix

#1360 fix(font): remove bold usage
  src/themes/creator.js
  src/themes/dark-theme-with-move.js
  src/themes/light-theme-with-move.js
Labels: bugfix

#1356 fix(datepicker): remove rounded corners, fix overrides example
  documentation-site/static/examples/datepicker/with-overrides.js
  src/datepicker/__tests__/stateful-calendar-overrides.scenario.js
  src/datepicker/styled-components.js
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/select.js
Labels: bugfix

#1361 fix(v7): addresses designer feedback
  documentation-site/pages/components/popover.mdx
  documentation-site/static/examples/popover/clipping.js
  documentation-site/static/examples/popover/dismiss.js
  documentation-site/static/examples/popover/overrides.js
  documentation-site/static/examples/popover/placements.js
  documentation-site/static/examples/popover/stateful-click.js
  documentation-site/static/examples/popover/stateful-hover.js
  documentation-site/static/examples/popover/stateless.js
  documentation-site/static/examples/popover/with-arrow.js
  src/button/styled-components.js
  src/toast/toast.js
Labels: bugfix

#1363 Release v7.0.0
  package.json
Labels: release

#1365 fix(select): use solid tags
  src/select/__tests__/__snapshots__/multi-value.test.js.snap
  src/select/multi-value.js
Labels: bugfix

#1267 docs: add debug mode
  documentation-site/helpers/styletron.js
  documentation-site/pages/_app.js
Labels: feature

#1372 docs(navigation): remove basic from input names
  documentation-site/routes.js
Labels: bugfix

#1377 fix(calendar): remove dayjs
  documentation-site/static/examples/datepicker/composed-range-pickers.js
  package.json
  src/datepicker/__tests__/datepickers-composed-range.scenario.js
  src/datepicker/datepicker.js
  src/datepicker/day.js
  src/datepicker/utils/index.js
  yarn.lock
Labels: bugfix

#1373 fix(docs): updates example to styletron v5
  documentation-site/components/example.js
Labels: bugfix

#1375 Release v7.0.1
  package.json
Labels: release

#1346 fix(menu): improves scroll item performance
  src/menu/__tests__/menu.test.js
  src/menu/option-list.js
  src/menu/stateful-container.js
  src/menu/types.js
Labels: bugfix

#1364 feat(form-control): positive option
  documentation-site/pages/components/form-control.mdx
  documentation-site/static/examples/form-control/kinds.js
  src/form-control/__tests__/form-control.test.js
  src/form-control/constants.js
  src/form-control/form-control.js
  src/form-control/styled-components.js
  src/form-control/types.js
Labels: feature

#1379 test(datepicker): add test to verify date-fns
  src/datepicker/__tests__/datepicker-range.scenario.js
  src/datepicker/__tests__/datepicker.e2e.js
Labels: bugfix

#1368 feat(input): adds input before/after examples
  documentation-site/static/examples/input/before-after.js
Labels: feature

#1382 Release v7.1.0
  package.json
Labels: release

#1384 docs: update phone-input docs with helpful information
  documentation-site/pages/components/phone-input.mdx
Labels: bugfix, documentation

#1387 feat: add all background CSS properties to Block
  src/block/__tests__/__snapshots__/block.test.js.snap
  src/block/__tests__/block.test.js
  src/block/block.js
  src/block/styled-components.js
  src/block/types.js
Labels: enhancement, feature

#1369 feat(payment-card): add component Payment Card
  documentation-site/pages/components/payment-card.mdx
  documentation-site/routes.js
  documentation-site/static/examples/payment-card/controlled.js
  documentation-site/static/examples/payment-card/defaultvalue.js
  documentation-site/static/examples/payment-card/uncontrolled.js
  package.json
  src/input/__tests__/__snapshots__/base-input.test.js.snap
  src/input/__tests__/__snapshots__/input.test.js.snap
  src/input/__tests__/__snapshots__/masked-input.test.js.snap
  src/input/base-input.js
  src/input/types.js
  src/payment-card/__tests__/payment-card.e2e.js
  src/payment-card/__tests__/payment-card.scenario.js
  src/payment-card/__tests__/payment-card.test.js
  src/payment-card/__tests__/stateful-payment-card.scenario.js
  src/payment-card/icons/amex.js
  src/payment-card/icons/dinersclub.js
  src/payment-card/icons/discover.js
  src/payment-card/icons/elo.js
  src/payment-card/icons/generic.js
  src/payment-card/icons/jcb.js
  src/payment-card/icons/maestro.js
  src/payment-card/icons/mastercard.js
  src/payment-card/icons/unionpay.js
  src/payment-card/icons/visa.js
  src/payment-card/index.js
  src/payment-card/payment-card.js
  src/payment-card/stateful-payment-card.js
  src/payment-card/styled-components.js
  src/payment-card/types.js
  src/payment-card/utils.js
  src/textarea/__tests__/__snapshots__/textarea.test.js.snap
  yarn.lock
Labels: feature

#1391 Release v7.2.0
  package.json
Labels: release

#1381 feat(a11y-checker): Utility to inspect components for violations at runtime
  documentation-site/pages/components/unstable-a11y.mdx
  documentation-site/routes.js
  documentation-site/static/examples/unstable-a11y/wrapper.js
  src/a11y/a11y.js
  src/a11y/index.js
  src/a11y/types.js
Labels: feature

#1331 feat(block): add textOverflow and whiteSpace props to Block
  src/block/block.js
  src/block/styled-components.js
  src/block/types.js
Labels: feature

#1393 fix: typo in BaseProvider docs
  documentation-site/pages/components/base-provider.mdx
Labels: documentation

#1394 feat(docs): adds datepicker example with localization
  documentation-site/pages/components/datepicker.mdx
  documentation-site/static/examples/datepicker/i18n.js
Labels: feature

#1398 fix(button): use simpler example for anchor
  documentation-site/static/examples/button/as-an-anchor.js
Labels: bugfix

#1389 fix: refactor useRoundedCorners to be more discrete
  src/button-group/button-group.js
  src/button/styled-components.js
  src/card/styled-components.js
  src/datepicker/styled-components.js
  src/input/styled-components.js
  src/menu/styled-components.js
  src/modal/styled-components.js
  src/popover/__tests__/__snapshots__/popover.test.js.snap
  src/popover/styled-components.js
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/styled-components.js
  src/styles/types.js
  src/themes/creator.js
  src/toast/styled-components.js
Labels: bugfix

#1404 Release v7.2.1
  package.json
Labels: release

#1405 docs: update v7 blog post with new borderRadius theme variables
  documentation-site/pages/blog/base-web-v7/index.mdx
Labels: bugfix, documentation

#1407 feat(slider): export StyledThumbValue
  src/slider/index.js
Labels: feature

#1409 fix(table): proper STYLETRON context propagation for the table element
  src/table/__tests__/borderless-table.scenario.js
  src/table/index.js
  src/table/styled-components.js
Labels: bugfix

#1410 Release v7.3.0
  package.json
Labels: release

#1411 fix(datepicker): fix date format for range select
  documentation-site/static/examples/datepicker/composed-range-pickers.js
Labels: bugfix

#1392 fix(dnd-list): prevent default to avoid double removals
  src/dnd-list/list.js
Labels: bugfix

#1413 Release v7.3.1
  package.json
Labels: release

#1406 feat(modal): a11y enhancements (focus order & trapping)
  documentation-site/pages/components/modal.mdx
  documentation-site/static/examples/modal/autofocus.js
  documentation-site/static/examples/modal/buried-interactive-element.js
  flow-typed/npm/focus-trap-react_vx.x.x.js
  package.json
  src/modal/__tests__/__snapshots__/modal.test.js.snap
  src/modal/__tests__/modal.e2e.js
  src/modal/__tests__/modal.scenario.js
  src/modal/focus-once.js
  src/modal/index.js
  src/modal/modal.js
  src/modal/styled-components.js
  src/modal/types.js
  src/table/filter.js
  src/table/trap-focus.js
  src/utils/ownerDocument.js
  yarn.lock
Labels: enhancement, feature

#1415 Release v7.4.0
  package.json
Labels: release

#1416 docs(select): add example for dropdown overrides
  documentation-site/pages/components/select.mdx
  documentation-site/static/examples/select/overridden-dropdown.js
Labels: documentation, feature

#1417 fix(flow): targeted fixes to flow types for consumers
  package.json
  src/a11y/a11y.js
  src/card/styled-components.js
  src/phone-input/country-select.js
  src/phone-input/styled-components.js
  src/select/styled-components.js
  src/select/types.js
  src/textarea/styled-components.js
  yarn.lock
Labels: bugfix

#1418 Release v7.4.1
  package.json
Labels: release

#1414 feat(aspect-ratio-box): add aspect-ratio-box utility component
  documentation-site/pages/components/aspect-ratio-box.mdx
  documentation-site/routes.js
  documentation-site/static/examples/aspect-ratio-box/basic.js
  documentation-site/static/examples/aspect-ratio-box/calendar.js
  documentation-site/static/examples/aspect-ratio-box/image.js
  src/aspect-ratio-box/__tests__/__snapshots__/aspect-ratio-box-body.test.js.snap
  src/aspect-ratio-box/__tests__/__snapshots__/aspect-ratio-box.test.js.snap
  src/aspect-ratio-box/__tests__/aspect-ratio-box-basic.scenario.js
  src/aspect-ratio-box/__tests__/aspect-ratio-box-body.test.js
  src/aspect-ratio-box/__tests__/aspect-ratio-box.test.js
  src/aspect-ratio-box/aspect-ratio-box-body.js
  src/aspect-ratio-box/aspect-ratio-box.js
  src/aspect-ratio-box/index.js
  src/aspect-ratio-box/types.js
Labels: feature

#1419 docs: resolve #1348 by including resizable textarea example
  documentation-site/pages/components/textarea.mdx
  documentation-site/static/examples/textarea/resizable.js
Labels: documentation, feature

#1401 fix(accordion): update focus highlight
  src/accordion/styled-components.js
  src/table/__tests__/table-cells.scenario.js
Labels: bugfix

#1425 Release v7.5.0
  package.json
Labels: release

#1426 docs(aspect-ratio-box): remove padding from calendar example
  documentation-site/static/examples/aspect-ratio-box/calendar.js
Labels: bugfix

#1420 feat(popover): accepting popperOptions
  src/popover/popover.js
  src/popover/types.js
Labels: feature

#1434 docs: add TypeScript info, don't wrap code snippets
  README.md
  documentation-site/components/markdown-elements.js
  documentation-site/pages/getting-started/installation.mdx
Labels: feature

#1439 fix(docs): update property on block flex example
  documentation-site/static/examples/block/flexbox.js
Labels: bugfix

#1428 feat(layer): add z-index support for the layer component
  documentation-site/pages/components/layer.mdx
  documentation-site/static/examples/layer/basic-tether.js
  documentation-site/static/examples/layer/basic.js
  documentation-site/static/examples/layer/layer-z-index.js
  src/layer/__tests__/layer-z-index-modal.scenario.js
  src/layer/__tests__/layer-z-index.scenario.js
  src/layer/layer.js
  src/layer/layers-manager.js
  src/layer/types.js
Labels: feature

#1440 Release v7.6.0
  package.json
Labels: release

#1442 fix(base-provider): add layers zIndex prop to BaseProvider
  src/helpers/base-provider.js
  src/helpers/types.js
Labels: bugfix

#1443 Release v7.6.1
  package.json
Labels: release

#1438 feat: expose StyleOverridesFunctionT + StyleOverridesObjectT
  src/helpers/overrides.js
Labels: feature

#1437 fix: random day highlight onMonthChange for DatePicker
  src/datepicker/calendar.js
Labels: bugfix

#1446 Release v7.7.0
  package.json
Labels: release

#1447 docs(roadmap): update
  documentation-site/pages/getting-started/roadmap.mdx
Labels: bugfix

#1422 feat: resolve #1129 by always rendering tab content
  documentation-site/pages/components/tabs.mdx
  documentation-site/static/examples/tabs/renderall.js
  src/tabs/__tests__/__snapshots__/stateful-tabs.test.js.snap
  src/tabs/__tests__/stateful-tabs.test.js
  src/tabs/tabs.js
  src/tabs/types.js
Labels: feature

#1403 fix(link): links inherit font size of the parent
  documentation-site/static/examples/link/basic.js
  src/card/styled-components.js
  src/link/__tests__/link.scenario.js
  src/link/styled-components.js
Labels: bugfix

#1421 feat: resolve #1282 exposing events in handlers and supporting onClick
  src/popover/stateful-container.js
  src/popover/types.js
Labels: feature

#1423 feat: resolve #1328 allowing custom keys in options
  package.json
  src/select/__tests__/select.test.js
  src/select/types.js
Labels: feature

#1432 feat(input): add clearable property
  .eslintrc.js
  documentation-site/pages/components/input.mdx
  documentation-site/static/examples/input/before-after.js
  documentation-site/static/examples/input/clearable.js
  src/input/__tests__/__snapshots__/input.test.js.snap
  src/input/__tests__/__snapshots__/stateful-container.test.js.snap
  src/input/__tests__/__snapshots__/stateful-input.test.js.snap
  src/input/__tests__/input-clearable.scenario.js
  src/input/__tests__/input.e2e.js
  src/input/base-input.js
  src/input/stateful-container.js
  src/input/styled-components.js
  src/input/types.js
  src/phone-input/stateful-phone-input-container.js
  src/select/select.js
  src/textarea/__tests__/__snapshots__/stateful-textarea.test.js.snap
  src/textarea/__tests__/__snapshots__/textarea.test.js.snap
  src/utils/create-event.js
Labels: feature

#1453 fix(icon): Filter styletron props to global icon overrides
  src/icon/README.md
  src/icon/__tests__/icon.test.js
  src/icon/alert.js
  src/icon/arrow-down.js
  src/icon/arrow-left.js
  src/icon/arrow-right.js
  src/icon/arrow-up.js
  src/icon/check-indeterminate.js
  src/icon/check.js
  src/icon/chevron-down.js
  src/icon/chevron-left.js
  src/icon/chevron-right.js
  src/icon/chevron-up.js
  src/icon/delete-alt.js
  src/icon/delete.js
  src/icon/filter.js
  src/icon/grab.js
  src/icon/icon-template.txt
  src/icon/menu.js
  src/icon/omit-dollar-prefixed-keys.js
  src/icon/overflow.js
  src/icon/plus.js
  src/icon/search.js
  src/icon/spinner.js
  src/icon/triangle-down.js
  src/icon/triangle-left.js
  src/icon/triangle-right.js
  src/icon/triangle-up.js
  src/icon/upload.js
Labels: bugfix

#1454 Release v7.8.0
  package.json
Labels: release

#1458 Release v8.0.0
  package.json
Labels: release

#1459 docs(versions): add v7
  documentation-site/components/header-navigation.js
Labels: feature

#1460 docs(v8): add a what is new button
  documentation-site/components/header-navigation.js
Labels: feature

#1455 docs: add blog post for phone input
  documentation-site/components/blog.js
  documentation-site/pages/blog/phone-input/ideal.png
  documentation-site/pages/blog/phone-input/index.mdx
  documentation-site/pages/blog/phone-input/keyboard.png
  documentation-site/pages/blog/phone-input/mapping.png
  documentation-site/pages/blog/phone-input/metadata.json
  documentation-site/pages/blog/phone-input/patterns.png
Labels: bugfix, documentation

#1465 fix(layout): on mobile, hide the whats new button
  documentation-site/components/header-navigation.js
Labels: bugfix

#1461 fix(docs): function name typo
  docs/migrations/01390.md
  documentation-site/pages/blog/base-web-v8/index.mdx
Labels: bugfix

#1467 feat(blog): add title and description
  documentation-site/components/blog.js
  documentation-site/components/posts.js
Labels: feature

#1463 feat(docs-site): center the content
  documentation-site/components/layout.js
Labels: feature

#1471 docs(github): add instruction for a codesandbox
  .github/ISSUE_TEMPLATE/1.bug.md
Labels: docs

#1474 fix(modal): allow interaction with select (& other portals)
  package.json
  src/modal/__tests__/__snapshots__/modal.test.js.snap
  src/modal/__tests__/modal-select.scenario.js
  src/modal/__tests__/modal.e2e.js
  src/modal/focus-once.js
  src/modal/modal.js
  src/table/filter.js
  yarn.lock
Labels: bugfix

#1475 Release v8.0.1
  package.json
Labels: release

#1476 fix: codesandbox modal examples
  package.json
  src/modal/__tests__/__snapshots__/modal.test.js.snap
  yarn.lock
Labels: bugfix

#1477 Release v8.0.2
  package.json
Labels: release

#1472 fix(layout): for the blog index, use the same layout as for the rest
  documentation-site/components/layout.js
  documentation-site/pages/blog/index.mdx
  documentation-site/pages/components/link.mdx
Labels: bugfix

#1473 feat(docs): add footer
  documentation-site/components/footer.js
  documentation-site/components/layout.js
  documentation-site/pages/_app.js
Labels: feature

#1478 fix(example): update the fusion example to use v8
  documentation-site/pages/getting-started/learn.mdx
Labels: bugfix

#1480 feat(babel): removes some experimental proposals
  .babelrc.js
  package.json
  yarn.lock
Labels: feature

#1482 fix(notification): support for longer messages
  src/notification/__tests__/notification.scenario.js
  src/toast/styled-components.js
  src/toast/toast.js
  src/toast/types.js
Labels: bugfix

#1484 Docs minor design fixes
  documentation-site/components/blog.js
  documentation-site/components/footer.js
  documentation-site/components/header-navigation.js
  documentation-site/components/layout.js
  documentation-site/components/posts.js
  documentation-site/components/sidebar.js
  documentation-site/pages/blog/getting-started-with-base-web/index.mdx
  documentation-site/pages/blog/getting-started-with-styletron/index.mdx
Labels: feature

#1481 feat(table): export SORT_DIRECTION const for SortableHeadCell
  documentation-site/static/examples/table/sortable.js
  src/table/__tests__/table-sortable.scenario.js
  src/table/constants.js
  src/table/index.js
  src/table/sortable-head-cell.js
  src/table/types.js
Labels: feature

#1479 [WIP] feat(blog): add more metadata to blog posts
  documentation-site/components/blog.js
  documentation-site/pages/blog/base-web-v7/metadata.json
  documentation-site/pages/blog/base-web-v8/metadata.json
  documentation-site/pages/blog/getting-started-with-base-web/metadata.json
  documentation-site/pages/blog/getting-started-with-styletron/metadata.json
  documentation-site/pages/blog/phone-input/metadata.json
Labels: bugfix

#1487 fix(phone-input): add disabled property to country select
  src/phone-input/country-select.js
  src/phone-input/types.js
Labels: bugfix
