Repository uber/baseweb, pull requests merged in 2019-09, with the labels that each got.

#1757 fix(vrt): adds back a flaky screener test
  src/layer/__tests__/layer-z-index-modal.scenario.js
Labels: bugfix

#1824 feat(tag): add title attribute when children is a string
  src/tag/__tests__/__snapshots__/tag.test.js.snap
  src/tag/__tests__/utils.test.js
  src/tag/tag.js
  src/tag/types.js
  src/tag/utils.js
Labels: feature

#1829 feat(storybook): add dark background for dark mode
  .storybook/load-stories.js
Labels: bugfix, documentation, enhancement

#1828 fix(vrt): reverts 'adds back a flaky screener test'
  src/layer/__tests__/layer-z-index-modal.scenario.js
Labels: bugfix

#1818 chore(responsive-helpers): remove 0px media queries from Block
  src/block/__tests__/__snapshots__/block.test.js.snap
  src/block/styled-components.js
  src/flex-grid/flex-grid-item.js
Labels: bugfix

#1837 fix(avatar): reset the error state when src is updated
  src/avatar/__tests__/avatar.test.js
  src/avatar/avatar.js
Labels: bugfix

#1835 feat(data-table): column measurement, table virtualization, cell formatting
  documentation-site/examples/data-table/basic.js
  documentation-site/examples/data-table/basic.tsx
  documentation-site/examples/table-grid/basic.js
  documentation-site/examples/table-grid/cell-span.js
  documentation-site/examples/table-grid/nested.js
  documentation-site/pages/components/unstable-data-table.mdx
  documentation-site/routes.js
  package.json
  src/data-table/__tests__/data-table.scenario.js
  src/data-table/column-boolean.js
  src/data-table/column-categorical.js
  src/data-table/column-custom.js
  src/data-table/column-numerical.js
  src/data-table/column-string.js
  src/data-table/constants.js
  src/data-table/data-table.js
  src/data-table/header-cell.js
  src/data-table/index.d.ts
  src/data-table/index.js
  src/data-table/measure-column-widths.js
  src/data-table/types.js
  yarn.lock
Labels: feature

#1841 feat(yard): defer loading
  documentation-site/components/yard/config/button.ts
  documentation-site/components/yard/config/input.ts
  documentation-site/components/yard/const.ts
  documentation-site/components/yard/index.tsx
  documentation-site/components/yard/types.ts
  documentation-site/components/yard/yard.tsx
  documentation-site/next.config.js
  documentation-site/pages/_app.js
  documentation-site/pages/components/button.mdx
  documentation-site/pages/components/input.mdx
  package.json
  yarn.lock
Labels: feature

#1844 fix(docs): using StrictMode for docs site
  documentation-site/pages/_app.js
Labels: feature

#1843 docs(exports): update exports component styles
  documentation-site/components/exports.js
  documentation-site/components/markdown-elements.js
Labels: bugfix, documentation, enhancement

#1846 fix(yard): fix theme switching (reset when changed)
  documentation-site/components/yard/code-generator.ts
  documentation-site/components/yard/yard.tsx
  src/index.js
Labels: bugfix

#1847 fix(docs): revert: using StrictMode for docs site
  documentation-site/pages/_app.js
Labels: bugfix

#1848 fix(yard): broken override tab
  documentation-site/components/yard/code-generator.ts
  documentation-site/components/yard/index.tsx
  documentation-site/components/yard/override.tsx
  documentation-site/components/yard/yard.tsx
Labels: bugfix

#1825 fix(drawer): some cleanup for the drawer and modal
  documentation-site/examples/drawer/anchors.js
  documentation-site/examples/drawer/anchors.tsx
  documentation-site/examples/drawer/sizes.js
  documentation-site/examples/drawer/sizes.tsx
  src/drawer/__tests__/drawer-rtl.scenario.js
  src/drawer/__tests__/drawer.e2e.js
  src/drawer/__tests__/drawer.scenario.js
  src/drawer/drawer.js
  src/drawer/index.d.ts
  src/drawer/index.js
  src/drawer/styled-components.js
  src/drawer/types.js
  src/modal/modal.js
  src/modal/types.js
Labels: bugfix

#1849 Release v8.17.2
  package.json
Labels: release

#1857 chore(deps): update transient deps
  yarn.lock
Labels: greenkeeping

#1839 fix: show months only in range on calendar header dropdown
  src/datepicker/__tests__/stateful-datepicker-min-max-date.scenario.js
  src/datepicker/__tests__/stateful-datepicker.e2e.js
  src/datepicker/calendar-header.js
Labels: bugfix

#1814 feat(datepicker): dates can be typed in using the keyboard
  src/datepicker/__tests__/datepicker.e2e.js
  src/datepicker/calendar.js
  src/datepicker/datepicker.js
  src/datepicker/types.js
Labels: feature

#1863 docs(layer): fix typo
  documentation-site/pages/components/layer.mdx
Labels: bugfix

#1864 Release v8.18.0
  package.json
Labels: release

#1867 Release v9.0.0
  package.json
Labels: release

#1868 fix(version-selector): group major versions properly
  documentation-site/components/version-selector.js
  scripts/version-generator.js
Labels: bugfix

#1870 fix(docs): use styledlink in docs
  documentation-site/components/markdown-elements.js
Labels: bugfix

#1871 fix(buttons): update loading spinner colors
  src/button/__tests__/button.scenario.js
  src/button/styled-components.js
  src/styles/types.js
  src/theme.ts
  src/themes/creator.js
  src/themes/dark-theme-colors.js
Labels: bugfix, enhancement

#1873 fix(accordion): use longhand prop for bg
  src/accordion/__tests__/__snapshots__/accordion.test.js.snap
  src/accordion/__tests__/__snapshots__/panel.test.js.snap
  src/accordion/styled-components.js
Labels: bugfix

#1872 Release v9.0.1
  package.json
Labels: release

#1875 fix(version-selector): add max-height
  documentation-site/components/version-selector.js
Labels: bugfix

#1876 fix(e2e): moves flakey test to end of suite
  src/datepicker/__tests__/datepicker.e2e.js
Labels: bugfix

#1877 chore(build): build docs site image too
  .buildkite/pipeline.yml
Labels: build/tooling, greenkeeping

#1860 fix(breadcrumbs): arrow icons rtl
  src/breadcrumbs/__tests__/__snapshots__/breadcrumbs.test.js.snap
  src/breadcrumbs/__tests__/breadcrumbs-rtl.scenario.js
  src/breadcrumbs/breadcrumbs.js
Labels: bugfix

#1861 feat(button): pill shape
  documentation-site/examples/button/shapes.js
  documentation-site/examples/button/shapes.tsx
  src/button/__tests__/button-shapes.scenario.js
  src/button/constants.js
  src/button/index.d.ts
  src/button/styled-components.js
Labels: feature

#1879 fix(datepicker): formatString and placeholder
  src/datepicker/__tests__/datepicker-int.scenario.js
  src/datepicker/datepicker.js
Labels: bugfix

#1865 docs(yard): adds button-group yard
  documentation-site/components/yard/ast.ts
  documentation-site/components/yard/code-generator.ts
  documentation-site/components/yard/config/button-group.ts
  documentation-site/pages/components/button-group.mdx
Labels: feature

#1881 fix(datepicker): update input value when props change
  e2e/tests.js
  src/datepicker/__tests__/datepicker.e2e.js
  src/datepicker/__tests__/datepicker.scenario.js
  src/datepicker/datepicker.js
Labels: bugfix

#1883 Release v9.1.0
  package.json
Labels: release

#1884 chore(actions): add a welcome message
  .github/workflows/greetings.yml
Labels: feature

#1896 fix(button): update colors for secondary button
  src/themes/creator.js
Labels: bugfix

#1897 chore(package): use the official extract-react-types package
  documentation-site/pages/components/accordion.mdx
  documentation-site/pages/components/aspect-ratio-box.mdx
  documentation-site/pages/components/avatar.mdx
  documentation-site/pages/components/base-provider.mdx
  documentation-site/pages/components/block.mdx
  documentation-site/pages/components/breadcrumbs.mdx
  documentation-site/pages/components/button-group.mdx
  documentation-site/pages/components/card.mdx
  documentation-site/pages/components/checkbox.mdx
  documentation-site/pages/components/datepicker.mdx
  documentation-site/pages/components/dnd-list.mdx
  documentation-site/pages/components/drawer.mdx
  documentation-site/pages/components/file-uploader.mdx
  documentation-site/pages/components/flex-grid.mdx
  documentation-site/pages/components/form-control.mdx
  documentation-site/pages/components/header-navigation.mdx
  documentation-site/pages/components/heading.mdx
  documentation-site/pages/components/icon.mdx
  documentation-site/pages/components/layer.mdx
  documentation-site/pages/components/menu.mdx
  documentation-site/pages/components/modal.mdx
  documentation-site/pages/components/notification.mdx
  documentation-site/pages/components/pagination.mdx
  documentation-site/pages/components/payment-card.mdx
  documentation-site/pages/components/phone-input.mdx
  documentation-site/pages/components/pin-code.mdx
  documentation-site/pages/components/popover.mdx
  documentation-site/pages/components/progress-bar.mdx
  documentation-site/pages/components/progress-steps.mdx
  documentation-site/pages/components/radio.mdx
  documentation-site/pages/components/rating.mdx
  documentation-site/pages/components/select.mdx
  documentation-site/pages/components/side-nav.mdx
  documentation-site/pages/components/slider.mdx
  documentation-site/pages/components/spinner.mdx
  documentation-site/pages/components/table.mdx
  documentation-site/pages/components/tabs.mdx
  documentation-site/pages/components/tag.mdx
  documentation-site/pages/components/textarea.mdx
  documentation-site/pages/components/toast.mdx
  documentation-site/pages/components/tooltip.mdx
  documentation-site/pages/components/typography.mdx
  flow-typed/npm/@uber-web-ui/extract-react-types-loader_vx.x.x.js
  package.json
  yarn.lock
Labels: greenkeeping

#1898 fix(e2e-tests): improve datepicker e2e test reliability
  jest.config.js
  jest.e2e.config.js
  package.json
  src/datepicker/__tests__/calendar.e2e.js
  src/datepicker/__tests__/datepicker-int.e2e.js
  src/datepicker/__tests__/datepicker-range.e2e.js
  src/datepicker/__tests__/datepicker-unreliable.e2e.js
  src/datepicker/__tests__/datepicker.e2e.js
  src/datepicker/__tests__/stateful-datepicker.e2e.js
  yarn.lock
Labels: bugfix

#1900 fix(timezone-picker): list all IANA timezone options + prioritize controlled value
  src/datepicker/__tests__/timezone-picker.e2e.js
  src/datepicker/timezone-picker.js
Labels: bugfix

#1880 fix(data-table): improve initial load performance
  src/data-table/column-boolean.js
  src/data-table/column-categorical.js
  src/data-table/column-custom.js
  src/data-table/column-numerical.js
  src/data-table/column-string.js
  src/data-table/data-table.js
  src/data-table/measure-column-widths.js
Labels: bugfix

#1842 feat(datepicker): update its look to the latest design with circles
  documentation-site/examples/datepicker/with-overrides.js
  src/datepicker/__tests__/calendar-multi-month.scenario.js
  src/datepicker/__tests__/stateful-calendar-overrides.scenario.js
  src/datepicker/calendar-header.js
  src/datepicker/day.js
  src/datepicker/styled-components.js
  src/datepicker/types.js
  src/datepicker/utils/day-state.js
  src/themes/creator.js
Labels: feature

#1903 feat(gallery): change url to just /components
  documentation-site/components/header-navigation.js
  documentation-site/pages/components/index.mdx
  documentation-site/pages/index.js
  documentation-site/routes.js
  netlify.toml
Labels: bugfix, documentation

#1905 fix(masked-input): use the Input as the override
  src/input/__tests__/__snapshots__/masked-input.test.js.snap
  src/input/masked-input.js
Labels: bugfix

#1904 Release v9.3.0
  package.json
Labels: release

#1906 test(datepicker): multi-month screener test
  src/datepicker/__tests__/calendar-multi-month.scenario.js
Labels: bugfix

#1834 fix(typescript): custom theme type support
  documentation-site/examples/styled/basic.tsx
  documentation-site/examples/table/cells.tsx
  src/index.d.ts
Labels: bugfix

#1909 fix(package): remove puppeteer from the bundle
  .buildkite/pipeline.yml
  Dockerfile
Labels: bugfix

#1914 Release v9.3.1
  package.json
Labels: release

#1922 fix(screener): update
  .buildkite/pipeline.yml
  package.json
  scripts/run-screener.sh
  yarn.lock
Labels: bugfix

#1913 fix(masked-input): revert to 06b8afd0e6e737a12ec6f56dc37f3b88d8f293cb
  src/input/__tests__/__snapshots__/masked-input.test.js.snap
  src/input/masked-input.js
Labels: bugfix

#1920 fix(datepicker): onChange does not change type of callback value
  src/datepicker/__tests__/datepicker.test.js
  src/datepicker/datepicker.js
Labels: bugfix

#1902 feat(docs): payment form
  documentation-site/examples/payment-card/form.js
  documentation-site/examples/payment-card/form.tsx
  documentation-site/pages/components/payment-card.mdx
  package.json
  src/payment-card/index.d.ts
  yarn.lock
Labels: feature

#1911 fix(documentation): changed css to useCss
  docs/migrations/01390.md
  documentation-site/components/gallery.js
  documentation-site/components/yard/code-box.tsx
  documentation-site/components/yard/knob.tsx
  documentation-site/components/yard/knobs.tsx
  documentation-site/components/yard/theme-editor.tsx
  documentation-site/components/yard/yard.tsx
  documentation-site/examples/table-grid/nested.js
  documentation-site/pages/blog/base-web-v8/index.mdx
  src/styles/__tests__/styled.test.js
  src/styles/styled.js
  src/table-grid/__tests__/table-grid-jobs.scenario.js
  src/table-grid/__tests__/table-grid-records.scenario.js
  src/table-grid/__tests__/table-grid.scenario.js
Labels: bugfix

#1923 Release v9.3.2
  package.json
Labels: release

#1924 fix(types): fix types of event handlers #1915
  src/button-group/index.d.ts
  src/checkbox/index.d.ts
  src/drawer/index.d.ts
  src/file-uploader/index.d.ts
  src/input/index.d.ts
  src/menu/index.d.ts
  src/radio/index.d.ts
  src/select/index.d.ts
  src/side-navigation/index.d.ts
Labels: bugfix

#1894 feat(data-table): Improve categorical filter ui
  documentation-site/examples/data-table/basic.js
  src/data-table/__tests__/column-categorical.test.js
  src/data-table/__tests__/data-table-categorical-column.scenario.js
  src/data-table/__tests__/data-table-columns.e2e.js
  src/data-table/column-categorical.js
  src/styles/__mocks__/styled.js
Labels: feature

#1901 feat(data-table): boolean filter ui
  src/data-table/__tests__/data-table-columns.e2e.js
  src/data-table/column-boolean.js
  src/data-table/column-categorical.js
Labels: feature

#1918 feat(data-table): numerical filter
  src/data-table/__tests__/column-categorical.test.js
  src/data-table/__tests__/column-numerical.test.js
  src/data-table/__tests__/data-table-columns.e2e.js
  src/data-table/__tests__/data-table-numerical-column.scenario.js
  src/data-table/__tests__/shared.js
  src/data-table/column-categorical.js
  src/data-table/column-numerical.js
  src/data-table/constants.js
  src/data-table/filter-shell.js
  src/data-table/header-cell.js
Labels: feature

#1931 Release v9.4.0
  package.json
Labels: release

#1930 fix(tag): improve tag kind type
  src/tag/__tests__/tag.test.js
  src/tag/constants.js
Labels: bugfix

#1932 fix(data-table): remove scroll jump and ensure no remounts
  src/data-table/data-table.js
  src/data-table/header-cell.js
  src/data-table/measure-column-widths.js
  src/data-table/types.js
Labels: feature

#1934 fix(input): background is mono200
  src/themes/creator.js
Labels: bugfix

#1933 Release v9.4.1
  package.json
Labels: release

#1929 fix(datepicker): timeselect labels (start/end)
  src/datepicker/calendar.js
  src/datepicker/locale.js
Labels: bugfix

#1862 feat(yard): new compiler, state editing, new code generation AST based module
  documentation-site/components/yard/ast.ts
  documentation-site/components/yard/code-generator.ts
  documentation-site/components/yard/compiler.tsx
  documentation-site/components/yard/config/input.ts
  documentation-site/components/yard/const.ts
  documentation-site/components/yard/editor.tsx
  documentation-site/components/yard/error.tsx
  documentation-site/components/yard/index.tsx
  documentation-site/components/yard/override.tsx
  documentation-site/components/yard/types.ts
  documentation-site/components/yard/yard.tsx
  documentation-site/next.config.js
  documentation-site/pages/components/button-group.mdx
  documentation-site/pages/components/button.mdx
  documentation-site/pages/components/input.mdx
  package.json
  yarn.lock
Labels: feature

#1935 Release v9.4.2
  package.json
Labels: release

#1937 Fix Button onClick typing
  src/button/index.d.ts
Labels: bugfix

#1938 feat(yard): add transforms and code generation tests, fix some bugs
  documentation-site/components/yard/__tests__/ast.test.ts
  documentation-site/components/yard/__tests__/code-generator.test.ts
  documentation-site/components/yard/ast.ts
  documentation-site/components/yard/code-generator.ts
  documentation-site/components/yard/config/button-group.ts
  documentation-site/components/yard/editor.tsx
  documentation-site/components/yard/overrides.tsx
  documentation-site/components/yard/yard.tsx
  jest.config.js
  package.json
  src/theme.ts
  yarn.lock
Labels: feature

#1940 docs(examples): replace generics for js
  documentation-site/components/example.js
Labels: bugfix

#1941 docs(input): fix alignment in focus example
  documentation-site/examples/input/focus.js
  documentation-site/examples/input/focus.tsx
Labels: bugfix, documentation

#1942 docs(gallery): update borders for more contrast
  documentation-site/components/gallery.js
Labels: bugfix, documentation

#1945 fix(masked-input): fix focus styling
  src/input/__tests__/__snapshots__/masked-input.test.js.snap
  src/input/__tests__/input-mask.scenario.js
  src/input/masked-input.js
Labels: bugfix

#1928 feat(list): adds list item component
  documentation-site/examples/list/artwork-sizes.js
  documentation-site/examples/list/artwork-sizes.tsx
  documentation-site/examples/list/basic.js
  documentation-site/examples/list/basic.tsx
  documentation-site/examples/list/enhancers.js
  documentation-site/examples/list/enhancers.tsx
  documentation-site/examples/list/menu-adapter.js
  documentation-site/examples/list/menu-adapter.tsx
  documentation-site/examples/list/sublist.js
  documentation-site/examples/list/sublist.tsx
  documentation-site/pages/components/list.mdx
  documentation-site/routes.js
  src/list/__tests__/list-item.scenario.js
  src/list/__tests__/menu-adapter.scenario.js
  src/list/constants.js
  src/list/index.d.ts
  src/list/index.js
  src/list/list-item-label.js
  src/list/list-item.js
  src/list/menu-adapter.js
  src/list/styled-components.js
  src/list/types.js
  src/menu/option-list.js
Labels: feature

#1943 docs(users): add extensis
  documentation-site/pages/index.js
  documentation-site/static/images/extensis-logo.png
Labels: docs

#1949 Release v9.5.0
  package.json
Labels: release

#1936 chore(data-table): introduces react-testing-library
  package.json
  src/data-table/__tests__/column-boolean.test.js
  src/data-table/__tests__/column-categorical.test.js
  src/data-table/__tests__/column-custom.test.js
  src/data-table/__tests__/column-numerical.test.js
  src/data-table/__tests__/column-string.test.js
  src/data-table/__tests__/shared.js
  src/toast/__tests__/toast.test.js
  yarn.lock
Labels: bugfix

#1953 fix(project): use ^ for date-fns
  package.json
  yarn.lock
Labels: bugfix

#1944 feat(yard): Better error messages/catching, lost focus bug
  documentation-site/components/yard/compiler.tsx
  documentation-site/components/yard/const.ts
  documentation-site/components/yard/index.tsx
  documentation-site/components/yard/knob.tsx
  documentation-site/components/yard/knobs.tsx
  documentation-site/components/yard/override.tsx
  documentation-site/components/yard/popup-error.tsx
  documentation-site/components/yard/types.ts
  documentation-site/components/yard/yard.tsx
Labels: bugfix, feature

#1952 fix(docs): removes props override function
  documentation-site/pages/guides/understanding-overrides.mdx
Labels: bugfix

#1955 docs(typography): add exports and fix heading example
  documentation-site/pages/components/typography.mdx
Labels: docs

#1957 fix(breadcrumbs): add missing List override property
  src/breadcrumbs/index.d.ts
Labels: bugfix

#1958 fix(data-table): ensure width dim exists before setting
  src/data-table/measure-column-widths.js
Labels: bugfix

#1962 Release v9.5.1
  package.json
Labels: release

#1963 fix(dark-theme): export dark theme overrides for the dark theme creation
  src/index.js
  src/themes/index.js
Labels: bugfix

#1965 Release v9.5.2
  package.json
Labels: release

#1961 feat(yard): add the Tabs component (nested components support)
  documentation-site/components/yard/__tests__/ast.test.ts
  documentation-site/components/yard/__tests__/code-generator.test.ts
  documentation-site/components/yard/__tests__/utils.test.ts
  documentation-site/components/yard/ast.ts
  documentation-site/components/yard/code-generator.ts
  documentation-site/components/yard/config/button-group.ts
  documentation-site/components/yard/config/tabs.ts
  documentation-site/components/yard/editor.tsx
  documentation-site/components/yard/index.tsx
  documentation-site/components/yard/knob.tsx
  documentation-site/components/yard/popup-error.tsx
  documentation-site/components/yard/types.ts
  documentation-site/components/yard/utils.ts
  documentation-site/components/yard/yard.tsx
  documentation-site/pages/components/tabs.mdx
Labels: feature

#1968 feat(menu): removes smoothscroll-polyfill
  component-sizes.json
  flow-typed/npm/smoothscroll-polyfill_v0.x.x.js
  package.json
  src/menu/utils.js
  yarn.lock
Labels: bugfix

#1959 feat(data-table): batch actions
  documentation-site/examples/data-table/basic.js
  documentation-site/examples/data-table/basic.tsx
  documentation-site/examples/data-table/batch-action.js
  documentation-site/examples/data-table/batch-action.tsx
  documentation-site/pages/components/unstable-data-table.mdx
  src/data-table/__tests__/data-table-batch-action.e2e.js
  src/data-table/__tests__/data-table-batch-action.scenario.js
  src/data-table/__tests__/data-table-columns.scenario.js
  src/data-table/__tests__/data-table.scenario.js
  src/data-table/cell-shell.js
  src/data-table/column-boolean.js
  src/data-table/column-categorical.js
  src/data-table/column-custom.js
  src/data-table/column-numerical.js
  src/data-table/column-string.js
  src/data-table/data-table.js
  src/data-table/header-cell.js
  src/data-table/index.d.ts
  src/data-table/measure-column-widths.js
  src/data-table/types.js
Labels: feature

#1973 fix(datepicker): add missing day states for highlight (#1972)
  src/datepicker/styled-components.js
Labels: bugfix
