Repository uber/baseweb, pull requests merged in 2019-07, with the labels that each got.

#1488 feat(deploys): add now
  now.json
  package.json
Labels: feature

#1492 fix(docs): update example for the resizable textarea with restrictions
  documentation-site/static/examples/textarea/resizable.js
Labels: bugfix

#1495 docs(blog): update commentary about phone input filtering
  documentation-site/pages/blog/phone-input/index.mdx
Labels: bugfix, documentation

#1496 chore(types): consistently export type components
  src/typography/index.js
Labels: greenkeeping

#1493 feat(now): deploy every commit
  .buildkite/pipeline.yml
  Dockerfile
  now.sh
  package.json
  yarn.lock
Labels: feature

#1497 Release v8.1.0
  package.json
Labels: release

#1449 feat(side-navigation): improve item rendering performance
  .storybook/load-stories.js
  documentation-site/pages/components/side-nav.mdx
  src/side-navigation/__tests__/__snapshots__/nav.test.js.snap
  src/side-navigation/__tests__/nav-long.scenario.js
  src/side-navigation/__tests__/nav.test.js
  src/side-navigation/nav-item.js
  src/side-navigation/nav.js
  src/side-navigation/types.js
Labels: feature

#1489 feat(table-grid): creates table components using css-grid
  .storybook/load-stories.js
  documentation-site/components/unstable-warning.js
  documentation-site/pages/components/table-grid.mdx
  documentation-site/pages/components/table.mdx
  documentation-site/routes.js
  documentation-site/static/examples/table-grid/basic.js
  documentation-site/static/examples/table-grid/cell-span.js
  documentation-site/static/examples/table-grid/nested.js
  src/button/styled-components.js
  src/styles/types.js
  src/table-grid/__tests__/table-grid-jobs.scenario.js
  src/table-grid/__tests__/table-grid-records.scenario.js
  src/table-grid/__tests__/table-grid.scenario.js
  src/table-grid/index.js
  src/table-grid/styled-components.js
  src/table/styled-components.js
  src/themes/creator.js
  src/themes/dark-theme-colors.js
Labels: feature

#1498 docs: center docs
  documentation-site/components/layout.js
Labels: bugfix

#1490 feat(phone-input): flow & prop enhancements
  src/phone-input/country-select-dropdown.js
  src/phone-input/country-select.js
  src/phone-input/default-props.js
  src/phone-input/phone-input.js
  src/phone-input/stateful-phone-input-container.js
  src/phone-input/stateful-phone-input.js
  src/phone-input/styled-components.js
  src/phone-input/types.js
Labels: enhancement, feature, refactor

#1499 fix(button-group): handles one button in group
  src/button-group/button-group.js
Labels: bugfix

#1502 Release v8.2.0
  package.json
Labels: release

#1503 fix(docs-site): update example to include base provider
  documentation-site/components/example.js
Labels: bugfix

#1501 feat(versions): show minor and patch versions
  .gitignore
  documentation-site/components/header-navigation.js
  documentation-site/components/version-selector.js
  package.json
  scripts/version-generator.js
  yarn.lock
Labels: feature

#1504 fix(codemod): update codemod to handle styled calls with existing generics
  src/codemods/__testfixtures__/styled-flowfixme-existing-generics.input.js
  src/codemods/__testfixtures__/styled-flowfixme-existing-generics.output.js
  src/codemods/__tests__/styled-flowfixme-test.js
  src/codemods/styled-flowfixme.js
Labels: bugfix

#1505 docs(grid-table): replace link to table-grid with link to table
  documentation-site/pages/components/table-grid.mdx
Labels: bugfix

#1508 feat(dnd-list): make items removable when out of bounds, add targetRect
  documentation-site/static/examples/dnd-list/removable.js
  package.json
  src/dnd-list/__tests__/stateful-list-container.test.js
  src/dnd-list/list.js
  src/dnd-list/stateful-list-container.js
  src/dnd-list/types.js
  yarn.lock
Labels: feature

#1509 Release v8.3.0
  package.json
Labels: release

#1511 fix(version-selector): minor improvements
  documentation-site/components/version-selector.js
Labels: bugfix

#1512 feat(seo): add keywords and description for components
  documentation-site/components/meta-favicons.js
  documentation-site/components/meta-seo.js
  documentation-site/pages/_document.js
  documentation-site/pages/components/accordion.mdx
  documentation-site/pages/index.js
Labels: feature

#1510 fix(select): always highlight the first item initially
  src/select/__tests__/select.e2e.js
  src/select/dropdown.js
Labels: bugfix

#1520 chore: Next.js v9
  documentation-site/components/header-navigation.js
  documentation-site/components/markdown-elements.js
  documentation-site/components/sidebar.js
  documentation-site/next.config.js
  package.json
  yarn.lock
Labels: feature

#1513 feat(versions): alias tags
  documentation-site/components/version-selector.js
  now.sh
Labels: feature

#1521 feat(themes): export dark theme primitives
  src/themes/index.js
Labels: feature

#1523 fix(now): fix deploy script
  now.sh
Labels: bugfix

#1448 feat(screener): add tests for the iphone
  .storybook/preview-head.html
  documentation-site/components/layout-landing.js
  documentation-site/pages/test.js
  screener.config.js
Labels: feature

#1524 fix(popover): propagate popperOptions through stateful-container
  src/popover/__tests__/__snapshots__/stateful-container.test.js.snap
  src/popover/__tests__/__snapshots__/stateful-popover.test.js.snap
  src/popover/__tests__/stateful-container.test.js
  src/popover/stateful-container.js
  src/tooltip/__tests__/__snapshots__/stateful-tooltip.test.js.snap
  src/tooltip/__tests__/stateful-tooltip-container.test.js
  src/tooltip/__tests__/stateful-tooltip.test.js
Labels: bugfix

#1527 Release v8.3.2
  package.json
Labels: release

#1528 fix(now): use cname from BUILDKITE_TAG
  now.sh
Labels: bugfix

#1500 feat(datepicker): positive, error and disabled states
  documentation-site/pages/components/datepicker.mdx
  documentation-site/static/examples/datepicker/datepickers-color-states.js
  src/datepicker/__tests__/datepickers-color-states.scenario.js
  src/datepicker/datepicker.js
  src/datepicker/timepicker.js
  src/datepicker/timezone-picker.js
  src/datepicker/types.js
Labels: feature

#1530 fix(screener): remove flaky modal test
  src/layer/__tests__/layer-z-index-modal.scenario.js
Labels: bugfix

#1519 feat(codemods): refactors codemods to dubstep and separate package
  .flowconfig
  packages/baseui-codemods/.flowconfig
  packages/baseui-codemods/.gitignore
  packages/baseui-codemods/.npmignore
  packages/baseui-codemods/babel.config.js
  packages/baseui-codemods/fixtures/.gitkeep
  packages/baseui-codemods/flow-typed/npm/jest_v24.x.x.js
  packages/baseui-codemods/jest.config.js
  packages/baseui-codemods/package.json
  packages/baseui-codemods/src/cli.js
  packages/baseui-codemods/src/index.js
  packages/baseui-codemods/src/shared.js
  packages/baseui-codemods/src/styled-flowfixme.js
  packages/baseui-codemods/src/styled-flowfixme.test.js
  packages/baseui-codemods/src/styled-v7-type-arguments.js
  packages/baseui-codemods/src/styled-v7-type-arguments.test.js
  packages/baseui-codemods/src/styled-v8-themedStyled.js
  packages/baseui-codemods/src/styled-v8-themedStyled.test.js
  packages/baseui-codemods/src/test-utilities.js
  packages/baseui-codemods/yarn.lock
Labels: feature

#1531 fix(phone-input): fix country-select overrides and nested overrides
  src/phone-input/__tests__/phone-input-overrides.scenario.js
  src/phone-input/country-select.js
  src/phone-input/phone-input.js
Labels: bugfix

#1529 docs(datepicker): add more verbose examples
  documentation-site/static/examples/datepicker/datepickers-color-states.js
Labels: feature

#1532 Release v8.4.0
  package.json
Labels: release

#1451 test: regression tests for datepicker highlight
  src/datepicker/__tests__/datepicker-range-highlight.scenario.js
  src/datepicker/__tests__/datepicker-range.scenario.js
  src/datepicker/__tests__/datepicker.e2e.js
Labels: bugfix

#1533 fix(now): use BUILDKITE_MESSAGE instead of TAG
  now.sh
Labels: bugfix

#1536 fix(types): fix styled() type so it can take a single string arg
  src/styles/__tests__/styled.test.js
  src/styles/styled.js
Labels: bugfix

#1541 docs(styled): use proper headings for useStyletron
  documentation-site/pages/components/styled.mdx
Labels: bugfix

#1540 docs(datepicker): add timezone integration
  documentation-site/pages/components/datepicker.mdx
  documentation-site/static/examples/datepicker/datepicker-with-timezone.js
Labels: feature

#1543 Release v8.4.1
  package.json
Labels: release

#1538 Move Typescript definitions into our repo
  .nvmrc
  package.json
  scripts/ts-copy.js
  src/accordion/index.d.ts
  src/avatar/index.d.ts
  src/block/index.d.ts
  src/breadcrumbs/index.d.ts
  src/button-group/index.d.ts
  src/button/index.d.ts
  src/card/index.d.ts
  src/checkbox/index.d.ts
  src/datepicker/index.d.ts
  src/dnd-list/index.d.ts
  src/file-uploader/index.d.ts
  src/flex-grid/index.d.ts
  src/form-control/index.d.ts
  src/header-navigation/index.d.ts
  src/heading/index.d.ts
  src/icon/index.d.ts
  src/index.d.ts
  src/input/index.d.ts
  src/layer/index.d.ts
  src/link/index.d.ts
  src/locale.d.ts
  src/menu/index.d.ts
  src/modal/index.d.ts
  src/notification/index.d.ts
  src/overrides.ts
  src/pagination/index.d.ts
  src/payment-card/index.d.ts
  src/phone-input/index.d.ts
  src/popover/index.d.ts
  src/progress-bar/index.d.ts
  src/progress-steps/index.d.ts
  src/radio/index.d.ts
  src/rating/index.d.ts
  src/select/index.d.ts
  src/side-navigation/index.d.ts
  src/slider/index.d.ts
  src/spinner/index.d.ts
  src/table/index.d.ts
  src/tabs/index.d.ts
  src/tag/index.d.ts
  src/textarea/index.d.ts
  src/theme.d.ts
  src/toast/index.d.ts
  src/tooltip/index.d.ts
  src/typography/index.d.ts
  tsconfig.json
  yarn.lock
Labels: feature

#1545 Release v8.5.0
  package.json
Labels: release

#1557 fix(ts): fix overrides, theme and locale exports
  scripts/ts-copy.js
  src/datepicker/index.d.ts
  src/index.d.ts
  src/locale.ts
  src/overrides.ts
  src/pagination/index.d.ts
  src/rating/index.d.ts
  src/select/index.d.ts
  src/theme.ts
Labels: bugfix

#1558 Release v8.5.1
  package.json
Labels: release

#1565 fix(build): use NODE_ENV for everything
  Dockerfile
  documentation-site/components/markdown-elements.js
  documentation-site/env-config.js
  netlify.toml
Labels: bugfix

#1554 feat: resolve #473 with aria-controls support for accordion
  src/accordion/__tests__/__snapshots__/panel.test.js.snap
  src/accordion/__tests__/panel.test.js
  src/accordion/panel.js
  src/accordion/types.js
Labels: feature

#1566 fix(docs): removes outdated sentence from side nav page
  documentation-site/pages/components/side-nav.mdx
Labels: bugfix

#1567 feat(select): add startOpen property
  documentation-site/pages/components/select.mdx
  documentation-site/static/examples/select/open.js
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/__tests__/select-open.scenario.js
  src/select/default-props.js
  src/select/select.js
  src/select/types.js
Labels: feature

#1570 Release v8.6.0
  package.json
Labels: release

#1568 fix(side-nav): removes memo fn from being passed to styled nav-item
  src/side-navigation/nav-item.js
Labels: bugfix

#1569 fix(docs): add path to select open example
  documentation-site/pages/components/select.mdx
Labels: bugfix, documentation

#1572 fix(phone-input): correct flow type for inputRef
  src/phone-input/country-select.js
Labels: bugfix

#1573 fix(table): forward refs to wrapped table style components
  src/styles/styled.js
  src/table/styled-components.js
Labels: bugfix

#1574 Release v8.6.1
  package.json
Labels: release

#1584 chore(screener): update version to 0.18.6
  package.json
  yarn.lock
Labels: greenkeeping

#1580 docs(phone-input): add example for nested overrides
  documentation-site/pages/components/phone-input.mdx
  documentation-site/static/examples/phone-input/nested-overrides.js
Labels: feature

#1564 fix: dont allow InputContainer to break flex flow
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/multi-value.js
  src/select/select.js
  src/select/styled-components.js
Labels: bugfix

#1560 feat(overrides): prop overrides accept a function too
  src/helpers/__tests__/__snapshots__/overrides.test.js.snap
  src/helpers/__tests__/overrides.test.js
  src/helpers/overrides.js
Labels: feature

#1588 Release v8.7.0
  package.json
Labels: release

#1539 fix(codemods): do not apply props type to styled if obj style arg
  packages/baseui-codemods/package.json
  packages/baseui-codemods/src/styled-v7-type-arguments.js
  packages/baseui-codemods/src/styled-v7-type-arguments.test.js
Labels: bugfix

#1586 fix(avatar): make styled component prop types less restrictive
  src/avatar/__tests__/styled-component.test.js
  src/avatar/styled-components.js
  src/avatar/types.js
Labels: bugfix

#1585 feat: new pin-code component
  documentation-site/examples/pin-code/autofocus.js
  documentation-site/examples/pin-code/basic.js
  documentation-site/examples/pin-code/completion.js
  documentation-site/examples/pin-code/event.js
  documentation-site/examples/pin-code/id-and-name.js
  documentation-site/examples/pin-code/length.js
  documentation-site/examples/pin-code/no-tab.js
  documentation-site/examples/pin-code/override.js
  documentation-site/examples/pin-code/placeholder.js
  documentation-site/examples/pin-code/size.js
  documentation-site/examples/pin-code/states.js
  documentation-site/pages/components/pin-code.mdx
  documentation-site/routes.js
  e2e/helpers/index.js
  package.json
  src/input/__tests__/__snapshots__/base-input.test.js.snap
  src/input/__tests__/__snapshots__/input.test.js.snap
  src/input/__tests__/__snapshots__/masked-input.test.js.snap
  src/input/base-input.js
  src/input/types.js
  src/pin-code/__tests__/pin-code-overrides.scenario.js
  src/pin-code/__tests__/pin-code-sizes.scenario.js
  src/pin-code/__tests__/pin-code-states.scenario.js
  src/pin-code/__tests__/pin-code.e2e.js
  src/pin-code/__tests__/pin-code.scenario.js
  src/pin-code/default-props.js
  src/pin-code/index.js
  src/pin-code/pin-code.js
  src/pin-code/stateful-pin-code-container.js
  src/pin-code/stateful-pin-code.js
  src/pin-code/styled-components.js
  src/pin-code/types.js
  src/textarea/__tests__/__snapshots__/textarea.test.js.snap
  yarn.lock
Labels: feature

#1593 Release v8.8.0
  package.json
Labels: release

#1594 fix(docs): remove comment
  documentation-site/examples/pin-code/event.js
Labels: bugfix

#1596 fix(examples): broken example links
  documentation-site/pages/components/select.mdx
  documentation-site/pages/getting-started/internationalization.mdx
  documentation-site/pages/getting-started/usage.mdx
  documentation-site/pages/theming/overriding-icons.mdx
  documentation-site/pages/theming/understanding-overrides.mdx
Labels: bugfix

#1597 feat(ci): run screener only on src change
  package.json
  scripts/run-screener.sh
Labels: ci, feature

#1602 fix(docs): add commas
  documentation-site/pages/blog/base-web-v7/index.mdx
Labels: bugfix

#1617 Release v8.9.0
  package.json
Labels: release

#1598 feat(icon): add mask toggle when type is password
  documentation-site/examples/input/password.js
  documentation-site/examples/input/password.tsx
  documentation-site/pages/components/input.mdx
  src/icon/build-icons.js
  src/icon/hide.js
  src/icon/icon-exports.js
  src/icon/show.js
  src/icon/svg/hide.svg
  src/icon/svg/show.svg
  src/input/__tests__/__snapshots__/input.test.js.snap
  src/input/__tests__/input-password.scenario.js
  src/input/base-input.js
  src/input/index.d.ts
  src/input/types.js
  src/styles/types.js
Labels: documentation, feature

#1621 Release v8.10.0
  package.json
Labels: release

#1619 fix(breakpoints): stable breakpoint keys
  src/helpers/__tests__/responsive-helpers.test.js
  src/helpers/responsive-helpers.js
Labels: bugfix

#1623 fix(docs): removes directly accessing children as array
  documentation-site/examples/menu/virtual-list.js
  documentation-site/examples/menu/virtual-list.tsx
  documentation-site/examples/select/with-many-options.js
  documentation-site/examples/select/with-many-options.tsx
  scripts/build-docs.js
  src/layer/layer.js
  src/phone-input/country-select-dropdown.js
  yarn.lock
Labels: bugfix

#1627 feat: seo improvements for modal w/out SSR
  src/modal/__tests__/__snapshots__/modal.test.js.snap
  src/modal/styled-components.js
Labels: feature

#1633 Release v8.11.0
  package.json
Labels: release

#1632 feat(docs): add twitter link
  documentation-site/components/footer.js
Labels: feature

#1636 fix(modal): markup for examples
  documentation-site/examples/modal/autofocus.js
  documentation-site/examples/modal/buried-interactive-element.js
Labels: bugfix

#1637 fix(docs): use aria-hidden
  documentation-site/components/code-icon.js
Labels: bugfix

#1595 fix(popover): make styled-components prop types less strict
  src/popover/__tests__/styled-component.test.js
  src/popover/styled-components.js
  src/popover/types.js
Labels: bugfix

#1638 fix: add breadcrumbs pseudo tsx example
  documentation-site/examples/breadcrumbs/pseudo.tsx
  src/breadcrumbs/index.d.ts
Labels: bugfix

#1639 feat(docs): improve landing
  documentation-site/components/layout-landing.js
  documentation-site/components/markdown-elements.js
  documentation-site/pages/index.js
  documentation-site/pages/test.js
Labels: feature

#1641 docs(adopters): add who is using section
  documentation-site/pages/index.js
  documentation-site/static/images/uber-logo.png
Labels: feature

#1630 feat(datepicker): horizontal calendar layout for multiple months
  documentation-site/examples/datepicker/calendar-multiple-months.js
  documentation-site/examples/datepicker/calendar-multiple-months.tsx
  documentation-site/pages/components/datepicker.mdx
  src/datepicker/__tests__/datepicker.test.js
  src/datepicker/calendar-header.js
  src/datepicker/calendar.js
  src/datepicker/constants.js
  src/datepicker/index.d.ts
  src/datepicker/index.js
  src/datepicker/styled-components.js
  src/datepicker/types.js
Labels: feature

#1644 fix(input): clearable icon sizing
  src/input/base-input.js
  src/input/styled-components.js
Labels: bugfix

#1649 docs(radio): change override of radio example to use backgroundColor
  documentation-site/examples/radio/overrides.js
  documentation-site/examples/radio/overrides.tsx
Labels: bugfix

#1645 fix(input): clear and focus correct input when using clearable prop
  src/input/__tests__/input-clearable.scenario.js
  src/input/__tests__/input.e2e.js
  src/input/__tests__/input.scenario.js
  src/input/base-input.js
  src/input/types.js
  src/textarea/__tests__/__snapshots__/stateful-textarea.test.js.snap
  src/textarea/__tests__/__snapshots__/textarea.test.js.snap
  src/textarea/__tests__/textarea.e2e.js
  src/textarea/__tests__/textarea.scenario.js
  src/textarea/textarea.js
Labels: bugfix

#1640 fix(ci): add buildkite tasks for typescript and example validation
  .buildkite/pipeline.yml
  .flowconfig
Labels: bugfix

#1647 feat: seo improvements for accordion
  documentation-site/examples/accordion/renderpanelcontent.js
  documentation-site/examples/accordion/renderpanelcontent.tsx
  documentation-site/pages/components/accordion.mdx
  package.json
  src/accordion/__tests__/__snapshots__/accordion.test.js.snap
  src/accordion/__tests__/accordion.e2e.js
  src/accordion/__tests__/accordion.test.js
  src/accordion/accordion.js
  src/accordion/index.d.ts
  src/accordion/panel.js
  src/accordion/styled-components.js
  src/accordion/types.js
  yarn.lock
Labels: feature

#1624 feat: seo improvements for progress steps
  src/progress-steps/styled-components.js
Labels: feature

#1654 fix(input): pass down 'required' prop
  src/input/__tests__/__snapshots__/base-input.test.js.snap
  src/input/__tests__/__snapshots__/input.test.js.snap
  src/input/base-input.js
  src/textarea/__tests__/__snapshots__/textarea.test.js.snap
Labels: bugfix

#1655 fix(button-group): apply overrides to children correctly
  src/button-group/__tests__/button-group-overrides.scenario.js
  src/button-group/button-group.js
Labels: bugfix

#1656 feat(select): pass id to internal input
  documentation-site/examples/form-control/basic.js
  documentation-site/examples/form-control/basic.tsx
  documentation-site/examples/form-control/checkbox.js
  documentation-site/examples/form-control/checkbox.tsx
  documentation-site/examples/form-control/input.js
  documentation-site/examples/form-control/input.tsx
  documentation-site/examples/form-control/kinds.js
  documentation-site/examples/form-control/radio-group.js
  documentation-site/examples/form-control/radio-group.tsx
  documentation-site/examples/form-control/select.js
  documentation-site/examples/form-control/select.tsx
  documentation-site/examples/form-control/textarea.js
  documentation-site/examples/form-control/textarea.tsx
  documentation-site/pages/components/form-control.mdx
  src/form-control/__tests__/form-control.scenario.js
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/index.d.ts
  src/select/select.js
  src/select/types.js
Labels: enhancement, feature

#1657 Release v8.12.0
  package.json
Labels: release

#1660 docs: update nested overrides copy and example
  documentation-site/components/example.js
  documentation-site/examples/datepicker/nested-override.js
  documentation-site/examples/datepicker/nested-override.tsx
  documentation-site/examples/select/overriden-tag.js
  documentation-site/examples/select/overriden-tag.tsx
  documentation-site/pages/components/datepicker.mdx
  documentation-site/pages/components/select.mdx
  documentation-site/pages/theming/understanding-overrides.mdx
Labels: bugfix, documentation

#1591 feat: Slider label overlap
  package.json
  src/slider/slider.js
  src/slider/styled-components.js
  yarn.lock
Labels: feature
