Repository uber/baseweb, pull requests merged in 2019-08, with the labels that each got.

#1622 feat: seo improvements for side nav
  src/side-navigation/__tests__/nav.e2e.js
  src/side-navigation/nav.js
  src/side-navigation/styled-components.js
Labels: feature

#1665 fix(doc): update readme types
  README.md
Labels: bugfix, docs, documentation

#1663 fix: match input height cross browser
  src/input/__tests__/__snapshots__/base-input.test.js.snap
  src/input/__tests__/__snapshots__/input.test.js.snap
  src/input/__tests__/__snapshots__/masked-input.test.js.snap
  src/input/styled-components.js
  src/textarea/__tests__/__snapshots__/textarea.test.js.snap
Labels: bugfix

#1648 fix(codemod): edit bin field
  packages/baseui-codemods/package.json
Labels: bugfix

#1652 fix(docs): document override prop function
  documentation-site/pages/theming/understanding-overrides.mdx
Labels: feature

#1666 docs(adopters): add broadcom
  documentation-site/pages/index.js
  documentation-site/static/images/broadcom-logo.svg
Labels: feature

#1667 fix(button): password mask button should not fire form submit
  src/input/base-input.js
Labels: bugfix

#1646 fix(theme): display docs toggle theme icon in mobile screens
  documentation-site/components/header-navigation.js
Labels: bugfix

#1674 Release v8.13.0
  package.json
Labels: release

#1661 feat(yard): introducing interactive documentation Yard, button component only
  documentation-site/components/code.js
  documentation-site/components/example.js
  documentation-site/components/footer.js
  documentation-site/components/markdown-elements.js
  documentation-site/components/search.js
  documentation-site/components/yard/ast.ts
  documentation-site/components/yard/code-box.tsx
  documentation-site/components/yard/const.ts
  documentation-site/components/yard/dark-theme.ts
  documentation-site/components/yard/knob.tsx
  documentation-site/components/yard/knobs.tsx
  documentation-site/components/yard/light-theme.ts
  documentation-site/components/yard/override.tsx
  documentation-site/components/yard/overrides.tsx
  documentation-site/components/yard/theme-editor.tsx
  documentation-site/components/yard/types.ts
  documentation-site/components/yard/utils.ts
  documentation-site/components/yard/yard.tsx
  documentation-site/helpers/ga.js
  documentation-site/helpers/ga.ts
  documentation-site/next.config.js
  documentation-site/pages/_app.js
  documentation-site/pages/components/button.mdx
  documentation-site/prism-coy.css
  documentation-site/tomorrow-night.css
  e2e/helpers/index.js
  package.json
  src/a11y/a11y.js
  src/accordion/stateful-panel-container.js
  src/button/styled-components.js
  src/checkbox/styled-components.js
  src/datepicker/__tests__/stateful-calendar-overrides.scenario.js
  src/datepicker/day.js
  src/datepicker/styled-components.js
  src/flex-grid/flex-grid-item.js
  src/layer/layers-manager.js
  src/menu/stateful-menu.js
  src/modal/__tests__/modal.e2e.js
  src/pagination/pagination.js
  src/popover/popover.js
  src/popover/types.js
  src/select/__tests__/select.e2e.js
  src/select/styled-components.js
  src/styles/styled.js
  src/tooltip/stateful-tooltip-container.js
  yarn.lock
Labels: documentation, feature

#1685 fix(yard): recover from bad URL source code
  documentation-site/components/yard/yard.tsx
Labels: bugfix

#1684 test(input): add regression tests for password masking
  src/input/__tests__/input-password.scenario.js
  src/input/__tests__/input.e2e.js
Labels: bugfix

#1686 feat: rtl support progress steps
  screener.config.js
  src/progress-steps/__tests__/progress-steps-rtl.scenario.js
  src/progress-steps/styled-components.js
  src/styles/types.js
  src/theme.ts
  src/themes/creator.js
Labels: feature

#1687 fix(progress-steps): remove textAlign from styled components
  src/progress-steps/__tests__/progress-steps-rtl.scenario.js
  src/progress-steps/styled-components.js
Labels: bugfix

#1688 docs(bidi): add page for bidirectionality
  documentation-site/pages/getting-started/bidirectionality.mdx
  documentation-site/routes.js
Labels: feature

#1689 fix(checkbox): rtl support
  src/checkbox/__tests__/checkbox-rtl.scenario.js
  src/checkbox/styled-components.js
Labels: bugfix

#1690 Release v8.14.0
  package.json
Labels: release

#1694 feat(modal): seo improvements w/out SSR (#1627) REVERT
  src/modal/__tests__/__snapshots__/modal.test.js.snap
  src/modal/styled-components.js
Labels: bugfix

#1695 Release v8.14.1
  package.json
Labels: release

#1710 feat(yard): add theme editor
  documentation-site/components/yard/ast.ts
  documentation-site/components/yard/code-generator.ts
  documentation-site/components/yard/const.ts
  documentation-site/components/yard/theme-editor.tsx
  documentation-site/components/yard/types.ts
  documentation-site/components/yard/yard.tsx
Labels: feature

#1708 feat: rtl support for side navigation
  src/side-navigation/__tests__/nav-rtl.scenario.js
  src/side-navigation/styled-components.js
Labels: feature

#1712 fix: deepMerge array properties correctly
  src/utils/__tests__/deep-merge.test.js
  src/utils/deep-merge.js
Labels: bugfix

#1714 feat(yard): add input
  documentation-site/components/yard/code-generator.ts
  documentation-site/components/yard/const.ts
  documentation-site/components/yard/knob.tsx
  documentation-site/components/yard/knobs.tsx
  documentation-site/components/yard/override.tsx
  documentation-site/components/yard/theme-editor.tsx
  documentation-site/components/yard/types.ts
  documentation-site/components/yard/yard.tsx
  documentation-site/pages/components/input.mdx
Labels: feature

#1713 fix(slider): fix flowtypes for react-range call
  src/slider/styled-components.js
Labels: bugfix

#1716 fix(select): type typo fix
  src/select/types.js
Labels: bugfix

#1711 feat(deploy): move deploy script to the repo
  .buildkite/pipeline.yml
  deploy.sh
Labels: feature

#1719 Release v8.15.0
  package.json
Labels: release

#1721 fix(deploy): npmrc
  deploy.sh
Labels: bugfix

#1722 Release v8.15.1
  package.json
Labels: release

#1720 fix(docs): ensure user logos are visible in dark mode
  documentation-site/pages/index.js
Labels: bugfix

#1723 fix(buildkite): propagate NPM_TOKEN
  docker-compose.yml
Labels: bugfix

#1724 Release v8.15.2
  package.json
Labels: release

#1725 fix(datepicker): let stateful container to take care of the initial state value in stateful datepicker
  src/datepicker/__tests__/stateful-range-datepicker.scenario.js
  src/datepicker/stateful-datepicker.js
Labels: bugfix

#1718 docs: responsive-web blog post
  documentation-site/components/blog.js
  documentation-site/pages/blog/responsive-web/aspect-ratio-box.gif
  documentation-site/pages/blog/responsive-web/index.mdx
  documentation-site/pages/blog/responsive-web/metadata.json
  documentation-site/pages/blog/responsive-web/responsive-flex-grid.gif
  documentation-site/pages/blog/responsive-web/responsive-hide.gif
  documentation-site/pages/blog/responsive-web/responsive-load-status.gif
  documentation-site/pages/blog/responsive-web/responsive-nav-bar.gif
  documentation-site/pages/blog/responsive-web/viewport-meta-tag.gif
  documentation-site/static/images/blog/responsive-web/responsive-shipper-tools.svg
Labels: feature

#1715 feat(rtl): enable rtl layout for components
  src/button/__tests__/button-rtl.scenario.js
  src/button/__tests__/button.scenario.js
  src/button/styled-components.js
  src/datepicker/__tests__/datepicker-rtl.scenario.js
  src/datepicker/styled-components.js
  src/dnd-list/__tests__/dnd-list-rtl.scenario.js
  src/dnd-list/styled-components.js
  src/input/__tests__/input-rtl.scenario.js
  src/input/styled-components.js
  src/menu/__tests__/menu-rtl.scenario.js
  src/menu/styled-components.js
  src/modal/__tests__/modal-rtl.scenario.js
  src/modal/styled-components.js
  src/pagination/__tests__/pagination-rtl.scenario.js
  src/pagination/styled-components.js
  src/payment-card/__tests__/payment-card-rtl.scenario.js
  src/payment-card/styled-components.js
  src/radio/__tests__/radio-rtl.scenario.js
  src/radio/styled-components.js
  src/select/__tests__/select-rtl.scenario.js
  src/select/styled-components.js
  src/tag/__tests__/tag-rtl.scenario.js
  src/tag/styled-components.js
Labels: feature

#1728 feat(table): add StyledSortableLabel as export
  src/table/index.d.ts
  src/table/index.js
Labels: feature

#1727 feat(rtl): components & docs
  .storybook/addons.js
  .storybook/config.js
  documentation-site/components/align-left-icon.js
  documentation-site/components/align-right-icon.js
  documentation-site/components/code.js
  documentation-site/components/direction-context.js
  documentation-site/components/header-navigation.js
  documentation-site/components/layout.js
  documentation-site/components/search.js
  documentation-site/pages/_app.js
  documentation-site/pages/index.js
  package.json
  src/button/__tests__/button-rtl.scenario.js
  src/button/__tests__/button.scenario.js
  src/button/styled-components.js
  src/datepicker/__tests__/datepicker-rtl.scenario.js
  src/datepicker/calendar-header.js
  src/datepicker/styled-components.js
  src/dnd-list/__tests__/dnd-list-rtl.scenario.js
  src/dnd-list/styled-components.js
  src/input/__tests__/input-rtl.scenario.js
  src/input/styled-components.js
  src/menu/__tests__/menu-rtl.scenario.js
  src/menu/styled-components.js
  src/modal/__tests__/modal-rtl.scenario.js
  src/modal/styled-components.js
  src/pagination/__tests__/pagination-rtl.scenario.js
  src/pagination/pagination.js
  src/pagination/styled-components.js
  src/payment-card/__tests__/payment-card-rtl.scenario.js
  src/payment-card/styled-components.js
  src/radio/__tests__/radio-rtl.scenario.js
  src/radio/styled-components.js
  src/select/__tests__/select-rtl.scenario.js
  src/select/styled-components.js
  src/tag/__tests__/tag-rtl.scenario.js
  src/tag/styled-components.js
  yarn.lock
Labels: feature

#1731 Release v8.16.0
  package.json
Labels: release

#1729 fix(tabs): add example with overrides
  documentation-site/examples/tabs/controlled.js
  documentation-site/examples/tabs/controlled.tsx
  documentation-site/examples/tabs/overrides.js
  documentation-site/examples/tabs/overrides.tsx
  documentation-site/pages/components/tabs.mdx
  src/tabs/__tests__/tabs-controlled.scenario.js
Labels: bugfix

#1733 fix(flex-grid): rtl support
  src/flex-grid/flex-grid-item.js
Labels: bugfix

#1732 fix(menu): set the initial state correctly
  src/menu/__tests__/menu-stateful.scenario.js
  src/menu/stateful-container.js
  src/menu/stateful-menu.js
  src/menu/types.js
Labels: bugfix

#1735 feat(docs): edit on github
  documentation-site/components/layout.js
  documentation-site/components/pencil-icon.js
  documentation-site/helpers/polyfills.js
  documentation-site/pages/_app.js
  documentation-site/routes.js
Labels: feature

#1737 fix(docs): small fixes
  documentation-site/components/layout.js
  documentation-site/pages/index.js
Labels: bugfix

#1736 fix(docs): move the controlled component examples to the top
  documentation-site/examples/breadcrumbs/basic.js
  documentation-site/examples/breadcrumbs/basic.tsx
  documentation-site/examples/breadcrumbs/pseudo.js
  documentation-site/examples/breadcrumbs/pseudo.tsx
  documentation-site/examples/header-navigation/basic.js
  documentation-site/examples/header-navigation/basic.tsx
  documentation-site/examples/header-navigation/with-search.js
  documentation-site/examples/header-navigation/with-search.tsx
  documentation-site/examples/pagination/controlled.js
  documentation-site/examples/pagination/controlled.tsx
  documentation-site/examples/tabs/controlled.js
  documentation-site/examples/tabs/controlled.tsx
  documentation-site/examples/tabs/overrides.js
  documentation-site/examples/tabs/overrides.tsx
  documentation-site/examples/tabs/uncontrolled.js
  documentation-site/examples/tabs/uncontrolled.tsx
  documentation-site/pages/components/breadcrumbs.mdx
  documentation-site/pages/components/tabs.mdx
Labels: bugfix, documentation

#1739 Release v8.16.1
  package.json
Labels: release

#1740 fix(docs): get rid of dev error messages
  documentation-site/components/api.js
  documentation-site/components/markdown-elements.js
  documentation-site/examples/datepicker/datepickers-color-states.js
  documentation-site/examples/popover/clipping.js
  documentation-site/examples/progress-bar/basic.js
  documentation-site/examples/progress-bar/basic.tsx
  documentation-site/examples/progress-bar/custom-label.js
  documentation-site/examples/progress-bar/custom-label.tsx
  documentation-site/examples/progress-bar/negative.js
  documentation-site/examples/progress-bar/negative.tsx
  documentation-site/examples/progress-bar/overrides.js
  documentation-site/examples/progress-bar/overrides.tsx
  documentation-site/examples/progress-bar/success-value.js
  documentation-site/examples/progress-bar/success-value.tsx
  documentation-site/examples/progress-bar/with-label.js
  documentation-site/examples/progress-bar/with-label.tsx
  documentation-site/examples/select/overriden-tag.js
  documentation-site/examples/slider/overrides.js
  documentation-site/examples/table-grid/basic.js
  documentation-site/examples/table-grid/cell-span.js
  documentation-site/examples/table-grid/nested.js
  documentation-site/examples/use-styletron/overrides.js
  documentation-site/examples/use-styletron/overrides.tsx
  src/header-navigation/header-navigation.js
Labels: bugfix

#1741 fix(bundle): make sure only the needed icons are bundled
  src/breadcrumbs/breadcrumbs.js
  src/input/styled-components.js
  src/spinner/spinner.js
Labels: bugfix

#1745 fix(docs): removes storybook build
  netlify.toml
Labels: bugfix

#1744 feat(bundle): show component size on the docs site
  .buildkite/pipeline.yml
  component-sizes.json
  documentation-site/components/layout.js
  package.json
  scripts/component-sizes.js
  yarn.lock
Labels: feature

#1747 Release v8.16.2
  package.json
Labels: release

#1742 docs(theming-values): add font1100 to theming-values documentation
  documentation-site/components/theming-values/typography.js
  src/styles/types.js
  src/theme.ts
Labels: bugfix

#1746 Docs content stateless examples
  documentation-site/pages/components/dnd-list.mdx
Labels: feature

#1753 fix(docs): various fixes for main page
  documentation-site/components/layout.js
  documentation-site/pages/index.js
  documentation-site/static/images/broadcom-logo.png
  documentation-site/static/images/broadcom-logo.svg
Labels: bugfix

#1749 feat(docs): progress prefer hooks
  documentation-site/examples/progress-bar/basic.js
  documentation-site/examples/progress-bar/basic.tsx
  documentation-site/examples/progress-bar/custom-label.js
  documentation-site/examples/progress-bar/custom-label.tsx
  documentation-site/examples/progress-bar/negative.js
  documentation-site/examples/progress-bar/negative.tsx
  documentation-site/examples/progress-bar/overrides.js
  documentation-site/examples/progress-bar/overrides.tsx
  documentation-site/examples/progress-bar/success-value.js
  documentation-site/examples/progress-bar/success-value.tsx
  documentation-site/examples/progress-bar/with-label.js
  documentation-site/examples/progress-bar/with-label.tsx
Labels: feature

#1751 fix(modal): add an example of how to handle closing of stacked modals
  documentation-site/examples/modal/basic.js
  documentation-site/examples/modal/nested.js
  documentation-site/examples/modal/nested.tsx
  documentation-site/pages/components/modal.mdx
Labels: bugfix, documentation

#1748 fix(flex-grid): tweak column width values for IE/Edge
  src/flex-grid/__tests__/__snapshots__/flex-grid-item.test.js.snap
  src/flex-grid/__tests__/flex-grid-fractional-pixel.scenario.js
  src/flex-grid/flex-grid-item.js
Labels: bugfix

#1750 feat(docs): re-write modal example with hooks
  documentation-site/examples/modal/basic.js
  documentation-site/examples/modal/basic.tsx
Labels: feature

#1756 fix(bundle-size): update build script
  component-sizes.json
  package.json
  scripts/component-sizes.js
  yarn.lock
Labels: bugfix

#1755 fix(timepicker): ensure onchange queues rerender
  src/datepicker/__tests__/time-picker.e2e.js
  src/datepicker/__tests__/time-picker.scenario.js
  src/datepicker/timepicker.js
Labels: bugfix

#1758 Release v8.16.3
  package.json
Labels: release

#1762 docs(roadmap): clarification on not-planned & adding API docs
  documentation-site/pages/getting-started/roadmap.mdx
Labels: greenkeeping

#1763 fix(slider): bidi support
  documentation-site/pages/getting-started/bidirectionality.mdx
  package.json
  src/slider/__tests__/slider-rtl.scenario.js
  src/slider/slider.js
  src/slider/styled-components.js
  yarn.lock
Labels: bugfix

#1766 docs(testing): point to testing.md
  CONTRIBUTING.md
Labels: docs

#1767 Release v8.16.4
  package.json
Labels: release

#1761 feat(docs): api cheat sheet
  .eslintignore
  .gitignore
  documentation-site/components/cheat-sheet.js
  documentation-site/components/layout.js
  documentation-site/env-config.js
  documentation-site/pages/cheat-sheet.mdx
  documentation-site/routes.js
  jest.config.js
  package.json
  scripts/__tests__/parse-type-file-to-outline.test.js
  scripts/build-documentation-site-files.js
  scripts/cheat-sheet-generator.js
  scripts/post-generator.js
  scripts/version-generator.js
Labels: feature

#1765 fix(block): fix responsive array prop behavior
  documentation-site/components/anchor.js
  documentation-site/components/blog.js
  documentation-site/components/footer.js
  documentation-site/components/header-navigation.js
  documentation-site/components/layout.js
  documentation-site/components/markdown-elements.js
  documentation-site/components/posts.js
  documentation-site/components/search.js
  documentation-site/components/theming-values/borders.js
  documentation-site/components/theming-values/colors.js
  documentation-site/components/theming-values/common.js
  documentation-site/components/theming-values/lighting.js
  documentation-site/components/theming-values/sizing.js
  documentation-site/pages/_app.js
  documentation-site/pages/components/block.mdx
  documentation-site/pages/index.js
  src/block/__tests__/__snapshots__/block.test.js.snap
  src/block/styled-components.js
  src/flex-grid/__tests__/__snapshots__/flex-grid-item.test.js.snap
  src/flex-grid/flex-grid-item.js
  src/helpers/responsive-helpers.js
Labels: bugfix

#1772 fix(bundle): remove puppeteer
  package.json
Labels: bugfix

#1773 Release v8.16.5
  package.json
Labels: release

#1771 docs(pages): add TOC
  documentation-site/components/api.js
  documentation-site/components/example.js
  documentation-site/components/layout.js
  documentation-site/components/table-of-contents.js
  documentation-site/pages/components/accordion.mdx
  documentation-site/pages/components/aspect-ratio-box.mdx
  documentation-site/pages/components/avatar.mdx
  documentation-site/pages/components/base-provider.mdx
  documentation-site/pages/components/block.mdx
  documentation-site/pages/components/breadcrumbs.mdx
  documentation-site/pages/components/button-group.mdx
  documentation-site/pages/components/button.mdx
  documentation-site/pages/components/card.mdx
  documentation-site/pages/components/checkbox.mdx
  documentation-site/pages/components/datepicker.mdx
  documentation-site/pages/components/dnd-list.mdx
  documentation-site/pages/components/file-uploader.mdx
  documentation-site/pages/components/flex-grid.mdx
  documentation-site/pages/components/form-control.mdx
  documentation-site/pages/components/header-navigation.mdx
  documentation-site/pages/components/heading.mdx
  documentation-site/pages/components/icon.mdx
  documentation-site/pages/components/input.mdx
  documentation-site/pages/components/layer.mdx
  documentation-site/pages/components/link.mdx
  documentation-site/pages/components/menu.mdx
  documentation-site/pages/components/modal.mdx
  documentation-site/pages/components/notification.mdx
  documentation-site/pages/components/pagination.mdx
  documentation-site/pages/components/payment-card.mdx
  documentation-site/pages/components/phone-input.mdx
  documentation-site/pages/components/pin-code.mdx
  documentation-site/pages/components/popover.mdx
  documentation-site/pages/components/progress-bar.mdx
  documentation-site/pages/components/progress-steps.mdx
  documentation-site/pages/components/radio.mdx
  documentation-site/pages/components/rating.mdx
  documentation-site/pages/components/select.mdx
  documentation-site/pages/components/side-nav.mdx
  documentation-site/pages/components/slider.mdx
  documentation-site/pages/components/spinner.mdx
  documentation-site/pages/components/styled.mdx
  documentation-site/pages/components/table-grid.mdx
  documentation-site/pages/components/table.mdx
  documentation-site/pages/components/tabs.mdx
  documentation-site/pages/components/tag.mdx
  documentation-site/pages/components/textarea.mdx
  documentation-site/pages/components/toast.mdx
  documentation-site/pages/components/tooltip.mdx
  documentation-site/pages/components/typography.mdx
  documentation-site/pages/components/unstable-a11y.mdx
  documentation-site/pages/components/use-styletron.mdx
Labels: feature

#1776 fix(docs): resolved clobbered git merge
  documentation-site/components/layout.js
  documentation-site/pages/cheat-sheet.mdx
Labels: bugfix

#1777 fix(toc): rtl support
  documentation-site/components/table-of-contents.js
  documentation-site/pages/components/modal.mdx
Labels: bugfix

#1781 feat(docs): adds ga events to cheat sheet
  documentation-site/components/cheat-sheet.js
Labels: feature

#1782 fix(toc): dark theme support
  documentation-site/components/table-of-contents.js
Labels: bugfix

#1783 docs(versioning): small update to visual changes
  documentation-site/pages/getting-started/versioning-policy.mdx
Labels: bugfix

#1780 fix(docs): avoid page layout jumping when ToC changes
  documentation-site/components/table-of-contents.js
Labels: bugfix

#1784 docs(contrib): highlight the usage of stateless components
  CONTRIBUTING.md
  src/template-component/examples.js
Labels: greenkeeping

#1787 docs(components): add controlled info
  documentation-site/pages/getting-started/learn.mdx
Labels: bugfix

#1785 fix(docs): show all gh contributors
  documentation-site/pages/index.js
Labels: bugfix

#1768 style(theme): update large breakpoint
  src/themes/creator.js
Labels: feature

#1805 fix(build): remove prepublish
  package.json
Labels: bugfix

#1806 fix(tag component): removing role and aria-label attrib if disabled
  src/tag/__tests__/tag.test.js
  src/tag/tag.js
Labels: bugfix

#1808 fix: add type annotation for scale750 in theme.sizing
  src/styles/types.js
  src/theme.ts
Labels: bugfix

#1801 feat(drawer): initial implementation of the drawer component
  documentation-site/components/search.js
  documentation-site/examples/drawer/anchors.js
  documentation-site/examples/drawer/anchors.tsx
  documentation-site/examples/drawer/sizes.js
  documentation-site/examples/drawer/sizes.tsx
  documentation-site/pages/components/drawer.mdx
  documentation-site/routes.js
  src/drawer/__tests__/__snapshots__/drawer.test.js.snap
  src/drawer/__tests__/drawer-rtl.scenario.js
  src/drawer/__tests__/drawer-select.scenario.js
  src/drawer/__tests__/drawer.e2e.js
  src/drawer/__tests__/drawer.scenario.js
  src/drawer/__tests__/drawer.test.js
  src/drawer/close-icon.js
  src/drawer/constants.js
  src/drawer/drawer.js
  src/drawer/index.d.ts
  src/drawer/index.js
  src/drawer/locale.js
  src/drawer/styled-components.js
  src/drawer/types.js
  src/locale/en_US.js
  src/locale/types.js
Labels: feature

#1815 docs: Update Learning Base Web - Overrides
  documentation-site/pages/getting-started/learn.mdx
Labels: bugfix

#1810 fix(modal): add contrasting color for close button in modal
  src/modal/styled-components.js
  src/styles/types.js
  src/theme.ts
  src/themes/creator.js
  src/themes/dark-theme-colors.js
Labels: bugfix

#1791 feat(phone-input): replace flag svg with emoji
  component-sizes.json
  documentation-site/examples/phone-input/flag-overrides.js
  documentation-site/examples/phone-input/flag-overrides.tsx
  documentation-site/examples/phone-input/localized.js
  documentation-site/examples/phone-input/localized.tsx
  documentation-site/pages/components/phone-input.mdx
  src/phone-input/__tests__/country-select-dropdown.scenario.js
  src/phone-input/__tests__/phone-input.e2e.js
  src/phone-input/__tests__/phone-input.scenario.js
  src/phone-input/country-select-dropdown.js
  src/phone-input/country-select.js
  src/phone-input/flag.js
  src/phone-input/index.d.ts
  src/phone-input/index.js
  src/phone-input/phone-input.js
  src/phone-input/styled-components.js
  src/phone-input/types.js
  src/phone-input/utils.js
Labels: feature

#1816 fix(datepicker): make the calendar arrows larger
  src/datepicker/calendar-header.js
  src/datepicker/styled-components.js
Labels: bugfix

#1817 Release v8.17.0
  package.json
Labels: release

#1813 fix(data-attr): add mising data-baseweb attributes
  src/side-navigation/nav.js
  src/table-grid/styled-components.js
Labels: bugfix

#1812 fix(link): forward the link ref so it works together with the popover
  documentation-site/examples/popover/dismiss.js
  documentation-site/examples/popover/dismiss.tsx
  documentation-site/examples/popover/link.js
  documentation-site/examples/popover/link.tsx
  documentation-site/pages/components/popover.mdx
  src/breadcrumbs/__tests__/__snapshots__/breadcrumbs.test.js.snap
  src/link/index.js
Labels: bugfix

#1823 Release v8.17.1
  package.json
Labels: release

#1826 docs: prioritize local storage for theme
  documentation-site/pages/_app.js
Labels: bugfix, documentation

#1822 fix(build): add doc site generation for tests
  package.json
Labels: bugfix
