Repository uber/baseweb, pull requests merged in 2019-11, with the labels that each got.

#2214 docs(announcement): done button after the last step
  documentation-site/components/walkthrough.js
Labels: docs

#2213 fix(modal): removes children type from shared style props
  src/modal/types.js
Labels: bugfix

#2217 fix(select): typo in nowrap
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/styled-components.js
Labels: bugfix

#2219 feat(checkbox): creates new round toggle style
  documentation-site/examples/checkbox/toggle.js
  documentation-site/examples/checkbox/toggle.tsx
  src/checkbox/__tests__/checkbox-toggle-round.scenario.js
  src/checkbox/checkbox.js
  src/checkbox/constants.js
  src/checkbox/index.d.ts
  src/checkbox/styled-components.js
  src/data-table/filter-shell.js
  vrt/__image_snapshots__/checkbox-toggle-round__dark-snap.png
  vrt/__image_snapshots__/checkbox-toggle-round__desktop-snap.png
  vrt/__image_snapshots__/checkbox-toggle-round__mobile-snap.png
  vrt/__image_snapshots__/data-table-categorical-column__dark-snap.png
  vrt/__image_snapshots__/data-table-categorical-column__desktop-snap.png
  vrt/__image_snapshots__/data-table-categorical-column__mobile-snap.png
  vrt/__image_snapshots__/data-table-numerical-column__dark-snap.png
  vrt/__image_snapshots__/data-table-numerical-column__desktop-snap.png
  vrt/__image_snapshots__/data-table-numerical-column__mobile-snap.png
Labels: feature

#2221 fix(data-table): properly applies row highlight
  src/data-table/data-table.js
Labels: bugfix

#2223 chore(project): remove undocumented withProps
  src/helpers/index.js
  src/index.d.ts
  src/index.js
Labels: greenkeeping

#2225 fix(modal): revert PR #2206
  src/modal/__tests__/__snapshots__/modal.test.js.snap
  src/modal/modal.js
  src/modal/styled-components.js
Labels: bugfix

#2226 Release v9.14.0
  package.json
Labels: release

#2228 fix(accordion): handle panel icon overrides
  src/accordion/__tests__/accordion-panel-override.scenario.js
  src/accordion/panel.js
  vrt/__image_snapshots__/accordion-panel-override__dark-snap.png
  vrt/__image_snapshots__/accordion-panel-override__desktop-snap.png
  vrt/__image_snapshots__/accordion-panel-override__mobile-snap.png
Labels: bugfix

#2239 fix(select): trigger dropdown for no results
  src/select/__tests__/select-creatable-multi.scenario.js
  src/select/__tests__/select.e2e.js
  src/select/select-component.js
Labels: bugfix

#2238 test(vrt): fix some vrt with interactions tests
  src/datepicker/__tests__/datepicker-range.e2e.js
  src/datepicker/__tests__/datepicker.e2e.js
  src/datepicker/__tests__/datepicker.scenario.js
  src/drawer/__tests__/drawer-select.scenario.js
  vrt/__image_snapshots__/datepicker-range__selectedRangeHighlighted-snap.png
  vrt/__image_snapshots__/datepicker-rtl__calendarOpened-snap.png
  vrt/__image_snapshots__/datepicker__setDateHighlighted-snap.png
  vrt/__image_snapshots__/drawer-select__dark-snap.png
  vrt/__image_snapshots__/drawer-select__desktop-snap.png
  vrt/__image_snapshots__/drawer-select__mobile-snap.png
  vrt/__image_snapshots__/drawer-select__selectDropdownVisible-snap.png
  vrt/__image_snapshots__/select-in-modal__selectDropdownVisible-snap.png
  vrt/config.js
Labels: bugfix, test

#2241 Release v9.14.1
  package.json
Labels: release

#2236 feat(data-table): swap boolean alignment
  src/data-table/column-boolean.js
  vrt/__image_snapshots__/data-table-batch-action__dark-snap.png
  vrt/__image_snapshots__/data-table-batch-action__desktop-snap.png
  vrt/__image_snapshots__/data-table-batch-action__mobile-snap.png
  vrt/__image_snapshots__/data-table-columns__dark-snap.png
  vrt/__image_snapshots__/data-table-columns__desktop-snap.png
  vrt/__image_snapshots__/data-table-columns__mobile-snap.png
  vrt/__image_snapshots__/data-table__dark-snap.png
  vrt/__image_snapshots__/data-table__desktop-snap.png
  vrt/__image_snapshots__/data-table__mobile-snap.png
Labels: feature

#2243 docs(survey): reduce timeout
  documentation-site/components/survey.js
Labels: docs

#2231 fix(modal): fix e2e test for modal+select case
  src/modal/__tests__/modal-select.scenario.js
  src/modal/__tests__/modal.scenario.js
  vrt/__image_snapshots__/modal-select__dark-snap.png
  vrt/__image_snapshots__/modal-select__desktop-snap.png
  vrt/__image_snapshots__/modal-select__mobile-snap.png
  vrt/__image_snapshots__/modal-select__selectOption-snap.png
  vrt/config.js
Labels: bugfix, test

#2235 fix(data-table): filter tags align with add filter btn height
  src/data-table/data-table.js
Labels: bugfix

#2244 docs(home): card same height and title for contributors
  documentation-site/components/contributors.js
  documentation-site/pages/index.js
Labels: docs

#2216 fix(polished): import darken and lighten only
  src/tag/styled-components.js
Labels: bugfix

#2248 docs(adopters): add uptime.ca
  documentation-site/pages/index.js
  documentation-site/static/images/uptime-logo.png
Labels: docs

#2103 test(select): adds e2e scenario for select in block
  src/select/__tests__/select-in-flex-container.scenario.js
  vrt/__image_snapshots__/select-in-flex-container-snap.png
  vrt/__image_snapshots__/select-in-flex-container__dark-snap.png
  vrt/__image_snapshots__/select-in-flex-container__desktop-snap.png
  vrt/__image_snapshots__/select-in-flex-container__mobile-snap.png
Labels: bugfix

#2252 fix(menu): do not capitalize no results text
  src/menu/styled-components.js
  vrt/__image_snapshots__/menu-empty__dark-snap.png
  vrt/__image_snapshots__/menu-empty__desktop-snap.png
  vrt/__image_snapshots__/menu-empty__mobile-snap.png
Labels: bugfix

#2246 feat(data-table): refactor to enable uncontrolled usage
  documentation-site/examples/data-table/basic.js
  documentation-site/examples/data-table/basic.tsx
  documentation-site/examples/data-table/batch-action.js
  documentation-site/examples/data-table/batch-action.tsx
  src/data-table/__tests__/column-boolean.test.js
  src/data-table/__tests__/column-categorical.test.js
  src/data-table/__tests__/column-custom.test.js
  src/data-table/__tests__/column-numerical.test.js
  src/data-table/__tests__/data-table-batch-action.e2e.js
  src/data-table/__tests__/data-table-batch-action.scenario.js
  src/data-table/__tests__/data-table-columns.e2e.js
  src/data-table/__tests__/data-table-columns.scenario.js
  src/data-table/__tests__/data-table-row-actions.e2e.js
  src/data-table/__tests__/data-table-row-actions.scenario.js
  src/data-table/__tests__/data-table-text-search.e2e.js
  src/data-table/__tests__/data-table-text-search.scenario.js
  src/data-table/__tests__/data-table.scenario.js
  src/data-table/__tests__/utilities.js
  src/data-table/column-boolean.js
  src/data-table/column-categorical.js
  src/data-table/column-custom.js
  src/data-table/column-numerical.js
  src/data-table/column-string.js
  src/data-table/data-table.js
  src/data-table/filter-menu.js
  src/data-table/index.d.ts
  src/data-table/index.js
  src/data-table/stateful-data-table.js
  src/data-table/types.js
Labels: feature

#2155 chore: bump flow to 0.110
  package.json
  src/drawer/styled-components.js
  src/input/input.js
  src/input/masked-input.js
  src/input/types.js
  src/menu/__tests__/stateful-container.test.js
  src/pagination/__tests__/stateful-container.test.js
  src/radio/types.js
  src/select/styled-components.js
  src/textarea/__tests__/textarea.test.js
  src/textarea/textarea.js
  src/textarea/types.js
  yarn.lock
Labels: feature

#2256 Release v9.15.0
  package.json
Labels: release

#2260 docs(input): password example to use input component
  documentation-site/pages/components/input.mdx
Labels: docs

#2250 fix(flex-grid): use consistent specificity for nth-child selectors
  src/flex-grid/__tests__/__snapshots__/flex-grid-item.test.js.snap
  src/flex-grid/__tests__/flex-grid-responsive.scenario.js
  src/flex-grid/flex-grid-item.js
  vrt/__image_snapshots__/flex-grid-responsive__dark-snap.png
  vrt/__image_snapshots__/flex-grid-responsive__desktop-snap.png
  vrt/__image_snapshots__/flex-grid-responsive__mobile-snap.png
Labels: bugfix

#2249 docs(seo): add guide & small fixes
  documentation-site/components/yard/config/header-navigation.ts
  documentation-site/examples/accordion/renderpanelcontent.js
  documentation-site/examples/accordion/renderpanelcontent.tsx
  documentation-site/pages/guides/seo.mdx
  documentation-site/routes.js
  src/accordion/__tests__/__snapshots__/accordion.test.js.snap
  src/accordion/__tests__/accordion.test.js
  src/accordion/accordion.js
  src/accordion/index.d.ts
  src/accordion/panel.js
  src/accordion/types.js
  src/header-navigation/styled-components.js
Labels: bugfix, docs

#2261 Release v9.15.1
  package.json
Labels: release

#2255 fix(build): cjs, es and esm
  .babelrc.js
  package.json
Labels: bugfix

#2262 docs(versioning): update the policy
  documentation-site/pages/discover-more/versioning-policy.mdx
Labels: docs

#2264 docs(yard): add icons for actions
  documentation-site/components/yard/yard.tsx
  package.json
  yarn.lock
Labels: docs

#2270 fix(ts): add missing defs for icons and inputs
  src/icon/index.d.ts
  src/input/index.d.ts
Labels: bugfix

#2263 docs(yard): link to API
  documentation-site/components/exports.js
  documentation-site/components/yard/styled-components.tsx
  documentation-site/components/yard/yard.tsx
Labels: docs

#2265 feat(data-table): stateful container
  src/data-table/__tests__/data-table-extracted-filters.e2e.js
  src/data-table/__tests__/data-table-extracted-filters.scenario.js
  src/data-table/__tests__/utilities.js
  src/data-table/index.js
  src/data-table/stateful-container.js
  src/data-table/stateful-data-table.js
  src/data-table/types.js
  vrt/__image_snapshots__/data-table-extracted-filters__dark-snap.png
  vrt/__image_snapshots__/data-table-extracted-filters__desktop-snap.png
  vrt/__image_snapshots__/data-table-extracted-filters__mobile-snap.png
Labels: feature

#2266 docs(yard): make it visible that props are hoverable
  documentation-site/components/yard/knob.tsx
Labels: docs

#2268 fix(calendar): remove role-application from calendar
  src/datepicker/__tests__/calendar.e2e.js
  src/datepicker/__tests__/datepicker-int.e2e.js
  src/datepicker/__tests__/datepicker-range.e2e.js
  src/datepicker/__tests__/datepicker-unreliable.e2e.js
  src/datepicker/__tests__/datepicker.e2e.js
  src/datepicker/__tests__/stateful-datepicker.e2e.js
  src/datepicker/calendar.js
  vrt/config.js
Labels: bugfix

#2277 fix(vrt): link to snapshot pr url in bot comments
  vrt/ci.js
Labels: bugfix

#2273 fix(data-table): visual polish - sort hover/active colors, filter pill row gap
  src/data-table/data-table.js
  src/data-table/filter-menu.js
  src/data-table/header-cell.js
  src/data-table/stateful-data-table.js
  vrt/__image_snapshots__/data-table-row-actions__dark-snap.png
  vrt/__image_snapshots__/data-table-row-actions__desktop-snap.png
  vrt/__image_snapshots__/data-table-row-actions__mobile-snap.png
Labels: bugfix

#2279 docs(overrides): remove the old inspector
  documentation-site/examples/dnd-list/overrides_state_props.js
  documentation-site/examples/dnd-list/overrides_state_props.tsx
  documentation-site/pages/guides/understanding-overrides.mdx
  documentation-site/static/images/react-view-overrides.png
Labels: docs

#2278 fix(build): explicitly targeting browsers
  .babelrc.js
Labels: bugfix

#2275 fix(timepicker): enable null value
  documentation-site/components/yard/config/timepicker.ts
  src/timepicker/__tests__/time-picker.scenario.js
  src/timepicker/index.d.ts
  src/timepicker/timepicker.js
  src/timepicker/types.js
  vrt/__image_snapshots__/time-picker__dark-snap.png
  vrt/__image_snapshots__/time-picker__desktop-snap.png
  vrt/__image_snapshots__/time-picker__mobile-snap.png
Labels: bugfix

#2280 Release v9.16.0
  package.json
Labels: release

#2271 feat(data-table): col max-width row-height line-clamp
  documentation-site/examples/data-table/row-height-line-clamp.js
  documentation-site/examples/data-table/row-height-line-clamp.tsx
  documentation-site/pages/components/unstable-data-table.mdx
  src/data-table/__tests__/data-table-row-height.scenario.js
  src/data-table/cell-shell.js
  src/data-table/column-boolean.js
  src/data-table/column-categorical.js
  src/data-table/column-custom.js
  src/data-table/column-numerical.js
  src/data-table/column-string.js
  src/data-table/data-table.js
  src/data-table/measure-column-widths.js
  src/data-table/stateful-data-table.js
  src/data-table/types.js
  vrt/__image_snapshots__/data-table-row-height__dark-snap.png
  vrt/__image_snapshots__/data-table-row-height__desktop-snap.png
  vrt/__image_snapshots__/data-table-row-height__mobile-snap.png
Labels: feature

#2286 feat(input): enable min max values for number type
  documentation-site/components/yard/config/input.ts
  src/input/__tests__/__snapshots__/base-input.test.js.snap
  src/input/__tests__/__snapshots__/input.test.js.snap
  src/input/__tests__/__snapshots__/masked-input.test.js.snap
  src/input/__tests__/input-number.scenario.js
  src/input/base-input.js
  src/input/index.d.ts
  src/input/types.js
  src/textarea/__tests__/__snapshots__/textarea.test.js.snap
  vrt/__image_snapshots__/input-number__dark-snap.png
  vrt/__image_snapshots__/input-number__desktop-snap.png
  vrt/__image_snapshots__/input-number__mobile-snap.png
  vrt/__image_snapshots__/input-number__numberInput-snap.png
  vrt/config.js
Labels: feature

#2282 chore(dependencies): update storybook to v5
  package.json
  yarn.lock
Labels: greenkeeping

#2284 [Select] Ignore keyevent Enter from IME
  src/menu/stateful-container.js
Labels: bugfix

#2291 fix(timepicker): enable nullable values
  src/timepicker/__tests__/time-picker.scenario.js
  src/timepicker/timepicker.js
Labels: bugfix

#2292 Release v9.17.0
  package.json
Labels: release

#2293 fix(progress-steps): pass down overrides to children
  documentation-site/components/yard/config/progress-steps.ts
  src/progress-steps/__tests__/progress-steps.test.js
  src/progress-steps/progress-steps.js
  src/progress-steps/types.js
Labels: bugfix

#2297 docs(select): fix virtualized example
  documentation-site/examples/select/with-many-options.js
  documentation-site/examples/select/with-many-options.tsx
Labels: bugfix

#2296 docs(yard): preserve defaultValue when value is undefined
  documentation-site/components/yard/utils.ts
Labels: docs

#2283 feat(data-table): filter update
  src/data-table/column-boolean.js
  src/data-table/column-categorical.js
  src/data-table/column-custom.js
  src/data-table/column-numerical.js
  src/data-table/stateful-data-table.js
  src/data-table/types.js
Labels: feature

#2288 feat(data-table): header filter tooltips
  src/data-table/data-table.js
  src/data-table/measure-column-widths.js
  vrt/__image_snapshots__/data-table-batch-action__dark-snap.png
  vrt/__image_snapshots__/data-table-batch-action__desktop-snap.png
  vrt/__image_snapshots__/data-table-batch-action__mobile-snap.png
  vrt/__image_snapshots__/data-table-columns__dark-snap.png
  vrt/__image_snapshots__/data-table-columns__desktop-snap.png
  vrt/__image_snapshots__/data-table-columns__mobile-snap.png
  vrt/__image_snapshots__/data-table-extracted-filters__dark-snap.png
  vrt/__image_snapshots__/data-table-extracted-filters__desktop-snap.png
  vrt/__image_snapshots__/data-table-row-actions__dark-snap.png
  vrt/__image_snapshots__/data-table-row-actions__desktop-snap.png
  vrt/__image_snapshots__/data-table-row-actions__mobile-snap.png
  vrt/__image_snapshots__/data-table-text-search__dark-snap.png
  vrt/__image_snapshots__/data-table-text-search__desktop-snap.png
  vrt/__image_snapshots__/data-table-text-search__mobile-snap.png
  vrt/__image_snapshots__/data-table__dark-snap.png
  vrt/__image_snapshots__/data-table__desktop-snap.png
  vrt/__image_snapshots__/data-table__mobile-snap.png
Labels: feature

#2300 Release v9.18.0
  package.json
Labels: release

#2302 docs(checkbox): remove default value for placement
  documentation-site/components/yard/config/checkbox.ts
Labels: docs

#2304 chore(project): remove actions
  .github/workflows/greetings.yml
  .github/workflows/stale.yml
Labels: bugfix, chore

#2305 feat(data-table): allow row data to take any shape
  documentation-site/examples/data-table/basic.js
  documentation-site/examples/data-table/basic.tsx
  documentation-site/examples/data-table/batch-action.js
  documentation-site/examples/data-table/batch-action.tsx
  documentation-site/examples/data-table/row-height-line-clamp.js
  documentation-site/examples/data-table/row-height-line-clamp.tsx
  src/data-table/__tests__/column-boolean.test.js
  src/data-table/__tests__/column-categorical.test.js
  src/data-table/__tests__/column-custom.test.js
  src/data-table/__tests__/column-numerical.test.js
  src/data-table/__tests__/column-string.test.js
  src/data-table/__tests__/data-table-batch-action.scenario.js
  src/data-table/__tests__/data-table-categorical-column.scenario.js
  src/data-table/__tests__/data-table-collection-of-objects.scenario.js
  src/data-table/__tests__/data-table-columns.scenario.js
  src/data-table/__tests__/data-table-extracted-filters.scenario.js
  src/data-table/__tests__/data-table-numerical-column.scenario.js
  src/data-table/__tests__/data-table-row-actions.scenario.js
  src/data-table/__tests__/data-table-row-height.scenario.js
  src/data-table/__tests__/data-table-text-search.scenario.js
  src/data-table/__tests__/data-table.scenario.js
  src/data-table/__tests__/graphql-array-data.js
  src/data-table/column-boolean.js
  src/data-table/column-categorical.js
  src/data-table/column-custom.js
  src/data-table/column-numerical.js
  src/data-table/column-string.js
  src/data-table/data-table.js
  src/data-table/index.d.ts
  src/data-table/measure-column-widths.js
  src/data-table/types.js
  vrt/__image_snapshots__/data-table-collection-of-objects__dark-snap.png
  vrt/__image_snapshots__/data-table-collection-of-objects__desktop-snap.png
  vrt/__image_snapshots__/data-table-collection-of-objects__mobile-snap.png
Labels: feature

#2308 Release v9.19.0
  package.json
Labels: release

#2309 docs(layout-grid): edit copy and fix shrink example
  documentation-site/examples/layout-grid/skip-shrink.js
  documentation-site/examples/layout-grid/skip-shrink.tsx
  documentation-site/pages/components/layout-grid.mdx
Labels: bugfix, docs

#2303 docs(select): use react-window for virtualized example
  documentation-site/examples/select/with-many-options.js
  documentation-site/examples/select/with-many-options.tsx
  documentation-site/pages/components/select.mdx
  package.json
  yarn.lock
Labels: docs

#2314 feat(media-query): add mediaQuery object to theme and update docs
  documentation-site/components/header-navigation.js
  documentation-site/components/help.js
  documentation-site/components/layout.js
  documentation-site/components/posts.js
  documentation-site/components/search.js
  documentation-site/components/survey.js
  documentation-site/components/walkthrough.js
  documentation-site/components/yard/knobs.tsx
  documentation-site/components/yard/override.tsx
  documentation-site/components/yard/theme-editor.tsx
  documentation-site/pages/_app.js
  documentation-site/pages/blog/responsive-web/index.mdx
  documentation-site/pages/components/block.mdx
  documentation-site/pages/index.js
  src/styles/types.js
  src/theme.ts
  src/themes/creator.js
Labels: feature

#2310 chore(bundle): add better support for checking each component size
  package.json
  scripts/bundle-size/.gitignore
  scripts/bundle-size/bundle-size.js
  scripts/bundle-size/webpack.config.js
  yarn.lock
Labels: feature, work in progress

#2321 docs(file-uploader): security
  documentation-site/pages/components/file-uploader.mdx
Labels: docs

#2322 docs(security): add a way for folks to contact us
  SECURITY.md
Labels: docs

#2328 fix(phone-input): remove extra text
  src/phone-input/country-select-dropdown.js
Labels: bugfix

#2325 chore(component-sizes): update to use the new script
  component-sizes.json
  documentation-site/components/layout.js
  package.json
  scripts/bundle-size/bundle-size.js
  scripts/component-sizes.js
  yarn.lock
Labels: bugfix, chore

#2334 fix(input): height for password field
  src/input/__tests__/input-password.scenario.js
  src/input/base-input.js
  vrt/__image_snapshots__/input-password__dark-snap.png
  vrt/__image_snapshots__/input-password__desktop-snap.png
  vrt/__image_snapshots__/input-password__mobile-snap.png
  vrt/__image_snapshots__/input-password__togglesMask-snap.png
  vrt/__image_snapshots__/input-rtl__desktop-snap.png
  vrt/__image_snapshots__/input-rtl__mobile-snap.png
Labels: bugfix

#2315 feat(slider): Adding onFinalChange prop to slider
  documentation-site/components/yard/config/slider.ts
  src/slider/constants.js
  src/slider/index.d.ts
  src/slider/slider.js
  src/slider/stateful-slider-container.js
  src/slider/types.js
Labels: feature

#2339 fix(modal): use camel case for prop autoFocus
  src/modal/__tests__/__snapshots__/modal.test.js.snap
  src/modal/index.d.ts
  src/modal/modal.js
  src/modal/types.js
Labels: bugfix

#2336 Release v9.20.0
  package.json
Labels: release

#2343 fix typo on docs homepage
  documentation-site/pages/index.js
Labels: docs

#2344 fix(datepicker): use en dash for date range
  documentation-site/examples/datepicker/in-popover.js
  documentation-site/examples/datepicker/in-popover.tsx
  src/datepicker/__tests__/datepicker-int.e2e.js
  src/datepicker/__tests__/datepicker-int.scenario.js
  src/datepicker/__tests__/datepicker-range.e2e.js
  src/datepicker/__tests__/datepicker.test.js
  src/datepicker/datepicker.js
  vrt/__image_snapshots__/datepicker-int__dark-snap.png
  vrt/__image_snapshots__/datepicker-int__desktop-snap.png
  vrt/__image_snapshots__/datepicker-int__mobile-snap.png
  vrt/__image_snapshots__/datepicker-range-highlight__dark-snap.png
  vrt/__image_snapshots__/datepicker-range-highlight__desktop-snap.png
  vrt/__image_snapshots__/datepicker-range-highlight__mobile-snap.png
  vrt/__image_snapshots__/datepicker-range-highlight__noHighlight-snap.png
  vrt/__image_snapshots__/datepicker-range__dark-snap.png
  vrt/__image_snapshots__/datepicker-range__desktop-snap.png
  vrt/__image_snapshots__/datepicker-range__mobile-snap.png
  vrt/__image_snapshots__/datepicker-range__selectedRangeHighlighted-snap.png
  vrt/__image_snapshots__/stateful-datepicker-quick-select__dark-snap.png
  vrt/__image_snapshots__/stateful-datepicker-quick-select__desktop-snap.png
  vrt/__image_snapshots__/stateful-datepicker-quick-select__mobile-snap.png
  vrt/__image_snapshots__/stateful-range-datepicker__dark-snap.png
  vrt/__image_snapshots__/stateful-range-datepicker__desktop-snap.png
  vrt/__image_snapshots__/stateful-range-datepicker__mobile-snap.png
Labels: bugfix

#2345 fix(radio-group): wrap items properly
  src/radio/styled-components.js
Labels: bugfix

#2320 chore(media-query): simplify getMediaQuery to min-width case
  src/flex-grid/flex-grid-item.js
  src/helpers/__tests__/responsive-helpers.test.js
  src/helpers/responsive-helpers.js
  src/themes/creator.js
Labels: feature

#2347 Release v9.21.0
  package.json
Labels: release

#2341 fix(datepicker): use the locale object for the input too
  documentation-site/examples/datepicker/i18n.js
  documentation-site/examples/datepicker/i18n.tsx
  src/datepicker/__tests__/datepicker-int.e2e.js
  src/datepicker/__tests__/datepicker-int.scenario.js
  src/datepicker/datepicker.js
  src/datepicker/index.d.ts
Labels: bugfix

#2355 Release v9.21.1
  package.json
Labels: release

#2351 feat(theme): add default grid values
  documentation-site/pages/components/layout-grid.mdx
  src/layout-grid/styled-components.js
  src/styles/types.js
  src/theme.ts
  src/themes/creator.js
Labels: feature

#2354 docs(survey): move back to delighted
  documentation-site/components/layout.js
  documentation-site/components/survey.js
  documentation-site/pages/_document.js
Labels: docs

#2357 fix(datepicker): mask argument accepts null
  src/datepicker/types.js
Labels: bugfix

#2338 docs(keywords): adds avatar, breadcrumbs and buttons
  documentation-site/pages/components/avatar.mdx
  documentation-site/pages/components/breadcrumbs.mdx
  documentation-site/pages/components/button-group.mdx
  documentation-site/pages/components/button.mdx
Labels: docs

#2342 feat(modal): add unstable prop for the backdrop scroll functionality
  documentation-site/components/yard/config/modal.ts
  src/modal/__tests__/__snapshots__/modal.test.js.snap
  src/modal/index.d.ts
  src/modal/modal.js
  src/modal/styled-components.js
  src/modal/types.js
Labels: feature

#2358 Release v9.22.0
  package.json
Labels: release

#2365 fix(doc-site): fix slack footer link
  documentation-site/components/footer.js
Labels: bugfix

#2367 fix(datepicker): aria-label i18n through the localeContext (#2349)
  src/datepicker/day.js
  src/datepicker/locale.js
Labels: bugfix

#2371 chore(versioning): add comments to v10
  src/accordion/accordion.js
  src/checkbox/checkbox.js
  src/modal/modal.js
  src/radio/radiogroup.js
Labels: chore, greenkeeping

#2369 feat(data-table): Data table anchor column
  src/data-table/__tests__/column-anchor.test.js
  src/data-table/__tests__/data-table-collection-of-objects.scenario.js
  src/data-table/__tests__/data-table.scenario.js
  src/data-table/column-anchor.js
  src/data-table/column-categorical.js
  src/data-table/constants.js
  src/data-table/index.js
  vrt/__image_snapshots__/data-table-collection-of-objects__dark-snap.png
  vrt/__image_snapshots__/data-table-collection-of-objects__desktop-snap.png
  vrt/__image_snapshots__/data-table-collection-of-objects__mobile-snap.png
Labels: feature

#2378 fix(tabs): space key a11y on Tabs and Accordion component.
  src/accordion/panel.js
  src/tabs/tab.js
Labels: bugfix

#2373 fix(data-table): removes duplicate sample cells from measurement
  src/data-table/measure-column-widths.js
Labels: bugfix

#2383 docs(yard): react-view 1.0.4
  package.json
  yarn.lock
Labels: docs

#2372 fix(phone-input): make the countries searchable
  src/phone-input/__tests__/phone-input.e2e.js
  src/phone-input/country-select.js
Labels: bugfix

#2382 Release v9.23.0
  package.json
Labels: release

#2374 fix(button): remove ModalButton margin outside button group
  src/modal/__tests__/modal-button.test.js
  src/modal/modal-button.js
  vrt/__image_snapshots__/modal-rtl__desktop-snap.png
  vrt/__image_snapshots__/modal-rtl__mobile-snap.png
Labels: bugfix

#2389 fix(side-nav): fix dark theme colors
  src/side-navigation/__tests__/__snapshots__/nav.test.js.snap
  src/side-navigation/__tests__/nav.test.js
  src/side-navigation/styled-components.js
  vrt/__image_snapshots__/nav__dark-snap.png
Labels: bugfix

#2387 fix(toggle): dark theme colors fix
  src/checkbox/styled-components.js
  src/styles/types.js
  src/themes/creator.js
  src/themes/dark-theme-colors.js
  vrt/__image_snapshots__/checkbox-toggle-round__dark-snap.png
  vrt/__image_snapshots__/data-table-categorical-column__dark-snap.png
  vrt/__image_snapshots__/data-table-extracted-filters__dark-snap.png
  vrt/__image_snapshots__/data-table-numerical-column__dark-snap.png
Labels: bugfix

#2395 Release v9.23.1
  package.json
Labels: release
