Repository uber/baseweb, pull requests merged in 2019-12, with the labels that each got.

#2398 fix(select): center search icon
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/styled-components.js
  vrt/__image_snapshots__/select-overridden-menu__dark-snap.png
  vrt/__image_snapshots__/select-overridden-menu__desktop-snap.png
  vrt/__image_snapshots__/select-overridden-menu__mobile-snap.png
  vrt/__image_snapshots__/select-search-multi__dark-snap.png
  vrt/__image_snapshots__/select-search-multi__desktop-snap.png
  vrt/__image_snapshots__/select-search-multi__mobile-snap.png
  vrt/__image_snapshots__/select-search-single__dark-snap.png
  vrt/__image_snapshots__/select-search-single__desktop-snap.png
  vrt/__image_snapshots__/select-search-single__mobile-snap.png
  vrt/__image_snapshots__/select-search-single__open-snap.png
Labels: bugfix

#2376 bugfix(datepicker): datepicker accessibility improvements
  src/datepicker/calendar.js
  src/datepicker/day.js
  src/datepicker/month.js
  src/datepicker/week.js
Labels: bugfix

#2406 docs(datepicker): more information on localization
  documentation-site/pages/components/datepicker.mdx
Labels: docs

#2404 feat(datepicker): support for type prop
  documentation-site/components/yard/config/datepicker.ts
  src/datepicker/__tests__/datepicker.scenario.js
  src/datepicker/datepicker.js
  src/datepicker/index.d.ts
  src/datepicker/types.js
  vrt/__image_snapshots__/datepicker-rtl__calendarOpened-snap.png
  vrt/__image_snapshots__/datepicker-rtl__desktop-snap.png
  vrt/__image_snapshots__/datepicker-rtl__mobile-snap.png
  vrt/__image_snapshots__/datepicker__dark-snap.png
  vrt/__image_snapshots__/datepicker__desktop-snap.png
  vrt/__image_snapshots__/datepicker__mobile-snap.png
  vrt/__image_snapshots__/datepicker__setDateHighlighted-snap.png
Labels: feature

#2408 Release v9.24.0
  package.json
Labels: release

#2410 chore: update react-view dep
  package.json
  yarn.lock
Labels: docs

#2409 fix(phone-input): account for filtering in country-select-dropdown
  src/phone-input/__tests__/phone-input-custom-flags.scenario.js
  src/phone-input/country-select-dropdown.js
  src/phone-input/types.js
  vrt/__image_snapshots__/phone-input-custom-flags__dark-snap.png
  vrt/__image_snapshots__/phone-input-custom-flags__desktop-snap.png
  vrt/__image_snapshots__/phone-input-custom-flags__expandedAndFiltered-snap.png
  vrt/__image_snapshots__/phone-input-custom-flags__mobile-snap.png
  vrt/config.js
  vrt/tests.vrt.js
Labels: bugfix

#2379 fix: support home, end, pageup, pagedwown in calendar key navigation
  src/datepicker/__tests__/calendar.e2e.js
  src/datepicker/calendar.js
  src/datepicker/utils/index.js
Labels: bugfix

#2412 Release v9.25.0
  package.json
Labels: release

#2394 docs(blog): introducing react-view
  documentation-site/components/markdown-elements.js
  documentation-site/components/posts.js
  documentation-site/components/yard/editor.tsx
  documentation-site/components/yard/index.tsx
  documentation-site/pages/blog/index.mdx
  documentation-site/pages/blog/introducing-react-view/index.mdx
  documentation-site/pages/blog/introducing-react-view/live-editor.js
  documentation-site/pages/blog/introducing-react-view/metadata.json
Labels: docs

#2413 fix(package): update module field to relative path
  package.json
Labels: bugfix

#2414 feat(form-control): propagate disabled, error and positive props
  src/form-control/__tests__/form-control.scenario.js
  src/form-control/form-control.js
  vrt/__image_snapshots__/form-control__dark-snap.png
  vrt/__image_snapshots__/form-control__desktop-snap.png
  vrt/__image_snapshots__/form-control__mobile-snap.png
Labels: feature

#2384 fix(data-table): fills available horizontal space
  .storybook/config.js
  src/data-table/data-table.js
  vrt/__image_snapshots__/data-table-batch-action__dark-snap.png
  vrt/__image_snapshots__/data-table-batch-action__desktop-snap.png
  vrt/__image_snapshots__/data-table-batch-action__mobile-snap.png
  vrt/__image_snapshots__/data-table-collection-of-objects__dark-snap.png
  vrt/__image_snapshots__/data-table-collection-of-objects__desktop-snap.png
  vrt/__image_snapshots__/data-table-collection-of-objects__mobile-snap.png
  vrt/__image_snapshots__/data-table-columns__dark-snap.png
  vrt/__image_snapshots__/data-table-columns__desktop-snap.png
  vrt/__image_snapshots__/data-table-columns__mobile-snap.png
  vrt/__image_snapshots__/data-table-row-height__dark-snap.png
  vrt/__image_snapshots__/data-table-row-height__desktop-snap.png
  vrt/__image_snapshots__/data-table-row-height__mobile-snap.png
Labels: bugfix

#2416 Release v9.26.0
  package.json
Labels: release

#2397 feat(select): separate overrides for SearchIcon and SearchIconContainer
  documentation-site/components/yard/config/select.ts
  src/select/__tests__/stateful-select.test.js
  src/select/index.d.ts
  src/select/index.js
  src/select/select-component.js
  src/select/styled-components.js
  src/select/types.js
Labels: feature

#2420 docs(layer): update to include detail on using BaseProvider overrides
  documentation-site/pages/components/layer.mdx
Labels: docs

#2421 chore(project): upgrade react-range to 1.4.4
  package.json
  yarn.lock
Labels: greenkeeping

#2423 feat(icon): allow icons to use colors from theme
  src/icon/styled-components.js
Labels: feature

#2419 feat(typography): rename components to match Base typography style names
  src/typography/index.d.ts
  src/typography/index.js
Labels: feature

#2425 Release v9.27.0
  package.json
Labels: release

#2426 docs(popover): fix typo in ref-handling description
  documentation-site/examples/popover/ref-handling.js
Labels: docs

#2428 docs(select): update select placeholders with working examples
  documentation-site/components/yard/config/select.ts
Labels: docs

#2432 fix(modal): fix autofocus deprecation
  src/modal/__tests__/__snapshots__/modal.test.js.snap
  src/modal/modal.js
  src/modal/types.js
Labels: bugfix

#2429 fix(select): use quotation marks for creatable options
  src/select/__tests__/select.e2e.js
  src/select/select-component.js
Labels: bugfix

#2431 fix(select): merge StatefulMenu overrides
  src/select/__tests__/dropdown.test.js
  src/select/dropdown.js
Labels: bugfix

#2437 docs(setup): fix styletron section
  documentation-site/pages/getting-started/setup.mdx
Labels: docs

#2427 docs(roadmap): update
  documentation-site/pages/discover-more/roadmap.mdx
Labels: docs

#2438 fix(masked-input): do not pass the prop positive
  src/input/masked-input.js
Labels: bugfix

#2446 Release v9.28.0
  package.json
Labels: release

#2443 fix(datepicker): improve readability in calendar scenario
  src/datepicker/__tests__/stateful-calendar-overrides.scenario.js
  vrt/__image_snapshots__/stateful-calendar-overrides__dark-snap.png
Labels: bugfix

#2445 fix(modal): properly render modal rtl vrt
  src/modal/__tests__/modal.scenario.js
Labels: bugfix

#2450 fix(modal): correct an error in effect hook
  src/modal/__tests__/modal.scenario.js
  vrt/__image_snapshots__/modal-rtl__desktop-snap.png
  vrt/__image_snapshots__/modal-rtl__mobile-snap.png
Labels: bugfix

#2447 fix(datepicker): removes vertical space in chrome
  src/datepicker/datepicker.js
Labels: bugfix

#2452 Release v9.28.1
  package.json
Labels: release

#2456 chore(select): clean up default filter
  src/select/utils/default-filter-options.js
Labels: bugfix

#2424 fix(datepicker): clicking scroll in month selection closes datepicker
  src/datepicker/calendar-header.js
  src/datepicker/calendar.js
  src/datepicker/datepicker.js
  src/datepicker/types.js
Labels: bugfix

#2458 feat(menu): option groups
  documentation-site/examples/menu/grouped.js
  documentation-site/examples/menu/grouped.tsx
  documentation-site/pages/components/menu.mdx
  src/menu/__tests__/menu-grouped-items.e2e.js
  src/menu/__tests__/menu-grouped-items.scenario.js
  src/menu/__tests__/menu-virtualized.scenario.js
  src/menu/index.d.ts
  src/menu/menu.js
  src/menu/stateful-container.js
  src/menu/styled-components.js
  src/menu/types.js
  vrt/__image_snapshots__/menu-grouped-items__dark-snap.png
  vrt/__image_snapshots__/menu-grouped-items__desktop-snap.png
  vrt/__image_snapshots__/menu-grouped-items__mobile-snap.png
  vrt/__image_snapshots__/menu-virtualized__dark-snap.png
  vrt/__image_snapshots__/menu-virtualized__desktop-snap.png
  vrt/__image_snapshots__/menu-virtualized__mobile-snap.png
Labels: feature

#2463 fix(select): apply input style overrides to autosizer
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/__tests__/select-search-single-fontsize.scenario.js
  src/select/autosize-input.js
  vrt/__image_snapshots__/select-search-single-fontsize__dark-snap.png
  vrt/__image_snapshots__/select-search-single-fontsize__desktop-snap.png
  vrt/__image_snapshots__/select-search-single-fontsize__mobile-snap.png
  vrt/__image_snapshots__/select-search-single-fontsize__showsAllText-snap.png
  vrt/config.js
Labels: bugfix

#2466 Release v9.29.0
  package.json
Labels: release

#2467 fix(dnd-list): handle interactive elements better, role checkbox
  package.json
  src/checkbox/checkbox.js
  yarn.lock
Labels: bugfix

#2468 fix(deploy): now version pinning
  Dockerfile
  documentation-site/components/version-selector.js
Labels: bugfix

#2454 feat(theme): refactor themes
  src/styles/types.js
  src/themes/creator.js
  src/themes/dark-theme-colors.js
  src/themes/dark-theme-with-move.js
  src/themes/dark-theme.js
  src/themes/dark-theme/color-component-tokens.js
  src/themes/dark-theme/color-deprecated-semantic-tokens.js
  src/themes/dark-theme/color-tokens.js
  src/themes/dark-theme/dark-theme.js
  src/themes/index.js
  src/themes/light-theme-with-move.js
  src/themes/light-theme/color-component-tokens.js
  src/themes/light-theme/color-deprecated-semantic-tokens.js
  src/themes/light-theme/color-tokens.js
  src/themes/light-theme/light-theme.js
  src/themes/move-theme/dark-theme-with-move.js
  src/themes/move-theme/light-theme-with-move.js
  src/themes/move-theme/typography.js
  src/themes/shared/animation.js
  src/themes/shared/borders.js
  src/themes/shared/breakpoints.js
  src/themes/shared/grid.js
  src/themes/shared/lighting.js
  src/themes/shared/media-query.js
  src/themes/shared/sizing.js
  src/themes/shared/typography.js
  src/themes/types.js
  src/utils/deep-merge.js
Labels: feature

#2480 feat(radio): add transition to RadioMarkOuter
  src/radio/styled-components.js
Labels: feature

#2481 fix(radio): radio's onChange prop typescript definition
  documentation-site/examples/radio/basic.tsx
  documentation-site/examples/radio/error.tsx
  documentation-site/examples/radio/horizontal-align.tsx
  documentation-site/examples/radio/overrides.tsx
  src/radio/index.d.ts
Labels: bugfix

#2474 feat(theme): add semantic color tokens
  documentation-site/components/markdown-elements.js
  documentation-site/components/theming-values/colors.js
  documentation-site/pages/components/tokens.mdx
  documentation-site/pages/guides/theming.mdx
  packages/baseui-codemods/src/v9-theme-scale.js
  packages/baseui-codemods/src/v9-theme-scale.test.js
  src/index.js
  src/styles/index.js
  src/styles/types.js
  src/theme.ts
  src/themes/creator.js
  src/themes/dark-theme/color-semantic-tokens.js
  src/themes/dark-theme/color-tokens.js
  src/themes/dark-theme/dark-theme.js
  src/themes/light-theme/color-semantic-tokens.js
  src/themes/light-theme/color-tokens.js
  src/themes/light-theme/light-theme.js
  src/themes/types.js
  src/tokens/colors.js
  src/tokens/index.d.ts
  src/tokens/index.js
  src/tokens/types.js
  vrt/__image_snapshots__/checkbox-toggle-round__dark-snap.png
  vrt/__image_snapshots__/datepickers-color-states__dark-snap.png
  vrt/__image_snapshots__/datepickers-color-states__desktop-snap.png
  vrt/__image_snapshots__/datepickers-color-states__mobile-snap.png
  vrt/__image_snapshots__/form-control__dark-snap.png
  vrt/__image_snapshots__/form-control__desktop-snap.png
  vrt/__image_snapshots__/form-control__mobile-snap.png
  vrt/__image_snapshots__/input-rtl__desktop-snap.png
  vrt/__image_snapshots__/input-rtl__mobile-snap.png
  vrt/__image_snapshots__/input-states__dark-snap.png
  vrt/__image_snapshots__/input-states__desktop-snap.png
  vrt/__image_snapshots__/input-states__mobile-snap.png
  vrt/__image_snapshots__/notification__dark-snap.png
  vrt/__image_snapshots__/notification__desktop-snap.png
  vrt/__image_snapshots__/notification__mobile-snap.png
  vrt/__image_snapshots__/pin-code-states__dark-snap.png
  vrt/__image_snapshots__/pin-code-states__desktop-snap.png
  vrt/__image_snapshots__/pin-code-states__mobile-snap.png
  vrt/__image_snapshots__/select-states__dark-snap.png
  vrt/__image_snapshots__/select-states__desktop-snap.png
  vrt/__image_snapshots__/select-states__mobile-snap.png
  vrt/__image_snapshots__/stateful-calendar-overrides__dark-snap.png
  vrt/__image_snapshots__/stateful-calendar-overrides__desktop-snap.png
  vrt/__image_snapshots__/stateful-calendar-overrides__mobile-snap.png
  vrt/__image_snapshots__/table-cells__dark-snap.png
  vrt/__image_snapshots__/table-cells__desktop-snap.png
  vrt/__image_snapshots__/table-cells__mobile-snap.png
  vrt/__image_snapshots__/table-grid-jobs__dark-snap.png
  vrt/__image_snapshots__/table-grid-jobs__desktop-snap.png
  vrt/__image_snapshots__/table-grid-jobs__mobile-snap.png
  vrt/__image_snapshots__/tag-rtl__desktop-snap.png
  vrt/__image_snapshots__/tag-rtl__mobile-snap.png
  vrt/__image_snapshots__/tag__dark-snap.png
  vrt/__image_snapshots__/tag__desktop-snap.png
  vrt/__image_snapshots__/tag__mobile-snap.png
  vrt/__image_snapshots__/toast__dark-snap.png
  vrt/__image_snapshots__/toast__desktop-snap.png
  vrt/__image_snapshots__/toast__mobile-snap.png
Labels: feature

#2485 Change StyledTable overflowX to 'auto'
  src/table/styled-components.js
Labels: bugfix

#2472 fix(modal): handle nested modal overflow reset
  src/modal/__tests__/modal.test.js
  src/modal/modal.js
Labels: bugfix

#2489 docs(sidebar): fix sidebar links
  documentation-site/components/sidebar.js
Labels: docs

#2492 chore(docs): case Datepicker consistently
  documentation-site/examples/datepicker/datepickers-color-states.js
  documentation-site/examples/datepicker/datepickers-color-states.tsx
  documentation-site/pages/components/datepicker.mdx
  src/datepicker/__tests__/datepickers-color-states.scenario.js
  vrt/__image_snapshots__/datepickers-color-states__dark-snap.png
  vrt/__image_snapshots__/datepickers-color-states__desktop-snap.png
  vrt/__image_snapshots__/datepickers-color-states__mobile-snap.png
Labels: docs

#2497 fix(build): do not include import of types in the esm target
  src/accordion/index.js
  src/aspect-ratio-box/index.js
  src/avatar/index.js
  src/block/index.js
  src/breadcrumbs/index.js
  src/button-group/index.js
  src/button/index.js
  src/card/index.js
  src/checkbox/index.js
  src/data-table/index.js
  src/datepicker/index.js
  src/dnd-list/index.js
  src/drawer/index.js
  src/file-uploader/index.js
  src/flex-grid/index.js
  src/form-control/index.js
  src/header-navigation/index.js
  src/heading/index.js
  src/icon/index.js
  src/input/index.js
  src/layer/index.js
  src/list/index.js
  src/menu/index.js
  src/modal/index.js
  src/pagination/index.js
  src/payment-card/index.js
  src/phone-input/index.js
  src/popover/index.js
  src/progress-bar/index.js
  src/progress-steps/index.js
  src/radio/index.js
  src/rating/index.js
  src/select/index.js
  src/side-navigation/index.js
  src/slider/index.js
  src/spinner/index.js
  src/table-semantic/index.js
  src/table/index.js
  src/tag/index.js
  src/template-component/index.js
  src/textarea/index.js
  src/timezonepicker/index.js
  src/toast/index.js
  src/tokens/index.js
  src/tree-view/index.js
Labels: bugfix

#2498 Release v9.30.0
  package.json
Labels: release

#2476 feat(select): enables option groups in dropdown menu
  documentation-site/components/code.js
  documentation-site/examples/select/grouped.js
  documentation-site/examples/select/grouped.tsx
  documentation-site/pages/components/select.mdx
  src/select/__tests__/__snapshots__/dropdown.test.js.snap
  src/select/__tests__/dropdown.test.js
  src/select/__tests__/select-option-group.scenario.js
  src/select/__tests__/select.e2e.js
  src/select/dropdown.js
  src/select/index.d.ts
  src/select/select-component.js
  src/select/types.js
  src/select/utils/index.js
  vrt/__image_snapshots__/select-option-group__dark-snap.png
  vrt/__image_snapshots__/select-option-group__desktop-snap.png
  vrt/__image_snapshots__/select-option-group__mobile-snap.png
  vrt/__image_snapshots__/select-option-group__selectGroupDropdownVisible-snap.png
  vrt/config.js
Labels: feature

#2494 fix(baseprovider) overrides types for baseprovider
  src/index.d.ts
Labels: bugfix

#2499 feat(datepicker): make it clearable
  documentation-site/components/yard/config/datepicker.ts
  src/datepicker/__tests__/datepicker-range.scenario.js
  src/datepicker/datepicker.js
  src/datepicker/index.d.ts
  src/datepicker/types.js
  vrt/__image_snapshots__/datepicker-range__selectedRangeHighlighted-snap.png
Labels: feature

#2493 chore(docs): clean up FlexGrid use cases
  documentation-site/examples/datepicker/datepickers-color-states.js
  documentation-site/examples/datepicker/datepickers-color-states.tsx
  documentation-site/pages/index.js
  src/datepicker/__tests__/datepickers-color-states.scenario.js
  vrt/__image_snapshots__/datepickers-color-states__mobile-snap.png
Labels: docs

#2457 fix(various): do not pass item as prop to styled component
  src/menu/styled-components.js
  src/phone-input/styled-components.js
  src/select/__tests__/dropdown.test.js
  src/side-navigation/styled-components.js
Labels: bugfix

#2484 docs(blog): add post on visual regression tests
  documentation-site/pages/blog/visual-regression-testing/changelog.png
  documentation-site/pages/blog/visual-regression-testing/comparison.png
  documentation-site/pages/blog/visual-regression-testing/examplesnapshot.png
  documentation-site/pages/blog/visual-regression-testing/index.mdx
  documentation-site/pages/blog/visual-regression-testing/left.png
  documentation-site/pages/blog/visual-regression-testing/metadata.json
  documentation-site/pages/blog/visual-regression-testing/mobilemodal.png
  documentation-site/pages/blog/visual-regression-testing/right.png
  documentation-site/pages/blog/visual-regression-testing/swipe.gif
  package.json
  yarn.lock
Labels: docs

#2496 fix(datepicker): fix Datepicker quickSelect
  src/datepicker/__tests__/stateful-datepicker-quick-select.e2e.js
  src/datepicker/calendar.js
Labels: bugfix

#2504 chore(utils): use String.prototype.trim() instead
  src/select/utils/default-filter-options.js
Labels: bugfix, chore

#2505 feat(datepicker): allow for endDate in quickSelectOptions
  documentation-site/components/yard/config/datepicker.ts
  src/datepicker/calendar.js
  src/datepicker/index.d.ts
  src/datepicker/types.js
Labels: feature

#2507 fix(data-table): properly map row data to filter
  src/data-table/filter-menu.js
Labels: bugfix

#2502 Release v9.31.0
  package.json
Labels: release

#2501 fix(datepicker): clearable fix
  documentation-site/components/yard/config/datepicker.ts
  src/datepicker/datepicker.js
  src/datepicker/day.js
Labels: bugfix

#2422 feat(typography): add Base design system typography names to theme
  src/themes/move-theme/typography.js
  src/themes/shared/typography.js
  src/themes/types.js
  src/typography/index.js
Labels: feature

#2508 docs: remove links to cheatsheet when no types available
  documentation-site/components/exports.js
  documentation-site/pages/components/notification.mdx
  documentation-site/pages/components/tooltip.mdx
  documentation-site/pages/components/typography.mdx
Labels: docs

#2495 chore(type): fix type warnings
  package.json
Labels: bugfix

#2509 fix(theme): remove duplicate code
  src/themes/shared/typography.js
Labels: bugfix

#2510 Release v9.32.0
  package.json
Labels: release

#2511 docs: make exports section consistent
  documentation-site/pages/components/aspect-ratio-box.mdx
  documentation-site/pages/components/block.mdx
  documentation-site/pages/components/checkbox.mdx
  documentation-site/pages/components/datepicker.mdx
  documentation-site/pages/components/flex-grid.mdx
  documentation-site/pages/components/heading.mdx
  documentation-site/pages/components/layer.mdx
  documentation-site/pages/components/layout-grid.mdx
  documentation-site/pages/components/link.mdx
  documentation-site/pages/components/pagination.mdx
  documentation-site/pages/components/payment-card.mdx
  documentation-site/pages/components/progress-bar.mdx
  documentation-site/pages/components/radio.mdx
  documentation-site/pages/components/rating.mdx
  documentation-site/pages/components/select.mdx
  documentation-site/pages/components/styled.mdx
  documentation-site/pages/components/table-grid.mdx
  documentation-site/pages/components/table-semantic.mdx
  documentation-site/pages/components/table.mdx
  documentation-site/pages/components/tabs.mdx
  documentation-site/pages/components/tokens.mdx
  documentation-site/pages/components/unstable-a11y.mdx
  documentation-site/pages/components/unstable-data-table.mdx
  documentation-site/pages/components/use-styletron.mdx
  documentation-site/routes.js
Labels: docs

#2515 feat(card): update styles to latest spec
  documentation-site/components/example.js
  documentation-site/pages/index.js
  src/card/styled-components.js
  vrt/__image_snapshots__/card-image-link__dark-snap.png
  vrt/__image_snapshots__/card-image-link__desktop-snap.png
  vrt/__image_snapshots__/card-image-link__mobile-snap.png
  vrt/__image_snapshots__/card-text-only__dark-snap.png
  vrt/__image_snapshots__/card-text-only__desktop-snap.png
  vrt/__image_snapshots__/card-text-only__mobile-snap.png
  vrt/__image_snapshots__/card__dark-snap.png
  vrt/__image_snapshots__/card__desktop-snap.png
  vrt/__image_snapshots__/card__mobile-snap.png
Labels: enhancement, feature

#2518 feat(avatar): allows for specific initials
  src/avatar/__tests__/avatar-custom-initials.scenario.js
  src/avatar/avatar.js
  src/avatar/types.js
  vrt/__image_snapshots__/avatar-custom-initials__dark-snap.png
  vrt/__image_snapshots__/avatar-custom-initials__desktop-snap.png
  vrt/__image_snapshots__/avatar-custom-initials__mobile-snap.png
Labels: feature

#2479 fix(theme): use primary and mono appropriately
  src/themes/dark-theme/color-component-tokens.js
  src/themes/light-theme/color-component-tokens.js
Labels: bugfix

#2520 Release v9.33.0
  package.json
Labels: release

#2514 feat(data-table): controlled row highlight
  src/data-table/__tests__/data-table-extracted-highlight.scenario.js
  src/data-table/data-table.js
  src/data-table/stateful-container.js
  src/data-table/stateful-data-table.js
  src/data-table/types.js
  vrt/__image_snapshots__/data-table-extracted-highlight__controlledRowHighlightIndex-snap.png
  vrt/__image_snapshots__/data-table-extracted-highlight__dark-snap.png
  vrt/__image_snapshots__/data-table-extracted-highlight__desktop-snap.png
  vrt/__image_snapshots__/data-table-extracted-highlight__mobile-snap.png
  vrt/__image_snapshots__/data-table-extracted-highlight__rowHighlightScrollsTableDown-snap.png
  vrt/__image_snapshots__/data-table-extracted-highlight__rowHighlightScrollsTableUp-snap.png
  vrt/config.js
Labels: feature

#2522 fix(docs): rename Datepicker basic usage example
  documentation-site/pages/components/datepicker.mdx
Labels: docs

#2523 chore(yard): avoid React warning
  documentation-site/components/yard/props-tooltip.tsx
Labels: docs

#2524 fix(input): avoid passing clearable prop to base-input
  src/input/input.js
  src/input/masked-input.js
  vrt/__image_snapshots__/datepicker-range__selectedRangeHighlighted-snap.png
  vrt/__image_snapshots__/datepicker-rtl__calendarOpened-snap.png
  vrt/__image_snapshots__/datepicker__setDateHighlighted-snap.png
Labels: bugfix

#2526 Revert "docs(sidebar): fix sidebar links (#2489)"
  documentation-site/components/sidebar.js
Labels: docs

#2530 docs(button-group): add relevant theme keys
  documentation-site/components/yard/config/button-group.ts
Labels: bugfix

#2531 docs(sidebar): clean up sidebar links
  documentation-site/components/sidebar.js
Labels: bugfix

#2528 feat(checkbox): update visuals
  documentation-site/examples/checkbox/indeterminate.js
  documentation-site/examples/checkbox/indeterminate.tsx
  src/checkbox/__tests__/checkbox-indeterminate.scenario.js
  src/checkbox/__tests__/checkbox-states.scenario.js
  src/checkbox/__tests__/checkbox.e2e.js
  src/checkbox/styled-components.js
  src/radio/__tests__/radio-states.scenario.js
  src/radio/styled-components.js
  src/themes/dark-theme/color-component-tokens.js
  src/themes/light-theme/color-component-tokens.js
  src/themes/shared/borders.js
  vrt/__image_snapshots__/checkbox-indeterminate__dark-snap.png
  vrt/__image_snapshots__/checkbox-indeterminate__desktop-snap.png
  vrt/__image_snapshots__/checkbox-indeterminate__mobile-snap.png
  vrt/__image_snapshots__/checkbox-rtl__desktop-snap.png
  vrt/__image_snapshots__/checkbox-rtl__mobile-snap.png
  vrt/__image_snapshots__/checkbox-states__dark-snap.png
  vrt/__image_snapshots__/checkbox-states__desktop-snap.png
  vrt/__image_snapshots__/checkbox-states__mobile-snap.png
  vrt/__image_snapshots__/checkbox-unlabeled__dark-snap.png
  vrt/__image_snapshots__/checkbox-unlabeled__desktop-snap.png
  vrt/__image_snapshots__/checkbox-unlabeled__mobile-snap.png
  vrt/__image_snapshots__/checkbox__dark-snap.png
  vrt/__image_snapshots__/checkbox__desktop-snap.png
  vrt/__image_snapshots__/checkbox__mobile-snap.png
  vrt/__image_snapshots__/data-table-batch-action__dark-snap.png
  vrt/__image_snapshots__/data-table-batch-action__desktop-snap.png
  vrt/__image_snapshots__/data-table-batch-action__mobile-snap.png
  vrt/__image_snapshots__/data-table-categorical-column__dark-snap.png
  vrt/__image_snapshots__/data-table-categorical-column__desktop-snap.png
  vrt/__image_snapshots__/data-table-categorical-column__mobile-snap.png
  vrt/__image_snapshots__/data-table-extracted-filters__dark-snap.png
  vrt/__image_snapshots__/data-table-extracted-filters__desktop-snap.png
  vrt/__image_snapshots__/data-table-extracted-filters__mobile-snap.png
  vrt/__image_snapshots__/data-table-row-height__dark-snap.png
  vrt/__image_snapshots__/data-table-row-height__desktop-snap.png
  vrt/__image_snapshots__/data-table-row-height__mobile-snap.png
  vrt/__image_snapshots__/form-control__dark-snap.png
  vrt/__image_snapshots__/form-control__desktop-snap.png
  vrt/__image_snapshots__/form-control__mobile-snap.png
  vrt/__image_snapshots__/radio-rtl__desktop-snap.png
  vrt/__image_snapshots__/radio-rtl__mobile-snap.png
  vrt/__image_snapshots__/radio-states__dark-snap.png
  vrt/__image_snapshots__/radio-states__desktop-snap.png
  vrt/__image_snapshots__/radio-states__mobile-snap.png
  vrt/__image_snapshots__/radio__dark-snap.png
  vrt/__image_snapshots__/radio__desktop-snap.png
  vrt/__image_snapshots__/radio__mobile-snap.png
Labels: enhancement, feature

#2534 fix(table): style filter icon when overriden
  src/table/filter.js
  src/table/styled-components.js
Labels: bugfix

#2535 feat(spinner): add new div based spinner
  documentation-site/examples/spinner/next-basic.js
  documentation-site/examples/spinner/next-basic.tsx
  documentation-site/examples/spinner/next-custom.js
  documentation-site/examples/spinner/next-custom.tsx
  documentation-site/examples/spinner/next-size.js
  documentation-site/examples/spinner/next-size.tsx
  documentation-site/pages/components/spinner.mdx
  src/spinner/__tests__/spinner-next.scenario.js
  src/spinner/constants.js
  src/spinner/index.d.ts
  src/spinner/index.js
  src/spinner/spinner.js
  src/spinner/styled-components.js
  src/spinner/types.js
  vrt/__image_snapshots__/spinner-next__dark-snap.png
  vrt/__image_snapshots__/spinner-next__desktop-snap.png
  vrt/__image_snapshots__/spinner-next__mobile-snap.png
Labels: feature

#2538 fix(select): respond to async options updates
  src/select/__tests__/select-async-options.scenario.js
  src/select/__tests__/select.e2e.js
  src/select/select-component.js
  vrt/__image_snapshots__/select-async-options__dark-snap.png
  vrt/__image_snapshots__/select-async-options__desktop-snap.png
  vrt/__image_snapshots__/select-async-options__mobile-snap.png
Labels: bugfix

#2542 fix: backfill some missing checks for dev
  src/accordion/accordion.js
  src/checkbox/checkbox.js
  src/phone-input/utils.js
  src/spinner/spinner.js
Labels: bugfix

#2545 docs(sidebar): fix link missing href
  documentation-site/components/sidebar.js
Labels: docs

#2543 docs(spinner): update example to use withstyle rather than $style
  documentation-site/examples/spinner/next-custom.js
  documentation-site/examples/spinner/next-custom.tsx
  documentation-site/pages/components/spinner.mdx
Labels: docs

#2541 Release v9.34.0
  package.json
Labels: release
