Repository uber/baseweb, pull requests merged in 2020-06, with the labels that each got.

#3383 fix(combobox): test name attr to remove credit card suggestion on docs site
  documentation-site/examples/combobox/async-options.js
  documentation-site/examples/combobox/async-options.tsx
  documentation-site/examples/combobox/filtered-options.js
  documentation-site/examples/combobox/filtered-options.tsx
  documentation-site/examples/combobox/input-overrides.js
  documentation-site/examples/combobox/input-overrides.tsx
  documentation-site/examples/combobox/replacement-node.js
  documentation-site/examples/combobox/replacement-node.tsx
  src/combobox/combobox.js
  src/combobox/index.d.ts
  src/combobox/types.js
Labels: bugfix

#3384 fix(accordion): fixed a typo in the deprecation warning
  src/accordion/accordion.js
Labels: bugfix, docs

#3385 feat(combobox): include option in change handler params if suggestion is selected
  src/combobox/__tests__/combobox.test.js
  src/combobox/combobox.js
  src/combobox/index.d.ts
  src/combobox/types.js
Labels: feature

#3386 fix(combobox): handles clear value
  src/combobox/__tests__/combobox.test.js
  src/combobox/combobox.js
Labels: bugfix

#3387 Release v9.81.0
  package.json
Labels: release

#3377 fix(datepicker): handle selected time preservation when date is changed
  src/datepicker/__tests__/datepicker-range.e2e.js
  src/datepicker/__tests__/datepicker-range.scenario.js
  src/datepicker/calendar.js
  src/datepicker/types.js
  vrt/__image_snapshots__/datepicker-range__selectedRangeHighlighted-snap.png
Labels: bugfix

#3388 Release v9.81.1
  package.json
Labels: release

#3395 docs(select): add select example with async options
  documentation-site/examples/select/async-options.js
  documentation-site/examples/select/async-options.tsx
  documentation-site/pages/components/select.mdx
Labels: docs

#3391 feat(combobox): add flag to disable autocomplete
  documentation-site/components/yard/config/combobox.ts
  src/combobox/__tests__/combobox-autocomplete-false.scenario.js
  src/combobox/__tests__/combobox.test.js
  src/combobox/combobox.js
  src/combobox/index.d.ts
  src/combobox/types.js
  vrt/__image_snapshots__/combobox-autocomplete-false__dark-snap.png
  vrt/__image_snapshots__/combobox-autocomplete-false__desktop-snap.png
  vrt/__image_snapshots__/combobox-autocomplete-false__mobile-snap.png
Labels: feature

#3389 fix(fileuploader): remove spinner when error message is shown
  src/file-uploader/file-uploader.js
Labels: bugfix

#3396 feat(table-semantic): expose col, colIndex, row, rowIndex in table
  src/table-semantic/__tests__/table.test.js
  src/table-semantic/table.js
Labels: feature

#3399 Release v9.82.0
  package.json
Labels: release

#3403 docs(menu): add noResultsMsg to yard
  documentation-site/components/yard/config/menu.ts
Labels: docs

#3405 chore(project): start using buildkit
  .buildkite/pipeline.yml
Labels: bugfix, chore

#3402 Add a controlRef prop to <Select/>
  documentation-site/examples/select/focus.js
  documentation-site/examples/select/focus.tsx
  documentation-site/pages/components/select.mdx
  src/select/__tests__/select.test.js
  src/select/index.d.ts
  src/select/select-component.js
  src/select/types.js
Labels: feature

#3397 feat(link): add underline animation option
  documentation-site/components/yard/config/link.ts
  documentation-site/pages/components/link.mdx
  src/breadcrumbs/__tests__/breadcrumbs.test.js
  src/link/index.js
  src/link/styled-components.js
  vrt/__image_snapshots__/breadcrumbs-pseudo__dark-snap.png
  vrt/__image_snapshots__/breadcrumbs-pseudo__desktop-snap.png
  vrt/__image_snapshots__/breadcrumbs-pseudo__mobile-snap.png
  vrt/__image_snapshots__/breadcrumbs-rtl__desktop-snap.png
  vrt/__image_snapshots__/breadcrumbs-rtl__mobile-snap.png
  vrt/__image_snapshots__/breadcrumbs__dark-snap.png
  vrt/__image_snapshots__/breadcrumbs__desktop-snap.png
  vrt/__image_snapshots__/breadcrumbs__mobile-snap.png
  vrt/__image_snapshots__/card-image-link__dark-snap.png
  vrt/__image_snapshots__/card-image-link__desktop-snap.png
  vrt/__image_snapshots__/card-image-link__mobile-snap.png
  vrt/__image_snapshots__/data-table-collection-of-objects__dark-snap.png
  vrt/__image_snapshots__/data-table-collection-of-objects__desktop-snap.png
  vrt/__image_snapshots__/data-table-collection-of-objects__mobile-snap.png
  vrt/__image_snapshots__/header-navigation__dark-snap.png
  vrt/__image_snapshots__/header-navigation__desktop-snap.png
  vrt/__image_snapshots__/header-navigation__mobile-snap.png
  vrt/__image_snapshots__/link__dark-snap.png
  vrt/__image_snapshots__/link__desktop-snap.png
  vrt/__image_snapshots__/link__mobile-snap.png
  vrt/__image_snapshots__/table-grid-jobs__dark-snap.png
  vrt/__image_snapshots__/table-grid-jobs__desktop-snap.png
  vrt/__image_snapshots__/table-grid-jobs__mobile-snap.png
  vrt/__image_snapshots__/table-grid-records__dark-snap.png
  vrt/__image_snapshots__/table-grid-records__desktop-snap.png
  vrt/__image_snapshots__/table-grid-records__mobile-snap.png
Labels: feature

#3418 docs(roadmap): update to reflect that we are not doing a major this year
  documentation-site/pages/discover-more/roadmap.mdx
Labels: docs

#3417 fix(eslint-plugin-baseui): add baseui prefix for recommended config
  packages/eslint-plugin-baseui/src/index.js
Labels: bugfix

#3409 fix(countries): update Macedonia to North Macedonia
  src/phone-input/constants.js
Labels: bugfix

#3415 fix(datepicker): split range datepickers update from text input
  documentation-site/examples/datepicker/composed-range-pickers.js
  documentation-site/examples/datepicker/composed-range-pickers.tsx
  src/datepicker/__tests__/datepickers-composed-range.e2e.js
  src/datepicker/__tests__/datepickers-composed-range.scenario.js
  src/datepicker/datepicker.js
  src/datepicker/index.d.ts
  src/datepicker/types.js
  vrt/__image_snapshots__/datepickers-composed-range__dark-snap.png
  vrt/__image_snapshots__/datepickers-composed-range__desktop-snap.png
  vrt/__image_snapshots__/datepickers-composed-range__mobile-snap.png
Labels: bugfix

#3420 fix(timepicker): handle update value to null
  src/timepicker/__tests__/timepicker.test.js
  src/timepicker/timepicker.js
Labels: bugfix

#3421 Release v9.84.0
  package.json
Labels: release

#3424 Release v9.84.1
  package.json
Labels: release

#3426 fix(button): fix spinner's size to include border
  src/button/styled-components.js
Labels: bugfix

#3434 docs(nav): rename tab to tabs
  documentation-site/routes.js
Labels: docs

#3436 fix(vercel): do not deploy to test.baseweb
  now.json
Labels: bugfix

#3440 docs(typo): understanding overrides
  documentation-site/pages/guides/understanding-overrides.mdx
Labels: docs

#3446 feat(select): add alias for tag override
  documentation-site/components/yard/config/select.ts
  documentation-site/examples/select/overriden-tag.js
  documentation-site/examples/select/overriden-tag.tsx
  documentation-site/pages/guides/understanding-overrides.mdx
  src/select/__tests__/stateful-select.test.js
  src/select/index.d.ts
  src/select/multi-value.js
  src/select/select-component.js
  src/select/types.js
Labels: feature

#3441 feat(radio):add unique id
  src/radio/__tests__/radio.e2e.js
  src/radio/__tests__/radio.scenario.js
  src/radio/radiogroup.js
  src/radio/types.js
  vrt/__image_snapshots__/radio-rtl__desktop-snap.png
  vrt/__image_snapshots__/radio-rtl__mobile-snap.png
  vrt/__image_snapshots__/radio__dark-snap.png
  vrt/__image_snapshots__/radio__desktop-snap.png
  vrt/__image_snapshots__/radio__mobile-snap.png
Labels: bugfix

#3445 docs: refactor nav and search
  documentation-site/components/header-navigation.js
  documentation-site/components/search.js
Labels: docs

#3447 Release v9.85.0
  package.json
Labels: release
