Repository uber/baseweb, pull requests merged in 2020-12, with the labels that each got.

#3960 docs(blog): Nested Overrides Playground
  documentation-site/components/header-navigation.js
  documentation-site/components/table-of-contents.js
  documentation-site/components/yard/index.tsx
  documentation-site/components/yard/styled-components.tsx
  documentation-site/components/yard/types.ts
  documentation-site/pages/blog/nested-overrides-playground/index.mdx
  documentation-site/pages/blog/nested-overrides-playground/live-editor-tag.js
  documentation-site/pages/blog/nested-overrides-playground/live-editor.js
  documentation-site/pages/blog/nested-overrides-playground/metadata.json
Labels: docs

#3961 fix(yard): nested override ignore nulls
  documentation-site/components/yard/config/tag.ts
  documentation-site/components/yard/custom-props.ts
  documentation-site/pages/blog/nested-overrides-playground/live-editor-tag.js
  documentation-site/pages/blog/nested-overrides-playground/live-editor.js
Labels: docs

#3965 added returnFocus prop to Table Filter
  src/table/filter.js
  src/table/index.d.ts
  src/table/types.js
Labels: feature

#3971 fix(data-table): forward resizeable prop through
  src/data-table/stateful-data-table.js
Labels: bugfix

#3970 fix(select): onblur handles unmount
  src/select/__tests__/select-unmount-blur.e2e.js
  src/select/__tests__/select-unmount-blur.scenario.js
  src/select/select-component.js
  vrt/__image_snapshots__/select-unmount-blur__dark-snap.png
  vrt/__image_snapshots__/select-unmount-blur__desktop-snap.png
  vrt/__image_snapshots__/select-unmount-blur__mobile-snap.png
Labels: bugfix

#3976 fix(data-table): query handles non-alphanumeric characters
  src/data-table/__tests__/text-search.test.js
  src/data-table/text-search.js
Labels: bugfix

#3983 Use uniform margins for buttons in groups
  src/button-group/button-group.js
  vrt/__image_snapshots__/button-group-checkbox__dark-snap.png
  vrt/__image_snapshots__/button-group-checkbox__desktop-snap.png
  vrt/__image_snapshots__/button-group-checkbox__mobile-snap.png
  vrt/__image_snapshots__/button-group-disabled__dark-snap.png
  vrt/__image_snapshots__/button-group-disabled__desktop-snap.png
  vrt/__image_snapshots__/button-group-disabled__mobile-snap.png
  vrt/__image_snapshots__/button-group-pill__dark-snap.png
  vrt/__image_snapshots__/button-group-pill__desktop-snap.png
  vrt/__image_snapshots__/button-group-pill__mobile-snap.png
  vrt/__image_snapshots__/button-group-radio__dark-snap.png
  vrt/__image_snapshots__/button-group-radio__desktop-snap.png
  vrt/__image_snapshots__/button-group-radio__mobile-snap.png
  vrt/__image_snapshots__/button-group-sizes__dark-snap.png
  vrt/__image_snapshots__/button-group-sizes__desktop-snap.png
  vrt/__image_snapshots__/button-group-sizes__mobile-snap.png
  vrt/__image_snapshots__/data-table-categorical-column__dark-snap.png
  vrt/__image_snapshots__/data-table-categorical-column__desktop-snap.png
  vrt/__image_snapshots__/data-table-categorical-column__mobile-snap.png
  vrt/__image_snapshots__/data-table-extracted-filters__dark-snap.png
  vrt/__image_snapshots__/data-table-extracted-filters__desktop-snap.png
  vrt/__image_snapshots__/data-table-extracted-filters__mobile-snap.png
Labels: bugfix

#3987 fix(data-table): increate max tag width
  src/data-table/stateful-data-table.js
  vrt/__image_snapshots__/data-table-initial-filters__dark-snap.png
  vrt/__image_snapshots__/data-table-initial-filters__desktop-snap.png
Labels: bugfix

#3994 fix(ts): handle ts error in example
  documentation-site/examples/table-semantic/alternating.tsx
Labels: bugfix

#4004 Fix password input toggle button (eye) visibility when shrunk in Firefox
  src/input/styled-components.js
Labels: bugfix
