Repository uber/baseweb, pull requests merged in 2020-08, with the labels that each got.

#3570 feat(select): add config to clear input value on backspace
  documentation-site/components/yard/config/select.ts
  src/select/__tests__/select-backspace-behavior.e2e.js
  src/select/__tests__/select-backspace-behavior.scenario.js
  src/select/index.d.ts
  src/select/select-component.js
  src/select/types.js
  vrt/__image_snapshots__/select-backspace-behavior__dark-snap.png
  vrt/__image_snapshots__/select-backspace-behavior__desktop-snap.png
  vrt/__image_snapshots__/select-backspace-behavior__mobile-snap.png
Labels: feature

#3574 feat(button-group): add pill shape support
  documentation-site/components/yard/config/button-group.ts
  src/button-group/__tests__/button-group-pill.scenario.js
  src/button-group/button-group.js
  src/button-group/index.d.ts
  src/button-group/index.js
  vrt/__image_snapshots__/button-group-pill__dark-snap.png
  vrt/__image_snapshots__/button-group-pill__desktop-snap.png
  vrt/__image_snapshots__/button-group-pill__mobile-snap.png
Labels: feature

#3576 fix: updated locale typescript types to match the flow types
  src/locale.ts
Labels: bugfix

#3560 feat(menu): add type-ahead function for menu
  src/menu/__tests__/menu.e2e.js
  src/menu/constants.js
  src/menu/index.d.ts
  src/menu/stateful-container.js
  src/menu/types.js
  src/select/dropdown.js
Labels: enhancement, feature

#3581 feat(button): update selected style for secondary
  src/button/styled-components.js
  vrt/__image_snapshots__/button-group-checkbox__dark-snap.png
  vrt/__image_snapshots__/button-group-checkbox__desktop-snap.png
  vrt/__image_snapshots__/button-group-checkbox__mobile-snap.png
  vrt/__image_snapshots__/button-group-overrides__dark-snap.png
  vrt/__image_snapshots__/button-group-overrides__desktop-snap.png
  vrt/__image_snapshots__/button-group-overrides__mobile-snap.png
  vrt/__image_snapshots__/button-group-pill__dark-snap.png
  vrt/__image_snapshots__/button-group-pill__desktop-snap.png
  vrt/__image_snapshots__/button-group-pill__mobile-snap.png
  vrt/__image_snapshots__/button-group-radio__dark-snap.png
  vrt/__image_snapshots__/button-group-radio__desktop-snap.png
  vrt/__image_snapshots__/button-group-radio__mobile-snap.png
  vrt/__image_snapshots__/button-rtl__desktop-snap.png
  vrt/__image_snapshots__/button-rtl__mobile-snap.png
  vrt/__image_snapshots__/button__dark-snap.png
  vrt/__image_snapshots__/button__desktop-snap.png
  vrt/__image_snapshots__/button__mobile-snap.png
  vrt/__image_snapshots__/data-table-datetime-column__dark-snap.png
  vrt/__image_snapshots__/data-table-datetime-column__desktop-snap.png
  vrt/__image_snapshots__/data-table-datetime-column__mobile-snap.png
  vrt/__image_snapshots__/data-table-numerical-column__dark-snap.png
  vrt/__image_snapshots__/data-table-numerical-column__desktop-snap.png
  vrt/__image_snapshots__/data-table-numerical-column__mobile-snap.png
Labels: feature

#3583 Release v9.92.0
  package.json
Labels: release

#3587 docs(toast): update example to show button left aligned
  documentation-site/components/yard/config/toast.ts
Labels: docs

#3588 fix(button-group): add 1px spacing between buttons
  src/button-group/button-group.js
  vrt/__image_snapshots__/button-group-checkbox__dark-snap.png
  vrt/__image_snapshots__/button-group-checkbox__desktop-snap.png
  vrt/__image_snapshots__/button-group-checkbox__mobile-snap.png
  vrt/__image_snapshots__/button-group-radio__dark-snap.png
  vrt/__image_snapshots__/button-group-radio__desktop-snap.png
  vrt/__image_snapshots__/button-group-radio__mobile-snap.png
  vrt/__image_snapshots__/button-group-sizes__dark-snap.png
  vrt/__image_snapshots__/button-group-sizes__desktop-snap.png
  vrt/__image_snapshots__/button-group-sizes__mobile-snap.png
  vrt/__image_snapshots__/data-table-categorical-column__dark-snap.png
  vrt/__image_snapshots__/data-table-categorical-column__desktop-snap.png
  vrt/__image_snapshots__/data-table-categorical-column__mobile-snap.png
  vrt/__image_snapshots__/data-table-extracted-filters__dark-snap.png
  vrt/__image_snapshots__/data-table-extracted-filters__desktop-snap.png
Labels: bugfix

#3573 build(alpha-test): sets up alpha testing on uber applications
  .buildkite/pipeline.yml
  docker-compose.yml
  scripts/alpha-test-web-code.js
  scripts/publish-stable-release.js
  scripts/publish-to-npm.js
Labels: bugfix, chore

#3585 feat(modal): update design to remove horizontal line
  src/modal/__tests__/__snapshots__/modal.test.js.snap
  src/modal/__tests__/modal.test.js
  src/modal/styled-components.js
  vrt/__image_snapshots__/modal-rtl__desktop-snap.png
  vrt/__image_snapshots__/modal-rtl__mobile-snap.png
  vrt/__image_snapshots__/modal-uncloseable__dark-snap.png
  vrt/__image_snapshots__/modal-uncloseable__desktop-snap.png
  vrt/__image_snapshots__/modal-uncloseable__mobile-snap.png
  vrt/__image_snapshots__/modal__dark-snap.png
  vrt/__image_snapshots__/modal__desktop-snap.png
  vrt/__image_snapshots__/modal__mobile-snap.png
  vrt/__image_snapshots__/select-in-modal__selectDropdownVisible-snap.png
Labels: feature

#3591 Release v9.93.0
  package.json
Labels: release

#3594 fix(build): correct eslint publish command
  scripts/alpha-test-web-code.js
  scripts/publish-to-npm.js
Labels: bugfix

#3595 fix(build): reads alpha version correctly
  scripts/alpha-test-web-code.js
Labels: bugfix

#3590 feat(combobox): open listbox on focus
  src/combobox/__tests__/combobox-autocomplete-false.scenario.js
  src/combobox/__tests__/combobox-disabled.scenario.js
  src/combobox/__tests__/combobox-form-control.scenario.js
  src/combobox/__tests__/combobox-form.scenario.js
  src/combobox/__tests__/combobox-overrides.scenario.js
  src/combobox/__tests__/combobox-replacement-node.scenario.js
  src/combobox/__tests__/combobox-search.scenario.js
  src/combobox/__tests__/combobox-sizes.scenario.js
  src/combobox/__tests__/combobox.scenario.js
  src/combobox/__tests__/combobox.test.js
  src/combobox/combobox.js
Labels: feature

#3599 fix(alpha-test): fail the bk job if web-code ci fails
  scripts/alpha-test-web-code.js
Labels: bugfix

#3569 feat(tree): add type-ahead for tree
  src/tree-view/__tests__/tree-view.e2e.js
  src/tree-view/__tests__/utils.test.js
  src/tree-view/tree-view.js
  src/tree-view/utils.js
Labels: enhancement, feature

#3598 fix: toast children flow type
  src/toast/types.js
Labels: bugfix

#3602 fix(publish): corrects eslint publish
  scripts/publish-to-npm.js
Labels: bugfix

#3600 docs(deployments): add info on how the doc site is deployed
  DEPLOYMENTS.md
Labels: docs

#3604 fix(alpha-publish): eslint-plugin has no dist
  scripts/publish-to-npm.js
Labels: bugfix

#3596 feat(progress-bar): add size prop
  documentation-site/components/yard/config/progress-bar.ts
  src/progress-bar/__tests__/__snapshots__/progressbar.test.js.snap
  src/progress-bar/__tests__/progressbar.scenario.js
  src/progress-bar/constants.js
  src/progress-bar/index.d.ts
  src/progress-bar/index.js
  src/progress-bar/progressbar.js
  src/progress-bar/styled-components.js
  src/progress-bar/types.js
  vrt/__image_snapshots__/progressbar__dark-snap.png
  vrt/__image_snapshots__/progressbar__desktop-snap.png
  vrt/__image_snapshots__/progressbar__mobile-snap.png
Labels: feature

#3607 fix(select):avoid no foucs when index out of range
  src/menu/constants.js
  src/menu/index.d.ts
  src/menu/stateful-container.js
  src/select/__tests__/select.e2e.js
Labels: bugfix

#3617 fix(docs): improve stackblitz label
  documentation-site/components/example.js
  documentation-site/components/yard/action-buttons.tsx
Labels: bugfix

#3612 fix(popover): add warning if popover anchor does not forward ref
  src/popover/popover.js
Labels: bugfix

#3613 feat(input): add max-length prop to top-level
  documentation-site/components/yard/config/input.ts
  src/input/__tests__/__snapshots__/base-input.test.js.snap
  src/input/__tests__/__snapshots__/input.test.js.snap
  src/input/__tests__/__snapshots__/masked-input.test.js.snap
  src/input/base-input.js
  src/input/types.js
  src/pin-code/pin-code.js
  src/textarea/__tests__/__snapshots__/textarea.test.js.snap
Labels: feature

#3616 fix(docs): improve i18n docs
  documentation-site/pages/guides/internationalization.mdx
Labels: bugfix, docs

#3618 feat(progress-bar): add stepped progress-bar option
  documentation-site/components/yard/config/progress-bar.ts
  src/progress-bar/__tests__/__snapshots__/progressbar.test.js.snap
  src/progress-bar/__tests__/progressbar.scenario.js
  src/progress-bar/index.d.ts
  src/progress-bar/index.js
  src/progress-bar/progressbar.js
  src/progress-bar/styled-components.js
  src/progress-bar/types.js
  vrt/__image_snapshots__/progressbar__dark-snap.png
  vrt/__image_snapshots__/progressbar__desktop-snap.png
  vrt/__image_snapshots__/progressbar__mobile-snap.png
Labels: feature

#3620 feat(block): add className prop to block TS def
  src/block/index.d.ts
Labels: feature

#3592 feat(list): add overrides to list item label
  component-sizes.json
  src/list/__tests__/list-item-overrides.scenario.js
  src/list/list-item-label.js
  src/list/styled-components.js
  src/list/types.js
  vrt/__image_snapshots__/list-item-overrides__dark-snap.png
  vrt/__image_snapshots__/list-item-overrides__desktop-snap.png
  vrt/__image_snapshots__/list-item-overrides__mobile-snap.png
Labels: feature

#3606 feat(combobx): adds example for slack-like behavior
  src/combobox/__tests__/combobox-inline-text-search.scenario.js
  vrt/__image_snapshots__/combobox-inline-text-search__dark-snap.png
  vrt/__image_snapshots__/combobox-inline-text-search__desktop-snap.png
  vrt/__image_snapshots__/combobox-inline-text-search__mobile-snap.png
Labels: feature

#3610 feat(modal): adds ability to disable focusLock in modal(#3609)
  documentation-site/components/yard/config/modal.ts
  src/modal/index.d.ts
  src/modal/modal.js
  src/modal/types.js
Labels: bugfix

#3624 Release v9.94.0
  package.json
Labels: release

#3629 fix(theme): add missing core spacing sizes
  documentation-site/pages/guides/theming.mdx
  packages/baseweb-vscode-extension/src/App.tsx
  src/theme.ts
  src/themes/shared/sizing.js
  src/themes/types.js
Labels: bugfix

#3636 feat(combobox): adds support for id attribute
  documentation-site/components/yard/config/combobox.ts
  src/combobox/__tests__/combobox-form-control.scenario.js
  src/combobox/combobox.js
  src/combobox/index.d.ts
  src/combobox/types.js
Labels: feature

#3635 feat(form-control): adds htmlFor support
  documentation-site/components/yard/config/form-control.ts
  src/form-control/__tests__/form-control-id.scenario.js
  src/form-control/form-control.js
  src/form-control/index.d.ts
  src/form-control/types.js
  vrt/__image_snapshots__/form-control-id__dark-snap.png
  vrt/__image_snapshots__/form-control-id__desktop-snap.png
  vrt/__image_snapshots__/form-control-id__mobile-snap.png
Labels: feature

#3632 fix(tabs-motion): handle conditional tabs
  src/tabs-motion/__tests__/tabs-motion-conditional.scenario.js
  src/tabs-motion/__tests__/tabs-motion.e2e.js
  src/tabs-motion/tabs.js
  vrt/config.js
Labels: bugfix

#3637 Release v9.95.0
  package.json
Labels: release

#3640 fix(deploy): proper error handling
  scripts/publish-to-npm.js
Labels: bugfix

#3641 fix(publish): eslint package should have access to the npmrc too
  scripts/publish-to-npm.js
Labels: bugfix

#3652 fix(datepicker): use short weekday format for calendar header
  src/datepicker/__tests__/datepicker-i18n-chinese.scenario.js
  src/datepicker/__tests__/utils.test.js
  src/datepicker/utils/date-helpers.js
  vrt/__image_snapshots__/datepicker-i18n-chinese__dark-snap.png
  vrt/__image_snapshots__/datepicker-i18n-chinese__desktop-snap.png
  vrt/__image_snapshots__/datepicker-i18n-chinese__mobile-snap.png
Labels: bugfix

#3657 fix(tabs): add Tab to top-level overrides types
  documentation-site/examples/tabs/overrides.js
  documentation-site/examples/tabs/overrides.tsx
  src/tabs/index.d.ts
  src/tabs/types.js
Labels: bugfix

#3631 fix(menu):avoid listening to doc
  src/menu/__tests__/menu-propagation.scenario.js
  src/menu/__tests__/menu.e2e.js
  src/menu/index.d.ts
  src/menu/menu.js
  src/menu/stateful-container.js
  src/menu/types.js
  src/select/dropdown.js
  src/select/index.d.ts
  src/select/select-component.js
  src/select/types.js
  vrt/__image_snapshots__/menu-propagation__dark-snap.png
  vrt/__image_snapshots__/menu-propagation__desktop-snap.png
  vrt/__image_snapshots__/menu-propagation__mobile-snap.png
Labels: bugfix

#3684 chore: remove nadiia from codeowners
  .github/CODEOWNERS
Labels: greenkeeping

#3625 feat(file-uploader): update file-uploader per its design spec
  src/file-uploader/__tests__/file-uploader-post-drop.scenario.js
  src/file-uploader/__tests__/file-uploader-pre-drop.scenario.js
  src/file-uploader/__tests__/file-uploader.test.js
  src/file-uploader/file-uploader.js
  src/file-uploader/locale.js
  src/file-uploader/styled-components.js
  src/themes/light-theme/color-component-tokens.js
  vrt/__image_snapshots__/file-uploader-disabled__dark-snap.png
  vrt/__image_snapshots__/file-uploader-disabled__desktop-snap.png
  vrt/__image_snapshots__/file-uploader-disabled__mobile-snap.png
  vrt/__image_snapshots__/file-uploader-error__dark-snap.png
  vrt/__image_snapshots__/file-uploader-error__desktop-snap.png
  vrt/__image_snapshots__/file-uploader-error__mobile-snap.png
  vrt/__image_snapshots__/file-uploader-post-drop__dark-snap.png
  vrt/__image_snapshots__/file-uploader-post-drop__desktop-snap.png
  vrt/__image_snapshots__/file-uploader-post-drop__mobile-snap.png
  vrt/__image_snapshots__/file-uploader-pre-drop__dark-snap.png
  vrt/__image_snapshots__/file-uploader-pre-drop__desktop-snap.png
  vrt/__image_snapshots__/file-uploader-pre-drop__mobile-snap.png
  vrt/__image_snapshots__/file-uploader-progress-bar__dark-snap.png
  vrt/__image_snapshots__/file-uploader-progress-bar__desktop-snap.png
  vrt/__image_snapshots__/file-uploader-progress-bar__mobile-snap.png
  vrt/__image_snapshots__/file-uploader-spinner__dark-snap.png
  vrt/__image_snapshots__/file-uploader-spinner__desktop-snap.png
  vrt/__image_snapshots__/file-uploader-spinner__mobile-snap.png
  vrt/__image_snapshots__/file-uploader__dark-snap.png
  vrt/__image_snapshots__/file-uploader__desktop-snap.png
  vrt/__image_snapshots__/file-uploader__mobile-snap.png
Labels: feature

#3691 docs: fix default values for payment card examples
  documentation-site/components/yard/config/payment-card.ts
  documentation-site/examples/payment-card/controlled.js
  documentation-site/examples/payment-card/controlled.tsx
  documentation-site/examples/payment-card/form.js
  documentation-site/examples/payment-card/form.tsx
Labels: docs

#3630 fix(input): add step definition to number input
  src/input/__tests__/__snapshots__/base-input.test.js.snap
  src/input/__tests__/__snapshots__/input.test.js.snap
  src/input/__tests__/__snapshots__/masked-input.test.js.snap
  src/input/base-input.js
  src/input/index.d.ts
  src/input/types.js
  src/textarea/__tests__/__snapshots__/textarea.test.js.snap
Labels: bugfix

#3701 docs(combobox): fix yard focus and blur handlers
  documentation-site/components/yard/config/combobox.ts
Labels: docs

#3710 fix(app-nav-bar): add data-baseweb attr
  src/app-nav-bar/app-nav-bar.js
Labels: enhancement
