Repository uber/baseweb, pull requests merged in 2020-05, with the labels that each got.

#3287 fix: bump react-range
  package.json
  yarn.lock
Labels: bugfix

#3289 Release v9.73.2
  package.json
Labels: release

#3288 feat(popover): accept event handlers on stateful similar to stateless
  src/datepicker/__tests__/datepicker-keyboard-nav.e2e.js
  src/popover/__tests__/__snapshots__/stateful-container.test.js.snap
  src/popover/__tests__/stateful-container.test.js
  src/popover/popover.js
  src/popover/stateful-container.js
  src/popover/types.js
Labels: feature

#3291 fix(button-group): remove duplicate definition
  src/button-group/index.d.ts
Labels: bugfix

#3293 chore(.github): PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: docs

#3294 fix(button): make .d.ts reflect that it's uses forwardRef
  documentation-site/examples/pin-code/completion.tsx
  src/button/__tests__/button.test.js
  src/button/index.d.ts
Labels: bugfix

#3296 fix(toast): don't reset animateOutCompleteTimer when toast dismissed
  src/toast/__tests__/toast.test.js
  src/toast/toast.js
Labels: bugfix

#3305 fix(tab): spread overrides for tabs too
  src/tabs/__tests__/__snapshots__/stateful-tabs.test.js.snap
  src/tabs/tabs.js
Labels: bugfix

#3306 docs(toast): adding new example for toast component
  documentation-site/examples/toast/toast-close-from-outside.js
  documentation-site/examples/toast/toast-close-from-outside.tsx
  documentation-site/pages/components/toast.mdx
Labels: docs

#3309 feat(side-nav): add disabled prop to items
  documentation-site/components/yard/config/side-nav.ts
  src/side-navigation/__tests__/nav.scenario.js
  src/side-navigation/index.d.ts
  src/side-navigation/nav-item.js
  src/side-navigation/nav.js
  src/side-navigation/styled-components.js
  src/side-navigation/types.js
  vrt/__image_snapshots__/nav-rtl__desktop-snap.png
  vrt/__image_snapshots__/nav-rtl__mobile-snap.png
  vrt/__image_snapshots__/nav__dark-snap.png
  vrt/__image_snapshots__/nav__desktop-snap.png
  vrt/__image_snapshots__/nav__mobile-snap.png
Labels: feature

#3312 chore(side-nav): small cleanup in the styled-components
  src/side-navigation/styled-components.js
Labels: bugfix

#3313 Release v9.75.0
  package.json
Labels: release

#3315 chore: bump react-range
  package.json
  yarn.lock
Labels: bugfix

#3316 Release v9.75.1
  package.json
Labels: release

#3245 feat(app-nav-bar): add horizontal subnav
  documentation-site/examples/app-nav-bar/basic.js
  documentation-site/examples/app-nav-bar/basic.tsx
  src/app-nav-bar/__tests__/app-nav-bar.scenario.js
  src/app-nav-bar/app-nav-bar.js
  src/app-nav-bar/constants.js
  src/app-nav-bar/index.d.ts
  src/app-nav-bar/index.js
  src/app-nav-bar/logo.js
  src/app-nav-bar/main-menu-item.js
  src/app-nav-bar/rfc.md
  src/app-nav-bar/secondary-menu.js
  src/app-nav-bar/styled-components.js
  src/app-nav-bar/types.js
  src/app-nav-bar/user-menu/user-menu.js
  vrt/__image_snapshots__/app-nav-bar__dark-snap.png
  vrt/__image_snapshots__/app-nav-bar__desktop-snap.png
  vrt/__image_snapshots__/app-nav-bar__mobile-snap.png
  vrt/__image_snapshots__/app-nav-bar__openedMenu-snap.png
Labels: feature

#3310 docs: figma
  .gitignore
  docker-compose.yml
  documentation-site/components/guidelines/render.js
  documentation-site/env-config.js
  documentation-site/pages/_app.js
  documentation-site/pages/_document.js
  documentation-site/pages/guidelines/[node].js
  documentation-site/pages/guidelines/index.js
  package.json
  yarn.lock
Labels: docs

#3318 fix(release): cleans up the release notes
  scripts/github-release.js
Labels: bugfix

#3317 fix(menu): use disabled value that comes from getRequiredItemProps
  src/menu/__tests__/stateful-container.test.js
  src/menu/stateful-container.js
Labels: bugfix

#3323 docs(adopters): add sprinklr
  documentation-site/pages/index.js
  documentation-site/static/images/extensis-logo.png
  documentation-site/static/images/sprinklr-logo.png
Labels: docs

#3326 chore(deps): update react-range
  package.json
  yarn.lock
Labels: bugfix

#3325 Release v9.76.0
  package.json
Labels: release

#3324 fix: call focus on treeItemRefs if ref is not null
  src/tree-view/tree-view.js
Labels: bugfix

#3327 docs(list): fix List example
  documentation-site/components/yard/config/list-item.ts
Labels: docs

#3321 feat(layers): expose layers context
  src/layer/index.js
Labels: feature

#3328 fix(combobox): adds vrt interaction
  vrt/__image_snapshots__/combobox-overrides__listboxOpen-snap.png
  vrt/__image_snapshots__/combobox__listboxOpen-snap.png
  vrt/config.js
Labels: bugfix

#3335 docs: update theming page with primitive colors
  documentation-site/pages/guides/theming.mdx
Labels: docs

#3329 fix(side-navigation): avoid setting href if disabled
  src/side-navigation/nav-item.js
Labels: bugfix

#3338 docs: add env variable info
  CONTRIBUTING.md
Labels: docs

#3337 feat(toast): accept 'closeable' prop on ToasterContainer
  src/toast/__tests__/toaster.scenario.js
  src/toast/toaster.js
  src/toast/types.js
Labels: feature

#3331 docs: use stackblitz for code examples
  .github/ISSUE_TEMPLATE/1.bug.md
  documentation-site/components/const.js
  documentation-site/components/example.js
  documentation-site/components/hooks.js
  documentation-site/components/yard/action-buttons.tsx
  documentation-site/pages/components/layout-grid.mdx
  flow-typed/npm/react-codesandboxer_vx.x.x.js
  package.json
  yarn.lock
Labels: docs

#3308 fix(ts): fix some TS errors
  src/app-nav-bar/index.d.ts
  src/button-group/index.d.ts
  src/pagination/index.d.ts
Labels: bugfix

#3339 build: remove mergify
  .mergify.yml
Labels: build/tooling, greenkeeping

#3342 docs: update examples with prefilled arrays
  documentation-site/examples/list/menu-adapter.js
  documentation-site/examples/list/menu-adapter.tsx
  documentation-site/examples/menu/profile.js
  documentation-site/examples/menu/profile.tsx
  documentation-site/examples/menu/virtual-list.js
  documentation-site/examples/menu/virtual-list.tsx
  documentation-site/examples/table/filter.js
  documentation-site/examples/table/filter.tsx
  documentation-site/examples/table/pagination.js
  documentation-site/examples/table/pagination.tsx
Labels: docs

#3340 fix(list): update list-item styles to spec
  documentation-site/examples/list/artwork-sizes.js
  documentation-site/examples/list/artwork-sizes.tsx
  src/list/__tests__/list-item-artwork-sizes.scenario.js
  src/list/index.d.ts
  src/list/list-item.js
  src/list/styled-components.js
  src/list/types.js
  src/list/utils.js
  vrt/__image_snapshots__/app-nav-bar__openedMenu-snap.png
  vrt/__image_snapshots__/list-item-artwork-sizes__dark-snap.png
  vrt/__image_snapshots__/list-item-artwork-sizes__desktop-snap.png
  vrt/__image_snapshots__/list-item-artwork-sizes__mobile-snap.png
  vrt/__image_snapshots__/list-item-menu-adapter__dark-snap.png
  vrt/__image_snapshots__/list-item-menu-adapter__desktop-snap.png
  vrt/__image_snapshots__/list-item-menu-adapter__mobile-snap.png
  vrt/__image_snapshots__/list-item__dark-snap.png
  vrt/__image_snapshots__/list-item__desktop-snap.png
  vrt/__image_snapshots__/list-item__mobile-snap.png
Labels: bugfix

#3344 Release v9.78.0
  package.json
Labels: release

#3346 docs(textarea): fix shared props crash
  documentation-site/components/yard/config/textarea.ts
  documentation-site/components/yard/override.tsx
  vrt/__image_snapshots__/drawer-rtl__desktop-snap.png
  vrt/__image_snapshots__/drawer-rtl__mobile-snap.png
  vrt/__image_snapshots__/drawer-select__dark-snap.png
  vrt/__image_snapshots__/drawer-select__desktop-snap.png
  vrt/__image_snapshots__/drawer-select__mobile-snap.png
  vrt/__image_snapshots__/drawer-select__selectDropdownVisible-snap.png
  vrt/__image_snapshots__/drawer__dark-snap.png
  vrt/__image_snapshots__/drawer__desktop-snap.png
  vrt/__image_snapshots__/drawer__mobile-snap.png
Labels: docs

#3350 feat(tree-view): export TreeLabelInteractable component for wrapping interactable tree node labels
  documentation-site/examples/tree-view/interactable.js
  documentation-site/examples/tree-view/interactable.tsx
  documentation-site/pages/components/tree-view.mdx
  src/tree-view/__tests__/tree-view-interactable.scenario.js
  src/tree-view/__tests__/tree-view.e2e.js
  src/tree-view/index.d.ts
  src/tree-view/index.js
  src/tree-view/styled-components.js
  src/tree-view/tree-label-interactable.js
  src/tree-view/tree-node.js
  vrt/__image_snapshots__/tree-view-interactable__dark-snap.png
  vrt/__image_snapshots__/tree-view-interactable__desktop-snap.png
  vrt/__image_snapshots__/tree-view-interactable__mobile-snap.png
Labels: feature

#3355 chore(project): update to next@9.4
  .gitignore
  documentation-site/components/meta-favicons.js
  documentation-site/env-config.js
  documentation-site/pages/_document.js
  documentation-site/pages/blog/getting-started-with-base-web/index.mdx
  documentation-site/pages/blog/getting-started-with-styletron/index.mdx
  documentation-site/pages/blog/responsive-web/index.mdx
  documentation-site/pages/blog/responsive-web/metadata.json
  documentation-site/pages/blog/vs-code-extension/metadata.json
  documentation-site/pages/guides/understanding-overrides.mdx
  documentation-site/pages/index.js
  documentation-site/public/android-chrome-192x192.png
  documentation-site/public/apple-touch-icon.png
  documentation-site/public/browserconfig.xml
  documentation-site/public/favicon-16x16.png
  documentation-site/public/favicon-32x32.png
  documentation-site/public/favicon.ico
  documentation-site/public/fonts.css
  documentation-site/public/images/banzaicloud-logo.png
  documentation-site/public/images/blog/getting-started-with-base-web/base-web.svg
  documentation-site/public/images/blog/getting-started-with-base-web/foundation.png
  documentation-site/public/images/blog/getting-started-with-base-web/input-with-cta.png
  documentation-site/public/images/blog/getting-started-with-base-web/mockup.png
  documentation-site/public/images/blog/getting-started-with-base-web/result.png
  documentation-site/public/images/blog/getting-started-with-base-web/strength-meter.gif
  documentation-site/public/images/blog/getting-started-with-base-web/styled.png
  documentation-site/public/images/blog/getting-started-with-styletron/fancy-button.gif
  documentation-site/public/images/blog/getting-started-with-styletron/themed-buttons.gif
  documentation-site/public/images/blog/responsive-web/responsive-shipper-tools.svg
  documentation-site/public/images/blog/vs-code-extension/vscodelogo.png
  documentation-site/public/images/broadcom-logo.png
  documentation-site/public/images/cadre-logo.png
  documentation-site/public/images/everbase-logo.png
  documentation-site/public/images/extensis-logo.png
  documentation-site/public/images/react-view-overrides.png
  documentation-site/public/images/sprinklr-logo.png
  documentation-site/public/images/streamlit-logo.png
  documentation-site/public/images/uber-logo.png
  documentation-site/public/images/uptime-logo.png
  documentation-site/public/mstile-150x150.png
  documentation-site/public/safari-pinned-tab.svg
  documentation-site/public/site.webmanifest
  package.json
  yarn.lock
Labels: chore, greenkeeping

#3360 docs(getting-started): copy improvements
  documentation-site/pages/getting-started/learn.mdx
  documentation-site/pages/getting-started/setup.mdx
Labels: docs

#3363 fix(tree-view): ensure nothing is rendered in treeview if data is empty
  src/tree-view/tree-view.js
Labels: bugfix

#3359 docs(bedrock): remove references to bedrock from public documentation
  documentation-site/pages/getting-started/setup.mdx
Labels: docs

#3364 Release v9.79.0
  package.json
Labels: release

#3370 fix(datepicker): consistent export names
  src/datepicker/index.js
Labels: bugfix

#3371 fix(datepicker): propagate new casing everywhere
  documentation-site/components/yard/config/datepicker.ts
  documentation-site/examples/datepicker/composed-range-pickers.js
  documentation-site/examples/datepicker/composed-range-pickers.tsx
  documentation-site/examples/datepicker/composed-single-pickers.js
  documentation-site/examples/datepicker/composed-single-pickers.tsx
  documentation-site/examples/datepicker/datepicker-with-timezone.js
  documentation-site/examples/datepicker/datepicker-with-timezone.tsx
  documentation-site/examples/datepicker/datepickers-color-states.js
  documentation-site/examples/datepicker/datepickers-color-states.tsx
  documentation-site/examples/datepicker/in-popover.js
  documentation-site/examples/datepicker/in-popover.tsx
  documentation-site/examples/datepicker/nested-override.js
  documentation-site/examples/datepicker/nested-override.tsx
  src/datepicker/index.d.ts
  src/datepicker/index.js
Labels: bugfix

#3372 Release v9.80.0
  package.json
Labels: release

#3365 fix(app-nav-bar): pass a str to Avatar, no drawer menu if no menu items
  src/app-nav-bar/app-nav-bar.js
  src/app-nav-bar/mobile-menu/mobile-nav-menu.js
  src/app-nav-bar/user-menu/user-menu.js
  src/app-nav-bar/user-menu/user-profile-tile.js
Labels: bugfix

#3374 docs: color tokens reorg
  src/tokens/colors.js
Labels: docs

#3375 Release v9.80.1
  package.json
Labels: release

#3378 docs(progress-bar): remove infinite example
  documentation-site/examples/progress-bar/infinite.js
  documentation-site/examples/progress-bar/infinite.tsx
  documentation-site/pages/components/progress-bar.mdx
Labels: docs

#3373 docs: fix ie errors
  documentation-site/components/code-icon.js
  documentation-site/components/search.js
  documentation-site/components/yard/index.tsx
  documentation-site/next.config.js
  package.json
  yarn.lock
Labels: docs

#3381 Release v9.80.2
  package.json
Labels: release
