Repository uber/baseweb, pull requests merged in 2020-04, with the labels that each got.

#3151 Release v9.67.1
  package.json
Labels: release

#3152 docs: add a note about Gatsby setup
  documentation-site/pages/getting-started/setup.mdx
Labels: docs

#3153 fix(overrides): hoc pattern implementation
  src/accordion/__tests__/__snapshots__/accordion.test.js.snap
  src/accordion/__tests__/__snapshots__/panel.test.js.snap
  src/aspect-ratio-box/__tests__/__snapshots__/aspect-ratio-box-body.test.js.snap
  src/aspect-ratio-box/__tests__/__snapshots__/aspect-ratio-box.test.js.snap
  src/block/__tests__/__snapshots__/block.test.js.snap
  src/drawer/__tests__/__snapshots__/drawer.test.js.snap
  src/flex-grid/__tests__/__snapshots__/flex-grid-item.test.js.snap
  src/flex-grid/__tests__/__snapshots__/flex-grid.test.js.snap
  src/header-navigation/__tests__/__snapshots__/header-navigation.test.js.snap
  src/heading/__tests__/__snapshots__/heading.test.js.snap
  src/helpers/__tests__/override.scenario.js
  src/helpers/__tests__/override.test.js
  src/helpers/override.js
  src/input/__tests__/__snapshots__/base-input.test.js.snap
  src/input/__tests__/__snapshots__/input.test.js.snap
  src/input/__tests__/__snapshots__/masked-input.test.js.snap
  src/modal/__tests__/__snapshots__/modal.test.js.snap
  src/popover/__tests__/__snapshots__/popover.test.js.snap
  src/progress-bar/__tests__/__snapshots__/progressbar.test.js.snap
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/styles/__mocks__/styled.js
  src/tabs/__tests__/__snapshots__/stateful-tabs.test.js.snap
  src/tag/__tests__/__snapshots__/tag.test.js.snap
  src/test/expect-to-have-style-rule.js
  src/test/test-framework-setup.js
  src/textarea/__tests__/__snapshots__/textarea.test.js.snap
  vrt/__image_snapshots__/override__dark-snap.png
  vrt/__image_snapshots__/override__desktop-snap.png
  vrt/__image_snapshots__/override__mobile-snap.png
Labels: bugfix, refactor

#2968 feat(timepicker): Swappable date libraries
  flow-typed/npm/moment_v2.x.x.js
  package.json
  src/data-table/column-datetime.js
  src/datepicker/utils/date-fns-adapter.js
  src/datepicker/utils/date-helpers.js
  src/datepicker/utils/types.js
  src/timepicker/__tests__/time-picker.e2e.js
  src/timepicker/__tests__/time-picker.scenario.js
  src/timepicker/__tests__/timepicker.test.js
  src/timepicker/timepicker.js
  src/timepicker/types.js
  vrt/__image_snapshots__/time-picker__dark-snap.png
  vrt/__image_snapshots__/time-picker__desktop-snap.png
  vrt/__image_snapshots__/time-picker__mobile-snap.png
  yarn.lock
Labels: feature

#3167 Update typography for radio and checkbox labels
  src/checkbox/styled-components.js
  src/radio/styled-components.js
  vrt/__image_snapshots__/checkbox-indeterminate__dark-snap.png
  vrt/__image_snapshots__/checkbox-indeterminate__desktop-snap.png
  vrt/__image_snapshots__/checkbox-indeterminate__mobile-snap.png
  vrt/__image_snapshots__/checkbox-rtl__desktop-snap.png
  vrt/__image_snapshots__/checkbox-rtl__mobile-snap.png
  vrt/__image_snapshots__/checkbox-states__dark-snap.png
  vrt/__image_snapshots__/checkbox-states__desktop-snap.png
  vrt/__image_snapshots__/checkbox-states__mobile-snap.png
  vrt/__image_snapshots__/checkbox-toggle-round__dark-snap.png
  vrt/__image_snapshots__/checkbox-toggle-round__desktop-snap.png
  vrt/__image_snapshots__/checkbox-toggle-round__mobile-snap.png
  vrt/__image_snapshots__/checkbox-toggle__dark-snap.png
  vrt/__image_snapshots__/checkbox-toggle__desktop-snap.png
  vrt/__image_snapshots__/checkbox-toggle__mobile-snap.png
  vrt/__image_snapshots__/checkbox__dark-snap.png
  vrt/__image_snapshots__/checkbox__desktop-snap.png
  vrt/__image_snapshots__/checkbox__mobile-snap.png
  vrt/__image_snapshots__/data-table-categorical-column__dark-snap.png
  vrt/__image_snapshots__/data-table-categorical-column__desktop-snap.png
  vrt/__image_snapshots__/data-table-categorical-column__mobile-snap.png
  vrt/__image_snapshots__/data-table-datetime-column__dark-snap.png
  vrt/__image_snapshots__/data-table-datetime-column__desktop-snap.png
  vrt/__image_snapshots__/data-table-datetime-column__mobile-snap.png
  vrt/__image_snapshots__/data-table-extracted-filters__dark-snap.png
  vrt/__image_snapshots__/data-table-extracted-filters__desktop-snap.png
  vrt/__image_snapshots__/data-table-extracted-filters__mobile-snap.png
  vrt/__image_snapshots__/data-table-numerical-column__dark-snap.png
  vrt/__image_snapshots__/data-table-numerical-column__desktop-snap.png
  vrt/__image_snapshots__/data-table-numerical-column__mobile-snap.png
  vrt/__image_snapshots__/form-control__dark-snap.png
  vrt/__image_snapshots__/form-control__desktop-snap.png
  vrt/__image_snapshots__/form-control__mobile-snap.png
Labels: bugfix

#3160 feat(themes): add createDarkTheme & createLightTheme
  documentation-site/pages/guides/theming.mdx
  src/index.d.ts
  src/themes/creator.js
  src/themes/dark-theme/create-dark-theme.js
  src/themes/dark-theme/dark-theme.js
  src/themes/dark-theme/primitives.js
  src/themes/index.js
  src/themes/light-theme/create-light-theme.js
  src/themes/light-theme/light-theme.js
  src/themes/light-theme/primitives.js
  src/themes/shared/typography.js
Labels: feature

#3169 docs(progress-bar): add successValue
  documentation-site/components/yard/config/progress-bar.ts
Labels: docs

#3170 fix(spinner): fix incorrect dom attribute warning
  src/file-uploader/file-uploader.js
  src/select/select-component.js
  src/spinner/spinner.js
  src/spinner/types.js
Labels: bugfix

#3177 fix(overrides): warn if using function props
  src/helpers/overrides.js
Labels: bugfix

#3176 fix(override): removes hoc
  src/helpers/__tests__/override-avoid-remount.scenario.js
  src/helpers/__tests__/override.test.js
  src/helpers/override.js
  vrt/__image_snapshots__/override-avoid-remount__dark-snap.png
  vrt/__image_snapshots__/override-avoid-remount__desktop-snap.png
  vrt/__image_snapshots__/override-avoid-remount__mobile-snap.png
Labels: bugfix

#3179 docs(users): add banzaicloud
  documentation-site/pages/index.js
  documentation-site/static/images/banzaicloud-logo.png
Labels: docs

#3175 greenkeeping(ts): fix and update types for tree-view
  documentation-site/examples/tree-view/custom-label.js
  documentation-site/examples/tree-view/label-overrides.js
  src/tree-view/__tests__/utils.test.js
  src/tree-view/index.d.ts
  src/tree-view/stateful-container.js
  src/tree-view/tree-view.js
  src/tree-view/types.js
  src/tree-view/utils.js
Labels: bugfix

#3183 fix(select): dark theme filter text color
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/styled-components.js
  vrt/__image_snapshots__/select__typeToFilter-snap.png
  vrt/config.js
Labels: bugfix

#3186 fix(docs): better responsive knobs
  documentation-site/components/yard/editor.tsx
  documentation-site/components/yard/knobs.tsx
Labels: bugfix

#3165 Release v9.68.0
  package.json
Labels: release

#3189 feat(eslint): add recommended config
  .eslintignore
  .gitignore
  packages/eslint-plugin-baseui/README.md
  packages/eslint-plugin-baseui/__tests__/config.test.js
  packages/eslint-plugin-baseui/__tests__/example-config/.eslintrc.js
  packages/eslint-plugin-baseui/__tests__/example-config/fixture.js
  packages/eslint-plugin-baseui/__tests__/example-config/node_modules/eslint-plugin-baseui/index.js
  packages/eslint-plugin-baseui/__tests__/example-config/node_modules/eslint-plugin-baseui/package.json
  packages/eslint-plugin-baseui/src/index.js
Labels: feature

#3193 fix(vscode): revert longhand properties
  packages/baseweb-vscode-extension/ext-src/coloring.ts
Labels: bugfix

#3180 feat(accordion): add stateless version
  documentation-site/examples/accordion/stateless.js
  documentation-site/examples/accordion/stateless.tsx
  documentation-site/pages/components/accordion.mdx
  src/accordion/__tests__/accordion-controlled.scenario.js
  src/accordion/index.d.ts
  src/accordion/index.js
  src/accordion/stateless-accordion.js
  src/accordion/types.js
  vrt/__image_snapshots__/accordion-controlled__dark-snap.png
  vrt/__image_snapshots__/accordion-controlled__desktop-snap.png
  vrt/__image_snapshots__/accordion-controlled__mobile-snap.png
Labels: feature

#3195 Release v9.69.0
  package.json
Labels: release

#3198 fix(theme): export createDarkTheme and createLightTheme
  src/index.js
Labels: bugfix

#3196 fix(overrides): removes prop generic. now set to any
  documentation-site/examples/file-uploader/_overrides_component.js
  src/accordion/types.js
  src/avatar/types.js
  src/block/types.js
  src/breadcrumbs/types.js
  src/button-group/types.js
  src/button/types.js
  src/card/types.js
  src/checkbox/types.js
  src/datepicker/types.js
  src/dnd-list/types.js
  src/drawer/types.js
  src/file-uploader/types.js
  src/form-control/types.js
  src/header-navigation/types.js
  src/helpers/__tests__/override-avoid-remount.scenario.js
  src/helpers/overrides.js
  src/helpers/types.js
  src/icon/types.js
  src/input/types.js
  src/layer/types.js
  src/layout-grid/types.js
  src/list/types.js
  src/menu/types.js
  src/modal/types.js
  src/pagination/types.js
  src/payment-card/types.js
  src/phone-input/types.js
  src/pin-code/types.js
  src/popover/types.js
  src/progress-bar/types.js
  src/progress-steps/types.js
  src/radio/types.js
  src/rating/types.js
  src/select/types.js
  src/side-navigation/types.js
  src/slider/types.js
  src/spinner/types.js
  src/table-semantic/types.js
  src/table/types.js
  src/tabs/types.js
  src/tag/types.js
  src/template-component/types.js
  src/timepicker/types.js
  src/timezonepicker/types.js
  src/toast/types.js
  src/tree-view/types.js
Labels: bugfix

#3200 fix(codesandbox): module resolution
  package.json
Labels: bugfix, build/tooling, work in progress

#3166 feat(app-nav-bar): initial implementation of the navigation bar
  documentation-site/components/yard/config/app-nav-bar.ts
  documentation-site/examples/app-nav-bar/basic.js
  documentation-site/examples/app-nav-bar/basic.tsx
  documentation-site/pages/components/app-nav-bar.mdx
  documentation-site/routes.js
  src/app-nav-bar/__tests__/app-nav-bar.scenario.js
  src/app-nav-bar/app-nav-bar.js
  src/app-nav-bar/index.d.ts
  src/app-nav-bar/index.js
  src/app-nav-bar/logo.js
  src/app-nav-bar/mobile-menu/mobile-nav-menu-item.js
  src/app-nav-bar/mobile-menu/mobile-nav-menu.js
  src/app-nav-bar/mobile-menu/mobile-nav.js
  src/app-nav-bar/primary-menu-item.js
  src/app-nav-bar/rfc.md
  src/app-nav-bar/styled-components.js
  src/app-nav-bar/types.js
  src/app-nav-bar/user-menu/user-menu-dropdown.js
  src/app-nav-bar/user-menu/user-menu-list-item.js
  src/app-nav-bar/user-menu/user-menu.js
  src/app-nav-bar/user-menu/user-profile-tile.js
  src/list/types.js
  vrt/__image_snapshots__/app-nav-bar__dark-snap.png
  vrt/__image_snapshots__/app-nav-bar__desktop-snap.png
  vrt/__image_snapshots__/app-nav-bar__mobile-snap.png
  vrt/__image_snapshots__/app-nav-bar__openedMenu-snap.png
  vrt/config.js
Labels: feature

#3207 fix(e2e): add e2e test for datepicker keyboard navigation
  src/datepicker/__tests__/datepicker-keyboard-nav.e2e.js
  src/datepicker/__tests__/datepicker.e2e.js
Labels: bugfix

#3206 fix(docs): render navigation bar example in a layer
  documentation-site/examples/app-nav-bar/basic.js
  documentation-site/examples/app-nav-bar/basic.tsx
Labels: bugfix, docs

#3209 fix(flow): removes unused supression comments
  src/accordion/panel.js
  src/icon/alert.js
  src/icon/arrow-down.js
  src/icon/arrow-left.js
  src/icon/arrow-right.js
  src/icon/arrow-up.js
  src/icon/blank.js
  src/icon/check-indeterminate.js
  src/icon/check.js
  src/icon/chevron-down.js
  src/icon/chevron-left.js
  src/icon/chevron-right.js
  src/icon/chevron-up.js
  src/icon/delete-alt.js
  src/icon/delete.js
  src/icon/filter.js
  src/icon/grab.js
  src/icon/hide.js
  src/icon/icon-template.txt
  src/icon/menu.js
  src/icon/overflow.js
  src/icon/plus.js
  src/icon/search.js
  src/icon/show.js
  src/icon/spinner.js
  src/icon/triangle-down.js
  src/icon/triangle-left.js
  src/icon/triangle-right.js
  src/icon/triangle-up.js
  src/icon/upload.js
  src/popover/__tests__/styled-component.test.js
Labels: bugfix

#3210 feat(table-semantic): expose col, colIndex, row, and rowIndex props
  src/table-semantic/__tests__/table-builder.test.js
  src/table-semantic/styled-components.js
  src/table-semantic/table-builder.js
Labels: feature

#3211 Release v9.70.0
  package.json
Labels: release

#3212 fix(input): adds missing props (pattern and aria-errormessage) to the TS defs
  src/input/index.d.ts
Labels: bugfix

#3202 feat(menu): ability to override Popover
  src/menu/__tests__/maybe-child-menu.test.js
  src/menu/index.d.ts
  src/menu/maybe-child-menu.js
  src/menu/option-list.js
  src/menu/option-profile.js
  src/menu/types.js
Labels: feature

#3171 feat(themes): add animation and easing values
  documentation-site/components/contributors.js
  documentation-site/components/gallery.js
  documentation-site/components/skip-to-content.js
  documentation-site/components/theming/animations.js
  documentation-site/pages/guides/theming.mdx
  src/button/styled-components.js
  src/checkbox/styled-components.js
  src/drawer/__tests__/__snapshots__/drawer.test.js.snap
  src/drawer/styled-components.js
  src/input/styled-components.js
  src/link/styled-components.js
  src/menu/styled-components.js
  src/modal/__tests__/__snapshots__/modal.test.js.snap
  src/modal/styled-components.js
  src/radio/styled-components.js
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/styled-components.js
  src/test/create-mock-theme.js
  src/theme.ts
  src/themes/shared/animation.js
  src/themes/types.js
  src/toast/styled-components.js
Labels: feature

#3215 fix(docs): fix app navigation bar codesandbox example
  documentation-site/examples/app-nav-bar/basic.js
  documentation-site/examples/app-nav-bar/basic.tsx
Labels: bugfix

#3220 chore(project): mergify for renovate
  .mergify.yml
  vrt/__image_snapshots__/datepickers-composed-range__dark-snap.png
  vrt/__image_snapshots__/datepickers-composed-range__desktop-snap.png
  vrt/__image_snapshots__/datepickers-composed-range__mobile-snap.png
  vrt/__image_snapshots__/menu-child-in-popover__dark-snap.png
  vrt/__image_snapshots__/menu-child-in-popover__desktop-snap.png
  vrt/__image_snapshots__/menu-child-in-popover__mobile-snap.png
  vrt/__image_snapshots__/override-avoid-remount__dark-snap.png
  vrt/__image_snapshots__/override-avoid-remount__desktop-snap.png
  vrt/__image_snapshots__/override-avoid-remount__mobile-snap.png
  vrt/__image_snapshots__/popover-focus-loop__dark-snap.png
  vrt/__image_snapshots__/popover-focus-loop__desktop-snap.png
  vrt/__image_snapshots__/popover-focus-loop__mobile-snap.png
  vrt/__image_snapshots__/select-calls-provided-blur__dark-snap.png
  vrt/__image_snapshots__/select-calls-provided-blur__desktop-snap.png
  vrt/__image_snapshots__/select-calls-provided-blur__mobile-snap.png
  vrt/__image_snapshots__/select-click-maintains-focus__dark-snap.png
  vrt/__image_snapshots__/select-click-maintains-focus__desktop-snap.png
  vrt/__image_snapshots__/select-click-maintains-focus__mobile-snap.png
  vrt/__image_snapshots__/timezone-picker__dark-snap.png
  vrt/__image_snapshots__/timezone-picker__desktop-snap.png
  vrt/__image_snapshots__/timezone-picker__mobile-snap.png
Labels: chore, greenkeeping

#3216 fix(button): fix button background timing function
  documentation-site/pages/guides/theming.mdx
  src/button/styled-components.js
  src/theme.ts
  src/themes/shared/animation.js
  src/themes/types.js
Labels: bugfix

#3222 chore(mergify): add auto-merge for RPs
  .mergify.yml
Labels: greenkeeping

#3225 chore(mergify): fix duplication
  .mergify.yml
Labels: bugfix, chore

#3217 feat(slider): allow custom merged labels
  .eslintignore
  package.json
  src/slider/__tests__/slider-custom-label.scenario.js
  src/slider/slider.js
  src/slider/styled-components.js
  src/slider/types.js
  vrt/__image_snapshots__/slider-custom-label__dark-snap.png
  vrt/__image_snapshots__/slider-custom-label__desktop-snap.png
  vrt/__image_snapshots__/slider-custom-label__mobile-snap.png
  vrt/__image_snapshots__/slider-disabled__dark-snap.png
  vrt/__image_snapshots__/slider-range__dark-snap.png
  vrt/__image_snapshots__/slider-step__dark-snap.png
  vrt/__image_snapshots__/slider__dark-snap.png
  yarn.lock
Labels: feature

#3226 chore(mergify): add dependabot
  .mergify.yml
Labels: bugfix, chore

#3223 fix: revert pkg.browser codesandbox hack
  package.json
Labels: bugfix, build/tooling

#3229 Release v9.71.0
  package.json
Labels: release

#3231 fix(docs): recommend better style util packages
  documentation-site/pages/guides/theming.mdx
Labels: bugfix

#3232 docs(website): update logo
  documentation-site/images/base-web-white.svg
  documentation-site/images/base-web.svg
  documentation-site/static/android-chrome-192x192.png
  documentation-site/static/android-chrome-512x512.png
  documentation-site/static/apple-touch-icon.png
  documentation-site/static/favicon-16x16.png
  documentation-site/static/favicon-32x32.png
  documentation-site/static/favicon.ico
  documentation-site/static/site.webmanifest
Labels: docs

#3233 docs: add tabs example with custom keys
  documentation-site/examples/tabs/custom-keys.js
  documentation-site/examples/tabs/custom-keys.tsx
  documentation-site/pages/components/tabs.mdx
Labels: docs

#3227 fix(docs): don't preload move fonts and move the link to the body end so it's not blocking
  documentation-site/pages/_document.js
Labels: bugfix, docs

#3234 fix(docs): add preloaded font type
  documentation-site/pages/_document.js
Labels: bugfix, docs

#3237 fix(megify): name of dependabot
  .mergify.yml
Labels: bugfix

#3236 fix(accordion): replace includes with indexOf for crossbrowser support, docs edits
  documentation-site/examples/accordion/stateful-panel.js
  documentation-site/examples/accordion/stateful-panel.tsx
  documentation-site/examples/accordion/stateless.js
  documentation-site/examples/accordion/stateless.tsx
  documentation-site/pages/components/accordion.mdx
  src/accordion/accordion.js
Labels: bugfix

#3240 fix: display numbered step children when active
  src/progress-steps/__tests__/__snapshots__/numbered-step.test.js.snap
  src/progress-steps/__tests__/numbered-steps.scenario.js
  src/progress-steps/numbered-step.js
  src/progress-steps/types.js
  vrt/__image_snapshots__/numbered-steps__dark-snap.png
  vrt/__image_snapshots__/numbered-steps__desktop-snap.png
  vrt/__image_snapshots__/numbered-steps__mobile-snap.png
Labels: bugfix

#3242 docs: add tooltip example for complex content
  documentation-site/examples/tooltip/stateful-complex-content.js
  documentation-site/examples/tooltip/stateful-complex-content.tsx
  documentation-site/pages/components/tooltip.mdx
  src/tooltip/__tests__/tooltip-complex.scenario.js
  vrt/__image_snapshots__/tooltip-complex__contrast-snap.png
  vrt/__image_snapshots__/tooltip-complex__dark-snap.png
  vrt/__image_snapshots__/tooltip-complex__desktop-snap.png
  vrt/__image_snapshots__/tooltip-complex__mobile-snap.png
  vrt/config.js
Labels: docs

#3248 fix(data-table): reverts expand border in non customizable data-table
  src/data-table/data-table.js
Labels: bugfix

#3251 fix(data-table): avoid sort on select all check click
  src/data-table/__tests__/data-table-batch-action.e2e.js
  src/data-table/header-cell.js
Labels: bugfix

#3249 fix(data-table): ensure columns with sortable is false cannot sort
  src/data-table/__tests__/data-table-columns-not-sortable.e2e.js
  src/data-table/__tests__/data-table-columns-not-sortable.scenario.js
  src/data-table/header-cell.js
  vrt/__image_snapshots__/data-table-columns-not-sortable__dark-snap.png
  vrt/__image_snapshots__/data-table-columns-not-sortable__desktop-snap.png
  vrt/__image_snapshots__/data-table-columns-not-sortable__mobile-snap.png
Labels: bugfix

#3253 feat(checkbox/radio): introduce the error prop
  documentation-site/components/yard/config/checkbox.ts
  documentation-site/components/yard/config/radio.ts
  documentation-site/examples/checkbox/error.js
  documentation-site/examples/checkbox/error.tsx
  documentation-site/examples/radio/error.js
  documentation-site/examples/radio/error.tsx
  src/checkbox/__tests__/checkbox-states.scenario.js
  src/checkbox/__tests__/checkbox-toggle-round.scenario.js
  src/checkbox/__tests__/checkbox.test.js
  src/checkbox/checkbox.js
  src/checkbox/index.d.ts
  src/checkbox/styled-components.js
  src/checkbox/types.js
  src/radio/__tests__/radio-states.scenario.js
  src/radio/index.d.ts
  src/radio/radio.js
  src/radio/radiogroup.js
  src/radio/styled-components.js
  src/radio/types.js
  vrt/__image_snapshots__/checkbox-states__dark-snap.png
  vrt/__image_snapshots__/checkbox-states__desktop-snap.png
  vrt/__image_snapshots__/checkbox-states__mobile-snap.png
Labels: feature

#3257 fix(tests): remove console.log in e2e
  src/toast/__tests__/toast.e2e.js
Labels: bugfix

#3258 fix(checkbox): add console.warn for isError removal in the next major
  src/checkbox/checkbox.js
  src/radio/radio.js
  src/radio/radiogroup.js
Labels: bugfix

#3261 Release v9.72.0
  package.json
Labels: release

#3256 fix(datepicker): prioritize selected date highlight over preset highlight date
  src/datepicker/__tests__/datepicker-keyboard-nav.e2e.js
  src/datepicker/calendar.js
Labels: bugfix

#3269 fix(build): add buildkite job to create github release
  .buildkite/pipeline.yml
  scripts/github-release.js
Labels: bugfix, build/tooling, chore

#3270 fix(menu): fix type checking MENUPROPS in menu
  src/menu/index.d.ts
  src/menu/types.js
Labels: bugfix

#3266 fix(layout-grid): fix ALIGNMENT enum
  src/layout-grid/index.d.ts
Labels: bugfix

#3268 feat(treeview): add rtl support
  src/tree-view/__tests__/tree-view-rtl.scenario.js
  src/tree-view/styled-components.js
  src/tree-view/tree-label.js
  vrt/__image_snapshots__/tree-view-rtl__desktop-snap.png
  vrt/__image_snapshots__/tree-view-rtl__mobile-snap.png
Labels: feature

#3271 docs(button-group): add size to yard
  documentation-site/components/yard/config/button-group.ts
  src/button-group/index.d.ts
  src/button-group/index.js
Labels: docs

#3274 docs(): fix typo on front page
  documentation-site/pages/index.js
Labels: docs

#3264 feat(layout grid): use Context in grid so React.Fragments can be used
  src/layout-grid/__tests__/layout-grid.scenario.js
  src/layout-grid/cell.js
  src/layout-grid/grid.js
  src/layout-grid/index.d.ts
  src/layout-grid/types.js
Labels: enhancement, feature

#3273 Release v9.73.0
  package.json
Labels: release

#3276 Border theme type avoid nullish
  src/styles/__tests__/styled.test.js
  src/themes/types.js
Labels: bugfix

#3278 fix(mergify): now has become vercel
  .mergify.yml
Labels: bugfix, chore

#3279 docs(modal): make cancel button tertiary
  documentation-site/components/yard/config/modal.ts
Labels: docs

#3280 Release v9.73.1
  package.json
Labels: release

#3275 fix(datepicker): inputting a date into input field results in right date
  src/datepicker/__tests__/datepicker.test.js
  src/datepicker/datepicker.js
  src/datepicker/types.js
Labels: bugfix

#3281 docs(modal): update the rest of the examples to use tertiary buttons
  documentation-site/examples/modal/autofocus.js
  documentation-site/examples/modal/autofocus.tsx
  documentation-site/examples/modal/basic.js
  documentation-site/examples/modal/basic.tsx
  documentation-site/examples/modal/nested.js
  documentation-site/examples/modal/nested.tsx
  documentation-site/examples/modal/sized.js
  documentation-site/examples/modal/sized.tsx
Labels: docs

#3282 fix(tag): forwards ref to root element
  src/tag/__tests__/__snapshots__/tag.test.js.snap
  src/tag/__tests__/tag.test.js
  src/tag/tag.js
  src/tag/types.js
Labels: bugfix

#3284 fix: export missing createThemedWithStyle TS type
  src/index.d.ts
Labels: bugfix
