Repository uber/baseweb, pull requests merged in 2020-03, with the labels that each got.

#2956 docs(figma): add to the doc pages
  documentation-site/pages/getting-started/setup.mdx
  documentation-site/pages/index.js
Labels: docs

#2952 docs: fix some ref examples
  documentation-site/examples/input/focus.js
  documentation-site/examples/input/focus.tsx
  documentation-site/examples/layer/basic-tether.js
  documentation-site/examples/layer/basic.js
Labels: bugfix

#2958 test(eslint-plugin): cover vars without init
  packages/eslint-plugin-baseui/__tests__/deprecated-theme-api-test.js
  packages/eslint-plugin-baseui/src/deprecated-theme-api.js
Labels: bugfix

#2947 fix(select): communicate component state to screen reader
  src/menu/__tests__/stateful-container.test.js
  src/menu/index.d.ts
  src/menu/menu.js
  src/menu/stateful-container.js
  src/menu/types.js
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/__tests__/dropdown.test.js
  src/select/dropdown.js
  src/select/index.d.ts
  src/select/select-component.js
  src/select/types.js
Labels: bugfix

#2959 fix(test): retry flakey e2e tests
  src/data-table/__tests__/data-table-columns.e2e.js
  src/data-table/__tests__/data-table-unreliable.e2e.js
  src/datepicker/__tests__/datepicker-range.e2e.js
  src/datepicker/__tests__/datepicker-unreliable.e2e.js
Labels: bugfix

#2961 docs: fix type tooltips
  documentation-site/components/yard/type-definition.js
Labels: bugfix

#2957 build(vrt): fix logic for generating snapshot branches from forks
  vrt/ci.js
Labels: bugfix, build/tooling

#2963 fix(timepicker): aria-label to announce time format
  src/datepicker/locale.js
  src/locale/index.js
  src/timepicker/timepicker.js
Labels: bugfix

#2964 fix(datepicker): update flow types
  scripts/flow-check-build.js
  src/datepicker/styled-components.js
  src/timepicker/__tests__/timepicker.test.js
Labels: bugfix

#2953 fix(tree-view): fix leaf item indent and add indent guides
  documentation-site/components/yard/config/tree-view.ts
  documentation-site/examples/tree-view/overrides.js
  documentation-site/examples/tree-view/overrides.tsx
  documentation-site/examples/tree-view/single-expanded.js
  src/tree-view/index.d.ts
  src/tree-view/styled-components.js
  src/tree-view/tree-label.js
  src/tree-view/tree-node.js
  src/tree-view/tree-view.js
  src/tree-view/types.js
  vrt/__image_snapshots__/tree-view-render-all__dark-snap.png
  vrt/__image_snapshots__/tree-view-render-all__desktop-snap.png
  vrt/__image_snapshots__/tree-view-render-all__mobile-snap.png
  vrt/__image_snapshots__/tree-view-single-expanded__dark-snap.png
  vrt/__image_snapshots__/tree-view-single-expanded__desktop-snap.png
  vrt/__image_snapshots__/tree-view-single-expanded__mobile-snap.png
  vrt/__image_snapshots__/tree-view__dark-snap.png
  vrt/__image_snapshots__/tree-view__desktop-snap.png
  vrt/__image_snapshots__/tree-view__mobile-snap.png
Labels: bugfix, feature

#2966 docs(input): add a note about masked input a11y
  documentation-site/pages/components/input.mdx
Labels: docs

#2967 fix(input): tabIndex typo
  src/input/base-input.js
Labels: bugfix

#2965 Release v9.60.1
  package.json
Labels: release

#2954 fix(form-control): propagate 'disabled' prop to children
  src/form-control/__tests__/form-control.test.js
  src/form-control/form-control.js
  vrt/__image_snapshots__/form-control__dark-snap.png
  vrt/__image_snapshots__/form-control__desktop-snap.png
  vrt/__image_snapshots__/form-control__mobile-snap.png
Labels: bugfix

#2950 fix(menu): improve for screen reader compatibility
  src/menu/locale.js
  src/menu/menu.js
  src/menu/option-list.js
Labels: bugfix

#2960 fix(theme): use border types as defined by styletron-standard
  packages/flow-check-build/package.json
  packages/flow-check-build/yarn.lock
  src/themes/types.js
Labels: bugfix

#2942 feat(modal): handle modal closure through the Layer's onDocumentClick handler
  documentation-site/examples/modal/buried-interactive-element.js
  documentation-site/examples/modal/buried-interactive-element.tsx
  src/modal/__tests__/__snapshots__/modal.test.js.snap
  src/modal/__tests__/modal-select.scenario.js
  src/modal/__tests__/modal.e2e.js
  src/modal/__tests__/modal.test.js
  src/modal/modal.js
Labels: feature

#2972 feat(phone-input): clarify default aria-label
  src/phone-input/default-props.js
Labels: feature

#2973 fix(progress-bar): improve screen reader controls
  documentation-site/components/yard/config/progress-bar.ts
  documentation-site/examples/progress-bar/basic.js
  documentation-site/examples/progress-bar/basic.tsx
  documentation-site/examples/progress-bar/custom-label.js
  documentation-site/examples/progress-bar/custom-label.tsx
  documentation-site/examples/progress-bar/negative.js
  documentation-site/examples/progress-bar/negative.tsx
  documentation-site/examples/progress-bar/overrides.js
  documentation-site/examples/progress-bar/overrides.tsx
  documentation-site/examples/progress-bar/success-value.js
  documentation-site/examples/progress-bar/success-value.tsx
  documentation-site/examples/progress-bar/with-label.js
  documentation-site/examples/progress-bar/with-label.tsx
  documentation-site/pages/components/progress-bar.mdx
  src/progress-bar/__tests__/__snapshots__/progressbar.test.js.snap
  src/progress-bar/progressbar.js
  src/progress-bar/types.js
Labels: bugfix

#2974 fix(build): corrects published flow types
  scripts/flow-copy-src.js
  src/checkbox/__tests__/stateful-checkbox-container.test.js
  src/checkbox/stateful-checkbox-container.js
  src/data-table/column-numerical.js
  src/flex-grid/flex-grid-item.js
  src/helpers/overrides.js
  src/input/masked-input.js
  src/input/styled-components.js
  src/input/types.js
  src/menu/types.js
  src/modal/modal-button.js
  src/pagination/stateful-container.js
  src/payment-card/payment-card.js
  src/phone-input/stateful-phone-input-container.js
  src/phone-input/types.js
  src/pin-code/stateful-pin-code-container.js
  src/pin-code/types.js
  src/radio/__tests__/stateful-radiogroup-container.test.js
  src/radio/stateful-radiogroup-container.js
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/select-component.js
  src/side-navigation/styled-components.js
  src/slider/types.js
  src/table/styled-components.js
  src/themes/types.js
  src/toast/toaster.js
  src/tree-view/stateful-container.js
Labels: bugfix

#2971 fix(layout-grid): enable conditional rendering
  src/layout-grid/__tests__/layout-grid.scenario.js
  src/layout-grid/grid.js
  src/layout-grid/types.js
Labels: bugfix

#2970 fix(tag): improve screen-reader controls
  documentation-site/pages/components/tag.mdx
  src/data-table/__tests__/data-table-columns.e2e.js
  src/data-table/__tests__/data-table-initial-filters.e2e.js
  src/tag/__tests__/__snapshots__/tag.test.js.snap
  src/tag/__tests__/tag.test.js
  src/tag/styled-components.js
  src/tag/tag.js
Labels: bugfix

#2976 fix(button): respect focus handler props
  src/button/button.js
Labels: bugfix

#2975 Release v9.61.0
  package.json
Labels: release

#2981 feat(tree-view): makes tree-view stable
  documentation-site/components/yard/config/tree-view.ts
  documentation-site/examples/tree-view/basic.js
  documentation-site/examples/tree-view/basic.tsx
  documentation-site/examples/tree-view/custom-label.js
  documentation-site/examples/tree-view/custom-label.tsx
  documentation-site/examples/tree-view/label-overrides.js
  documentation-site/examples/tree-view/label-overrides.tsx
  documentation-site/examples/tree-view/overrides.js
  documentation-site/examples/tree-view/overrides.tsx
  documentation-site/examples/tree-view/single-expanded.js
  documentation-site/examples/tree-view/single-expanded.tsx
  documentation-site/examples/tree-view/uncontrolled.js
  documentation-site/examples/tree-view/uncontrolled.tsx
  documentation-site/pages/components/tree-view.mdx
  scripts/component-sizes.js
  src/tree-view/__tests__/tree-view-render-all.scenario.js
  src/tree-view/__tests__/tree-view-single-expanded.scenario.js
  src/tree-view/__tests__/tree-view.scenario.js
  src/tree-view/index.d.ts
  src/tree-view/index.js
Labels: feature

#2983 fix(typescript): Fix Typography definitions
  src/theme.ts
Labels: bugfix

#2984 fix(table-semantic): screen-reader fixes and nicer focus
  src/table-semantic/styled-components.js
  src/table-semantic/table-builder.js
Labels: bugfix

#2985 fix(button): vertical align for spinner
  src/button/button.js
  src/button/styled-components.js
  vrt/__image_snapshots__/button-rtl__desktop-snap.png
  vrt/__image_snapshots__/button-rtl__mobile-snap.png
  vrt/__image_snapshots__/button-sizes-loading__dark-snap.png
  vrt/__image_snapshots__/button-sizes-loading__desktop-snap.png
  vrt/__image_snapshots__/button-sizes-loading__mobile-snap.png
  vrt/__image_snapshots__/button__dark-snap.png
  vrt/__image_snapshots__/button__desktop-snap.png
  vrt/__image_snapshots__/button__mobile-snap.png
Labels: bugfix

#2989 fix(table-grid): provides suggestion to improve accessibility
  documentation-site/examples/table-grid/cell-navigation.js
  documentation-site/examples/table-grid/cell-navigation.tsx
  documentation-site/pages/components/table-grid.mdx
  src/table-grid/__tests__/shared.js
  src/table-grid/__tests__/table-grid-jobs.scenario.js
  src/table-grid/__tests__/table-grid-records.scenario.js
  src/table-grid/__tests__/table-grid-sortable.scenario.js
  src/table-grid/__tests__/table-grid.scenario.js
  src/table-grid/index.js
  src/table-grid/sortable-head-cell.js
  src/table-grid/styled-components.js
Labels: bugfix

#2987 fix(styles): use withWrapper to set props on styled components
  src/link/index.js
  src/menu/styled-components.js
  src/phone-input/styled-components.js
  src/select/__tests__/dropdown.test.js
  src/side-navigation/styled-components.js
  src/styles/__mocks__/styled.js
  src/styles/__tests__/styled.test.js
  src/styles/index.js
  src/styles/styled.js
  src/table-grid/styled-components.js
  src/table/styled-components.js
Labels: bugfix

#2991 Release v9.62.0
  package.json
Labels: release

#2995 fix(data-table): makes initial sort always ascending
  src/data-table/__tests__/column-numerical.test.js
  src/data-table/__tests__/data-table-columns.e2e.js
  src/data-table/column-numerical.js
Labels: bugfix

#3002 fix(button-group): remove logging
  src/button-group/button-group.js
Labels: bugfix

#2992 feat(input): accept number type for value
  src/input/__tests__/input-number.scenario.js
  src/input/index.d.ts
  src/input/types.js
  src/payment-card/payment-card.js
  vrt/__image_snapshots__/input-number__dark-snap.png
  vrt/__image_snapshots__/input-number__desktop-snap.png
  vrt/__image_snapshots__/input-number__mobile-snap.png
  vrt/__image_snapshots__/input-number__numberInput-snap.png
Labels: feature

#3004 fix(select): fallback to first dropdown option
  src/select/__tests__/select.e2e.js
  src/select/dropdown.js
Labels: bugfix

#3001 docs(text-area): removed redundant props
  documentation-site/components/yard/config/textarea.ts
Labels: docs

#3000 feat(input): add inputBorder to themes
  documentation-site/components/yard/config/input.ts
  documentation-site/components/yard/config/select.ts
  documentation-site/components/yard/editor.tsx
  src/input/styled-components.js
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/styled-components.js
  src/theme.ts
  src/themes/dark-theme/color-component-tokens.js
  src/themes/light-theme/color-component-tokens.js
  src/themes/types.js
Labels: feature

#3007 feat(styles): add withWrapper to base module
  src/index.js
Labels: feature

#2997 fix(dropdown): defer initial autoFocus and add focus lock
  documentation-site/examples/button/dropdown.js
  documentation-site/examples/button/dropdown.tsx
  src/menu/stateful-container.js
  src/popover/__tests__/__snapshots__/popover.test.js.snap
  src/popover/__tests__/popover.test.js
  src/popover/popover.js
  src/popover/types.js
  src/tooltip/__tests__/tooltip.e2e.js
Labels: bugfix

#3005 Release v9.63.0
  package.json
Labels: release

#3011 chore(build): split deploy steps
  .buildkite/pipeline.yml
  scripts/deploy-docs.sh
  scripts/deploy-npm.sh
  scripts/deploy-vscode.sh
Labels: bugfix, chore

#3012 docs(versions): disable broken builds 9.61 and 9.62
  documentation-site/components/version-selector.js
Labels: docs

#3016 docs(theming): respect media prop
  documentation-site/components/theming/breakpoints.js
Labels: docs

#3010 fix(datepicker): improve a11y
  src/datepicker/__tests__/calendar.e2e.js
  src/datepicker/__tests__/datepicker-range.e2e.js
  src/datepicker/__tests__/datepicker-range.scenario.js
  src/datepicker/__tests__/datepicker-unreliable.e2e.js
  src/datepicker/__tests__/datepicker.e2e.js
  src/datepicker/__tests__/stateful-datepicker.e2e.js
  src/datepicker/calendar-header.js
  src/datepicker/calendar.js
  src/datepicker/datepicker.js
  src/datepicker/day.js
  src/datepicker/locale.js
  src/datepicker/month.js
  src/datepicker/types.js
  src/datepicker/utils/index.js
  src/datepicker/week.js
  src/helpers/__tests__/i18n-interpolation.test.js
  src/helpers/i18n-interpolation.js
  vrt/__image_snapshots__/datepicker-range-highlight__noHighlight-snap.png
  vrt/__image_snapshots__/datepicker__setDateHighlighted-snap.png
  vrt/config.js
Labels: bugfix

#3021 fix(flow-check-build): use local package path
  package.json
  packages/flow-check-build/package.json
  packages/flow-check-build/yarn.lock
  scripts/flow-check-build.js
Labels: bugfix

#3019 fix(data-table): screen reader improvements
  package.json
  src/data-table/column-categorical.js
  src/data-table/filter-menu.js
  src/data-table/stateful-data-table.js
  vrt/__image_snapshots__/data-table-categorical-column__dark-snap.png
  vrt/__image_snapshots__/data-table-categorical-column__desktop-snap.png
  vrt/__image_snapshots__/data-table-categorical-column__mobile-snap.png
  vrt/__image_snapshots__/data-table-extracted-filters__dark-snap.png
  vrt/__image_snapshots__/data-table-extracted-filters__desktop-snap.png
  vrt/__image_snapshots__/data-table-extracted-filters__mobile-snap.png
Labels: bugfix

#3027 fix(checkbox): declare toggleInner function at the top level
  src/checkbox/styled-components.js
Labels: bugfix

#3026 fix(input): adds inputMode to props in typescript
  src/input/index.d.ts
Labels: bugfix

#3030 fix(deploy): netlify
  scripts/deploy-docs.sh
Labels: bugfix, docs

#3013 docs(v10): create a change-log
  documentation-site/pages/discover-more/roadmap.mdx
Labels: docs

#3031 fix(deploy): netlify deploy, take 2
  scripts/deploy-docs.sh
Labels: bugfix, docs

#3032 fix(deploy): move deploy scripts back to the root
  .buildkite/pipeline.yml
  deploy-docs.sh
  deploy-npm.sh
  deploy-vscode.sh
Labels: bugfix, docs

#3008 fix(select): allow input text clear on clear button press
  src/select/__tests__/select-maintains-input-value.e2e.js
  src/select/__tests__/select-maintains-input-value.scenario.js
  src/select/__tests__/select-search-single.scenario.js
  src/select/__tests__/select.e2e.js
  src/select/select-component.js
  src/select/utils/index.js
  vrt/__image_snapshots__/select-maintains-input-value__dark-snap.png
  vrt/__image_snapshots__/select-maintains-input-value__desktop-snap.png
  vrt/__image_snapshots__/select-maintains-input-value__mobile-snap.png
Labels: bugfix

#3034 fix(sortable-head-cell): add titles to icons
  src/table/sortable-head-cell.js
Labels: bugfix

#3029 Release v9.64.0
  package.json
Labels: release

#3035 Release v9.64.1
  package.json
Labels: release

#3036 fix(cf): use bearer token
  deploy-docs.sh
Labels: bugfix, chore

#3037 docs(roadmap): tell folks that we will have codemods
  documentation-site/pages/discover-more/roadmap.mdx
Labels: docs

#3038 fix(menu): avoid react error, state update in render
  src/menu/stateful-container.js
Labels: bugfix

#3041 fix(tree-view): use node-id as key instead of index
  src/tree-view/tree-node.js
  src/tree-view/tree-view.js
  src/tree-view/types.js
Labels: bugfix

#3051 docs(deploy): move to zeit
  now.json
Labels: chore, docs

#3053 fix(datepicker): nvda can navigate month dropdown
  src/datepicker/__tests__/datepicker.e2e.js
  src/datepicker/calendar-header.js
Labels: bugfix

#3056 fix(popover): always apply appropriate aria-attrs
  src/popover/popover.js
Labels: bugfix

#3057 fix(storybook): broken styles in storybook after HMR
  e2e/storybook/config.js
Labels: bugfix

#3054 fix(toaster) order when using custom icons
  src/icon/__tests__/icon-overrides.scenario.js
  src/toast/styled-components.js
  src/toast/toast.js
  vrt/__image_snapshots__/icon-overrides__dark-snap.png
  vrt/__image_snapshots__/icon-overrides__desktop-snap.png
  vrt/__image_snapshots__/icon-overrides__mobile-snap.png
Labels: bugfix

#3059 Release v9.64.2
  package.json
Labels: release

#3060 fix(rating): update scenario to controlled value
  src/rating/__tests__/rating-emoticon.scenario.js
Labels: bugfix

#3063 fix(vscode): add back command-based activation
  packages/baseweb-vscode-extension/package.json
  packages/baseweb-vscode-extension/scripts/update-package.js
Labels: bugfix

#3064 Release v9.64.3
  package.json
Labels: release

#3065 fix(storybook): HMR styling issues
  e2e/storybook/config.js
Labels: bugfix

#3071 docs(theming): add info on shorthand to longhand conversion
  documentation-site/pages/guides/theming.mdx
Labels: docs

#3077 docs(versioning-policy): add info on versioning together
  documentation-site/pages/discover-more/versioning-policy.mdx
Labels: docs

#3072 feat(vscode): show more theme prop values in tooltip hints
  packages/baseweb-vscode-extension/ext-src/coloring.ts
Labels: feature

#3075 fix(select): support backspace/delete for single select
  src/icon/__tests__/icon-overrides.scenario.js
  src/select/__tests__/select-backspace-behavior.e2e.js
  src/select/__tests__/select-backspace-behavior.scenario.js
  src/select/select-component.js
  vrt/__image_snapshots__/select-backspace-behavior__dark-snap.png
  vrt/__image_snapshots__/select-backspace-behavior__desktop-snap.png
  vrt/__image_snapshots__/select-backspace-behavior__mobile-snap.png
Labels: bugfix

#3078 Release v9.64.4
  package.json
Labels: release

#3074 fix(codesandbox-focus): make sure all focusVisible flags are global
  src/utils/focusVisible.js
Labels: bugfix

#3080 fix(select): backspaceRemoves fixes
  src/select/select-component.js
  src/select/types.js
Labels: bugfix

#3079 docs(blog): add screen reader improvement post
  documentation-site/pages/blog/screen-reader-improvements/index.mdx
  documentation-site/pages/blog/screen-reader-improvements/metadata.json
Labels: docs

#3082 fix(build): only run deploy script on tags with semantic pattern
  .buildkite/pipeline.yml
  deploy-docs.sh
  deploy-npm.sh
  deploy-versioned-docs.sh
  deploy-vscode.sh
Labels: bugfix

#3083 Release v9.64.5
  package.json
Labels: release

#3086 fix(build): use message instead of tag
  .buildkite/pipeline.yml
Labels: bugfix

#3088 docs(version-selector): update disabled versions
  documentation-site/components/version-selector.js
Labels: docs

#3089 Release v9.64.6
  package.json
Labels: release

#3081 fix(popover): retry flakey popover tests
  src/popover/__tests__/popover-unreliable.e2e.js
  src/popover/__tests__/popover.e2e.js
Labels: bugfix

#3090 fix(build): corrects deploy step regex
  .buildkite/pipeline.yml
Labels: bugfix

#3092 Release v9.64.7
  package.json
Labels: release

#3091 fix(docs): adds another disabled version
  documentation-site/components/version-selector.js
Labels: bugfix

#3084 fix(input): remove Button dependency
  src/input/__tests__/input-password.scenario.js
  src/input/base-input.js
  src/input/styled-components.js
  src/input/types.js
  vrt/__image_snapshots__/input-password__dark-snap.png
  vrt/__image_snapshots__/input-password__desktop-snap.png
  vrt/__image_snapshots__/input-password__mobile-snap.png
  vrt/__image_snapshots__/input-password__togglesMask-snap.png
  vrt/__image_snapshots__/input-rtl__desktop-snap.png
  vrt/__image_snapshots__/input-rtl__mobile-snap.png
Labels: bugfix, build/tooling, enhancement

#3094 fix(build): correct some publish script errors
  deploy-npm.sh
  deploy-versioned-docs.sh
  deploy-vscode.sh
Labels: bugfix, build/tooling

#3095 Release v9.64.8
  package.json
Labels: release

#3096 fix(timepicker): do not remove on backspace
  src/timepicker/timepicker.js
Labels: bugfix

#3097 fix(build): correct versioned doc site cname config
  deploy-versioned-docs.sh
Labels: bugfix, build/tooling

#3098 Release v9.64.9
  package.json
Labels: release

#3101 docs(components): add title
  documentation-site/pages/components/index.mdx
Labels: docs

#2909 feat: support initial selected row ids
  src/data-table/__tests__/data-table-initial-selected-rows.e2e.js
  src/data-table/__tests__/data-table-initial-selected-rows.scenario.js
  src/data-table/stateful-container.js
  src/data-table/stateful-data-table.js
  src/data-table/types.js
  vrt/__image_snapshots__/data-table-initial-selected-rows__dark-snap.png
  vrt/__image_snapshots__/data-table-initial-selected-rows__desktop-snap.png
  vrt/__image_snapshots__/data-table-initial-selected-rows__mobile-snap.png
Labels: feature

#3105 build: remove link checker script from ci
  .buildkite/pipeline.yml
  flow-typed/npm/broken-link-checker_vx.x.x.js
  package.json
  scripts/link-checker.js
  yarn.lock
Labels: bugfix, build/tooling

#3106 fix(docs): exclude disabled versions in dropdown
  documentation-site/components/version-selector.js
Labels: bugfix

#3111 docs(spinner): add example showcasing $as prop
  documentation-site/examples/spinner/next-span.js
  documentation-site/examples/spinner/next-span.tsx
  documentation-site/pages/components/spinner.mdx
  src/spinner/styled-components.js
Labels: docs

#3113 fix(eslint-plugin-baseui): object spread crash
  packages/eslint-plugin-baseui/__tests__/deprecated-component-api.test.js
  packages/eslint-plugin-baseui/src/deprecated-component-api.js
Labels: bugfix

#3114 Release v9.65.1
  package.json
Labels: release

#3110 fix(docs): use latest version in code sandboxer
  documentation-site/components/example.js
Labels: bugfix

#3116 fix(yard): remove code query param
  documentation-site/components/yard/action-buttons.tsx
  documentation-site/components/yard/index.tsx
Labels: bugfix

#3118 fix(docs): fix incorrect breakpoint documentation
  documentation-site/pages/components/block.mdx
Labels: bugfix

#3119 docs(accordion): add ul wrapper for standalone panel
  documentation-site/examples/accordion/stateful.js
  documentation-site/examples/accordion/stateful.tsx
Labels: docs

#3123 docs(adopters): add cadre
  documentation-site/pages/index.js
  documentation-site/static/images/cadre-logo.png
Labels: docs

#3122 fix(input): vertically align 'show password' icon button
  src/input/styled-components.js
Labels: bugfix

#3124 Release v9.65.2
  package.json
Labels: release

#3125 fix(menu): unhighlights item on mouse leave
  src/menu/__tests__/menu.e2e.js
  src/menu/constants.js
  src/menu/menu.js
  src/menu/stateful-container.js
  src/menu/types.js
Labels: bugfix

#3128 fix(codesandbox): fix DarkTheme, focus-ring, add CI integration
  .codesandbox/ci.json
  documentation-site/components/const.js
  package.json
  src/utils/focusVisible.js
Labels: bugfix

#3132 fix(deps): remove main field
  documentation-site/components/const.js
  package.json
Labels: bugfix

#3136 Release v9.65.4
  package.json
Labels: release

#3140 feat: added a check before overriding isActive
  src/progress-steps/__tests__/__snapshots__/step.test.js.snap
  src/progress-steps/__tests__/progress-steps-isActive.scenario.js
  src/progress-steps/__tests__/progress-steps.test.js
  src/progress-steps/progress-steps.js
  src/progress-steps/step.js
  src/progress-steps/types.js
  vrt/__image_snapshots__/progress-steps-isActive__dark-snap.png
  vrt/__image_snapshots__/progress-steps-isActive__desktop-snap.png
  vrt/__image_snapshots__/progress-steps-isActive__mobile-snap.png
Labels: feature

#3141 Release v9.66.0
  package.json
Labels: release

#3130 feat(data-table): add onIncludedRowsChange callback
  src/data-table/__tests__/data-table-included-rows-change.e2e.js
  src/data-table/__tests__/data-table-included-rows-change.scenario.js
  src/data-table/data-table.js
  src/data-table/stateful-container.js
  src/data-table/stateful-data-table.js
  src/data-table/types.js
  vrt/__image_snapshots__/data-table-included-rows-change__dark-snap.png
  vrt/__image_snapshots__/data-table-included-rows-change__desktop-snap.png
  vrt/__image_snapshots__/data-table-included-rows-change__mobile-snap.png
Labels: feature

#3143 fix(spinner): only warn on usage outside of baseui
  src/file-uploader/file-uploader.js
  src/select/select-component.js
  src/spinner/spinner.js
  src/spinner/types.js
Labels: bugfix

#3145 fix(locale-provider): check if locale.datepicker exists
  src/locale/index.js
Labels: bugfix

#3142 fix(select): disable select href render as anchor
  src/menu/index.d.ts
  src/menu/option-list.js
  src/menu/types.js
  src/select/__tests__/dropdown.test.js
  src/select/__tests__/select-disable-href-anchor.scenario.js
  src/select/dropdown.js
  vrt/__image_snapshots__/select-disable-href-anchor__dark-snap.png
  vrt/__image_snapshots__/select-disable-href-anchor__desktop-snap.png
  vrt/__image_snapshots__/select-disable-href-anchor__mobile-snap.png
Labels: bugfix

#3137 Update ListItem to be a ForwardRefExoticComponent [typescript]
  src/list/index.d.ts
Labels: bugfix

#3148 fix(select): calls provided onBlur function
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/__tests__/select-calls-provided-blur.e2e.js
  src/select/__tests__/select-calls-provided-blur.scenario.js
  src/select/select-component.js
  vrt/__image_snapshots__/select-calls-provided-blur__dark-snap.png
  vrt/__image_snapshots__/select-calls-provided-blur__desktop-snap.png
  vrt/__image_snapshots__/select-calls-provided-blur__mobile-snap.png
Labels: bugfix
