Repository uber/baseweb, pull requests merged in 2020-07, with the labels that each got.

#3454 docs(typo): fix link to styletron's styled api
  documentation-site/pages/components/styled.mdx
Labels: bugfix, docs

#3462 feat(button): add an alias for Root
  src/button/button.js
  src/button/index.d.ts
  src/button/types.js
Labels: feature

#3461 docs: fix Styletron debug mode errors
  documentation-site/next.config.js
Labels: docs

#3456 fix(table grid):modifies example to better navigate
  documentation-site/examples/table-grid/basic.js
  documentation-site/examples/table-grid/basic.tsx
  documentation-site/examples/table-grid/nested.js
  documentation-site/examples/table-grid/nested.tsx
  documentation-site/examples/table-grid/sortable.js
  documentation-site/examples/table-grid/sortable.tsx
Labels: bugfix

#3464 docs(Popover): fix `onMouseLeaveDelay` description
  documentation-site/components/yard/config/popover.ts
Labels: bugfix, docs

#3465 fix(build): update react-extract-types packages
  package.json
  yarn.lock
Labels: bugfix

#3463 docs(link): remove overrides from props
  documentation-site/components/yard/config/link.ts
Labels: docs

#3469 fix(docs): fix yard if component does not have overrides
  documentation-site/components/yard/index.tsx
  documentation-site/components/yard/utils.ts
Labels: bugfix

#3468 Release v9.85.1
  package.json
Labels: release

#3473 Release v9.85.2
  package.json
Labels: release

#3474 chore(build): Publish alpha build when release PR is open
  .buildkite/pipeline.yml
  deploy-npm.sh
  scripts/publish-to-npm.js
  scripts/sync-package-versions.js
Labels: build/tooling, chore, feature

#3478 fix(alpha-publish): correct root_dir in publish script
  scripts/publish-to-npm.js
  scripts/sync-package-versions.js
Labels: bugfix

#3484 fix(accordian): remove :never from type file
  src/accordion/index.d.ts
Labels: bugfix

#3485 Release v9.85.3
  package.json
Labels: release

#3489 docs(datepicker): add missing props
  documentation-site/components/yard/config/datepicker.ts
Labels: docs

#3490 feat(data-table): custom column can be searched by text query
  src/data-table/__tests__/data-table-text-search.e2e.js
  src/data-table/__tests__/data-table-text-search.scenario.js
  src/data-table/column-categorical.js
  src/data-table/column-custom.js
  src/data-table/column-string.js
  src/data-table/data-table.js
  src/data-table/types.js
  vrt/__image_snapshots__/data-table-text-search__dark-snap.png
  vrt/__image_snapshots__/data-table-text-search__desktop-snap.png
Labels: feature

#3494 Release v9.86.0
  package.json
Labels: release

#3239 feat(datepicker) swappable date libraries
  package.json
  src/datepicker/__tests__/datepicker.scenario.js
  src/datepicker/__tests__/utils.test.js
  src/datepicker/calendar-header.js
  src/datepicker/calendar.js
  src/datepicker/datepicker.js
  src/datepicker/day.js
  src/datepicker/month.js
  src/datepicker/stateful-calendar.js
  src/datepicker/stateful-container.js
  src/datepicker/stateful-datepicker.js
  src/datepicker/types.js
  src/datepicker/utils/date-helpers.js
  src/datepicker/utils/index.js
  src/datepicker/utils/types.js
  src/datepicker/week.js
  src/timepicker/types.js
  vrt/__image_snapshots__/datepicker-rtl__calendarOpened-snap.png
  vrt/__image_snapshots__/datepicker-rtl__desktop-snap.png
  vrt/__image_snapshots__/datepicker-rtl__mobile-snap.png
  vrt/__image_snapshots__/datepicker__dark-snap.png
  vrt/__image_snapshots__/datepicker__desktop-snap.png
  vrt/__image_snapshots__/datepicker__mobile-snap.png
  vrt/__image_snapshots__/datepicker__setDateHighlighted-snap.png
  yarn.lock
Labels: feature

#3497 feat(input): add clearOnEscape prop
  documentation-site/components/yard/config/input.ts
  documentation-site/pages/components/input.mdx
  src/input/__tests__/input-clearable-noescape.scenario.js
  src/input/__tests__/input.e2e.js
  src/input/base-input.js
  src/input/types.js
  src/textarea/__tests__/__snapshots__/textarea.test.js.snap
  vrt/__image_snapshots__/input-clearable-noescape__dark-snap.png
  vrt/__image_snapshots__/input-clearable-noescape__desktop-snap.png
  vrt/__image_snapshots__/input-clearable-noescape__mobile-snap.png
Labels: feature

#3500 feat(combobox): adds onSubmit callback and close handler
  src/combobox/__tests__/combobox-form.scenario.js
  src/combobox/__tests__/combobox.test.js
  src/combobox/combobox.js
  src/combobox/index.d.ts
  src/combobox/types.js
  vrt/__image_snapshots__/combobox-form__dark-snap.png
  vrt/__image_snapshots__/combobox-form__desktop-snap.png
  vrt/__image_snapshots__/combobox-form__mobile-snap.png
Labels: feature

#3504 test: fix possible e2e screenshot issue
  jest.e2e.setup.js
Labels: bugfix, build/tooling

#3505 feat(rating): add size prop
  documentation-site/components/yard/config/rating.ts
  src/rating/__tests__/__snapshots__/emoticon-rating.test.js.snap
  src/rating/__tests__/__snapshots__/star-rating.test.js.snap
  src/rating/__tests__/rating-size.scenario.js
  src/rating/emoticon-rating.js
  src/rating/index.d.ts
  src/rating/star-rating.js
  src/rating/styled-components.js
  src/rating/svg-icons.js
  src/rating/types.js
  vrt/__image_snapshots__/rating-size__dark-snap.png
  vrt/__image_snapshots__/rating-size__desktop-snap.png
  vrt/__image_snapshots__/rating-size__mobile-snap.png
  vrt/__image_snapshots__/rating-star__dark-snap.png
  vrt/__image_snapshots__/rating-star__desktop-snap.png
  vrt/__image_snapshots__/rating-star__mobile-snap.png
  vrt/__image_snapshots__/rating-star__selectFiveStars-snap.png
Labels: feature

#3510 fix(tabs-motion): add cursor:pointer
  src/tabs-motion/styled-components.js
Labels: bugfix

#3512 chore(comments): changes v10 comments to v11
  documentation-site/components/yard/config/progress-bar.ts
  documentation-site/pages/components/phone-input.mdx
  documentation-site/pages/components/spinner.mdx
  documentation-site/pages/discover-more/roadmap.mdx
  documentation-site/pages/guides/theming.mdx
  packages/eslint-plugin-baseui/src/messages.js
  src/accordion/accordion.js
  src/checkbox/checkbox.js
  src/combobox/types.js
  src/file-uploader/file-uploader.js
  src/helpers/overrides.js
  src/layout-grid/cell.js
  src/layout-grid/types.js
  src/locale/index.js
  src/modal/modal.js
  src/phone-input/country-select.js
  src/progress-bar/types.js
  src/radio/radiogroup.js
  src/select/index.d.ts
  src/select/index.js
  src/select/multi-value.js
  src/select/select-component.js
  src/spinner/spinner.js
  src/spinner/styled-components.js
  src/spinner/types.js
  src/styles/types.js
  src/themes/dark-theme/color-component-tokens.js
  src/themes/dark-theme/color-deprecated-semantic-tokens.js
  src/themes/dark-theme/create-dark-theme.js
  src/themes/dark-theme/dark-theme.js
  src/themes/light-theme/color-component-tokens.js
  src/themes/light-theme/color-deprecated-semantic-tokens.js
  src/themes/light-theme/create-light-theme.js
  src/themes/light-theme/light-theme.js
  src/typography/index.d.ts
  src/typography/index.js
Labels: bugfix, chore

#3503 chore(flow): removes flow-check-build
  .buildkite/pipeline.yml
  packages/flow-check-build/.flowconfig
  packages/flow-check-build/.gitignore
  packages/flow-check-build/.npmrc
  packages/flow-check-build/build-dependencies.js
  packages/flow-check-build/index.js
  packages/flow-check-build/package.json
  packages/flow-check-build/yarn.lock
  scripts/flow-check-build.js
  src/menu/stateful-container.js
Labels: bugfix, build/tooling, chore

#3472 feat: add skeleton module
  src/skeleton/__tests__/skeleton-animation.scenario.js
  src/skeleton/__tests__/skeleton-loading.scenario.js
  src/skeleton/__tests__/skeleton.e2e.js
  src/skeleton/__tests__/skeleton.scenario.js
  src/skeleton/__tests__/static/adorable.png
  src/skeleton/index.js
  src/skeleton/skeleton.js
  src/skeleton/styled-components.js
  src/skeleton/types.js
  vrt/__image_snapshots__/skeleton-animation__dark-snap.png
  vrt/__image_snapshots__/skeleton-animation__desktop-snap.png
  vrt/__image_snapshots__/skeleton-animation__mobile-snap.png
  vrt/__image_snapshots__/skeleton-loading__dark-snap.png
  vrt/__image_snapshots__/skeleton-loading__desktop-snap.png
  vrt/__image_snapshots__/skeleton-loading__mobile-snap.png
  vrt/__image_snapshots__/skeleton__dark-snap.png
  vrt/__image_snapshots__/skeleton__desktop-snap.png
  vrt/__image_snapshots__/skeleton__mobile-snap.png
Labels: feature

#3518 docs(popover): proper type for mountNode
  documentation-site/components/yard/config/popover.ts
Labels: docs

#3520 fix(tabs-motion): buttons should not trigger form submit
  src/tabs-motion/__tests__/tabs-motion.scenario.js
  src/tabs-motion/tabs.js
Labels: bugfix

#3521 Release v9.87.1
  package.json
Labels: release

#3523 docs(adopters): add metromile
  documentation-site/pages/index.js
  documentation-site/public/images/metromile-logo.png
  vrt/__image_snapshots__/slider-rtl__desktop-snap.png
  vrt/__image_snapshots__/slider-rtl__mobile-snap.png
  vrt/__image_snapshots__/table-grid-jobs__dark-snap.png
  vrt/__image_snapshots__/table-grid-jobs__mobile-snap.png
  vrt/__image_snapshots__/table-grid-records__dark-snap.png
  vrt/__image_snapshots__/table-grid-records__desktop-snap.png
  vrt/__image_snapshots__/table-grid-records__mobile-snap.png
  vrt/__image_snapshots__/table-grid__dark-snap.png
  vrt/__image_snapshots__/table-scroll__dark-snap.png
  vrt/__image_snapshots__/table-scroll__desktop-snap.png
Labels: docs

#3531 feat(color-tokens): update greens
  src/tokens/colors.js
  vrt/__image_snapshots__/combobox-form-control__dark-snap.png
  vrt/__image_snapshots__/combobox-form-control__desktop-snap.png
  vrt/__image_snapshots__/combobox-form-control__mobile-snap.png
  vrt/__image_snapshots__/country-select-dropdown__dark-snap.png
  vrt/__image_snapshots__/datepickers-color-states__dark-snap.png
  vrt/__image_snapshots__/form-control__dark-snap.png
  vrt/__image_snapshots__/form-control__desktop-snap.png
  vrt/__image_snapshots__/form-control__mobile-snap.png
  vrt/__image_snapshots__/input-states__dark-snap.png
  vrt/__image_snapshots__/notification__desktop-snap.png
  vrt/__image_snapshots__/notification__mobile-snap.png
  vrt/__image_snapshots__/phone-input-next__dark-snap.png
  vrt/__image_snapshots__/pin-code-states__dark-snap.png
  vrt/__image_snapshots__/select-states__dark-snap.png
  vrt/__image_snapshots__/stateful-calendar-overrides__dark-snap.png
  vrt/__image_snapshots__/stateful-calendar-overrides__desktop-snap.png
  vrt/__image_snapshots__/stateful-calendar-overrides__mobile-snap.png
  vrt/__image_snapshots__/table-cells__dark-snap.png
  vrt/__image_snapshots__/table-cells__desktop-snap.png
  vrt/__image_snapshots__/table-cells__mobile-snap.png
  vrt/__image_snapshots__/table-grid-jobs__dark-snap.png
  vrt/__image_snapshots__/table-grid-jobs__desktop-snap.png
  vrt/__image_snapshots__/table-grid-jobs__mobile-snap.png
  vrt/__image_snapshots__/tag-rtl__desktop-snap.png
  vrt/__image_snapshots__/tag-rtl__mobile-snap.png
  vrt/__image_snapshots__/tag__dark-snap.png
  vrt/__image_snapshots__/tag__desktop-snap.png
  vrt/__image_snapshots__/tag__mobile-snap.png
  vrt/__image_snapshots__/toast__dark-snap.png
  vrt/__image_snapshots__/toast__desktop-snap.png
  vrt/__image_snapshots__/toast__mobile-snap.png
Labels: feature

#3536 Release v9.88.0
  package.json
Labels: release

#3539 feat(file-uploader): use the latest spinner
  src/file-uploader/__tests__/file-uploader.test.js
  src/file-uploader/file-uploader.js
  vrt/__image_snapshots__/file-uploader-spinner__dark-snap.png
  vrt/__image_snapshots__/file-uploader-spinner__desktop-snap.png
  vrt/__image_snapshots__/file-uploader-spinner__mobile-snap.png
Labels: feature

#3541 feat(file-uploader): make spinner overridable
  documentation-site/components/yard/config/file-uploader.ts
  src/file-uploader/file-uploader.js
  src/file-uploader/index.d.ts
  src/file-uploader/types.js
Labels: feature

#3542 Release v9.89.0
  package.json
Labels: release

#3507 feat: add mask for pin-code
  documentation-site/components/yard/config/pin-code.ts
  documentation-site/examples/pin-code/mask.js
  documentation-site/examples/pin-code/mask.tsx
  documentation-site/pages/components/pin-code.mdx
  src/pin-code/__tests__/pin-code-mask.scenario.js
  src/pin-code/__tests__/pin-code.e2e.js
  src/pin-code/default-props.js
  src/pin-code/index.d.ts
  src/pin-code/pin-code.js
  src/pin-code/stateful-pin-code-container.js
  src/pin-code/types.js
  vrt/__image_snapshots__/pin-code-mask__dark-snap.png
  vrt/__image_snapshots__/pin-code-mask__desktop-snap.png
  vrt/__image_snapshots__/pin-code-mask__mobile-snap.png
  vrt/__image_snapshots__/pin-code-mask__numberInput-snap.png
  vrt/config.js
Labels: feature

#3544 docs: add skeleton docs
  documentation-site/components/yard/config/skeleton.ts
  documentation-site/examples/skeleton/animation.js
  documentation-site/examples/skeleton/animation.tsx
  documentation-site/examples/skeleton/basic.js
  documentation-site/examples/skeleton/basic.tsx
  documentation-site/examples/skeleton/circle.js
  documentation-site/examples/skeleton/circle.tsx
  documentation-site/examples/skeleton/subElements.js
  documentation-site/examples/skeleton/subElements.tsx
  documentation-site/pages/components/skeleton.mdx
  documentation-site/routes.js
  src/skeleton/index.d.ts
  src/skeleton/styled-components.js
Labels: docs

#3550 fix(datepicker): add missing ts override
  documentation-site/components/yard/config/datepicker.ts
  src/datepicker/index.d.ts
Labels: bugfix

#3549 fix(form-control): don't pass non-DOM props to DOM children
  src/form-control/form-control.js
  src/form-control/types.js
Labels: bugfix

#3552 fix(icons): update titles to not contain the word chevron
  src/icon/build-icons.js
  src/icon/chevron-down.js
  src/icon/chevron-left.js
  src/icon/chevron-right.js
  src/icon/chevron-up.js
Labels: bugfix

#3554 docs(icons): ask users not to pass in the props to the DOM
  documentation-site/pages/guides/theming.mdx
Labels: docs

#3556 Release v9.90.0
  package.json
Labels: release

#3559 feat(breadcrumbs): add prop to display trailing separator
  documentation-site/components/yard/config/breadcrumbs.ts
  src/breadcrumbs/__tests__/breadcrumbs-trailing.scenario.js
  src/breadcrumbs/breadcrumbs.js
  src/breadcrumbs/index.d.ts
  src/breadcrumbs/types.js
  vrt/__image_snapshots__/breadcrumbs-trailing__dark-snap.png
  vrt/__image_snapshots__/breadcrumbs-trailing__desktop-snap.png
  vrt/__image_snapshots__/breadcrumbs-trailing__mobile-snap.png
Labels: feature

#3561 chore(e2e): extend jest timeout on popover e2e tests
  src/popover/__tests__/popover-unreliable.e2e.js
Labels: bugfix

#3562 docs(toc): use slugify helper to create anchor link
  documentation-site/components/table-of-contents.js
Labels: docs

#3563 fix(breadcrumb): align the seperator to the middle
  src/breadcrumbs/styled-components.js
  vrt/__image_snapshots__/breadcrumbs-rtl__desktop-snap.png
  vrt/__image_snapshots__/breadcrumbs-rtl__mobile-snap.png
  vrt/__image_snapshots__/breadcrumbs-trailing__dark-snap.png
  vrt/__image_snapshots__/breadcrumbs-trailing__desktop-snap.png
  vrt/__image_snapshots__/breadcrumbs-trailing__mobile-snap.png
  vrt/__image_snapshots__/breadcrumbs__dark-snap.png
  vrt/__image_snapshots__/breadcrumbs__desktop-snap.png
  vrt/__image_snapshots__/breadcrumbs__mobile-snap.png
Labels: bugfix

#3565 Release v9.91.0
  package.json
Labels: release
