Repository uber/baseweb, pull requests merged in 2020-11, with the labels that each got.

#3892 fix(tests): handle date test failure
  src/datepicker/__tests__/datepicker.test.js
Labels: bugfix

#3891 fix(docs): data testid
  documentation-site/examples/dnd-list/overrides_style.js
  documentation-site/examples/dnd-list/overrides_style.tsx
  documentation-site/pages/guides/understanding-overrides.mdx
Labels: docs

#3887 fix(checkbox): prevent second click event from firing
  src/checkbox/__tests__/checkbox.test.js
  src/checkbox/checkbox.js
Labels: bugfix

#3893 feat(helper): new component
  src/helper/__tests__/helper-position.scenario.js
  src/helper/__tests__/helper-steps.scenario.js
  src/helper/__tests__/helper-with-steps.scenario.js
  src/helper/constants.js
  src/helper/helper-steps.js
  src/helper/helper.js
  src/helper/index.d.ts
  src/helper/index.js
  src/helper/stateful-helper.js
  src/helper/styled-components.js
  src/helper/types.js
  src/popover/__tests__/popover-position.scenario.js
  src/popover/__tests__/utils.test.js
  src/popover/styled-components.js
  src/popover/utils.js
  vrt/__image_snapshots__/helper-position__dark-snap.png
  vrt/__image_snapshots__/helper-position__desktop-snap.png
  vrt/__image_snapshots__/helper-position__mobile-snap.png
  vrt/__image_snapshots__/helper-steps__dark-snap.png
  vrt/__image_snapshots__/helper-steps__desktop-snap.png
  vrt/__image_snapshots__/helper-steps__mobile-snap.png
  vrt/__image_snapshots__/helper-with-steps__dark-snap.png
  vrt/__image_snapshots__/helper-with-steps__desktop-snap.png
  vrt/__image_snapshots__/helper-with-steps__mobile-snap.png
  vrt/__image_snapshots__/popover-position__dark-snap.png
  vrt/__image_snapshots__/popover-position__desktop-snap.png
  vrt/__image_snapshots__/popover-position__mobile-snap.png
Labels: feature

#3899 fix(rating): fix styletron warning
  src/rating/styled-components.js
Labels: bugfix

#3897 feat(theme): add contentOnColorInverse
  documentation-site/pages/guides/theming.mdx
  src/themes/dark-theme/color-semantic-tokens.js
  src/themes/light-theme/color-semantic-tokens.js
  src/themes/types.js
Labels: feature

#3901 chore(docs): add table guide
  documentation-site/components/gallery.js
  documentation-site/components/table-guide-notification.js
  documentation-site/pages/components/data-table.mdx
  documentation-site/pages/components/table-grid.mdx
  documentation-site/pages/components/table-semantic.mdx
  documentation-site/pages/components/table.mdx
  documentation-site/pages/guides/tables.mdx
  documentation-site/routes.js
Labels: chore

#3895 fix(icon): improve prop pass through logic
  documentation-site/pages/guides/theming.mdx
  src/button/button-internals.js
  src/icon/__tests__/icon-attributes.scenario.js
  src/icon/__tests__/icon.test.js
  src/icon/alert.js
  src/icon/arrow-down.js
  src/icon/arrow-left.js
  src/icon/arrow-right.js
  src/icon/arrow-up.js
  src/icon/blank.js
  src/icon/build-icons.js
  src/icon/check-indeterminate.js
  src/icon/check.js
  src/icon/chevron-down.js
  src/icon/chevron-left.js
  src/icon/chevron-right.js
  src/icon/chevron-up.js
  src/icon/delete-alt.js
  src/icon/delete.js
  src/icon/filter.js
  src/icon/grab.js
  src/icon/hide.js
  src/icon/icon-template.txt
  src/icon/icon.js
  src/icon/menu.js
  src/icon/overflow.js
  src/icon/plus.js
  src/icon/search.js
  src/icon/show.js
  src/icon/spinner.js
  src/icon/styled-components.js
  src/icon/triangle-down.js
  src/icon/triangle-left.js
  src/icon/triangle-right.js
  src/icon/triangle-up.js
  src/icon/upload.js
  src/spinner/__tests__/component.test.js
  src/spinner/__tests__/spinner.scenario.js
  vrt/__image_snapshots__/icon-attributes__dark-snap.png
  vrt/__image_snapshots__/icon-attributes__desktop-snap.png
  vrt/__image_snapshots__/icon-attributes__mobile-snap.png
  vrt/__image_snapshots__/spinner__dark-snap.png
  vrt/__image_snapshots__/spinner__desktop-snap.png
  vrt/__image_snapshots__/spinner__mobile-snap.png
Labels: bugfix, enhancement

#3900 fix(textarea): restore border focus
  src/textarea/styled-components.js
  src/textarea/textarea.js
  src/textarea/types.js
  vrt/__image_snapshots__/form-control__dark-snap.png
  vrt/__image_snapshots__/form-control__desktop-snap.png
  vrt/__image_snapshots__/form-control__mobile-snap.png
  vrt/__image_snapshots__/textarea__dark-snap.png
  vrt/__image_snapshots__/textarea__desktop-snap.png
  vrt/__image_snapshots__/textarea__focus-snap.png
  vrt/__image_snapshots__/textarea__mobile-snap.png
  vrt/config.js
Labels: bugfix

#3910 fix(menu): avoid loop when inside focus lock
  src/menu/locale.js
  src/menu/stateful-container.js
  src/modal/__tests__/modal-select.scenario.js
  src/modal/__tests__/modal.test.js
Labels: bugfix

#3912 fix(type): Bug with theme sizing type
  src/theme.ts
Labels: bugfix

#3918 fix(select): opt dropdown out of focus locking
  src/menu/stateful-container.js
  src/select/dropdown.js
Labels: bugfix

#3915 docs: add styling guide
  documentation-site/pages/guides/styling.mdx
  documentation-site/public/images/overrides1.png
  documentation-site/public/images/overrides2.png
  documentation-site/routes.js
Labels: docs

#3921 fix(datepicker): handles time selection after end datetime
  documentation-site/examples/datepicker/composed-range-pickers.js
  documentation-site/examples/datepicker/composed-range-pickers.tsx
  jest.e2e.config.js
  src/datepicker/__tests__/datepickers-composed-range.e2e.js
  src/datepicker/__tests__/datepickers-composed-range.scenario.js
  src/datepicker/datepicker.js
  src/datepicker/day.js
  vrt/__image_snapshots__/datepickers-composed-range__desktop-snap.png
  vrt/__image_snapshots__/datepickers-composed-range__mobile-snap.png
Labels: bugfix

#3930 feat(table): head cell accepts non string title
  src/table/index.d.ts
  src/table/sortable-head-cell.js
  src/table/types.js
Labels: feature

#3934 feat(phone-input): rtl-ify the component
  src/phone-input/__tests__/phone-input-next-rtl.scenario.js
  src/phone-input/country-picker.js
  src/phone-input/phone-input-next.js
  src/phone-input/styled-components.js
  vrt/__image_snapshots__/phone-input-next-rtl__desktop-snap.png
  vrt/__image_snapshots__/phone-input-next-rtl__mobile-snap.png
Labels: feature

#3937 chore(e2e): increase retry times
  jest.e2e.setup.js
  src/data-table/__tests__/data-table-unreliable.e2e.js
  src/datepicker/__tests__/datepicker-unreliable.e2e.js
  src/datepicker/__tests__/stateful-datepicker-quick-select.e2e.js
  src/datepicker/__tests__/stateful-datepicker.e2e.js
  src/popover/__tests__/popover-unreliable.e2e.js
  src/snackbar/__tests__/snackbar-provider.scenario.js
Labels: chore

#3932 feat(data-table): add cell block alignment option
  src/data-table/__tests__/data-table-row-height.scenario.js
  src/data-table/cell-shell.js
  src/data-table/column-anchor.js
  src/data-table/column-boolean.js
  src/data-table/column-categorical.js
  src/data-table/column-custom.js
  src/data-table/column-datetime.js
  src/data-table/column-numerical.js
  src/data-table/column-string.js
  src/data-table/column.js
  src/data-table/types.js
  vrt/__image_snapshots__/data-table-row-height__dark-snap.png
  vrt/__image_snapshots__/data-table-row-height__desktop-snap.png
  vrt/__image_snapshots__/data-table-row-height__mobile-snap.png
Labels: feature

#3940 Nested overrides playground
  documentation-site/components/yard/__tests__/ast.test.ts
  documentation-site/components/yard/config/select.ts
  documentation-site/components/yard/custom-props.ts
  documentation-site/components/yard/index.tsx
  documentation-site/components/yard/nested-tooltip.tsx
  documentation-site/components/yard/override.tsx
  documentation-site/components/yard/overrides-description.tsx
  documentation-site/components/yard/overrides.tsx
  package.json
  yarn.lock
Labels: docs

#3948 fix(yard): Fix nested override refs
  documentation-site/components/yard/config/breadcrumbs.ts
  documentation-site/components/yard/config/combobox.ts
  documentation-site/components/yard/config/datepicker.ts
  documentation-site/components/yard/config/file-uploader.ts
  documentation-site/components/yard/config/pagination.ts
  documentation-site/components/yard/config/phone-input.ts
  documentation-site/components/yard/config/pin-code.ts
  documentation-site/components/yard/config/select.ts
  documentation-site/components/yard/config/timepicker.ts
  documentation-site/components/yard/config/timezonepicker.ts
Labels: docs

#3941 feat(data-table): adds row index column
  src/data-table/__tests__/column-anchor.test.js
  src/data-table/__tests__/column-boolean.test.js
  src/data-table/__tests__/column-categorical.test.js
  src/data-table/__tests__/column-custom.test.js
  src/data-table/__tests__/column-datetime.test.js
  src/data-table/__tests__/column-numerical.test.js
  src/data-table/__tests__/column-string.test.js
  src/data-table/__tests__/data-table-cell-indices.scenario.js
  src/data-table/__tests__/data-table-initial-selected-rows.scenario.js
  src/data-table/column-anchor.js
  src/data-table/column-boolean.js
  src/data-table/column-categorical.js
  src/data-table/column-custom.js
  src/data-table/column-datetime.js
  src/data-table/column-numerical.js
  src/data-table/column-row-index.js
  src/data-table/column-string.js
  src/data-table/column.js
  src/data-table/constants.js
  src/data-table/data-table.js
  src/data-table/index.js
  src/data-table/measure-column-widths.js
  src/data-table/types.js
  vrt/__image_snapshots__/data-table-cell-indices__dark-snap.png
  vrt/__image_snapshots__/data-table-cell-indices__desktop-snap.png
  vrt/__image_snapshots__/data-table-cell-indices__mobile-snap.png
  vrt/__image_snapshots__/data-table-initial-selected-rows__dark-snap.png
  vrt/__image_snapshots__/data-table-initial-selected-rows__desktop-snap.png
  vrt/__image_snapshots__/data-table-initial-selected-rows__mobile-snap.png
Labels: feature

#3943 docs(input): add input with select example
  documentation-site/examples/input/with-select.js
  documentation-site/examples/input/with-select.tsx
  documentation-site/pages/components/input.mdx
  src/checkbox/checkbox.js
  src/input/__tests__/input-selector.scenario.js
  vrt/__image_snapshots__/input-selector__dark-snap.png
  vrt/__image_snapshots__/input-selector__desktop-snap.png
  vrt/__image_snapshots__/input-selector__mobile-snap.png
Labels: docs

#3946 docs(datepicker): composed datetime range pickers render well on mobile
  documentation-site/examples/datepicker/composed-range-pickers.js
  documentation-site/examples/datepicker/composed-range-pickers.tsx
  src/datepicker/__tests__/datepickers-composed-range.scenario.js
  vrt/__image_snapshots__/datepickers-composed-range__mobile-snap.png
Labels: docs
