Repository uber/baseweb, pull requests merged in 2020-10, with the labels that each got.

#3796 fix(input): align disabled text color with select
  src/input/__tests__/input-disabled-matches-select.scenario.js
  src/input/styled-components.js
  vrt/__image_snapshots__/data-table-numerical-column__dark-snap.png
  vrt/__image_snapshots__/data-table-numerical-column__desktop-snap.png
  vrt/__image_snapshots__/data-table-numerical-column__mobile-snap.png
  vrt/__image_snapshots__/datepickers-color-states__dark-snap.png
  vrt/__image_snapshots__/datepickers-color-states__desktop-snap.png
  vrt/__image_snapshots__/datepickers-color-states__mobile-snap.png
  vrt/__image_snapshots__/input-disabled-matches-select__dark-snap.png
  vrt/__image_snapshots__/input-disabled-matches-select__desktop-snap.png
  vrt/__image_snapshots__/input-disabled-matches-select__mobile-snap.png
  vrt/__image_snapshots__/input-rtl__desktop-snap.png
  vrt/__image_snapshots__/input-rtl__mobile-snap.png
  vrt/__image_snapshots__/input-states__dark-snap.png
  vrt/__image_snapshots__/input-states__desktop-snap.png
  vrt/__image_snapshots__/input-states__mobile-snap.png
Labels: bugfix

#3800 fix(data-table): column-width fill handles scrollbar width
  src/data-table/data-table.js
  vrt/__image_snapshots__/data-table-batch-action__dark-snap.png
  vrt/__image_snapshots__/data-table-batch-action__desktop-snap.png
  vrt/__image_snapshots__/data-table-collection-of-objects__dark-snap.png
  vrt/__image_snapshots__/data-table-collection-of-objects__desktop-snap.png
  vrt/__image_snapshots__/data-table-collection-of-objects__mobile-snap.png
  vrt/__image_snapshots__/data-table-columns-not-sortable__dark-snap.png
  vrt/__image_snapshots__/data-table-columns-not-sortable__desktop-snap.png
  vrt/__image_snapshots__/data-table-columns-not-sortable__mobile-snap.png
  vrt/__image_snapshots__/data-table-columns__dark-snap.png
  vrt/__image_snapshots__/data-table-columns__desktop-snap.png
  vrt/__image_snapshots__/data-table-columns__mobile-snap.png
  vrt/__image_snapshots__/data-table-empty__dark-snap.png
  vrt/__image_snapshots__/data-table-empty__desktop-snap.png
  vrt/__image_snapshots__/data-table-included-rows-change__dark-snap.png
  vrt/__image_snapshots__/data-table-included-rows-change__desktop-snap.png
  vrt/__image_snapshots__/data-table-initial-filters__dark-snap.png
  vrt/__image_snapshots__/data-table-initial-filters__desktop-snap.png
  vrt/__image_snapshots__/data-table-initial-selected-rows__dark-snap.png
  vrt/__image_snapshots__/data-table-initial-selected-rows__desktop-snap.png
  vrt/__image_snapshots__/data-table-initial-sort__dark-snap.png
  vrt/__image_snapshots__/data-table-initial-sort__desktop-snap.png
  vrt/__image_snapshots__/data-table-loading__dark-snap.png
  vrt/__image_snapshots__/data-table-loading__desktop-snap.png
  vrt/__image_snapshots__/data-table-not-filterable__dark-snap.png
  vrt/__image_snapshots__/data-table-not-filterable__desktop-snap.png
  vrt/__image_snapshots__/data-table-not-filterable__mobile-snap.png
  vrt/__image_snapshots__/data-table-not-searchable__dark-snap.png
  vrt/__image_snapshots__/data-table-not-searchable__desktop-snap.png
  vrt/__image_snapshots__/data-table-not-searchable__mobile-snap.png
  vrt/__image_snapshots__/data-table-row-height__dark-snap.png
  vrt/__image_snapshots__/data-table-row-height__desktop-snap.png
  vrt/__image_snapshots__/data-table-row-height__mobile-snap.png
Labels: bugfix

#3801 feat(data-table): stabilize component
  documentation-site/examples/data-table/basic.js
  documentation-site/examples/data-table/basic.tsx
  documentation-site/examples/data-table/batch-action.js
  documentation-site/examples/data-table/batch-action.tsx
  documentation-site/examples/data-table/customized-empty-state.js
  documentation-site/examples/data-table/customized-empty-state.tsx
  documentation-site/examples/data-table/row-height-line-clamp.js
  documentation-site/examples/data-table/row-height-line-clamp.tsx
  documentation-site/pages/components/unstable-data-table.mdx
  scripts/component-sizes.js
  src/data-table/__tests__/data-table-batch-action.scenario.js
  src/data-table/__tests__/data-table-collection-of-objects.scenario.js
  src/data-table/__tests__/data-table-columns-not-sortable.scenario.js
  src/data-table/__tests__/data-table-columns.scenario.js
  src/data-table/__tests__/data-table-empty.scenario.js
  src/data-table/__tests__/data-table-extracted-filters.scenario.js
  src/data-table/__tests__/data-table-extracted-highlight.scenario.js
  src/data-table/__tests__/data-table-full-window.scenario.js
  src/data-table/__tests__/data-table-included-rows-change.scenario.js
  src/data-table/__tests__/data-table-initial-filters.scenario.js
  src/data-table/__tests__/data-table-initial-selected-rows.scenario.js
  src/data-table/__tests__/data-table-initial-sort.scenario.js
  src/data-table/__tests__/data-table-loading.scenario.js
  src/data-table/__tests__/data-table-not-filterable.scenario.js
  src/data-table/__tests__/data-table-not-searchable.scenario.js
  src/data-table/__tests__/data-table-row-actions.scenario.js
  src/data-table/__tests__/data-table-row-height.scenario.js
  src/data-table/__tests__/data-table-rtl.scenario.js
  src/data-table/__tests__/data-table-text-search.scenario.js
  src/data-table/__tests__/data-table.scenario.js
  src/data-table/data-table.js
  src/data-table/index.d.ts
  src/data-table/index.js
  src/data-table/stateful-container.js
  src/data-table/stateful-data-table.js
Labels: feature

#3803 fix(e2e): migrate from deprecated waitFor fn
  documentation-site/pages/blog/visual-regression-testing/index.mdx
  e2e/helpers/index.js
  src/accordion/__tests__/accordion.e2e.js
  src/breadcrumbs/__tests__/breadcrumbs.e2e.js
  src/button-group/__tests__/button-group.e2e.js
  src/button/__tests__/button.e2e.js
  src/checkbox/__tests__/checkbox.e2e.js
  src/data-table/__tests__/data-table-columns-not-sortable.e2e.js
  src/data-table/__tests__/data-table-columns.e2e.js
  src/data-table/__tests__/data-table-extracted-filters.e2e.js
  src/data-table/__tests__/data-table-included-rows-change.e2e.js
  src/data-table/__tests__/data-table-initial-filters.e2e.js
  src/data-table/__tests__/data-table-initial-selected-rows.e2e.js
  src/data-table/__tests__/data-table-initial-sort.e2e.js
  src/data-table/__tests__/data-table-text-search.e2e.js
  src/data-table/__tests__/data-table-unreliable.e2e.js
  src/datepicker/__tests__/calendar.e2e.js
  src/datepicker/__tests__/datepicker-int-range.e2e.js
  src/datepicker/__tests__/datepicker-int.e2e.js
  src/datepicker/__tests__/datepicker-keyboard-nav.e2e.js
  src/datepicker/__tests__/datepicker-range.e2e.js
  src/datepicker/__tests__/datepicker-unreliable.e2e.js
  src/datepicker/__tests__/datepicker.e2e.js
  src/datepicker/__tests__/datepickers-composed-range.e2e.js
  src/datepicker/__tests__/stateful-datepicker-quick-select.e2e.js
  src/datepicker/__tests__/stateful-datepicker.e2e.js
  src/drawer/__tests__/drawer.e2e.js
  src/input/__tests__/input.e2e.js
  src/menu/__tests__/menu.e2e.js
  src/modal/__tests__/modal.e2e.js
  src/pagination/__tests__/pagination.e2e.js
  src/payment-card/__tests__/payment-card.e2e.js
  src/phone-input/__tests__/phone-input-next-dropdown.e2e.js
  src/phone-input/__tests__/phone-input.e2e.js
  src/pin-code/__tests__/pin-code.e2e.js
  src/popover/__tests__/popover-focus-loop.e2e.js
  src/popover/__tests__/popover-unreliable.e2e.js
  src/popover/__tests__/popover.e2e.js
  src/progress-bar/__tests__/progressbar.e2e.js
  src/progress-steps/__tests__/progress-steps.e2e.js
  src/rating/__tests__/rating.e2e.js
  src/select/__tests__/select-backspace-behavior.e2e.js
  src/select/__tests__/select-calls-provided-blur.e2e.js
  src/select/__tests__/select-click-maintains-focus.e2e.js
  src/select/__tests__/select-maintains-input-value.e2e.js
  src/select/__tests__/select.e2e.js
  src/side-navigation/__tests__/nav.e2e.js
  src/tabs-motion/__tests__/tabs-motion.e2e.js
  src/tabs/__tests__/tabs.e2e.js
  src/textarea/__tests__/textarea.e2e.js
  src/timepicker/__tests__/time-picker.e2e.js
  src/timezonepicker/__tests__/timezone-picker.e2e.js
  src/toast/__tests__/toast.e2e.js
  src/tooltip/__tests__/tooltip.e2e.js
  src/tree-view/__tests__/tree-view.e2e.js
  vrt/config.js
  vrt/tests.vrt.js
Labels: bugfix

#3805 fix(typography): add mono-font components typescript definitions
  src/typography/index.d.ts
Labels: chore

#3809 fix(docs): updates the slack invite link
  documentation-site/components/footer.js
  documentation-site/components/header-navigation.js
  documentation-site/pages/getting-started/learn.mdx
Labels: bugfix

#3804 fix(link): add prop types for styled link component
  documentation-site/examples/table-grid/cell-navigation.tsx
  documentation-site/examples/table-grid/cell-span.tsx
  src/link/index.d.ts
Labels: chore

#3819 chore(test): fail unit tests of console warn/error
  src/test/test-setup.js
Labels: bugfix

#3821 chore(test): adds react@next CI job
  .buildkite/pipeline.yml
Labels: chore, ci

#3807 fix(accordion): prevent panel icon from shrinking
  src/accordion/__tests__/__snapshots__/accordion.test.js.snap
  src/accordion/__tests__/__snapshots__/panel.test.js.snap
  src/accordion/styled-components.js
Labels: bugfix, hacktoberfest-accepted

#3839 fix(slider): updates to react-range 1.8.0 and fixes error
  package.json
  src/slider/slider.js
  yarn.lock
Labels: bugfix

#3831 fix(header-navigation): update style to longhand
  src/header-navigation/styled-components.js
Labels: bugfix

#3834 fix(tabs-motion): reduce initial re-rendering
  src/tabs-motion/tabs.js
Labels: bugfix

#3844 fix(radio): expand shorthand css properties
  src/radio/styled-components.js
Labels: bugfix

#3856 fix(dnd-list): wrap dragged items in a layer
  component-sizes.json
  src/dnd-list/list.js
  vrt/__image_snapshots__/tabs-motion-scroll-vertical__dark-snap.png
  vrt/__image_snapshots__/tabs-motion-scroll-vertical__desktop-snap.png
  vrt/__image_snapshots__/tabs-motion-scroll-vertical__mobile-snap.png
Labels: bugfix

#3860 feat(datepicker): add disable mask feature
  documentation-site/examples/datepicker/null-mask.js
  documentation-site/examples/datepicker/null-mask.tsx
  documentation-site/pages/components/datepicker.mdx
  src/datepicker/__tests__/datepicker-mask.scenario.js
  src/datepicker/__tests__/datepicker.test.js
  src/datepicker/datepicker.js
  vrt/__image_snapshots__/data-table-datetime-column__dark-snap.png
  vrt/__image_snapshots__/data-table-datetime-column__desktop-snap.png
  vrt/__image_snapshots__/data-table-datetime-column__mobile-snap.png
  vrt/__image_snapshots__/datepicker-mask__dark-snap.png
  vrt/__image_snapshots__/datepicker-mask__desktop-snap.png
  vrt/__image_snapshots__/datepicker-mask__mobile-snap.png
Labels: feature

#3869 fix(dnd-list): add thumbIndex to ThumbValue
  src/slider/slider.js
Labels: bugfix

#3853 feat(spinner): add determinate spinner
  component-sizes.json
  documentation-site/examples/spinner/determinate.js
  documentation-site/examples/spinner/determinate.tsx
  documentation-site/pages/components/spinner.mdx
  src/helpers/overrides.js
  src/spinner/__tests__/spinner-determinate-animated.scenario.js
  src/spinner/__tests__/spinner-determinate-overrides.scenario.js
  src/spinner/__tests__/spinner-determinate.scenario.js
  src/spinner/index.d.ts
  src/spinner/index.js
  src/spinner/spinner-determinate.js
  src/spinner/styled-components.js
  src/spinner/types.js
  vrt/__image_snapshots__/spinner-determinate-overrides__dark-snap.png
  vrt/__image_snapshots__/spinner-determinate-overrides__desktop-snap.png
  vrt/__image_snapshots__/spinner-determinate-overrides__mobile-snap.png
  vrt/__image_snapshots__/spinner-determinate__dark-snap.png
  vrt/__image_snapshots__/spinner-determinate__desktop-snap.png
  vrt/__image_snapshots__/spinner-determinate__mobile-snap.png
  vrt/config.js
Labels: feature

#3873 docs: fix flow in js stackblitz code
  documentation-site/components/example.js
Labels: docs

#3866 feat(app-nav-bar): add isMainItemActive feature
  src/app-nav-bar/__tests__/app-nav-bar-is-main-item-active.scenario.js
  src/app-nav-bar/app-nav-bar.js
  src/app-nav-bar/index.d.ts
  src/app-nav-bar/types.js
  src/app-nav-bar/utils.js
  vrt/__image_snapshots__/app-nav-bar-is-main-item-active__dark-snap.png
  vrt/__image_snapshots__/app-nav-bar-is-main-item-active__desktop-snap.png
  vrt/__image_snapshots__/app-nav-bar-is-main-item-active__mobile-snap.png
Labels: feature

#3872 fix(stackblitz): pin react to v 16
  documentation-site/components/hooks.js
Labels: chore

#3871 chore(flow): fix flow check
  .buildkite/pipeline.yml
  package.json
  src/datepicker/__tests__/utils.test.js
  src/datepicker/stateful-container.js
Labels: chore

#3870 chore(react-17): fixes tests
  .buildkite/pipeline.yml
  package.json
  src/datepicker/__tests__/datepicker.test.js
  src/toast/__tests__/toaster.test.js
  yarn.lock
Labels: chore

#3878 chore(ci): use stable release in react 17 tests
  .buildkite/pipeline.yml
Labels: chore

#3876 fix(docs): replace stackblitz with codesandbox
  .github/ISSUE_TEMPLATE/1.bug.md
  documentation-site/components/code-sandboxer.js
  documentation-site/components/const.js
  documentation-site/components/example.js
  documentation-site/components/hooks.js
  documentation-site/components/yard/action-buttons.tsx
  documentation-site/pages/components/layout-grid.mdx
  documentation-site/pages/components/tabs-motion.mdx
  package.json
  yarn.lock
Labels: chore

#3882 fix(popover): applies popoverMargin if showArrow true
  src/popover/__tests__/popover-large-margin.scenario.js
  src/popover/__tests__/utils.test.js
  src/popover/utils.js
  src/tooltip/__tests__/tooltip-arrow-margin.scenario.js
  src/tooltip/default-props.js
  vrt/__image_snapshots__/popover-large-margin__dark-snap.png
  vrt/__image_snapshots__/popover-large-margin__desktop-snap.png
  vrt/__image_snapshots__/popover-large-margin__mobile-snap.png
  vrt/__image_snapshots__/tooltip-arrow-margin__dark-snap.png
  vrt/__image_snapshots__/tooltip-arrow-margin__desktop-snap.png
  vrt/__image_snapshots__/tooltip-arrow-margin__mobile-snap.png
Labels: bugfix

#3886 Release v9.104.0
  package.json
Labels: release
