Repository uber/baseweb, pull requests merged in 2020-01, with the labels that each got.

#2548 docs(select): stress importance of id and label as default properties
  documentation-site/pages/components/select.mdx
Labels: docs

#2540 fix(table): show last column border in RTL
  src/table/__tests__/table-rtl.scenario.js
  src/table/styled-components.js
  vrt/__image_snapshots__/table-rtl__desktop-snap.png
  vrt/__image_snapshots__/table-rtl__mobile-snap.png
Labels: bugfix

#2554 fix(toast): adds override props InnerContainer to the typescript def
  src/toast/index.d.ts
Labels: bugfix

#2544 chore(border): update Card Root to follow BorderT pattern
  src/card/styled-components.js
  src/table-semantic/styled-components.js
Labels: bugfix

#2557 docs: fix font flash on initial page loads
  documentation-site/pages/_document.js
Labels: docs

#2551 fix(datepicker): add call to onChange if input value is empty
  src/datepicker/__tests__/datepicker.test.js
  src/datepicker/datepicker.js
Labels: bugfix

#2550 fix(flex-grid): re-implement FlexGridItem to avoid nth-child selectors
  src/flex-grid/__tests__/__snapshots__/flex-grid-item.test.js.snap
  src/flex-grid/__tests__/__snapshots__/flex-grid.test.js.snap
  src/flex-grid/__tests__/flex-grid-item.test.js
  src/flex-grid/flex-grid-item.js
  src/flex-grid/flex-grid.js
  src/flex-grid/index.d.ts
  src/flex-grid/types.js
Labels: bugfix

#2558 Release v9.34.1
  package.json
Labels: release

#2560 chore(checkbox): add comment for v10 change
  src/checkbox/checkbox.js
Labels: greenkeeping

#2449 feat(menu): add home, end key navigation to menu
  src/menu/constants.js
  src/menu/stateful-container.js
Labels: feature

#2564 docs(tables): create a new category in the side nav
  documentation-site/routes.js
Labels: docs

#2566 docs(side-nav): add mapItem and activePredicate
  documentation-site/components/yard/config/side-nav.ts
Labels: docs

#2567 fix(side-nav): correct yard config types
  documentation-site/components/yard/config/side-nav.ts
Labels: bugfix

#2486 feat(data-table): enables column resizing
  src/data-table/__tests__/data-table-columns.e2e.js
  src/data-table/data-table.js
  src/data-table/header-cell.js
Labels: feature

#2569 chore(project): update to the lts nodejs version
  .nvmrc
  build-now.sh
  package.json
Labels: greenkeeping

#2570 Release v9.35.0
  package.json
Labels: release

#2565 docs(theming): update guide
  documentation-site/components/theming-values/borders.js
  documentation-site/components/theming-values/colors.js
  documentation-site/components/theming-values/common.js
  documentation-site/components/theming-values/lighting.js
  documentation-site/components/theming-values/sizing.js
  documentation-site/components/theming-values/typography.js
  documentation-site/components/theming/animations.js
  documentation-site/components/theming/borders.js
  documentation-site/components/theming/breakpoints.js
  documentation-site/components/theming/colors.js
  documentation-site/components/theming/common.js
  documentation-site/components/theming/grid.js
  documentation-site/components/theming/lighting.js
  documentation-site/components/theming/sizing.js
  documentation-site/components/theming/typography.js
  documentation-site/pages/guides/theming.mdx
Labels: docs

#2572 docs(gallery): update to match tables sections
  documentation-site/components/gallery.js
  documentation-site/components/thumbs/index.js
Labels: docs

#2576 feat(timepicker): add size prop
  documentation-site/components/yard/config/timepicker.ts
  documentation-site/components/yard/config/timezonepicker.ts
  src/timepicker/__tests__/time-picker.scenario.js
  src/timepicker/index.d.ts
  src/timepicker/timepicker.js
  src/timepicker/types.js
  src/timezonepicker/index.d.ts
  src/timezonepicker/timezone-picker.js
  src/timezonepicker/types.js
  vrt/__image_snapshots__/time-picker__dark-snap.png
  vrt/__image_snapshots__/time-picker__desktop-snap.png
  vrt/__image_snapshots__/time-picker__mobile-snap.png
Labels: feature

#2581 fix(data-table): ignore case in search
  src/data-table/data-table.js
Labels: bugfix

#2577 feat(timezone): export the timezone type
  src/timezonepicker/index.d.ts
  src/timezonepicker/types.js
Labels: feature

#2583 fix(checkbox): fix undefined style value when disabled/not checked
  src/checkbox/styled-components.js
Labels: bugfix

#2584 Release v9.36.0
  package.json
Labels: release

#2585 docs: add API table for button
  documentation-site/components/api-table.js
  documentation-site/components/table-of-contents.js
  documentation-site/components/yard/type-definition.js
  documentation-site/pages/components/accordion.mdx
  documentation-site/pages/components/avatar.mdx
  documentation-site/pages/components/breadcrumbs.mdx
  documentation-site/pages/components/button-group.mdx
  documentation-site/pages/components/button.mdx
  documentation-site/pages/components/card.mdx
  documentation-site/pages/components/checkbox.mdx
  documentation-site/pages/components/datepicker.mdx
  documentation-site/pages/components/dnd-list.mdx
  documentation-site/pages/components/drawer.mdx
  documentation-site/pages/components/file-uploader.mdx
  documentation-site/pages/components/form-control.mdx
  documentation-site/pages/components/header-navigation.mdx
  documentation-site/pages/components/icon.mdx
  documentation-site/pages/components/input.mdx
  documentation-site/pages/components/link.mdx
  documentation-site/pages/components/list.mdx
  documentation-site/pages/components/menu.mdx
  documentation-site/pages/components/modal.mdx
  documentation-site/pages/components/notification.mdx
  documentation-site/pages/components/pagination.mdx
  documentation-site/pages/components/payment-card.mdx
  documentation-site/pages/components/phone-input.mdx
  documentation-site/pages/components/pin-code.mdx
  documentation-site/pages/components/popover.mdx
  documentation-site/pages/components/progress-bar.mdx
  documentation-site/pages/components/progress-steps.mdx
  documentation-site/pages/components/radio.mdx
  documentation-site/pages/components/rating.mdx
  documentation-site/pages/components/select.mdx
  documentation-site/pages/components/side-nav.mdx
  documentation-site/pages/components/slider.mdx
  documentation-site/pages/components/spinner.mdx
  documentation-site/pages/components/table-semantic.mdx
  documentation-site/pages/components/table.mdx
  documentation-site/pages/components/tabs.mdx
  documentation-site/pages/components/tag.mdx
  documentation-site/pages/components/textarea.mdx
  documentation-site/pages/components/time-picker.mdx
  documentation-site/pages/components/timezone-picker.mdx
  documentation-site/pages/components/toast.mdx
  documentation-site/pages/components/tooltip.mdx
  src/select/select-component.js
  src/select/types.js
Labels: docs

#2588 fix(select): add warning for value prop miss-use
  src/select/select-component.js
Labels: bugfix

#2568 fix(select): stop event propagation when option from select dropdown clicked
  src/popover/__tests__/popover-select.scenario.js
  src/popover/__tests__/popover.e2e.js
  src/select/__tests__/select.e2e.js
  src/select/dropdown.js
  vrt/__image_snapshots__/popover-select__dark-snap.png
  vrt/__image_snapshots__/popover-select__desktop-snap.png
  vrt/__image_snapshots__/popover-select__mobile-snap.png
Labels: bugfix

#2590 chore: Minor grammatical tweak
  src/select/select-component.js
Labels: bugfix

#2587 feat(card): add img props
  documentation-site/components/yard/config/card.ts
  src/card/__tests__/card-image-object.scenario.js
  src/card/__tests__/card.test.js
  src/card/card.js
  src/card/index.d.ts
  src/card/types.js
  vrt/__image_snapshots__/card-image-object__dark-snap.png
  vrt/__image_snapshots__/card-image-object__desktop-snap.png
  vrt/__image_snapshots__/card-image-object__mobile-snap.png
Labels: feature

#2593 Release v9.37.0
  package.json
Labels: release

#2596 fix(select): more accurate prop type for Select component
  src/select/select.js
Labels: bugfix

#2597 fix(tag): update tag types
  src/tag/index.d.ts
Labels: bugfix

#2599 docs(theming): update anchor links that point to theming guide
  documentation-site/components/yard/theme-editor.tsx
  documentation-site/pages/blog/base-web-v7/index.mdx
  documentation-site/pages/blog/getting-started-with-base-web/index.mdx
  documentation-site/pages/blog/responsive-web/index.mdx
  documentation-site/pages/components/base-provider.mdx
  documentation-site/pages/components/input.mdx
  documentation-site/pages/components/layout-grid.mdx
  documentation-site/pages/components/styled.mdx
  documentation-site/pages/components/typography.mdx
  documentation-site/pages/components/use-styletron.mdx
  documentation-site/pages/guides/understanding-overrides.mdx
Labels: docs

#2601 Release v9.37.1
  package.json
Labels: release

#2582 fix(phone-input): autocomplete to show phone numbers without dialcode
  src/phone-input/phone-input-lite.js
Labels: bugfix

#2602 docs(adopters): add streamlit
  documentation-site/pages/index.js
  documentation-site/static/images/streamlit-logo.png
Labels: docs

#2603 fix(timezone-picker): include options with no acronym
  src/timezonepicker/__tests__/timezone-picker.e2e.js
  src/timezonepicker/timezone-picker.js
Labels: bugfix

#2605 fix(datepicker): handle hyphens and em dashes
  src/datepicker/__tests__/datepicker.test.js
  src/datepicker/datepicker.js
Labels: bugfix

#2606 Release v9.37.2
  package.json
Labels: release

#2611 fix(popover): update link to popper.js docs
  src/layer/types.js
  src/popover/types.js
Labels: bugfix

#2612 feat(semantic-table): make it stable
  documentation-site/components/api-table.js
  documentation-site/components/yard/config/table-semantic.ts
  documentation-site/examples/table-semantic/basic.js
  documentation-site/examples/table-semantic/basic.tsx
  documentation-site/examples/table-semantic/builder.js
  documentation-site/examples/table-semantic/builder.tsx
  documentation-site/examples/table-semantic/scroll.js
  documentation-site/examples/table-semantic/scroll.tsx
  documentation-site/examples/table-semantic/sortable.js
  documentation-site/examples/table-semantic/sortable.tsx
  documentation-site/examples/table-semantic/toggleable.js
  documentation-site/examples/table-semantic/toggleable.tsx
  documentation-site/pages/components/layout-grid.mdx
  documentation-site/pages/components/table-semantic.mdx
  scripts/component-sizes.js
  src/table-semantic/__tests__/table-builder.test.js
  src/table-semantic/__tests__/table-semantic-builder.scenario.js
  src/table-semantic/__tests__/table-semantic.scenario.js
  src/table-semantic/__tests__/table.test.js
  src/table-semantic/index.d.ts
  src/table-semantic/index.js
Labels: feature

#2607 docs(tooltip): change default triggerType to hover
  documentation-site/components/yard/config/tooltip.ts
Labels: bugfix

#2608 fix(avatar): reset to error state when src is missing
  src/avatar/__tests__/avatar.test.js
  src/avatar/avatar.js
Labels: bugfix

#2604 fix(select): allow clear icon svg overrides
  src/select/select-component.js
Labels: bugfix

#2614 Release v9.38.0
  package.json
Labels: release

#2619 feat(checkbox, radio): update default border color
  src/themes/light-theme/color-component-tokens.js
  vrt/__image_snapshots__/checkbox-indeterminate__desktop-snap.png
  vrt/__image_snapshots__/checkbox-indeterminate__mobile-snap.png
  vrt/__image_snapshots__/checkbox-rtl__desktop-snap.png
  vrt/__image_snapshots__/checkbox-rtl__mobile-snap.png
  vrt/__image_snapshots__/checkbox-states__desktop-snap.png
  vrt/__image_snapshots__/checkbox-states__mobile-snap.png
  vrt/__image_snapshots__/checkbox-unlabeled__desktop-snap.png
  vrt/__image_snapshots__/checkbox-unlabeled__mobile-snap.png
  vrt/__image_snapshots__/checkbox__desktop-snap.png
  vrt/__image_snapshots__/checkbox__mobile-snap.png
  vrt/__image_snapshots__/data-table-batch-action__desktop-snap.png
  vrt/__image_snapshots__/data-table-batch-action__mobile-snap.png
  vrt/__image_snapshots__/data-table-categorical-column__desktop-snap.png
  vrt/__image_snapshots__/data-table-categorical-column__mobile-snap.png
  vrt/__image_snapshots__/data-table-extracted-filters__desktop-snap.png
  vrt/__image_snapshots__/data-table-extracted-filters__mobile-snap.png
  vrt/__image_snapshots__/data-table-row-height__desktop-snap.png
  vrt/__image_snapshots__/data-table-row-height__mobile-snap.png
  vrt/__image_snapshots__/form-control__desktop-snap.png
  vrt/__image_snapshots__/form-control__mobile-snap.png
  vrt/__image_snapshots__/radio-rtl__desktop-snap.png
  vrt/__image_snapshots__/radio-rtl__mobile-snap.png
  vrt/__image_snapshots__/radio-states__desktop-snap.png
  vrt/__image_snapshots__/radio-states__mobile-snap.png
  vrt/__image_snapshots__/radio__desktop-snap.png
  vrt/__image_snapshots__/radio__mobile-snap.png
Labels: feature

#2621 fix(select): don't perform setState on unmounted component
  src/select/select-component.js
Labels: bugfix

#2618 feat(layout-grid): make layout grid stable
  documentation-site/examples/layout-grid/align.js
  documentation-site/examples/layout-grid/align.tsx
  documentation-site/examples/layout-grid/basic.js
  documentation-site/examples/layout-grid/basic.tsx
  documentation-site/examples/layout-grid/behavior.js
  documentation-site/examples/layout-grid/behavior.tsx
  documentation-site/examples/layout-grid/custom.js
  documentation-site/examples/layout-grid/custom.tsx
  documentation-site/examples/layout-grid/hide.js
  documentation-site/examples/layout-grid/hide.tsx
  documentation-site/examples/layout-grid/order.js
  documentation-site/examples/layout-grid/order.tsx
  documentation-site/examples/layout-grid/responsive.js
  documentation-site/examples/layout-grid/responsive.tsx
  documentation-site/examples/layout-grid/skip-shrink.js
  documentation-site/examples/layout-grid/skip-shrink.tsx
  documentation-site/examples/layout-grid/skip.js
  documentation-site/examples/layout-grid/skip.tsx
  documentation-site/examples/layout-grid/span.js
  documentation-site/examples/layout-grid/span.tsx
  documentation-site/pages/components/layout-grid.mdx
  src/layout-grid/__tests__/layout-grid-align.scenario.js
  src/layout-grid/__tests__/layout-grid-custom.scenario.js
  src/layout-grid/__tests__/layout-grid-hide.scenario.js
  src/layout-grid/__tests__/layout-grid-order.scenario.js
  src/layout-grid/__tests__/layout-grid-sizing.scenario.js
  src/layout-grid/__tests__/layout-grid-skip.scenario.js
  src/layout-grid/__tests__/layout-grid-wrap.scenario.js
  src/layout-grid/__tests__/layout-grid.scenario.js
  src/layout-grid/index.d.ts
  src/layout-grid/index.js
  src/utils/deprecated-component.js
Labels: feature

#2625 Release v9.39.0
  package.json
Labels: release

#2615 feat(slider): add step to useThumbOverlap for decimals
  package.json
  src/slider/slider.js
  vrt/__image_snapshots__/slider-disabled__desktop-snap.png
  vrt/__image_snapshots__/slider-disabled__mobile-snap.png
  vrt/__image_snapshots__/slider-range__desktop-snap.png
  vrt/__image_snapshots__/slider-range__mobile-snap.png
  vrt/__image_snapshots__/slider-rtl__mobile-snap.png
  vrt/__image_snapshots__/slider-step__desktop-snap.png
  vrt/__image_snapshots__/slider-step__mobile-snap.png
  vrt/__image_snapshots__/slider__desktop-snap.png
  vrt/__image_snapshots__/slider__mobile-snap.png
  yarn.lock
Labels: feature

#2627 docs(version): failed deploys on the list of docs not shown
  documentation-site/components/version-selector.js
Labels: docs

#2624 docs(home-page): make avatars smaller in size
  documentation-site/components/contributors.js
Labels: docs

#2628 fix(layer): fix for a regression breaking layer's index prop usage
  src/layer/__tests__/layer.test.js
  src/layer/layer.js
Labels: bugfix

#2629 Release v9.39.1
  package.json
Labels: release

#2635 docs(walkthrough): remove
  documentation-site/components/layout.js
  documentation-site/components/walkthrough.js
Labels: docs

#2632 feat(components): add a mini size
  src/button/__tests__/button-sizes.scenario.js
  src/button/constants.js
  src/button/styled-components.js
  src/input/__tests__/input-sizes.scenario.js
  src/input/base-input.js
  src/input/constants.js
  src/input/styled-components.js
  src/payment-card/payment-card.js
  src/payment-card/styled-components.js
  src/phone-input/flag.js
  src/phone-input/styled-components.js
  src/pin-code/styled-components.js
  src/select/__tests__/select-sizes.scenario.js
  src/select/styled-components.js
  vrt/__image_snapshots__/button-sizes__dark-snap.png
  vrt/__image_snapshots__/button-sizes__desktop-snap.png
  vrt/__image_snapshots__/button-sizes__mobile-snap.png
  vrt/__image_snapshots__/input-sizes__dark-snap.png
  vrt/__image_snapshots__/input-sizes__desktop-snap.png
  vrt/__image_snapshots__/input-sizes__mobile-snap.png
  vrt/__image_snapshots__/select-sizes__dark-snap.png
  vrt/__image_snapshots__/select-sizes__desktop-snap.png
  vrt/__image_snapshots__/select-sizes__mobile-snap.png
Labels: feature

#2639 Release v9.40.0
  package.json
Labels: release

#2637 feat(block): add scale transformation to top, right, left, and bottom
  CONTRIBUTING.md
  src/block/styled-components.js
Labels: feature

#2642 fix(docs): add forward ref on input tag + update overrides ts types
  documentation-site/examples/dnd-list/overrides_whole_subcomponent.tsx
  documentation-site/examples/input/with-tags.js
  documentation-site/examples/input/with-tags.tsx
  documentation-site/examples/pagination/overrides.tsx
  src/overrides.ts
Labels: bugfix

#2616 feat(eslint): add eslint-plugin-baseui package
  .eslintrc.js
  deploy.sh
  documentation-site/pages/getting-started/setup.mdx
  packages/eslint-plugin-baseui/.eslintrc.js
  packages/eslint-plugin-baseui/README.md
  packages/eslint-plugin-baseui/__tests__/deprecated-component-api.test.js
  packages/eslint-plugin-baseui/__tests__/deprecated-theme-api-test.js
  packages/eslint-plugin-baseui/__tests__/no-deep-imports.js
  packages/eslint-plugin-baseui/bump.js
  packages/eslint-plugin-baseui/index.js
  packages/eslint-plugin-baseui/package.json
  packages/eslint-plugin-baseui/src/deprecated-component-api.js
  packages/eslint-plugin-baseui/src/deprecated-theme-api.js
  packages/eslint-plugin-baseui/src/index.js
  packages/eslint-plugin-baseui/src/messages.js
  packages/eslint-plugin-baseui/src/no-deep-imports.js
  packages/eslint-plugin-baseui/yarn.lock
Labels: feature

#2643 fix(input): autocomplete for password
  documentation-site/pages/components/input.mdx
  src/input/__tests__/base-input.test.js
  src/input/base-input.js
Labels: bugfix

#2644 Release v9.41.0
  package.json
Labels: release

#2646 chore(eslint-plugin-baseui): add some info to readme and package.json
  packages/eslint-plugin-baseui/README.md
  packages/eslint-plugin-baseui/package.json
Labels: feature

#2641 feat(data-table): added empty state
  documentation-site/examples/data-table/customized-empty-state.js
  documentation-site/examples/data-table/customized-empty-state.tsx
  documentation-site/pages/components/unstable-data-table.mdx
  src/data-table/data-table.js
  src/data-table/locale.js
  src/data-table/stateful-data-table.js
  src/data-table/styled-components.js
  src/data-table/types.js
  src/locale/en_US.js
  src/locale/types.js
Labels: feature

#2648 Release v9.42.0
  package.json
Labels: release

#2645 fix(data-table): does not introduce scroll bars if full height/width
  .storybook/preview-head.html
  src/data-table/__tests__/data-table-batch-action.scenario.js
  src/data-table/__tests__/data-table-full-window.scenario.js
  src/data-table/data-table.js
  vrt/__image_snapshots__/data-table-batch-action__dark-snap.png
  vrt/__image_snapshots__/data-table-batch-action__desktop-snap.png
  vrt/__image_snapshots__/data-table-batch-action__mobile-snap.png
  vrt/__image_snapshots__/data-table-collection-of-objects__dark-snap.png
  vrt/__image_snapshots__/data-table-collection-of-objects__desktop-snap.png
  vrt/__image_snapshots__/data-table-collection-of-objects__mobile-snap.png
  vrt/__image_snapshots__/data-table-columns__dark-snap.png
  vrt/__image_snapshots__/data-table-columns__desktop-snap.png
  vrt/__image_snapshots__/data-table-columns__mobile-snap.png
  vrt/__image_snapshots__/data-table-extracted-filters__dark-snap.png
  vrt/__image_snapshots__/data-table-extracted-filters__desktop-snap.png
  vrt/__image_snapshots__/data-table-extracted-filters__mobile-snap.png
  vrt/__image_snapshots__/data-table-extracted-highlight__controlledRowHighlightIndex-snap.png
  vrt/__image_snapshots__/data-table-extracted-highlight__dark-snap.png
  vrt/__image_snapshots__/data-table-extracted-highlight__desktop-snap.png
  vrt/__image_snapshots__/data-table-extracted-highlight__mobile-snap.png
  vrt/__image_snapshots__/data-table-extracted-highlight__rowHighlightScrollsTableDown-snap.png
  vrt/__image_snapshots__/data-table-extracted-highlight__rowHighlightScrollsTableUp-snap.png
  vrt/__image_snapshots__/data-table-full-window__dark-snap.png
  vrt/__image_snapshots__/data-table-full-window__desktop-snap.png
  vrt/__image_snapshots__/data-table-full-window__mobile-snap.png
  vrt/__image_snapshots__/data-table-row-actions__dark-snap.png
  vrt/__image_snapshots__/data-table-row-actions__desktop-snap.png
  vrt/__image_snapshots__/data-table-row-actions__mobile-snap.png
  vrt/__image_snapshots__/data-table-row-height__dark-snap.png
  vrt/__image_snapshots__/data-table-row-height__desktop-snap.png
  vrt/__image_snapshots__/data-table-row-height__mobile-snap.png
  vrt/__image_snapshots__/data-table-text-search__dark-snap.png
  vrt/__image_snapshots__/data-table-text-search__desktop-snap.png
  vrt/__image_snapshots__/data-table-text-search__mobile-snap.png
  vrt/__image_snapshots__/data-table__dark-snap.png
  vrt/__image_snapshots__/data-table__desktop-snap.png
Labels: bugfix

#2650 feat(popover): add autoFocus and returnFocus
  documentation-site/components/yard/config/popover.ts
  documentation-site/components/yard/config/tooltip.ts
  documentation-site/pages/components/popover.mdx
  src/datepicker/calendar-header.js
  src/datepicker/datepicker.js
  src/menu/__tests__/menu.e2e.js
  src/menu/maybe-child-menu.js
  src/phone-input/country-select.js
  src/phone-input/default-props.js
  src/popover/__tests__/__snapshots__/popover.test.js.snap
  src/popover/__tests__/__snapshots__/stateful-popover.test.js.snap
  src/popover/__tests__/popover.test.js
  src/popover/default-props.js
  src/popover/popover.js
  src/popover/types.js
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/select-component.js
  src/tooltip/__tests__/__snapshots__/stateful-tooltip.test.js.snap
  src/tooltip/default-props.js
Labels: feature

#2653 Release v9.43.0
  package.json
Labels: release

#2663 docs(header-navigation): fix weird padding in burger menu button
  documentation-site/components/header-navigation.js
Labels: docs

#2664 feat(vscode): add skeleton
  Dockerfile
  deploy.sh
  docker-compose.yml
  package.json
  packages/baseweb-vscode-extension/.npmrc
  packages/baseweb-vscode-extension/.vscodeignore
  packages/baseweb-vscode-extension/README.md
  packages/baseweb-vscode-extension/package.json
  packages/baseweb-vscode-extension/src/extension.ts
  packages/baseweb-vscode-extension/src/test/runTest.ts
  packages/baseweb-vscode-extension/src/test/suite/extension.test.ts
  packages/baseweb-vscode-extension/src/test/suite/index.ts
  packages/baseweb-vscode-extension/tsconfig.json
  packages/baseweb-vscode-extension/tslint.json
  packages/baseweb-vscode-extension/vsc-extension-quickstart.md
  packages/baseweb-vscode-extension/yarn.lock
  packages/eslint-plugin-baseui/package.json
  scripts/sync-package-versions.js
  yarn.lock
Labels: feature

#2655 chore(layer): add console warning for missing BaseProvider/LayersManager
  src/layer/layer.js
Labels: bugfix

#2631 feat: add href support to menu item
  src/menu/option-list.js
  src/menu/styled-components.js
  src/menu/types.js
Labels: feature

#2666 Release v9.44.0
  package.json
Labels: release

#2669 fix(vscode): add dep to the package
  deploy.sh
  package.json
  packages/baseweb-vscode-extension/package.json
  packages/baseweb-vscode-extension/yarn.lock
  yarn.lock
Labels: bugfix

#2671 docs(eslint-plugin-baseui): small tweaks
  packages/eslint-plugin-baseui/README.md
  packages/eslint-plugin-baseui/package.json
Labels: docs

#2674 chore(refs): forward refs for FlexGrid, FlexGridItem, and AspectRatioBox
  src/aspect-ratio-box/__tests__/__snapshots__/aspect-ratio-box.test.js.snap
  src/aspect-ratio-box/aspect-ratio-box.js
  src/aspect-ratio-box/types.js
  src/flex-grid/__tests__/__snapshots__/flex-grid-item.test.js.snap
  src/flex-grid/__tests__/__snapshots__/flex-grid.test.js.snap
  src/flex-grid/flex-grid-item.js
  src/flex-grid/flex-grid.js
Labels: feature

#2667 fix(form-control): add data attribute to form-control-caption
  src/form-control/__tests__/form-control.test.js
  src/form-control/form-control.js
Labels: bugfix

#2675 Release v9.44.1
  package.json
Labels: release

#2676 chore(ts): disable vscode-extension till lerna adoption
  tsconfig.json
Labels: greenkeeping

#2668 fix(datepicker): pass sharedProps and custom dayProps to empty days rendered
  src/datepicker/day.js
  src/datepicker/styled-components.js
Labels: bugfix

#2678 fix(vscode): add publisher
  packages/baseweb-vscode-extension/package.json
Labels: bugfix

#2657 fix(toast): deduplicate toasts with same key
  documentation-site/components/yard/config/toast.ts
  documentation-site/examples/toast/toast-same-key-notification.js
  documentation-site/examples/toast/toast-same-key-notification.tsx
  documentation-site/pages/components/toast.mdx
  src/toast/__tests__/toast.e2e.js
  src/toast/__tests__/toaster.scenario.js
  src/toast/__tests__/toaster.test.js
  src/toast/toast.js
  src/toast/toaster.js
  src/toast/types.js
  vrt/__image_snapshots__/toaster__dark-snap.png
  vrt/__image_snapshots__/toaster__desktop-snap.png
  vrt/__image_snapshots__/toaster__mobile-snap.png
Labels: bugfix

#2661 fix(progress-steps): refactor unncessary ContentTail :after into just plain div
  src/progress-steps/styled-components.js
  vrt/__image_snapshots__/progress-steps-rtl__desktop-snap.png
  vrt/__image_snapshots__/progress-steps-rtl__mobile-snap.png
  vrt/__image_snapshots__/progress-steps__dark-snap.png
  vrt/__image_snapshots__/progress-steps__desktop-snap.png
  vrt/__image_snapshots__/progress-steps__mobile-snap.png
  vrt/__image_snapshots__/progress-steps__triggerNextStep-snap.png
Labels: bugfix

#2672 fix(datepicker): advance calendar only if date is not isInView
  documentation-site/components/yard/config/datepicker.ts
  src/datepicker/__tests__/datepicker-range-multi-month.scenario.js
  src/datepicker/__tests__/datepicker-range.e2e.js
  src/datepicker/__tests__/datepicker.e2e.js
  src/datepicker/__tests__/datepicker.scenario.js
  src/datepicker/calendar.js
  vrt/__image_snapshots__/datepicker-range-multi-month__dark-snap.png
  vrt/__image_snapshots__/datepicker-range-multi-month__desktop-snap.png
  vrt/__image_snapshots__/datepicker-range-multi-month__mobile-snap.png
Labels: bugfix

#2681 Release v9.44.2
  package.json
Labels: release

#2686 fix(modal): add warning for closeable prop
  src/modal/__tests__/modal-uncloseable.scenario.js
  src/modal/__tests__/modal.scenario.js
  src/modal/modal.js
  vrt/__image_snapshots__/modal-uncloseable__dark-snap.png
  vrt/__image_snapshots__/modal-uncloseable__desktop-snap.png
  vrt/__image_snapshots__/modal-uncloseable__mobile-snap.png
Labels: bugfix

#2688 chore: update react-range and react-view
  package.json
  yarn.lock
Labels: chore, greenkeeping

#2689 fix(theme): have theme specific lighting and borders
  src/themes/creator.js
  src/themes/dark-theme/borders.js
  src/themes/dark-theme/dark-theme.js
  src/themes/dark-theme/lighting.js
  src/themes/light-theme/light-theme.js
  src/themes/light-theme/lighting.js
  src/themes/shared/borders.js
  vrt/__image_snapshots__/card__dark-snap.png
  vrt/__image_snapshots__/checkbox-toggle-round__dark-snap.png
  vrt/__image_snapshots__/checkbox-toggle__dark-snap.png
  vrt/__image_snapshots__/data-table-batch-action__dark-snap.png
  vrt/__image_snapshots__/data-table-categorical-column__dark-snap.png
  vrt/__image_snapshots__/data-table-collection-of-objects__dark-snap.png
  vrt/__image_snapshots__/data-table-columns__dark-snap.png
  vrt/__image_snapshots__/data-table-extracted-filters__dark-snap.png
  vrt/__image_snapshots__/data-table-extracted-highlight__dark-snap.png
  vrt/__image_snapshots__/data-table-full-window__dark-snap.png
  vrt/__image_snapshots__/data-table-numerical-column__dark-snap.png
  vrt/__image_snapshots__/data-table-row-actions__dark-snap.png
  vrt/__image_snapshots__/data-table-row-height__dark-snap.png
  vrt/__image_snapshots__/data-table-text-search__dark-snap.png
  vrt/__image_snapshots__/data-table__dark-snap.png
  vrt/__image_snapshots__/list-item-menu-adapter__dark-snap.png
  vrt/__image_snapshots__/menu-child__dark-snap.png
  vrt/__image_snapshots__/menu-empty__dark-snap.png
  vrt/__image_snapshots__/menu-grouped-items__dark-snap.png
  vrt/__image_snapshots__/menu-stateful__dark-snap.png
  vrt/__image_snapshots__/menu-virtualized__dark-snap.png
  vrt/__image_snapshots__/menu__dark-snap.png
  vrt/__image_snapshots__/popover__dark-snap.png
  vrt/__image_snapshots__/select-open__dark-snap.png
  vrt/__image_snapshots__/table-borderless__dark-snap.png
  vrt/__image_snapshots__/table-cells__dark-snap.png
  vrt/__image_snapshots__/table-few-rows__dark-snap.png
  vrt/__image_snapshots__/table-filter__dark-snap.png
  vrt/__image_snapshots__/table-grid-jobs__dark-snap.png
  vrt/__image_snapshots__/table-grid-records__dark-snap.png
  vrt/__image_snapshots__/table-grid__dark-snap.png
  vrt/__image_snapshots__/table-pagination__dark-snap.png
  vrt/__image_snapshots__/table-scroll__dark-snap.png
  vrt/__image_snapshots__/table-semantic-builder__dark-snap.png
  vrt/__image_snapshots__/table-semantic-compose__dark-snap.png
  vrt/__image_snapshots__/table-semantic__dark-snap.png
  vrt/__image_snapshots__/table-sortable-fill-click__dark-snap.png
  vrt/__image_snapshots__/table-sortable__dark-snap.png
  vrt/__image_snapshots__/toast__dark-snap.png
  vrt/__image_snapshots__/tree-view__dark-snap.png
Labels: bugfix

#2660 fix(radio): margin considering horizontal/vertical/rtl/description
  src/radio/radio.js
  src/radio/radiogroup.js
  src/radio/styled-components.js
  src/radio/types.js
Labels: bugfix

#2693 fix(vscode): add repository field to package.json
  packages/baseweb-vscode-extension/.gitignore
  packages/baseweb-vscode-extension/package.json
Labels: bugfix

#2697 docs(theming): fix object syntax
  documentation-site/pages/guides/theming.mdx
Labels: docs

#2699 Release v9.44.3
  package.json
Labels: release

#2700 docs(types): add the proper env var for extract-types-loader
  docker-compose.yml
  package.json
  yarn.lock
Labels: bugfix

#2701 fix(vscode): remove failing ts checks for now
  packages/baseweb-vscode-extension/package.json
Labels: bugfix

#2682 feat(theme): misc updates and fixes based on design QA
  documentation-site/components/theming/colors.js
  documentation-site/pages/guides/theming.mdx
  src/theme.ts
  src/themes/dark-theme/color-semantic-tokens.js
  src/themes/dark-theme/color-tokens.js
  src/themes/light-theme/color-component-tokens.js
  src/themes/light-theme/color-semantic-tokens.js
  src/themes/light-theme/color-tokens.js
  src/themes/types.js
  vrt/__image_snapshots__/checkbox-states__dark-snap.png
  vrt/__image_snapshots__/checkbox-toggle-round__dark-snap.png
  vrt/__image_snapshots__/data-table__dark-snap.png
  vrt/__image_snapshots__/file-uploader-error__dark-snap.png
  vrt/__image_snapshots__/notification__dark-snap.png
  vrt/__image_snapshots__/notification__desktop-snap.png
  vrt/__image_snapshots__/notification__mobile-snap.png
  vrt/__image_snapshots__/progressbar-negative__dark-snap.png
  vrt/__image_snapshots__/spinner-negative__dark-snap.png
  vrt/__image_snapshots__/table-cells__dark-snap.png
  vrt/__image_snapshots__/tag-rtl__desktop-snap.png
  vrt/__image_snapshots__/tag-rtl__mobile-snap.png
  vrt/__image_snapshots__/tag__dark-snap.png
  vrt/__image_snapshots__/tag__desktop-snap.png
  vrt/__image_snapshots__/tag__mobile-snap.png
  vrt/__image_snapshots__/toast__dark-snap.png
  vrt/__image_snapshots__/toast__desktop-snap.png
  vrt/__image_snapshots__/toast__mobile-snap.png
Labels: docs, feature

#2705 fix(vscode): do not expose PAT
  deploy.sh
Labels: bugfix

#2706 Release v9.45.0
  package.json
Labels: release

#2707 docs(contribution): expand on what should not be in base
  CONTRIBUTING.md
Labels: docs

#2709 fix(vscode): deploy :fingers-crossed:
  deploy.sh
  packages/baseweb-vscode-extension/README.md
  packages/baseweb-vscode-extension/images/icon.png
  packages/baseweb-vscode-extension/package.json
Labels: bugfix

#2580 feat(table): implement loading state
  documentation-site/components/yard/config/progress-bar.ts
  documentation-site/components/yard/config/table.ts
  documentation-site/examples/progress-bar/infinite.js
  documentation-site/examples/progress-bar/infinite.tsx
  documentation-site/pages/components/progress-bar.mdx
  scripts/validate-examples.js
  src/progress-bar/__tests__/__snapshots__/progressbar.test.js.snap
  src/progress-bar/index.d.ts
  src/progress-bar/progressbar.js
  src/progress-bar/styled-components.js
  src/progress-bar/types.js
  src/table/table.js
Labels: ci, feature

#2710 Release v9.46.0
  package.json
Labels: release

#2712 chore: add new promo image to README
  README.md
Labels: docs

#2715 chore(scripts): run scripts with node command
  package.json
Labels: bugfix

#2718 test(vrt): update shadows for some snapshots
  vrt/__image_snapshots__/checkbox-toggle-round__dark-snap.png
  vrt/__image_snapshots__/country-select-dropdown__expanded-snap.png
  vrt/__image_snapshots__/country-select-small-dropdown__expanded-snap.png
  vrt/__image_snapshots__/drawer-select__selectDropdownVisible-snap.png
  vrt/__image_snapshots__/select-in-modal__selectDropdownVisible-snap.png
  vrt/__image_snapshots__/select-open__dark-snap.png
  vrt/__image_snapshots__/select-open__desktop-snap.png
  vrt/__image_snapshots__/select-open__mobile-snap.png
  vrt/__image_snapshots__/select-option-group__selectGroupDropdownVisible-snap.png
  vrt/__image_snapshots__/select-search-single-fontsize__showsAllText-snap.png
  vrt/__image_snapshots__/select-search-single__open-snap.png
  vrt/__image_snapshots__/toast__dark-snap.png
  vrt/__image_snapshots__/toast__desktop-snap.png
  vrt/__image_snapshots__/toast__mobile-snap.png
Labels: bugfix, build/tooling, chore

#2723 docs(contributing): minor improvement
  CONTRIBUTING.md
Labels: docs

#2724 docs(versioning-policy): updates
  documentation-site/pages/discover-more/supported-platforms.mdx
Labels: docs

#2729 fix(vscode): fix bootstrapping of the extension
  packages/baseweb-vscode-extension/package.json
  packages/baseweb-vscode-extension/tsconfig.json
  packages/baseweb-vscode-extension/yarn.lock
Labels: bugfix

#2727 Popover stateful pass props
  src/popover/__tests__/__snapshots__/stateful-container.test.js.snap
  src/popover/stateful-container.js
Labels: bugfix

#2713 feat(popover): added popover renderAll prop, tests and docs
  documentation-site/components/yard/config/drawer.ts
  documentation-site/components/yard/config/menu.ts
  documentation-site/components/yard/config/popover.ts
  documentation-site/examples/drawer/ssr-render-all.js
  documentation-site/examples/drawer/ssr-render-all.tsx
  documentation-site/examples/menu/child-render-all.js
  documentation-site/examples/menu/child-render-all.tsx
  documentation-site/examples/popover/ssr-render-all.js
  documentation-site/examples/popover/ssr-render-all.tsx
  documentation-site/pages/components/drawer.mdx
  documentation-site/pages/components/menu.mdx
  documentation-site/pages/components/popover.mdx
  src/drawer/__tests__/__snapshots__/drawer.test.js.snap
  src/drawer/__tests__/drawer-render-all.scenario.js
  src/drawer/__tests__/drawer.e2e.js
  src/drawer/drawer.js
  src/drawer/index.d.ts
  src/drawer/styled-components.js
  src/drawer/types.js
  src/menu/__tests__/menu-child-render-all.scenario.js
  src/menu/__tests__/menu.e2e.js
  src/menu/index.d.ts
  src/menu/maybe-child-menu.js
  src/menu/menu.js
  src/menu/nested-menus.js
  src/menu/option-list.js
  src/menu/option-profile.js
  src/menu/types.js
  src/popover/__tests__/__snapshots__/popover.test.js.snap
  src/popover/__tests__/__snapshots__/stateful-container.test.js.snap
  src/popover/__tests__/__snapshots__/stateful-popover.test.js.snap
  src/popover/__tests__/popover-render-all.scenario.js
  src/popover/__tests__/popover.e2e.js
  src/popover/__tests__/popover.test.js
  src/popover/default-props.js
  src/popover/index.d.ts
  src/popover/popover.js
  src/popover/stateful-container.js
  src/popover/styled-components.js
  src/popover/types.js
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/tooltip/__tests__/__snapshots__/stateful-tooltip.test.js.snap
  src/tooltip/default-props.js
  vrt/__image_snapshots__/drawer-render-all__dark-snap.png
  vrt/__image_snapshots__/drawer-render-all__desktop-snap.png
  vrt/__image_snapshots__/drawer-render-all__mobile-snap.png
  vrt/__image_snapshots__/menu-child-render-all__dark-snap.png
  vrt/__image_snapshots__/menu-child-render-all__desktop-snap.png
  vrt/__image_snapshots__/menu-child-render-all__mobile-snap.png
  vrt/__image_snapshots__/popover-render-all__dark-snap.png
  vrt/__image_snapshots__/popover-render-all__desktop-snap.png
  vrt/__image_snapshots__/popover-render-all__mobile-snap.png
Labels: feature

#2732 feat(vscode): open docs for components
  .eslintrc.js
  packages/baseweb-vscode-extension/README.md
  packages/baseweb-vscode-extension/package.json
  packages/baseweb-vscode-extension/scripts/update-package.js
  packages/baseweb-vscode-extension/src/components.json
  packages/baseweb-vscode-extension/src/extension.ts
  packages/baseweb-vscode-extension/tsconfig.json
Labels: feature

#2736 fix(vscode): add back the vsce dependency
  packages/baseweb-vscode-extension/package.json
  packages/baseweb-vscode-extension/yarn.lock
Labels: bugfix

#2735 Release v9.47.0
  package.json
Labels: release

#2740 docs(select): clarify filteroutselected prop
  documentation-site/components/yard/config/select.ts
Labels: docs

#2741 fix(button): longhand for border width
  src/button/styled-components.js
Labels: bugfix

#2746 fix(card): use longhand for borders
  src/card/styled-components.js
Labels: bugfix

#2747 fix(vsce): add compile step before publishing
  deploy.sh
  packages/baseweb-vscode-extension/package.json
Labels: bugfix

#2743 fix(datepicker): properly handle min and max values in calendar header
  .eslintignore
  src/datepicker/__tests__/stateful-calendar.scenario.js
  src/datepicker/calendar-header.js
  vrt/__image_snapshots__/stateful-calendar__dark-snap.png
  vrt/__image_snapshots__/stateful-calendar__desktop-snap.png
  vrt/__image_snapshots__/stateful-calendar__mobile-snap.png
Labels: bugfix

#2748 Release v9.47.1
  package.json
Labels: release

#2750 fix(vscode): test folder to pass tsc check
  packages/baseweb-vscode-extension/src/test/suite/index.ts
Labels: bugfix

#2751 Release v9.47.2
  package.json
Labels: release

#2716 feat(tree-view): TreeLabel override, renderAll, singleExpanded
  documentation-site/examples/tree-view/label-overrides.js
  documentation-site/examples/tree-view/label-overrides.tsx
  documentation-site/examples/tree-view/overrides.js
  documentation-site/examples/tree-view/overrides.tsx
  documentation-site/examples/tree-view/single-expanded.js
  documentation-site/examples/tree-view/single-expanded.tsx
  documentation-site/pages/components/tree-view.mdx
  src/tree-view/__tests__/tree-view-render-all.scenario.js
  src/tree-view/__tests__/tree-view-single-expanded.scenario.js
  src/tree-view/__tests__/tree-view.e2e.js
  src/tree-view/__tests__/tree-view.test.js
  src/tree-view/index.d.ts
  src/tree-view/index.js
  src/tree-view/stateful-container.js
  src/tree-view/styled-components.js
  src/tree-view/tree-label.js
  src/tree-view/tree-node.js
  src/tree-view/tree-view.js
  src/tree-view/types.js
  vrt/__image_snapshots__/tree-view-render-all__dark-snap.png
  vrt/__image_snapshots__/tree-view-render-all__desktop-snap.png
  vrt/__image_snapshots__/tree-view-render-all__mobile-snap.png
  vrt/__image_snapshots__/tree-view-single-expanded__dark-snap.png
  vrt/__image_snapshots__/tree-view-single-expanded__desktop-snap.png
  vrt/__image_snapshots__/tree-view-single-expanded__mobile-snap.png
Labels: feature

#2756 Release v9.48.0
  package.json
Labels: release

#2738 feat(data-table): numerical column accepts a format function
  src/data-table/__tests__/column-numerical.test.js
  src/data-table/column-numerical.js
Labels: feature

#2759 fix(eslint-plugin): missing $theme
  packages/eslint-plugin-baseui/__tests__/deprecated-theme-api-test.js
  packages/eslint-plugin-baseui/src/deprecated-theme-api.js
Labels: bugfix

#2726 fix(tree-view): add $isExpanded and $hasChildren styling props
  src/tree-view/tree-label.js
  src/tree-view/types.js
Labels: feature

#2764 Release v9.49.0
  package.json
Labels: release

#2761 fix(progress-steps): prioritize step child overrides
  src/progress-steps/__tests__/progress-step-overrides.scenario.js
  src/progress-steps/progress-steps.js
  vrt/__image_snapshots__/progress-step-overrides__dark-snap.png
  vrt/__image_snapshots__/progress-step-overrides__desktop-snap.png
  vrt/__image_snapshots__/progress-step-overrides__mobile-snap.png
Labels: bugfix

#2767 fix(vscode): tsc ignore snippets since it has its own tsconfig setup
  packages/baseweb-vscode-extension/tsconfig.json
Labels: bugfix

#2766 Release v9.49.1
  package.json
Labels: release

#2757 fix(notification): do not clear animateInTimer on focus
  src/toast/__tests__/toast.test.js
  src/toast/toast.js
Labels: bugfix

#2768 fix(eslint-plugin): handle styled function without a param
  packages/eslint-plugin-baseui/__tests__/deprecated-theme-api-test.js
  packages/eslint-plugin-baseui/src/deprecated-theme-api.js
Labels: bugfix

#2765 feat(ci): migrate link checker script to node with some improvements
  .buildkite/pipeline.yml
  scripts/link-checker.js
  scripts/link-checker.sh
Labels: build/tooling, feature

#2769 Release v9.49.2
  package.json
Labels: release

#2771 fix(ci): link checker url typo
  scripts/link-checker.js
Labels: bugfix, build/tooling

#2773 docs(toaster): add a bit more descriptive error message, and a link
  src/toast/toaster.js
Labels: docs

#2731 feat(data-table): datetime column
  component-sizes.json
  src/data-table/__tests__/column-datetime.test.js
  src/data-table/__tests__/data-table-columns.e2e.js
  src/data-table/__tests__/data-table-columns.scenario.js
  src/data-table/__tests__/data-table-datetime-column.scenario.js
  src/data-table/__tests__/data-table.scenario.js
  src/data-table/column-datetime.js
  src/data-table/constants.js
  src/data-table/filter-menu.js
  src/data-table/index.js
  src/data-table/types.js
  src/datepicker/calendar-header.js
  src/datepicker/calendar.js
  src/datepicker/datepicker.js
  src/datepicker/utils/index.js
  src/select/select-component.js
  src/timepicker/timepicker.js
  vrt/__image_snapshots__/data-table-columns__dark-snap.png
  vrt/__image_snapshots__/data-table-columns__desktop-snap.png
  vrt/__image_snapshots__/data-table-columns__mobile-snap.png
  vrt/__image_snapshots__/data-table-datetime-column__dark-snap.png
  vrt/__image_snapshots__/data-table-datetime-column__desktop-snap.png
  vrt/__image_snapshots__/data-table-datetime-column__mobile-snap.png
  vrt/__image_snapshots__/data-table__dark-snap.png
  vrt/__image_snapshots__/data-table__desktop-snap.png
Labels: feature

#2774 fix(ci): link-checker script env vars and url sanitization
  docker-compose.yml
  scripts/link-checker.js
Labels: bugfix, build/tooling

#2775 feat(vscode): add theme cheat sheet
  deploy.sh
  packages/baseweb-vscode-extension/.env
  packages/baseweb-vscode-extension/.gitignore
  packages/baseweb-vscode-extension/.vscode/launch.json
  packages/baseweb-vscode-extension/.vscode/settings.json
  packages/baseweb-vscode-extension/.vscodeignore
  packages/baseweb-vscode-extension/ext-src/components.json
  packages/baseweb-vscode-extension/ext-src/extension.ts
  packages/baseweb-vscode-extension/ext-src/react-app-env.d.ts
  packages/baseweb-vscode-extension/ext-src/test/runTest.ts
  packages/baseweb-vscode-extension/ext-src/test/suite/extension.test.ts
  packages/baseweb-vscode-extension/ext-src/test/suite/index.ts
  packages/baseweb-vscode-extension/package.json
  packages/baseweb-vscode-extension/public/index.html
  packages/baseweb-vscode-extension/scripts/build-non-split.js
  packages/baseweb-vscode-extension/scripts/update-package.js
  packages/baseweb-vscode-extension/src/App.tsx
  packages/baseweb-vscode-extension/src/extension.ts
  packages/baseweb-vscode-extension/src/index.css
  packages/baseweb-vscode-extension/src/index.tsx
  packages/baseweb-vscode-extension/src/react-app-env.d.ts
  packages/baseweb-vscode-extension/tsconfig.extension.json
  packages/baseweb-vscode-extension/tsconfig.json
  packages/baseweb-vscode-extension/vsc-extension-quickstart.md
  packages/baseweb-vscode-extension/yarn.lock
Labels: feature

#2722 docs: added description of datepicker formatString
  documentation-site/pages/components/datepicker.mdx
Labels: ci, docs

#2711 fix(MaskedInput): pass style overrides, add datepicker example with readonly input attr
  documentation-site/examples/datepicker/nested-override.js
  documentation-site/examples/datepicker/nested-override.tsx
  src/input/masked-input.js
Labels: bugfix

#2728 test(vrt): reduce flakiness
  jest.vrt.config.js
  vrt/__image_snapshots__/aspect-ratio-box__dark-snap.png
  vrt/__image_snapshots__/aspect-ratio-box__desktop-snap.png
  vrt/__image_snapshots__/data-table-categorical-column__dark-snap.png
  vrt/__image_snapshots__/data-table-categorical-column__desktop-snap.png
  vrt/__image_snapshots__/data-table-categorical-column__mobile-snap.png
  vrt/__image_snapshots__/data-table-full-window__dark-snap.png
  vrt/__image_snapshots__/data-table-full-window__desktop-snap.png
  vrt/__image_snapshots__/data-table-full-window__mobile-snap.png
  vrt/__image_snapshots__/data-table__dark-snap.png
  vrt/__image_snapshots__/data-table__desktop-snap.png
  vrt/__image_snapshots__/data-table__mobile-snap.png
  vrt/__image_snapshots__/form-control__dark-snap.png
  vrt/__image_snapshots__/form-control__desktop-snap.png
  vrt/__image_snapshots__/form-control__mobile-snap.png
  vrt/__image_snapshots__/heading__dark-snap.png
  vrt/__image_snapshots__/heading__desktop-snap.png
  vrt/__image_snapshots__/heading__mobile-snap.png
  vrt/__image_snapshots__/input-rtl__desktop-snap.png
  vrt/__image_snapshots__/input-rtl__mobile-snap.png
  vrt/__image_snapshots__/layout-grid-align__dark-snap.png
  vrt/__image_snapshots__/layout-grid-align__desktop-snap.png
  vrt/__image_snapshots__/layout-grid-align__mobile-snap.png
  vrt/__image_snapshots__/list-item__dark-snap.png
  vrt/__image_snapshots__/list-item__desktop-snap.png
  vrt/__image_snapshots__/list-item__mobile-snap.png
  vrt/__image_snapshots__/menu-rtl__desktop-snap.png
  vrt/__image_snapshots__/menu-rtl__mobile-snap.png
  vrt/__image_snapshots__/typography-body__mobile-snap.png
  vrt/__image_snapshots__/typography-display__mobile-snap.png
  vrt/__image_snapshots__/typography-heading__mobile-snap.png
  vrt/config.js
  vrt/tests.vrt.js
Labels: bugfix, build/tooling

#2780 Release v9.50.0
  package.json
Labels: release

#2782 fix(vscode): fix the build
  package.json
  packages/baseweb-vscode-extension/.eslintignore
  packages/baseweb-vscode-extension/package.json
  packages/baseweb-vscode-extension/scripts/build-non-split.js
  packages/baseweb-vscode-extension/yarn.lock
  src/utils/deep-merge.js
  yarn.lock
Labels: bugfix
