Repository uber/baseweb, pull requests merged in 2020-09, with the labels that each got.

#3716 feat(button): add a circle shape
  documentation-site/examples/button/shapes.js
  documentation-site/examples/button/shapes.tsx
  src/button/__tests__/button-circle.scenario.js
  src/button/constants.js
  src/button/index.d.ts
  src/button/styled-components.js
  vrt/__image_snapshots__/button-circle__dark-snap.png
  vrt/__image_snapshots__/button-circle__desktop-snap.png
  vrt/__image_snapshots__/button-circle__mobile-snap.png
  vrt/__image_snapshots__/table-grid-jobs__dark-snap.png
  vrt/__image_snapshots__/table-grid-jobs__desktop-snap.png
  vrt/__image_snapshots__/table-grid-jobs__mobile-snap.png
Labels: feature

#3718 feat(card): update title spacing
  src/card/styled-components.js
  vrt/__image_snapshots__/card-image-link__dark-snap.png
  vrt/__image_snapshots__/card-image-link__desktop-snap.png
  vrt/__image_snapshots__/card-image-link__mobile-snap.png
  vrt/__image_snapshots__/card-image-object__dark-snap.png
  vrt/__image_snapshots__/card-image-object__desktop-snap.png
  vrt/__image_snapshots__/card-image-object__mobile-snap.png
  vrt/__image_snapshots__/card__dark-snap.png
  vrt/__image_snapshots__/card__desktop-snap.png
  vrt/__image_snapshots__/card__mobile-snap.png
Labels: enhancement

#3720 fix(skeleton): clear up warning
  src/skeleton/styled-components.js
Labels: bugfix

#3721 docs(tree-view): fix flow in my typescript
  documentation-site/examples/tree-view/interactable.tsx
Labels: docs

#3738 feat(data-table): update anchor types to allow function elementAs
  src/data-table/__tests__/data-table-collection-of-objects.scenario.js
  src/data-table/column-anchor.js
  vrt/__image_snapshots__/data-table-collection-of-objects__dark-snap.png
  vrt/__image_snapshots__/data-table-collection-of-objects__desktop-snap.png
  vrt/__image_snapshots__/data-table-collection-of-objects__mobile-snap.png
Labels: feature

#3726 fix(button): focus respects rounded corners
  src/button/styled-components.js
Labels: bugfix

#3748 fix(select): makes highlight/focus color same in select option
  src/themes/dark-theme/color-component-tokens.js
  vrt/__image_snapshots__/select-disable-href-anchor__dark-snap.png
  vrt/__image_snapshots__/select-open__dark-snap.png
Labels: bugfix

#3751 feat(data-table): add initial sort props
  src/data-table/__tests__/data-table-initial-sort.e2e.js
  src/data-table/__tests__/data-table-initial-sort.scenario.js
  src/data-table/stateful-container.js
  src/data-table/stateful-data-table.js
  src/data-table/types.js
  vrt/__image_snapshots__/data-table-initial-sort__dark-snap.png
  vrt/__image_snapshots__/data-table-initial-sort__desktop-snap.png
  vrt/__image_snapshots__/data-table-initial-sort__mobile-snap.png
Labels: feature

#3763 fix(tabs-motion): remove focus from tabpanel
  src/tabs-motion/__tests__/tabs-motion.e2e.js
  src/tabs-motion/index.d.ts
  src/tabs-motion/styled-components.js
  src/tabs-motion/tabs.js
  src/utils/focusVisible.js
Labels: bugfix

#3769 docs: remove guidelines prototype
  .gitignore
  documentation-site/components/guidelines/render.js
  documentation-site/env-config.js
  documentation-site/pages/guidelines/[node].js
  documentation-site/pages/guidelines/index.js
  package.json
  yarn.lock
Labels: docs

#3770 fix(radio): cleanup unused path
  src/radio/styled-components.js
Labels: bugfix

#3773 fix(link): styletron component typescript
  src/link/index.d.ts
Labels: bugfix

#3779 feat(theme): export typescript theme properties
  src/theme.ts
Labels: enhancement

#3757 feat(snackbar): initial layout
  documentation-site/examples/snackbar/action-button-usage.js
  documentation-site/examples/snackbar/action-button-usage.tsx
  documentation-site/examples/snackbar/infinite-duration.js
  documentation-site/examples/snackbar/infinite-duration.tsx
  documentation-site/examples/snackbar/line-lengths.js
  documentation-site/examples/snackbar/line-lengths.tsx
  documentation-site/examples/snackbar/placement.js
  documentation-site/examples/snackbar/placement.tsx
  documentation-site/pages/components/snackbar.mdx
  documentation-site/routes.js
  src/snackbar/__tests__/snackbar-element-overrides.scenario.js
  src/snackbar/__tests__/snackbar-element-rtl.scenario.js
  src/snackbar/__tests__/snackbar-element.scenario.js
  src/snackbar/__tests__/snackbar-placement.scenario.js
  src/snackbar/__tests__/snackbar-provider-overrides.scenario.js
  src/snackbar/__tests__/snackbar-provider.scenario.js
  src/snackbar/__tests__/snackbar.e2e.js
  src/snackbar/constants.js
  src/snackbar/index.d.ts
  src/snackbar/index.js
  src/snackbar/snackbar-context.js
  src/snackbar/snackbar-element.js
  src/snackbar/styled-components.js
  src/snackbar/types.js
  vrt/__image_snapshots__/snackbar-element-overrides__dark-snap.png
  vrt/__image_snapshots__/snackbar-element-overrides__desktop-snap.png
  vrt/__image_snapshots__/snackbar-element-overrides__mobile-snap.png
  vrt/__image_snapshots__/snackbar-element-rtl__desktop-snap.png
  vrt/__image_snapshots__/snackbar-element-rtl__mobile-snap.png
  vrt/__image_snapshots__/snackbar-element__dark-snap.png
  vrt/__image_snapshots__/snackbar-element__desktop-snap.png
  vrt/__image_snapshots__/snackbar-element__mobile-snap.png
  vrt/__image_snapshots__/snackbar-placement__dark-snap.png
  vrt/__image_snapshots__/snackbar-placement__desktop-snap.png
  vrt/__image_snapshots__/snackbar-placement__mobile-snap.png
  vrt/__image_snapshots__/snackbar-provider-overrides__dark-snap.png
  vrt/__image_snapshots__/snackbar-provider-overrides__desktop-snap.png
  vrt/__image_snapshots__/snackbar-provider-overrides__mobile-snap.png
  vrt/__image_snapshots__/snackbar-provider__dark-snap.png
  vrt/__image_snapshots__/snackbar-provider__desktop-snap.png
  vrt/__image_snapshots__/snackbar-provider__mobile-snap.png
Labels: feature

#3782 feat(menu): export the nested menu context
  src/menu/index.js
  src/menu/nested-menus.js
  src/menu/types.js
Labels: feature

#3786 fix(StyledLink): remove unused css rule
  src/link/styled-components.js
Labels: bugfix

#3788 fix(docs): correct input type config
  documentation-site/components/yard/config/input.ts
Labels: bugfix
