Repository uber/baseweb, pull requests merged in 2020-02, with the labels that each got.

#2784 fix(typescript) types for phone input and data-table
  src/data-table/index.d.ts
  src/phone-input/index.d.ts
Labels: bugfix

#2785 fix(typescript): mini button type
  src/button/index.d.ts
Labels: bugfix

#2783 feat(theme): add borderAccentLight
  documentation-site/pages/guides/theming.mdx
  packages/baseweb-vscode-extension/src/App.tsx
  src/theme.ts
  src/themes/dark-theme/color-semantic-tokens.js
  src/themes/light-theme/color-semantic-tokens.js
  src/themes/types.js
Labels: feature

#2792 chore(docs): migrate from deprecated github api param
  documentation-site/pages/index.js
Labels: bugfix, chore

#2793 feat(pin-code): add autoComplete prop
  src/pin-code/default-props.js
  src/pin-code/pin-code.js
  src/pin-code/types.js
Labels: feature

#2790 docs(theming): always show dark theme & restyling
  documentation-site/components/theming/animations.js
  documentation-site/components/theming/borders.js
  documentation-site/components/theming/breakpoints.js
  documentation-site/components/theming/colors.js
  documentation-site/components/theming/common.js
  documentation-site/components/theming/grid.js
  documentation-site/components/theming/lighting.js
  documentation-site/components/theming/sizing.js
  documentation-site/components/theming/typography.js
  documentation-site/pages/guides/theming.mdx
Labels: docs

#2659 Feat: added support for alternate css units for grid layout
  documentation-site/examples/layout-grid/custom-css-unit.js
  documentation-site/examples/layout-grid/custom-css-unit.tsx
  documentation-site/pages/components/layout-grid.mdx
  src/layout-grid/__tests__/layout-grid-custom-css-length-unit.scenario.js
  src/layout-grid/grid.js
  src/layout-grid/index.d.ts
  src/layout-grid/styled-components.js
  src/layout-grid/types.js
  src/theme.ts
  src/themes/shared/grid.js
  src/themes/types.js
  vrt/__image_snapshots__/layout-grid-custom-css-length-unit__dark-snap.png
  vrt/__image_snapshots__/layout-grid-custom-css-length-unit__desktop-snap.png
  vrt/__image_snapshots__/layout-grid-custom-css-length-unit__mobile-snap.png
Labels: feature

#2796 Release v9.51.0
  package.json
Labels: release

#2797 fix(popover): avoid infinite focus loop
  src/popover/__tests__/popover-focus-loop.e2e.js
  src/popover/__tests__/popover-focus-loop.scenario.js
  src/popover/popover.js
  vrt/__image_snapshots__/popover-focus-loop__dark-snap.png
  vrt/__image_snapshots__/popover-focus-loop__desktop-snap.png
  vrt/__image_snapshots__/popover-focus-loop__mobile-snap.png
Labels: bugfix, regression

#2798 chore: bump react-view
  package.json
  yarn.lock
Labels: bugfix

#2399 docs(skeleton): add proposal
  proposals/skeleton.md
Labels: docs

#2758 feat: add sort to table grid
  documentation-site/examples/table-grid/sortable.js
  documentation-site/examples/table-grid/sortable.tsx
  documentation-site/pages/components/table-grid.mdx
  src/table-grid/__tests__/table-grid-sortable.scenario.js
  src/table-grid/index.d.ts
  src/table-grid/index.js
  src/table-grid/styled-components.js
  src/table/index.js
  src/table/sortable-head-cell.js
  vrt/__image_snapshots__/table-grid-sortable__dark-snap.png
  vrt/__image_snapshots__/table-grid-sortable__desktop-snap.png
  vrt/__image_snapshots__/table-grid-sortable__mobile-snap.png
Labels: feature

#2808 fix(theme): make lighting vals the same in the light and dark themes
  src/themes/creator.js
  src/themes/dark-theme/dark-theme.js
  src/themes/dark-theme/lighting.js
  src/themes/light-theme/light-theme.js
  src/themes/shared/lighting.js
  vrt/__image_snapshots__/checkbox-toggle-round__dark-snap.png
  vrt/__image_snapshots__/checkbox-toggle__dark-snap.png
  vrt/__image_snapshots__/data-table-categorical-column__dark-snap.png
  vrt/__image_snapshots__/data-table-datetime-column__dark-snap.png
  vrt/__image_snapshots__/data-table-extracted-filters__dark-snap.png
  vrt/__image_snapshots__/data-table-numerical-column__dark-snap.png
  vrt/__image_snapshots__/list-item-menu-adapter__dark-snap.png
  vrt/__image_snapshots__/menu-child-render-all__dark-snap.png
  vrt/__image_snapshots__/menu-child__dark-snap.png
  vrt/__image_snapshots__/menu-empty__dark-snap.png
  vrt/__image_snapshots__/menu-grouped-items__dark-snap.png
  vrt/__image_snapshots__/menu-stateful__dark-snap.png
  vrt/__image_snapshots__/menu-virtualized__dark-snap.png
  vrt/__image_snapshots__/menu__dark-snap.png
  vrt/__image_snapshots__/popover__dark-snap.png
  vrt/__image_snapshots__/select-open__dark-snap.png
  vrt/__image_snapshots__/table-borderless__dark-snap.png
  vrt/__image_snapshots__/table-cells__dark-snap.png
  vrt/__image_snapshots__/table-few-rows__dark-snap.png
  vrt/__image_snapshots__/table-filter__dark-snap.png
  vrt/__image_snapshots__/table-grid-jobs__dark-snap.png
  vrt/__image_snapshots__/table-grid-records__dark-snap.png
  vrt/__image_snapshots__/table-grid__dark-snap.png
  vrt/__image_snapshots__/table-pagination__dark-snap.png
  vrt/__image_snapshots__/table-scroll__dark-snap.png
  vrt/__image_snapshots__/table-sortable-fill-click__dark-snap.png
  vrt/__image_snapshots__/table-sortable__dark-snap.png
  vrt/__image_snapshots__/toast__dark-snap.png
Labels: bugfix

#2805 fix(overrides): properly implement dynamic props value
  component-sizes.json
  src/helpers/__tests__/__snapshots__/overrides.test.js.snap
  src/helpers/__tests__/overrides.test.js
  src/helpers/overrides.js
  vrt/__image_snapshots__/table-grid-sortable__dark-snap.png
Labels: bugfix

#2813 fix(link-checker): exclude zeit.co
  scripts/link-checker.js
Labels: bugfix

#2811 fix(menu): mount child menus in shared container
  src/menu/__tests__/menu-child-in-popover.scenario.js
  src/menu/__tests__/menu.e2e.js
  src/menu/maybe-child-menu.js
  src/menu/nested-menus.js
  src/menu/option-list.js
  vrt/__image_snapshots__/menu-child-in-popover__dark-snap.png
  vrt/__image_snapshots__/menu-child-in-popover__desktop-snap.png
  vrt/__image_snapshots__/menu-child-in-popover__mobile-snap.png
Labels: bugfix

#2816 fix(file-uploader): fix ContentSeparator override usage
  src/file-uploader/file-uploader.js
  src/file-uploader/index.js
  src/file-uploader/styled-components.js
Labels: bugfix

#2817 fix(popover): change popover autofocus false default
  documentation-site/components/yard/config/popover.ts
  src/popover/__tests__/__snapshots__/popover.test.js.snap
  src/popover/__tests__/__snapshots__/stateful-popover.test.js.snap
  src/popover/__tests__/popover-focus-loop.scenario.js
  src/popover/__tests__/popover.test.js
  src/popover/default-props.js
Labels: bugfix

#2818 Release v9.52.0
  package.json
Labels: release

#2819 fix(select): maintain focus on option click
  src/select/__tests__/select-click-maintains-focus.e2e.js
  src/select/__tests__/select-click-maintains-focus.scenario.js
  src/select/select-component.js
  vrt/__image_snapshots__/modal-select__selectOption-snap.png
  vrt/__image_snapshots__/select-click-maintains-focus__dark-snap.png
  vrt/__image_snapshots__/select-click-maintains-focus__desktop-snap.png
  vrt/__image_snapshots__/select-click-maintains-focus__mobile-snap.png
Labels: bugfix

#2829 docs(delighted): make the csat survey recurring
  documentation-site/pages/_document.js
Labels: docs

#2828 chore(docs): add documentation on commit message format
  CONTRIBUTING.md
Labels: docs

#2806 fix(slider): improve focus-ring styles
  src/layer/layers-manager.js
  src/slider/slider.js
  src/slider/styled-components.js
  src/slider/types.js
  src/utils/focusVisible.js
Labels: bugfix

#2830 fix(eslint-plugin): update error message
  packages/eslint-plugin-baseui/__tests__/deprecated-component-api.test.js
  packages/eslint-plugin-baseui/src/deprecated-component-api.js
Labels: bugfix

#2832 docs(tooltip): fix yard config
  documentation-site/components/yard/config/tooltip.ts
Labels: docs

#2821 fix(button): properly position loading spinner
  src/button/button.js
  src/button/styled-components.js
Labels: bugfix

#2826 fix(button-group): selected color diff from hover
  src/themes/light-theme/color-component-tokens.js
  vrt/__image_snapshots__/button-group-checkbox__desktop-snap.png
  vrt/__image_snapshots__/button-group-checkbox__mobile-snap.png
  vrt/__image_snapshots__/button-group-radio__desktop-snap.png
  vrt/__image_snapshots__/button-group-radio__mobile-snap.png
  vrt/__image_snapshots__/button-rtl__desktop-snap.png
  vrt/__image_snapshots__/button-rtl__mobile-snap.png
  vrt/__image_snapshots__/button__desktop-snap.png
  vrt/__image_snapshots__/button__mobile-snap.png
  vrt/__image_snapshots__/data-table-datetime-column__desktop-snap.png
  vrt/__image_snapshots__/data-table-datetime-column__mobile-snap.png
  vrt/__image_snapshots__/data-table-numerical-column__desktop-snap.png
  vrt/__image_snapshots__/data-table-numerical-column__mobile-snap.png
Labels: bugfix

#2833 Release v9.52.1
  package.json
Labels: release

#2842 fix(button): consistent height in loading button
  src/button/__tests__/button-sizes-loading.scenario.js
  src/button/styled-components.js
  vrt/__image_snapshots__/button-sizes-loading__dark-snap.png
  vrt/__image_snapshots__/button-sizes-loading__desktop-snap.png
  vrt/__image_snapshots__/button-sizes-loading__mobile-snap.png
Labels: bugfix

#2845 Release v9.52.2
  package.json
Labels: release

#2834 fix(input-components): Improve focus ring styles
  documentation-site/components/yard/config/radio.ts
  documentation-site/components/yard/editor.tsx
  documentation-site/components/yard/index.tsx
  documentation-site/components/yard/knob.tsx
  documentation-site/examples/radio/basic.js
  documentation-site/examples/radio/basic.tsx
  documentation-site/examples/radio/disabled.js
  documentation-site/examples/radio/disabled.tsx
  documentation-site/examples/radio/error.js
  documentation-site/examples/radio/error.tsx
  documentation-site/examples/radio/horizontal-align.js
  documentation-site/examples/radio/horizontal-align.tsx
  documentation-site/examples/radio/overrides.js
  documentation-site/examples/radio/overrides.tsx
  documentation-site/examples/radio/stateful.js
  documentation-site/examples/radio/stateful.tsx
  package.json
  src/button/button.js
  src/button/styled-components.js
  src/button/types.js
  src/checkbox/checkbox.js
  src/checkbox/styled-components.js
  src/checkbox/types.js
  src/radio/__tests__/radiogroup.test.js
  src/radio/index.d.ts
  src/radio/radio.js
  src/radio/radiogroup.js
  src/radio/styled-components.js
  src/radio/types.js
  src/slider/slider.js
  vrt/__image_snapshots__/modal-rtl__desktop-snap.png
  vrt/__image_snapshots__/modal-rtl__mobile-snap.png
  vrt/__image_snapshots__/modal-uncloseable__dark-snap.png
  vrt/__image_snapshots__/modal-uncloseable__desktop-snap.png
  vrt/__image_snapshots__/modal-uncloseable__mobile-snap.png
  vrt/__image_snapshots__/modal__dark-snap.png
  vrt/__image_snapshots__/modal__desktop-snap.png
  vrt/__image_snapshots__/modal__mobile-snap.png
  yarn.lock
Labels: bugfix

#2844 docs(blog): figma communities
  documentation-site/pages/blog/base-figma-community/index.mdx
  documentation-site/pages/blog/base-figma-community/metadata.json
Labels: docs

#2849 docs(menu): update example for menu with href,
  documentation-site/examples/menu/href.js
  documentation-site/examples/menu/href.tsx
  documentation-site/pages/components/menu.mdx
Labels: docs

#2852 fix(link-checker): update sanitization
  scripts/link-checker.js
Labels: bugfix, build/tooling

#2853 docs(menu): example to use example.com
  documentation-site/examples/menu/href.js
  documentation-site/examples/menu/href.tsx
  scripts/link-checker.js
Labels: docs

#2850 fix(pagination): center current page with chevron
  src/pagination/pagination.js
  vrt/__image_snapshots__/pagination-rtl__desktop-snap.png
  vrt/__image_snapshots__/pagination-rtl__mobile-snap.png
  vrt/__image_snapshots__/pagination__dark-snap.png
  vrt/__image_snapshots__/pagination__desktop-snap.png
  vrt/__image_snapshots__/pagination__mobile-snap.png
  vrt/__image_snapshots__/table-pagination__dark-snap.png
  vrt/__image_snapshots__/table-pagination__desktop-snap.png
Labels: bugfix

#2846 fix(picker-components): improve focus styles
  src/datepicker/calendar-header.js
  src/datepicker/day.js
  src/datepicker/styled-components.js
  src/datepicker/types.js
  src/file-uploader/file-uploader.js
  src/file-uploader/styled-components.js
  src/menu/menu.js
  src/menu/styled-components.js
  src/rating/__tests__/__snapshots__/emoticon-rating.test.js.snap
  src/rating/__tests__/__snapshots__/star-rating.test.js.snap
  src/rating/__tests__/emoticon-rating.test.js
  src/rating/__tests__/star-rating.test.js
  src/rating/emoticon-rating.js
  src/rating/star-rating.js
  src/rating/styled-components.js
  src/rating/types.js
  src/rating/utils.js
  vrt/__image_snapshots__/datepicker-range-highlight__noHighlight-snap.png
Labels: bugfix

#2717 fix(typescript): add createThemedStyled & type argument to withStyle
  src/index.d.ts
Labels: bugfix

#2802 feat(vscode-extension): add theme color samples in code
  deploy.sh
  packages/baseweb-vscode-extension/.vscode/tasks.json
  packages/baseweb-vscode-extension/ext-src/coloring.ts
  packages/baseweb-vscode-extension/ext-src/extension.ts
  packages/baseweb-vscode-extension/package.json
  packages/baseweb-vscode-extension/public/index.html
  packages/baseweb-vscode-extension/tsconfig.extension.json
  packages/baseweb-vscode-extension/yarn.lock
Labels: feature

#2859 docs(input): add placeholder to input tags example
  documentation-site/examples/input/with-tags.js
  documentation-site/examples/input/with-tags.tsx
Labels: bugfix

#2854 Release v9.53.0
  package.json
Labels: release

#2864 fix(focus-styles): the rest of components and doc site
  documentation-site/components/anchor.js
  documentation-site/components/blog.js
  documentation-site/components/contributors.js
  documentation-site/components/footer.js
  documentation-site/components/header-navigation.js
  documentation-site/components/layout.js
  documentation-site/components/skip-to-content.js
  documentation-site/components/unstable-warning.js
  documentation-site/pages/discover-more/roadmap.mdx
  documentation-site/pages/index.js
  src/accordion/__tests__/__snapshots__/accordion.test.js.snap
  src/accordion/__tests__/__snapshots__/panel.test.js.snap
  src/accordion/accordion.js
  src/accordion/panel.js
  src/accordion/styled-components.js
  src/accordion/types.js
  src/button/styled-components.js
  src/data-table/header-cell.js
  src/dnd-list/list.js
  src/dnd-list/styled-components.js
  src/dnd-list/types.js
  src/drawer/__tests__/__snapshots__/drawer.test.js.snap
  src/drawer/drawer.js
  src/drawer/styled-components.js
  src/drawer/types.js
  src/link/index.js
  src/link/styled-components.js
  src/modal/__tests__/__snapshots__/modal.test.js.snap
  src/modal/modal.js
  src/modal/styled-components.js
  src/modal/types.js
  src/pagination/pagination.js
  src/pagination/styled-components.js
  src/side-navigation/nav.js
  src/side-navigation/styled-components.js
  src/tabs/__tests__/__snapshots__/stateful-tabs.test.js.snap
  src/tabs/__tests__/__snapshots__/tab.test.js.snap
  src/tabs/styled-components.js
  src/tabs/tab.js
  src/tabs/types.js
  src/tag/__tests__/__snapshots__/tag.test.js.snap
  src/tag/styled-components.js
  src/tag/tag.js
  src/tag/types.js
  src/toast/styled-components.js
  src/toast/toast.js
  src/toast/types.js
  vrt/__image_snapshots__/drawer-rtl__desktop-snap.png
  vrt/__image_snapshots__/drawer-rtl__mobile-snap.png
  vrt/__image_snapshots__/drawer__dark-snap.png
  vrt/__image_snapshots__/drawer__desktop-snap.png
  vrt/__image_snapshots__/drawer__mobile-snap.png
Labels: bugfix

#2866 Release v9.54.0
  package.json
Labels: release

#2855 fix(button): Change spinner to use span instead of div
  src/button/__tests__/button-sizes-loading.scenario.js
  src/button/styled-components.js
  vrt/__image_snapshots__/button-rtl__desktop-snap.png
  vrt/__image_snapshots__/button-rtl__mobile-snap.png
  vrt/__image_snapshots__/button-sizes-loading__dark-snap.png
  vrt/__image_snapshots__/button-sizes-loading__desktop-snap.png
  vrt/__image_snapshots__/button-sizes-loading__mobile-snap.png
  vrt/__image_snapshots__/button__dark-snap.png
  vrt/__image_snapshots__/button__desktop-snap.png
  vrt/__image_snapshots__/button__mobile-snap.png
Labels: bugfix

#2858 docs(getting-started/setup): fix the spelling of baseui
  documentation-site/pages/getting-started/setup.mdx
Labels: docs

#2871 docs(users): add everbase
  documentation-site/pages/index.js
  documentation-site/static/images/everbase-logo.png
Labels: docs

#2867 fix(vscode): cleanup the plugin activation events
  packages/baseweb-vscode-extension/package.json
  packages/baseweb-vscode-extension/scripts/update-package.js
Labels: bugfix

#2868 Release v9.54.1
  package.json
Labels: release

#2874 docs(code-snippet): extract props & cleanup netlify toml
  deploy.sh
  netlify.toml
Labels: docs

#2873 fix(timepicker): handle midnight properly
  src/timepicker/timepicker.js
Labels: bugfix

#2877 fix(data-table): pulls out column data based on mapDataToValue
  src/data-table/__tests__/data-table-collection-of-objects.scenario.js
  src/data-table/__tests__/data-table-columns.e2e.js
  src/data-table/stateful-data-table.js
  vrt/__image_snapshots__/data-table-collection-of-objects__dark-snap.png
  vrt/__image_snapshots__/data-table-collection-of-objects__desktop-snap.png
  vrt/__image_snapshots__/data-table-collection-of-objects__mobile-snap.png
Labels: bugfix

#2876 fix(layer): escape only closes top-most layer
  src/datepicker/__tests__/datepicker.e2e.js
  src/datepicker/calendar-header.js
  src/drawer/__tests__/__snapshots__/drawer.test.js.snap
  src/drawer/__tests__/drawer.e2e.js
  src/drawer/drawer.js
  src/layer/layer.js
  src/layer/layers-manager.js
  src/layer/types.js
  src/modal/__tests__/__snapshots__/modal.test.js.snap
  src/modal/__tests__/modal.e2e.js
  src/modal/modal.js
  src/popover/__tests__/popover-select.scenario.js
  src/popover/__tests__/popover.e2e.js
  src/popover/__tests__/popover.test.js
  src/popover/popover.js
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/select-component.js
Labels: bugfix

#2881 fix(vscode): fix the vscode extention compilation
  packages/baseweb-vscode-extension/ext-src/coloring.ts
  packages/baseweb-vscode-extension/package.json
  packages/baseweb-vscode-extension/tsconfig.extension.json
  packages/baseweb-vscode-extension/yarn.lock
Labels: bugfix

#2880 chore(codemods): removes outdated codemods dir
  .eslintignore
  .prettierignore
  documentation-site/pages/blog/base-web-v7/index.mdx
  documentation-site/pages/blog/base-web-v8/index.mdx
  src/codemods/README.md
  src/codemods/__testfixtures__/styled-flowfixme-baseui-import.input.js
  src/codemods/__testfixtures__/styled-flowfixme-baseui-import.output.js
  src/codemods/__testfixtures__/styled-flowfixme-existing-generics.input.js
  src/codemods/__testfixtures__/styled-flowfixme-existing-generics.output.js
  src/codemods/__testfixtures__/styled-flowfixme-flow.input.js
  src/codemods/__testfixtures__/styled-flowfixme-flow.output.js
  src/codemods/__testfixtures__/styled-flowfixme-no-flow.input.js
  src/codemods/__testfixtures__/styled-flowfixme-no-flow.output.js
  src/codemods/__testfixtures__/styled-flowfixme-renamed.input.js
  src/codemods/__testfixtures__/styled-flowfixme-renamed.output.js
  src/codemods/__testfixtures__/styled-flowfixme-styletron-import.input.js
  src/codemods/__testfixtures__/styled-flowfixme-styletron-import.output.js
  src/codemods/__testfixtures__/styled-v8-themedStyled-component.input.js
  src/codemods/__testfixtures__/styled-v8-themedStyled-component.output.js
  src/codemods/__testfixtures__/styled-v8-themedStyled-element.input.js
  src/codemods/__testfixtures__/styled-v8-themedStyled-element.output.js
  src/codemods/__testfixtures__/styled-v8-themedStyled-mixed.input.js
  src/codemods/__testfixtures__/styled-v8-themedStyled-mixed.output.js
  src/codemods/__testfixtures__/styled-v8-themedStyled-multi-diff.input.js
  src/codemods/__testfixtures__/styled-v8-themedStyled-multi-diff.output.js
  src/codemods/__testfixtures__/styled-v8-themedStyled-multi-dup.input.js
  src/codemods/__testfixtures__/styled-v8-themedStyled-multi-dup.output.js
  src/codemods/__testfixtures__/styled-v8-themedStyled-object.input.js
  src/codemods/__testfixtures__/styled-v8-themedStyled-object.output.js
  src/codemods/__tests__/styled-flowfixme-test.js
  src/codemods/__tests__/styled-v7-themedStyled-test.js
  src/codemods/shared.js
  src/codemods/styled-flowfixme.js
  src/codemods/styled-v8-themedStyled.js
Labels: bugfix, chore

#2883 Release v9.55.1
  package.json
Labels: release

#2875 docs: VS Code Extension for Base Web and React View Code Snippets
  documentation-site/components/blog.js
  documentation-site/pages/blog/vs-code-extension/cheat-sheet.png
  documentation-site/pages/blog/vs-code-extension/code-snippets.gif
  documentation-site/pages/blog/vs-code-extension/coloring.png
  documentation-site/pages/blog/vs-code-extension/commands.png
  documentation-site/pages/blog/vs-code-extension/index.mdx
  documentation-site/pages/blog/vs-code-extension/metadata.json
  documentation-site/static/images/blog/vs-code-extension/vscodelogo.png
Labels: docs

#2885 docs: update VS code extension's README
  packages/baseweb-vscode-extension/README.md
Labels: docs

#2886 docs(setup): add vscode
  documentation-site/pages/getting-started/setup.mdx
Labels: docs

#2887 feat(pagination): add size prop
  documentation-site/components/yard/config/pagination.ts
  scripts/link-checker.js
  src/input/index.d.ts
  src/pagination/__tests__/pagination.scenario.js
  src/pagination/index.d.ts
  src/pagination/index.js
  src/pagination/pagination.js
  src/pagination/types.js
  vrt/__image_snapshots__/pagination-rtl__desktop-snap.png
  vrt/__image_snapshots__/pagination-rtl__mobile-snap.png
  vrt/__image_snapshots__/pagination__dark-snap.png
  vrt/__image_snapshots__/pagination__desktop-snap.png
  vrt/__image_snapshots__/pagination__mobile-snap.png
Labels: feature

#2890 fix(button): improve a11y of the loading state
  src/button/button.js
Labels: bugfix

#2891 Release v9.56.0
  package.json
Labels: release

#2893 fix(breadcrumbs): ignore null, true, and false
  src/breadcrumbs/__tests__/__snapshots__/breadcrumbs.test.js.snap
  src/breadcrumbs/__tests__/breadcrumbs.test.js
  src/breadcrumbs/breadcrumbs.js
Labels: bugfix

#2888 fix(flow): transform cup globals before dist copy
  .babelrc.js
  babel/transform-cup-globals.js
  component-sizes.json
  jest.e2e.config.js
  jest.vrt.config.js
  package.json
  scripts/flow-copy-src.js
  yarn.lock
Labels: bugfix

#2879 feat(eslint-plugin-baseui): improve deprecated-component-api importing logic
  packages/eslint-plugin-baseui/__tests__/deprecated-component-api.test.js
  packages/eslint-plugin-baseui/src/deprecated-component-api.js
  packages/eslint-plugin-baseui/src/messages.js
Labels: feature

#2900 fix(ci): expose docker-compose env var to e2e server
  docker-compose.yml
Labels: bugfix, chore

#2896 fix(flow): maintain suppression comment position
  scripts/flow-copy-src.js
Labels: bugfix

#2823 feat: rtl support for data table
  src/data-table/__tests__/data-table-rtl.e2e.js
  src/data-table/__tests__/data-table-rtl.scenario.js
  src/data-table/__tests__/data-table.scenario.js
  src/data-table/column-numerical.js
  src/data-table/data-table.js
  vrt/__image_snapshots__/data-table-rtl__desktop-snap.png
  vrt/__image_snapshots__/data-table-rtl__mobile-snap.png
Labels: feature

#2904 fix(link-checker): exclude flakey external addresses
  scripts/link-checker.js
Labels: bugfix, build/tooling, chore

#2903 fix(typescript): add zIndex prop to BaseProvider
  src/index.d.ts
Labels: bugfix

#2905 fix(card): use section for root instead of div
  src/card/styled-components.js
Labels: bugfix

#2901 fix(flow): resolve errors on other flow versions
  .buildkite/pipeline.yml
  .flowconfig
  package.json
  packages/flow-check-build/.flowconfig
  packages/flow-check-build/.gitignore
  packages/flow-check-build/.npmrc
  packages/flow-check-build/build-dependencies.js
  packages/flow-check-build/index.js
  packages/flow-check-build/package.json
  packages/flow-check-build/yarn.lock
  scripts/flow-check-build.js
  src/button/styled-components.js
  src/datepicker/styled-components.js
  src/dnd-list/styled-components.js
  src/drawer/styled-components.js
  src/input/styled-components.js
  src/modal/styled-components.js
  src/pagination/styled-components.js
  src/popover/utils.js
  src/progress-steps/styled-components.js
  src/select/styled-components.js
  src/styles/types.js
  src/tag/styled-components.js
  src/themes/types.js
Labels: bugfix

#2910 Release v9.57.0
  package.json
Labels: release

#2911 docs: remove sticky "help" card
  documentation-site/components/help.js
  documentation-site/components/layout.js
Labels: docs

#2898 feat(layout-grid): add overrides to Grid and Cell
  documentation-site/examples/layout-grid/align.js
  documentation-site/examples/layout-grid/basic.js
  documentation-site/examples/layout-grid/behavior.js
  documentation-site/examples/layout-grid/custom.js
  documentation-site/examples/layout-grid/hide.js
  documentation-site/examples/layout-grid/order.js
  documentation-site/examples/layout-grid/overrides.js
  documentation-site/examples/layout-grid/overrides.tsx
  documentation-site/examples/layout-grid/responsive.js
  documentation-site/examples/layout-grid/skip-shrink.js
  documentation-site/examples/layout-grid/skip.js
  documentation-site/examples/layout-grid/span.js
  documentation-site/examples/layout-grid/unit.js
  documentation-site/examples/layout-grid/unit.tsx
  documentation-site/pages/components/layout-grid.mdx
  src/layout-grid/__tests__/layout-grid-custom-css-length-unit.scenario.js
  src/layout-grid/__tests__/layout-grid-overrides.scenario.js
  src/layout-grid/__tests__/layout-grid-unit.scenario.js
  src/layout-grid/cell.js
  src/layout-grid/grid.js
  src/layout-grid/index.d.ts
  src/layout-grid/types.js
  vrt/__image_snapshots__/layout-grid-custom-css-length-unit__dark-snap.png
  vrt/__image_snapshots__/layout-grid-custom-css-length-unit__desktop-snap.png
  vrt/__image_snapshots__/layout-grid-custom-css-length-unit__mobile-snap.png
  vrt/__image_snapshots__/layout-grid-overrides__dark-snap.png
  vrt/__image_snapshots__/layout-grid-overrides__desktop-snap.png
  vrt/__image_snapshots__/layout-grid-overrides__mobile-snap.png
  vrt/__image_snapshots__/layout-grid-unit__dark-snap.png
  vrt/__image_snapshots__/layout-grid-unit__desktop-snap.png
  vrt/__image_snapshots__/layout-grid-unit__mobile-snap.png
Labels: feature

#2913 fix(button-group): improve screen-reader support
  src/button-group/button-group.js
Labels: bugfix

#2912 feat(menu): improvements to nested menus
  documentation-site/components/version-selector.js
  src/menu/maybe-child-menu.js
  src/menu/nested-menus.js
Labels: bugfix, docs, feature

#2919 fix(menu): add OptgroupHeader to react-view config
  documentation-site/components/yard/config/menu.ts
Labels: bugfix

#2922 fix(build): exclude tabs types from esm target
  src/tabs/index.js
Labels: bugfix

#2918 fix(checkbox): applies screen-reader improvements
  src/checkbox/checkbox.js
  src/checkbox/index.d.ts
  src/checkbox/types.js
  src/form-control/__tests__/form-control.test.js
  src/form-control/form-control.js
  src/form-control/index.d.ts
  src/form-control/types.js
  src/input/__tests__/__snapshots__/base-input.test.js.snap
  src/input/__tests__/__snapshots__/input.test.js.snap
  src/input/__tests__/__snapshots__/masked-input.test.js.snap
  src/input/base-input.js
  src/input/types.js
  src/radio/index.d.ts
  src/radio/radiogroup.js
  src/radio/types.js
  src/select/__tests__/__snapshots__/select.test.js.snap
  src/select/default-props.js
  src/select/index.d.ts
  src/select/select-component.js
  src/select/types.js
  src/textarea/__tests__/__snapshots__/textarea.test.js.snap
Labels: bugfix

#2914 fix(typescript): add missing theme properties
  src/theme.ts
Labels: bugfix

#2923 Release v9.58.0
  package.json
Labels: release

#2926 docs: update the roadmap
  documentation-site/pages/discover-more/roadmap.mdx
Labels: docs

#2925 fix(spinner): add missing aria-label
  src/spinner/index.d.ts
  src/spinner/spinner.js
  src/spinner/types.js
Labels: bugfix

#2915 feat(phone-input): add standalone phone picker component
  documentation-site/components/yard/config/phone-input.ts
  documentation-site/examples/phone-input/basic-next.js
  documentation-site/examples/phone-input/basic-next.tsx
  documentation-site/pages/components/phone-input.mdx
  src/phone-input/__tests__/country-select-dropdown.scenario.js
  src/phone-input/__tests__/phone-input-next-dropdown.e2e.js
  src/phone-input/__tests__/phone-input-next-dropdown.scenario.js
  src/phone-input/__tests__/phone-input-next.scenario.js
  src/phone-input/__tests__/phone-input.scenario.js
  src/phone-input/base-country-picker.js
  src/phone-input/country-picker.js
  src/phone-input/country-select.js
  src/phone-input/default-props.js
  src/phone-input/index.d.ts
  src/phone-input/index.js
  src/phone-input/phone-input-next.js
  src/phone-input/stateful-phone-input-next.js
  src/phone-input/styled-components.js
  src/phone-input/types.js
  vrt/__image_snapshots__/country-select-dropdown__dark-snap.png
  vrt/__image_snapshots__/country-select-dropdown__desktop-snap.png
  vrt/__image_snapshots__/country-select-dropdown__expanded-snap.png
  vrt/__image_snapshots__/country-select-dropdown__mobile-snap.png
  vrt/__image_snapshots__/phone-input-next-dropdown__dark-snap.png
  vrt/__image_snapshots__/phone-input-next-dropdown__desktop-snap.png
  vrt/__image_snapshots__/phone-input-next-dropdown__mobile-snap.png
  vrt/__image_snapshots__/phone-input-next__dark-snap.png
  vrt/__image_snapshots__/phone-input-next__desktop-snap.png
  vrt/__image_snapshots__/phone-input-next__mobile-snap.png
  vrt/__image_snapshots__/phone-input__desktop-snap.png
  vrt/__image_snapshots__/phone-input__mobile-snap.png
Labels: feature

#2924 feat(tree-view): add keyboard shortcuts and other improvements
  component-sizes.json
  documentation-site/components/yard/config/tree-view.ts
  documentation-site/examples/tree-view/basic.js
  documentation-site/examples/tree-view/basic.tsx
  documentation-site/examples/tree-view/controlled.js
  documentation-site/examples/tree-view/controlled.tsx
  documentation-site/examples/tree-view/custom-label.js
  documentation-site/examples/tree-view/custom-label.tsx
  documentation-site/examples/tree-view/label-overrides.js
  documentation-site/examples/tree-view/label-overrides.tsx
  documentation-site/examples/tree-view/overrides.js
  documentation-site/examples/tree-view/overrides.tsx
  documentation-site/examples/tree-view/single-expanded.js
  documentation-site/examples/tree-view/single-expanded.tsx
  documentation-site/examples/tree-view/uncontrolled.js
  documentation-site/examples/tree-view/uncontrolled.tsx
  documentation-site/pages/components/tree-view.mdx
  src/tree-view/__tests__/tree-view-render-all.scenario.js
  src/tree-view/__tests__/tree-view-single-expanded.scenario.js
  src/tree-view/__tests__/tree-view.scenario.js
  src/tree-view/__tests__/tree-view.test.js
  src/tree-view/__tests__/utils.test.js
  src/tree-view/index.d.ts
  src/tree-view/index.js
  src/tree-view/styled-components.js
  src/tree-view/tree-label.js
  src/tree-view/tree-node.js
  src/tree-view/tree-view.js
  src/tree-view/types.js
  src/tree-view/utils.js
  vrt/__image_snapshots__/tree-view-render-all__dark-snap.png
  vrt/__image_snapshots__/tree-view-render-all__desktop-snap.png
  vrt/__image_snapshots__/tree-view-render-all__mobile-snap.png
  vrt/__image_snapshots__/tree-view-single-expanded__dark-snap.png
  vrt/__image_snapshots__/tree-view-single-expanded__desktop-snap.png
  vrt/__image_snapshots__/tree-view-single-expanded__mobile-snap.png
  vrt/__image_snapshots__/tree-view__dark-snap.png
  vrt/__image_snapshots__/tree-view__desktop-snap.png
  vrt/__image_snapshots__/tree-view__mobile-snap.png
Labels: feature

#2916 docs(panel): custom panel component example
  documentation-site/examples/accordion/custom.js
  documentation-site/examples/accordion/custom.tsx
  documentation-site/pages/components/accordion.mdx
Labels: docs

#2932 fix(select): fix for an error in an empty clearable select on esc
  src/select/select-component.js
Labels: bugfix

#2934 fix(side-bar): active border was not visible when focused
  src/side-navigation/styled-components.js
Labels: bugfix

#2936 feat(input): make "clear input" keyboard interactive
  src/input/__tests__/input.e2e.js
  src/input/base-input.js
  src/input/styled-components.js
  src/input/types.js
Labels: enhancement, feature

#2939 fix(eslint): guard declarator.init
  packages/eslint-plugin-baseui/src/deprecated-theme-api.js
Labels: bugfix

#2940 Release v9.59.0
  package.json
Labels: release

#2933 feat(layers): handle doc click event on the layers level
  documentation-site/examples/datepicker/in-popover.js
  src/datepicker/calendar-header.js
  src/datepicker/calendar.js
  src/datepicker/types.js
  src/layer/layer.js
  src/layer/layers-manager.js
  src/layer/types.js
  src/popover/__tests__/__snapshots__/popover.test.js.snap
  src/popover/__tests__/popover-select.scenario.js
  src/popover/__tests__/popover.e2e.js
  src/popover/popover.js
  vrt/__image_snapshots__/popover-select__dark-snap.png
  vrt/__image_snapshots__/popover-select__desktop-snap.png
  vrt/__image_snapshots__/popover-select__mobile-snap.png
Labels: feature

#2937 fix(file-uploader): add error aria state
  documentation-site/components/yard/config/file-uploader.ts
  src/file-uploader/file-uploader.js
  src/file-uploader/types.js
Labels: bugfix

#2941 fix(button-group): radiogroup role should use arrows to change selection
  documentation-site/components/yard/config/button-group.ts
  src/button-group/button-group.js
Labels: bugfix

#2931 fix(tree-view): update default styling to chevron
  documentation-site/examples/tree-view/label-overrides.js
  documentation-site/examples/tree-view/overrides.js
  src/tree-view/__tests__/tree-view.test.js
  src/tree-view/styled-components.js
  src/tree-view/tree-label.js
Labels: bugfix

#2944 fix(tree-view): update default styling to chevron (#2931)
  documentation-site/examples/tree-view/label-overrides.js
  documentation-site/examples/tree-view/overrides.js
  src/tree-view/__tests__/tree-view.test.js
  src/tree-view/styled-components.js
  src/tree-view/tree-label.js
Labels: bugfix

#2945 fix(tree-view): update vrt
  README.md
  vrt/__image_snapshots__/tree-view-render-all__dark-snap.png
  vrt/__image_snapshots__/tree-view-render-all__desktop-snap.png
  vrt/__image_snapshots__/tree-view-render-all__mobile-snap.png
  vrt/__image_snapshots__/tree-view-single-expanded__dark-snap.png
  vrt/__image_snapshots__/tree-view-single-expanded__desktop-snap.png
  vrt/__image_snapshots__/tree-view-single-expanded__mobile-snap.png
  vrt/__image_snapshots__/tree-view__dark-snap.png
  vrt/__image_snapshots__/tree-view__desktop-snap.png
  vrt/__image_snapshots__/tree-view__mobile-snap.png
Labels: bugfix

#2948 build(vrt): sanitize branch names
  vrt/ci.js
Labels: bugfix, build/tooling

#2928 feat(toast): add autoFocus prop
  documentation-site/pages/components/toast.mdx
  src/toast/__tests__/toast.e2e.js
  src/toast/__tests__/toaster-focus.scenario.js
  src/toast/styled-components.js
  src/toast/toast.js
  src/toast/toaster.js
  src/toast/types.js
  vrt/config.js
Labels: feature

#2949 Release v9.60.0
  package.json
Labels: release
