Repository uber/baseweb, pull requests merged in 2021-05, with the labels that each got.

#4212 fix(dnd-list): update react-movabe to fix mobile scrolling
  package.json
  yarn.lock
Labels: bugfix

#4241 fix: panel should not render content when not expanded
  src/accordion/__tests__/panel.test.js
  src/accordion/panel.js
Labels: bugfix

#4242 Release v9.115.1
  package.json
Labels: release

#4263 chore: update codeowners and coc contact
  .github/CODEOWNERS
  CODE_OF_CONDUCT.md
Labels: docs

#4262 fix: replace adorable avatars with dicebear
  documentation-site/components/yard/config/avatar.ts
  documentation-site/examples/aspect-ratio-box/image.js
  documentation-site/examples/aspect-ratio-box/image.tsx
  documentation-site/examples/avatar/override.js
  documentation-site/examples/avatar/override.tsx
  documentation-site/examples/avatar/sizes.js
  documentation-site/examples/avatar/sizes.tsx
Labels: docs

#4259 fix(menu): item with child menu triggers click handler
  src/menu/__tests__/menu-child.scenario.js
  src/menu/__tests__/menu.e2e.js
  src/menu/maybe-child-menu.js
  src/menu/option-list.js
  src/menu/types.js
Labels: bugfix

#4266 chore(alpha-test): test block step
  .buildkite/pipeline.yml
Labels: chore

#4272 chore(alpha): set PR green if not unblocked
  .buildkite/pipeline.yml
Labels: chore

#4274 fix(file-uploader): remove block from the implementation
  src/file-uploader/file-uploader.js
Labels: bugfix
