Repository uber/baseweb, pull requests merged in 2021-11, with the labels that each got.

#4592 Update Ladle - Snowpack replaced by Vite
  .codesandbox/ci.json
  .ladle/components.js
  .ladle/config.mjs
  package.json
  src/dnd-list/index.js
  src/select/select-component.js
  yarn.lock
Labels: docs, chore, dependencies

#4610 docs: link working nextjs baseweb project in setup
  documentation-site/pages/getting-started/setup.mdx
Labels: docs

#4614 fix(rating): reset preview on outside blur only
  src/rating/emoticon-rating.js
  src/rating/star-rating.js
Labels: bugfix

#4615 fix: change accordion background color to primary / improve its contrast
  src/themes/dark-theme/color-component-tokens.js
  src/themes/light-theme/color-component-tokens.js
  vrt/__image_snapshots__/accordion--controlled__dark-snap.png
  vrt/__image_snapshots__/accordion--controlled__desktop-snap.png
  vrt/__image_snapshots__/accordion--controlled__mobile-snap.png
  vrt/__image_snapshots__/accordion--expanded__dark-snap.png
  vrt/__image_snapshots__/accordion--expanded__desktop-snap.png
  vrt/__image_snapshots__/accordion--expanded__mobile-snap.png
  vrt/__image_snapshots__/accordion--panel-override__dark-snap.png
  vrt/__image_snapshots__/accordion--panel-override__desktop-snap.png
  vrt/__image_snapshots__/accordion--panel-override__mobile-snap.png
  vrt/__image_snapshots__/accordion--stateless-accordion__dark-snap.png
  vrt/__image_snapshots__/accordion--stateless-accordion__desktop-snap.png
  vrt/__image_snapshots__/accordion--stateless-accordion__mobile-snap.png
Labels: bugfix

#4618 fix(button): update loading spinner color
  src/themes/light-theme/color-component-tokens.js
  vrt/__image_snapshots__/button--button__desktop-snap.png
  vrt/__image_snapshots__/button--button__mobile-snap.png
  vrt/__image_snapshots__/button--sizes-loading__desktop-snap.png
  vrt/__image_snapshots__/button--sizes-loading__mobile-snap.png
Labels: bugfix

#4611 fix(snackbar): handles enqueue calls in async context
  src/snackbar/__tests__/snackbar-async.scenario.js
  src/snackbar/__tests__/snackbar.e2e.js
  src/snackbar/__tests__/snackbar.stories.js
  src/snackbar/snackbar-context.js
  vrt/__image_snapshots__/snackbar--async__dark-snap.png
  vrt/__image_snapshots__/snackbar--async__desktop-snap.png
  vrt/__image_snapshots__/snackbar--async__mobile-snap.png
Labels: bugfix
