Repository uber/baseweb, pull requests merged in 2021-06, with the labels that each got.

#3622 feat(progress-bar): update animation for infinite progress bar
  .eslintignore
  documentation-site/components/yard/config/progress-bar.ts
  src/progress-bar/__tests__/progressbar.scenario.js
  src/progress-bar/index.d.ts
  src/progress-bar/progressbar.js
  src/progress-bar/styled-components.js
  src/progress-bar/types.js
  vrt/__image_snapshots__/file-uploader--error__dark-snap.png
  vrt/__image_snapshots__/file-uploader--error__desktop-snap.png
  vrt/__image_snapshots__/file-uploader--error__mobile-snap.png
  vrt/__image_snapshots__/file-uploader--post-drop__dark-snap.png
  vrt/__image_snapshots__/file-uploader--post-drop__desktop-snap.png
  vrt/__image_snapshots__/file-uploader--post-drop__mobile-snap.png
  vrt/__image_snapshots__/file-uploader--progress-bar__dark-snap.png
  vrt/__image_snapshots__/file-uploader--progress-bar__desktop-snap.png
  vrt/__image_snapshots__/file-uploader--progress-bar__mobile-snap.png
  vrt/__image_snapshots__/progress-bar--progressbar-negative__dark-snap.png
  vrt/__image_snapshots__/progress-bar--progressbar-negative__desktop-snap.png
  vrt/__image_snapshots__/progress-bar--progressbar-negative__mobile-snap.png
  vrt/__image_snapshots__/progress-bar--progressbar__dark-snap.png
  vrt/__image_snapshots__/progress-bar--progressbar__desktop-snap.png
  vrt/__image_snapshots__/progress-bar--progressbar__mobile-snap.png
  vrt/__image_snapshots__/tabs-motion--fixed__mobile-snap.png
Labels: feature

#4315 feat(table-semantic): add dividers and cell spacing
  documentation-site/components/yard/config/table-semantic.ts
  src/table-semantic/__tests__/table-semantic-divider.scenario.js
  src/table-semantic/__tests__/table-semantic-size.scenario.js
  src/table-semantic/__tests__/table-semantic.stories.js
  src/table-semantic/constants.js
  src/table-semantic/index.d.ts
  src/table-semantic/index.js
  src/table-semantic/styled-components.js
  src/table-semantic/table.js
  src/table-semantic/types.js
  vrt/__image_snapshots__/table-semantic--builder__dark-snap.png
  vrt/__image_snapshots__/table-semantic--builder__desktop-snap.png
  vrt/__image_snapshots__/table-semantic--builder__mobile-snap.png
  vrt/__image_snapshots__/table-semantic--compose__dark-snap.png
  vrt/__image_snapshots__/table-semantic--compose__desktop-snap.png
  vrt/__image_snapshots__/table-semantic--compose__mobile-snap.png
  vrt/__image_snapshots__/table-semantic--divider__dark-snap.png
  vrt/__image_snapshots__/table-semantic--divider__desktop-snap.png
  vrt/__image_snapshots__/table-semantic--divider__mobile-snap.png
  vrt/__image_snapshots__/table-semantic--size__dark-snap.png
  vrt/__image_snapshots__/table-semantic--size__desktop-snap.png
  vrt/__image_snapshots__/table-semantic--size__mobile-snap.png
  vrt/__image_snapshots__/table-semantic--table-semantic__dark-snap.png
  vrt/__image_snapshots__/table-semantic--table-semantic__desktop-snap.png
  vrt/__image_snapshots__/table-semantic--table-semantic__mobile-snap.png
Labels: feature

#4249 fix(slider): use semantic theme overrides for slider
  documentation-site/components/yard/config/slider.ts
  src/checkbox/styled-components.js
  src/slider/styled-components.js
  src/themes/dark-theme/color-component-tokens.js
  src/themes/light-theme/color-component-tokens.js
  vrt/__image_snapshots__/checkbox--toggle__dark-snap.png
Labels: enhancement

#4334 feat(tag): add start enhancer
  documentation-site/components/yard/config/tag.ts
  src/tag/__tests__/tag-long-text.scenario.js
  src/tag/__tests__/tag-start-enhancer.scenario.js
  src/tag/__tests__/tag.stories.js
  src/tag/index.d.ts
  src/tag/styled-components.js
  src/tag/tag.js
  src/tag/types.js
  vrt/__image_snapshots__/tag--long-text__dark-snap.png
  vrt/__image_snapshots__/tag--long-text__desktop-snap.png
  vrt/__image_snapshots__/tag--long-text__mobile-snap.png
  vrt/__image_snapshots__/tag--start-enhancer__dark-snap.png
  vrt/__image_snapshots__/tag--start-enhancer__desktop-snap.png
  vrt/__image_snapshots__/tag--start-enhancer__mobile-snap.png
Labels: feature

#4326 fix(avatar): display fallback until image load
  src/avatar/__tests__/avatar-update-image.scenario.js
  src/avatar/__tests__/avatar.stories.js
  src/avatar/__tests__/avatar.test.js
  src/avatar/avatar.js
  src/avatar/styled-components.js
  src/avatar/types.js
  vrt/__image_snapshots__/avatar--update-image__dark-snap.png
  vrt/__image_snapshots__/avatar--update-image__desktop-snap.png
  vrt/__image_snapshots__/avatar--update-image__mobile-snap.png
Labels: bugfix

#4341 chore(docs): add list-item-label yarn config
  documentation-site/components/yard/config/list-item-label.ts
  documentation-site/pages/components/list.mdx
Labels: docs

#4340 fix(docs): explicitly scroll to cheat sheet entry
  documentation-site/components/cheat-sheet.js
  documentation-site/components/exports.js
  src/menu/__tests__/menu-profile-menu.scenario.js
  vrt/__image_snapshots__/menu--profile-menu__dark-snap.png
  vrt/__image_snapshots__/menu--profile-menu__mobile-snap.png
Labels: docs

#4345 fix(drawer): fix showBackdrop behavior
  src/drawer/__tests__/drawer-hide-backdrop.scenario.js
  src/drawer/__tests__/drawer.stories.js
  src/drawer/styled-components.js
  vrt/__image_snapshots__/drawer--hide-backdrop__dark-snap.png
  vrt/__image_snapshots__/drawer--hide-backdrop__desktop-snap.png
  vrt/__image_snapshots__/drawer--hide-backdrop__mobile-snap.png
Labels: bugfix

#4348 fix(table-semantic): table bottom border in horizontal
  src/table-semantic/styled-components.js
  vrt/__image_snapshots__/table-semantic--divider__dark-snap.png
  vrt/__image_snapshots__/table-semantic--divider__desktop-snap.png
  vrt/__image_snapshots__/table-semantic--divider__mobile-snap.png
Labels: bugfix

#4360 fix(color-tokens): update colors for better contrast
  src/themes/dark-theme/color-semantic-tokens.js
  src/themes/light-theme/color-semantic-tokens.js
  src/themes/light-theme/color-tokens.js
  vrt/__image_snapshots__/datepicker--stateful-calendar-overrides__desktop-snap.png
  vrt/__image_snapshots__/datepicker--stateful-calendar-overrides__mobile-snap.png
  vrt/__image_snapshots__/list--item-overrides__desktop-snap.png
  vrt/__image_snapshots__/list--item-overrides__mobile-snap.png
  vrt/__image_snapshots__/table--cells__desktop-snap.png
  vrt/__image_snapshots__/table--cells__mobile-snap.png
Labels: bugfix

#4364 docs(table): add cell examples
  documentation-site/examples/table-semantic/cells.js
  documentation-site/examples/table-semantic/cells.tsx
  documentation-site/pages/components/table-semantic.mdx
Labels: docs
