Repository uber/baseweb, pull requests merged in 2021-03, with the labels that each got.

#4095 chore(build): relax react peer dep constraint
  package.json
  vrt/__image_snapshots__/avatar--avatar__dark-snap.png
  vrt/__image_snapshots__/avatar--avatar__desktop-snap.png
  vrt/__image_snapshots__/avatar--avatar__mobile-snap.png
  vrt/__image_snapshots__/button--button__dark-snap.png
  vrt/__image_snapshots__/button--button__desktop-snap.png
  vrt/__image_snapshots__/button--button__mobile-snap.png
  vrt/__image_snapshots__/card--image-link__dark-snap.png
  vrt/__image_snapshots__/card--image-link__desktop-snap.png
  vrt/__image_snapshots__/card--image-link__mobile-snap.png
  vrt/__image_snapshots__/card--image-object__dark-snap.png
  vrt/__image_snapshots__/card--image-object__desktop-snap.png
  vrt/__image_snapshots__/card--image-object__mobile-snap.png
  vrt/__image_snapshots__/phone-input--custom-flags__dark-snap.png
  vrt/__image_snapshots__/phone-input--custom-flags__desktop-snap.png
  vrt/__image_snapshots__/phone-input--custom-flags__mobile-snap.png
  vrt/__image_snapshots__/table-semantic--builder__dark-snap.png
  vrt/__image_snapshots__/table-semantic--builder__desktop-snap.png
  vrt/__image_snapshots__/table-semantic--builder__mobile-snap.png
  vrt/__image_snapshots__/table-semantic--compose__dark-snap.png
  vrt/__image_snapshots__/table-semantic--compose__desktop-snap.png
  vrt/__image_snapshots__/table-semantic--compose__mobile-snap.png
  vrt/__image_snapshots__/table-semantic--table-semantic__dark-snap.png
  vrt/__image_snapshots__/table-semantic--table-semantic__desktop-snap.png
  vrt/__image_snapshots__/table-semantic--table-semantic__mobile-snap.png
Labels: chore

#4091 feat(tag): Make Tag border radius themeable like similar components
  src/tag/styled-components.js
  src/theme.ts
  src/themes/shared/borders.js
  src/themes/types.js
Labels: feature

#4116 chore(publish): change deploy stdio to debug npm publish failure
  .buildkite/pipeline.yml
  scripts/publish-to-npm.js
Labels: chore

#4133 docs(accordion): add custom title example
  documentation-site/examples/accordion/title.js
  documentation-site/examples/accordion/title.tsx
  documentation-site/pages/components/accordion.mdx
Labels: docs

#4134 fix(link): static position when default
  src/link/__tests__/link.scenario.js
  src/link/styled-components.js
  vrt/__image_snapshots__/link--link__dark-snap.png
  vrt/__image_snapshots__/link--link__desktop-snap.png
  vrt/__image_snapshots__/link--link__mobile-snap.png
Labels: bugfix

#4125 fix(data-table): measure in useEffect avoid ssr warning
  src/data-table/measure-column-widths.js
Labels: bugfix

#4138 fix(input): render clear when initial value is number
  src/input/__tests__/input-clearable.scenario.js
  src/input/base-input.js
  vrt/__image_snapshots__/input--clearable__dark-snap.png
  vrt/__image_snapshots__/input--clearable__desktop-snap.png
  vrt/__image_snapshots__/input--clearable__mobile-snap.png
Labels: bugfix

#4142 fix(input): correct typeof usage
  src/input/base-input.js
Labels: bugfix

#4140 fix(input): avoid webkit input text fade
  src/input/styled-components.js
Labels: bugfix

#4113 fix(tether): scheduleUpdate popper when anchor element changes (#4112)
  src/layer/tether.js
  src/popover/__tests__/popover-reposition-with-anchor-update.scenario.js
  src/popover/__tests__/popover.stories.js
  vrt/__image_snapshots__/popover--reposition-with-anchor-update__addOptions-snap.png
  vrt/__image_snapshots__/popover--reposition-with-anchor-update__dark-snap.png
  vrt/__image_snapshots__/popover--reposition-with-anchor-update__desktop-snap.png
  vrt/__image_snapshots__/popover--reposition-with-anchor-update__mobile-snap.png
  vrt/config.js
Labels: bugfix
