Repository uber/baseweb, pull requests merged in 2021-01, with the labels that each got.

#3999 fix(button-group): remove root margin
  src/button-group/button-group.js
  src/button-group/styled-components.js
  vrt/__image_snapshots__/button-group-checkbox__dark-snap.png
  vrt/__image_snapshots__/button-group-checkbox__desktop-snap.png
  vrt/__image_snapshots__/button-group-checkbox__mobile-snap.png
  vrt/__image_snapshots__/button-group-disabled__dark-snap.png
  vrt/__image_snapshots__/button-group-disabled__desktop-snap.png
  vrt/__image_snapshots__/button-group-disabled__mobile-snap.png
  vrt/__image_snapshots__/button-group-pill__dark-snap.png
  vrt/__image_snapshots__/button-group-pill__desktop-snap.png
  vrt/__image_snapshots__/button-group-pill__mobile-snap.png
  vrt/__image_snapshots__/button-group-radio__dark-snap.png
  vrt/__image_snapshots__/button-group-radio__desktop-snap.png
  vrt/__image_snapshots__/button-group-radio__mobile-snap.png
  vrt/__image_snapshots__/button-group-sizes__dark-snap.png
  vrt/__image_snapshots__/button-group-sizes__desktop-snap.png
  vrt/__image_snapshots__/button-group-sizes__mobile-snap.png
  vrt/__image_snapshots__/data-table-categorical-column__dark-snap.png
  vrt/__image_snapshots__/data-table-categorical-column__desktop-snap.png
  vrt/__image_snapshots__/data-table-categorical-column__mobile-snap.png
  vrt/__image_snapshots__/data-table-datetime-column__dark-snap.png
  vrt/__image_snapshots__/data-table-datetime-column__desktop-snap.png
  vrt/__image_snapshots__/data-table-datetime-column__mobile-snap.png
  vrt/__image_snapshots__/data-table-extracted-filters__dark-snap.png
  vrt/__image_snapshots__/data-table-extracted-filters__desktop-snap.png
  vrt/__image_snapshots__/data-table-extracted-filters__mobile-snap.png
  vrt/__image_snapshots__/data-table-numerical-column__dark-snap.png
  vrt/__image_snapshots__/data-table-numerical-column__desktop-snap.png
  vrt/__image_snapshots__/data-table-numerical-column__mobile-snap.png
Labels: bugfix

#4005 docs: add override example for tabs motion
  documentation-site/examples/tabs-motion/tab-override.js
  documentation-site/examples/tabs-motion/tab-override.tsx
  documentation-site/pages/components/tabs-motion.mdx
Labels: docs

#3997 Close open filter
  src/table/filter.js
  src/table/index.d.ts
  src/table/types.js
Labels: enhancement, feature

#3985 fix(tag): reorder text for rtl direction
  src/tag/styled-components.js
  vrt/__image_snapshots__/select-rtl__desktop-snap.png
  vrt/__image_snapshots__/select-rtl__mobile-snap.png
  vrt/__image_snapshots__/tag-rtl__desktop-snap.png
  vrt/__image_snapshots__/tag-rtl__mobile-snap.png
Labels: bugfix

#4011 fix(data-table): adds y-overflow to filter menu
  src/data-table/filter-menu.js
Labels: bugfix

#4010 docs: show border values as objects
  documentation-site/components/theming/borders.js
  documentation-site/components/theming/grid.js
  documentation-site/components/theming/typography.js
Labels: docs

#4016 improve performance of datepicker
  src/datepicker/calendar-header.js
  src/datepicker/styled-components.js
  src/datepicker/utils/date-helpers.js
Labels: bugfix

#4017 fix(data-table): handle add/remove columns
  src/data-table/__tests__/data-table-add-remove-columns.scenario.js
  src/data-table/__tests__/data-table-resizable-column-widths.scenario.js
  src/data-table/data-table.js
  src/data-table/measure-column-widths.js
  vrt/__image_snapshots__/data-table-add-remove-columns__addColumn-snap.png
  vrt/__image_snapshots__/data-table-add-remove-columns__dark-snap.png
  vrt/__image_snapshots__/data-table-add-remove-columns__desktop-snap.png
  vrt/__image_snapshots__/data-table-add-remove-columns__mobile-snap.png
  vrt/__image_snapshots__/data-table-add-remove-columns__removeColumn-snap.png
  vrt/__image_snapshots__/data-table-resizable-column-widths__dark-snap.png
  vrt/__image_snapshots__/data-table-resizable-column-widths__desktop-snap.png
  vrt/__image_snapshots__/data-table-resizable-column-widths__mobile-snap.png
  vrt/config.js
Labels: bugfix

#4020 fix(docs): include menu option override
  documentation-site/components/yard/config/menu.ts
Labels: bugfix

#4003 Add ES-AR localization
  src/locale/es_AR.js
Labels: feature

#4029 fix(typescript): add missing types to ts theme file
  src/theme.ts
Labels: bugfix

#4040 fix(drawer): showBackdrop prop fix from Issues
  documentation-site/components/yard/config/drawer.ts
  src/drawer/__tests__/drawer.test.js
  src/drawer/drawer.js
  src/drawer/types.js
Labels: bugfix

#4041 fix(data-table): full height table
  src/data-table/__tests__/data-table-full-window.scenario.js
  src/data-table/data-table.js
  vrt/__image_snapshots__/data-table-full-window__dark-snap.png
  vrt/__image_snapshots__/data-table-full-window__desktop-snap.png
  vrt/__image_snapshots__/data-table-full-window__mobile-snap.png
Labels: bugfix
