Repository uber/baseweb, pull requests merged in 2021-02, with the labels that each got.

#4047 Don't marginRight on the last star, so as to preserve centering
  src/rating/styled-components.js
Labels: bugfix

#4050 Add a 'uid' option to tabs
  src/tabs-motion/tabs.js
  src/tabs-motion/types.js
Labels: feature

#4066 chore(alpha-test): fix to main branch
  scripts/alpha-test-web-code.js
Labels: chore

#4069 Ladle: Fix minor story errors
  .nvmrc
  package.json
  src/list/list-item.js
  yarn.lock
Labels: bugfix

#4070 Add a missing type definition for uid in tabs-motion
  src/tabs-motion/index.d.ts
Labels: bugfix

#4077 fix(toast): "key" must be optional parameter in typescript definitions
  src/toast/index.d.ts
Labels: bugfix

#4089 Publish a 'next' tag on every master release
  .buildkite/pipeline.yml
  scripts/publish-bleeding-edge.js
Labels: ci, enhancement

#4092 Allow 'next' tag in publishing
  scripts/publish-to-npm.js
Labels: ci

#4094 Publish 'next' tag with unique semver
  scripts/publish-bleeding-edge.js
  scripts/publish-to-npm.js
Labels: ci
