Repository uber/baseweb, pull requests merged in 2022-06, with the labels that each got.

#4984 chore(spinner): remove styledspinnernext deprecation warning
  packages/eslint-plugin-baseui/__tests__/deprecated-component-api.test.js
  packages/eslint-plugin-baseui/src/deprecated-component-api.js
  packages/eslint-plugin-baseui/src/messages.js
Labels: greenkeeping

#4985 chore: test Ladle v1
  .ladle/config.mjs
  package.json
  scripts/collect-bundle-sizes.js
  vite.config.mjs
  yarn.lock
Labels: build/tooling

#4990 Fix select with many options
  src/select/__tests__/select-controlref.test.js
  src/select/__tests__/select-many-options.scenario.js
  src/select/__tests__/select.stories.js
  src/select/select-component.js
Labels: bugfix
